<?php
    $optionPage = $this->home()->optionPage();
?>
<footer class="footer">
    <div class="container">
        <div class="footer__two">
            <div class="footer__social">
                <ul>
                    <li><a href=""><i class="fa fa-facebook"></i></a></li>
                    <li><a href=""><i class="fa fa-google"></i></a></li>
                    <li><a href=""><i class="fa fa-instagram"></i></a></li>
                    <li><a href=""><i class="fa fa-skype"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>