<?php
    use Home\Model\DateBase;
    echo $this->headtitle($this->escapehtml($this->translate('Sửa')));
    $form = $this->form;
    $dep = $this->dependencies;
    $vDep = $this->vDep;
    $data = $this->data;
?>


<form method="post" class="form-horizontal" enctype="multipart/form-data" data-parsley-validate novalidate>
    <div class="row">
        <div class="col-sm-12">
        <div class="card-box">
            <div class="row">
                <div class="col-sm-4">
                    <h5><b>Tài khoản</b></h5>
                    <p class="text-muted font-13 m-b-30">
                        Thông tin tài khoản
                    </p>
                    <div class="portlet-body form">

                        <div class="form-group">
                            <label class="col-sm-4 control-label" for="Password">Mật khẩu cũ</label>
                            <div class="col-sm-7">
                                <?= $this->formelement($form->get('passwordOld')->setAttributes(['class' => 'form-control', 'placeholder'=>'Mật khẩu cũ', 'data-parsley-minlength' => '6', 'data-parsley-error-message' => 'Mật khẩu tối thiểu 6 ký tự'])) ?>
                                <?= $this->formelementerrors($form->get('passwordOld'),['class' => 'parsley-errors-list filled']) ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-4 control-label" for="Password">Mật khẩu mới</label>
                            <div class="col-sm-7">
                                <?= $this->formelement($form->get('passwordNew')->setAttributes(['class' => 'form-control', 'placeholder'=>'Mật khẩu mới', 'data-parsley-minlength' => '6', 'data-parsley-error-message' => 'Mật khẩu tối thiểu 6 ký tự'])) ?>
                                <?= $this->formelementerrors($form->get('passwordNew'),['class' => 'parsley-errors-list filled']) ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-4 control-label" for="Password">Email</label>
                            <div class="col-sm-7">
                                <p class="form-control-static">
                                    <?= $data['email'] ? $data['email']:'' ?>
                                </p>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-4 control-label" for="Password">Số điện thoại</label>
                            <div class="col-sm-7">
                                <p class="form-control-static">
                                    <?= $data['mobile'] ? $data['mobile']:'' ?>
                                </p>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-4 control-label" for="Password">Ngày tạo</label>
                            <div class="col-sm-7">
                                <p class="form-control-static">
                                    <?= DateBase::toDisplayDateTime($data['createdDateTime']) ?>
                                </p>
                            </div>
                        </div>


                        <div class="form-group">
                            <div class="col-sm-offset-4 col-sm-7 m-t-15">
                                <?=$this->formelement($form->get('submit')->setAttributes(['class' => 'btn btn-default']))?>
                            </div>
                        </div>

                    </div>
                </div>

                <div class="col-sm-8">
                    <h5><b>Phân quyền</b></h5>
                    <p class="text-muted font-13 m-b-30">
                        Chi tiết phân quyền
                    </p>
                    <div class="row">
                    <?php
                        if(!empty($dep)):
                        foreach($dep as $k => $d):
                    ?>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label class="col-sm-3 control-label"><?= $k ?>
                                        <?php if($k == 'Tài khoản'):  ?>
                                            <p class="text-muted font-13 font-light"> Khuyến cáo không lựa chọn cho tài khoản thường </p>
                                        <?php endif; ?>
                                    </label>
                                    <div class="col-sm-9">
                                        <?php
                                            if(!empty($d)):
                                            foreach($d as $text => $v):
                                        ?>
                                        <div class="checkbox checkbox-custom">
                                            <?php if($k == 'Tài khoản'): ?>
                                                <input id="remember-2" <?= $vDep['user'][$v] ? 'checked':'' ?> name="<?= vnString($k).' '.$v ?>" type="checkbox" >
                                            <?php endif; ?>
                                            <?php if($k == 'Trang'): ?>
                                                <input id="remember-2" <?= $vDep['page'][$v] ? 'checked':'' ?> name="<?= vnString($k).' '.$v ?>" type="checkbox" >
                                            <?php endif; ?>
                                            <?php if($k == 'Cài đặt'): ?>
                                                <input id="remember-2" <?= $vDep['setup'][$v] ? 'checked':'' ?> name="<?= vnString($k).' '.$v ?>" type="checkbox" >
                                            <?php endif; ?>
                                            <?php if($k == 'Hình Ảnh'): ?>
                                                <input id="remember-2" <?= $vDep['media'][$v] ? 'checked':'' ?> name="<?= vnString($k).' '.$v ?>" type="checkbox" >
                                            <?php endif; ?>
                                            <?php if($k == 'Bài viết'): ?>
                                                <input id="remember-2" <?= $vDep['article'][$v] ? 'checked':'' ?> name="<?= vnString($k).' '.$v ?>" type="checkbox" >
                                            <?php endif; ?>
                                            <?php if($k == 'Sản phẩm'): ?>
                                                <input id="remember-2" <?= !empty($vDep['product'][$v]) ? 'checked':'' ?> name="<?= vnString($k).' '.$v ?>" type="checkbox" >
                                            <?php endif; ?>
                                            <?php if($k == 'Question'): ?>
                                                <input id="remember-2" <?= !empty($vDep['question'][$v]) ? 'checked':'' ?> name="<?= vnString($k).' '.$v ?>" type="checkbox" >
                                            <?php endif; ?>
                                            <label for="remember-2"> <?= $text ?> </label>
                                        </div>
                                        <?php
                                            endforeach;
                                            endif;
                                        ?>
                                    </div>
                                </div>
                            </div>
                    <?php
                        endforeach;
                        endif;
                    ?>
                    </div>
                </div>
            </div>


        </div>
        </div>
    </div>
</form>