<?php
echo $this->headtitle($this->escapehtml($this->translate('Gửi yêu cầu')));
$typePage = $this->typePage;
$form = $this->form;
$result = $this->results;
use Home\Model\DateBase;
?>

<form method="post" enctype="multipart/form-data" data-parsley-validate novalidate>
    <div class="row">
        <div class="col-sm-8">
            <div class="card-box">
                <div class="portlet-title">
                    <h4 class="m-t-0 header-title m-b-20"><b>Gửi yêu cầu</b></h4>
                    <p class="text-muted m-b-15 font-13">
                        Để gửi yêu cầu nhanh về chỉnh sửa giao diện chúng tôi có 1 vài lưu ý sau.
                    </p>
                    <p class="text-muted m-b-5 font-13">
                        1. Sử dụng công cụ chụp hình <a href="https://app.prntscr.com/en/index.html" class="text-custom" target="_blank">Lightshot</a> copy và paste trực tiếp hình vào nội dung yêu cầu.
                    </p>
                    <p class="text-muted m-b-15 font-13">
                        2. Mô tả dõ hiện tại và mong muốn thay đổi, có hình đính kèm cho cả hai (Hiện tại/ mong muốn).
                    </p>
                </div>
                <div class="portlet-body form">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <?= $this->formelement($form->get('title')->setAttributes(['class' => 'form-control', 'placeholder'=>'Tiêu đề', 'required' => 'required', 'data-parsley-error-message' => 'Tiêu đề không được để trống'])) ?>
                                <?= $this->formelementerrors($form->get('title'),['class' => 'parsley-errors-list filled']) ?>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <?= $this->formelement($form->get('content')->setAttributes(['class' => 'summernote form-control', 'placeholder'=>'Tên trang', 'required' => 'required', 'data-parsley-error-message' => 'Nội dung không được để trống'])) ?>
                                <?= $this->formelementerrors($form->get('content'),['class' => 'parsley-errors-list filled']) ?>
                            </div>
                        </div>
                    </div>

                    <div class="form-actions">
                        <?=$this->formelement($form->get('submit')->setAttributes(['class' => 'btn btn-default']))?>
                        <?=$this->formelement($form->get('reset')->setAttributes(['class' => 'btn']))?>
                    </div>

                </div>
            </div>
        </div>

        <?php if(!empty($result->getData())): ?>
            <div class="col-sm-4">
                <div class="card-box">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <h3 class="m-t-0 header-title m-b-20" for="firstName">Yêu cầu bạn đã gửi</h3>
                                <div class="search-result-box">
                                    <ul class="taskList list-unstyled">
                                        <?php foreach($result->getData() as $r): ?>
                                            <li class="task-info">
                                                <h4 class="header-title m-t-0 m-b-5">
                                                    <a class="text-dark" href="/admin/question/<?= $r->getId() ?>"><?= $r->getTitle() ?></a>
                                                </h4>
                                                <p class="text-muted m-b-0 font-13">
                                                    <?= DateBase::toDisplayDateTime($r->getCreatedDateTime()) ?> - #<?= $r->getId() ?>
                                                </p>
                                            </li>
                                        <?php endforeach; ?>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php endif; ?>

    </div>

</form>
