<?php
$key = $this->keyName;
$page = $this->page;
$extra = json_decode($page->getExtraContent(), true);
if(!empty($key)):
    ?>
    <div class="card-box card-box__element">
        <?php
        foreach($key as $c):
            $i = explode(':', $c);
            ?>
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                        <label class="control-label" for="<?= $i[0] ?>"><?= $i[0] ?></label>
                        <?php if($i[1] == 'text'): ?>
                            <input name="field_<?= $i[2] ?>" value="<?= $extra[$i[2]] ?>" class="form-control" placeholder="<?= $i[0] ?>" />
                        <?php elseif ($i[1] == 'textarea'): ?>
                            <textarea name="field_<?= $i[2] ?>" class="form-control" placeholder="<?= $i[0] ?>"><?= $extra[$i[2]] ?></textarea>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>