<?php
use Home\Model\DateBase;
echo $this->headtitle($this->escapehtml($this->translate('Danh sách yêu cầu')));
$result = $this->results;
?>
<style>
    .task__list {
        display: flex;
        flex-wrap: wrap;
    }
    .task__item {
        width: 33.333%;
        padding: 0 10px;
    }
</style>

<form method="post" enctype="multipart/form-data" data-parsley-validate novalidate>
    <div class="row">
        <?php if(!empty($result->getData())): ?>
            <div class="col-sm-12">
                <div class="card-box">
                    <h3 class="m-t-0 header-title m-b-20" for="firstName">Danh sách yêu cầu</h3>
                    <div class="row">
                        <div class="task__list">
                            <?php foreach($result->getData() as $r): ?>
                            <div class="task__item">
                                <div class="form-group">
                                    <ul class="taskList list-unstyled">
                                        <li class="task-info">
                                            <h4 class="header-title m-t-0 m-b-5">
                                                <a class="text-dark" href="/admin/question/<?= $r->getId() ?>"><?= $r->getTitle() ?></a>
                                            </h4>
                                            <p class="text-muted m-b-0 font-13">
                                                <?= DateBase::toDisplayDateTime($r->getCreatedDateTime()) ?> - #<?= $r->getId() ?>
                                            </p>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>
            </div>
        <?php endif; ?>

    </div>

</form>
