<?php
use Home\Model\DateBase;
$view = $this->view;
echo $this->headtitle($this->escapehtml($this->translate('Yêu cầu - '.$view->getTitle())));
$result = $this->results;
?>

<form method="post" enctype="multipart/form-data" data-parsley-validate novalidate>
    <div class="row">
        <div class="col-sm-8">
            <div class="card-box">
                <div class="row">
                    <div class="col-md-12">
                        <div class="pull-left">
                            <h4 class="m-t-0 header-title m-b-10"><b><?= $view->getTitle() ?></b></h4>
                            <p class="text-muted m-b-0 font-13">
                                Ngày tạo: <?= DateBase::toDisplayDateTime($view->getCreatedDateTime()) ?> -
                                Cập nhập: <?= DateBase::toDisplayDateTime($view->getUpdateDateTime()) ?>
                            </p>
                        </div>
                        <div class="pull-right">
                            <button type="button" class="btn btn-info waves-effect waves-light"><span class="btn-label"><i class="fa fa-send-o"></i></span>Mới</button>
                        </div>
                    </div>
                </div>

                <hr style="margin: 15px 0">
                <?= $view->getContent(); ?>
            </div>
            <div class="card-box">
                <div class="comment">
                    <img src="/assets/images/users/avatar-1.jpg" alt="" class="comment-avatar">
                    <div class="comment-body">
                        <div class="comment-text">
                            <div class="comment-header">
                                <a href="#" title="">DWEB</a><span>02/10/2018 9:01:27</span>
                            </div>
                            Vẫn chưa thấy sự thay đổi, cần deadline cụ thể.
                        </div>
                        <div class="comment-footer">
                            <a href="#"><i class="fa fa-thumbs-o-up"></i></a>
                            <a href="#"><i class="fa fa-thumbs-o-down"></i></a>
                            <a href="#">Reply</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-box">
                <form method="post" class="well">
                    <span class="input-icon icon-right">
                        <textarea rows="2" class="form-control" placeholder="Bình luận"></textarea>
                    </span>
                    <div class="p-t-10 pull-right">
                        <a class="btn btn-sm btn-primary waves-effect waves-light">Gửi</a>
                    </div>
                    <ul class="nav nav-pills profile-pills m-t-10">
                        <li>
                            <a href="#"><i class="fa fa-user"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-location-arrow"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class=" fa fa-camera"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-smile-o"></i></a>
                        </li>
                    </ul>

                </form>
            </div>
        </div>

        <?php if(!empty($result->getData())): ?>
            <div class="col-sm-4">
                <div class="card-box">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <h3 class="m-t-0 header-title m-b-20" for="firstName">Yêu cầu bạn đã gửi</h3>
                                <ul class="taskList list-unstyled">
                                    <?php foreach($result->getData() as $r): ?>
                                        <li class="task-info">
                                            <h4 class="header-title m-t-0 m-b-5">
                                                <a class="text-dark" href="/admin/question/<?= $r->getId() ?>"><?= $r->getTitle() ?></a>
                                            </h4>
                                            <p class="text-muted m-b-0 font-13">
                                                <?= DateBase::toDisplayDateTime($r->getCreatedDateTime()) ?> - #<?= $r->getId() ?>
                                            </p>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php endif; ?>

    </div>

</form>
