<?php if(!empty($this->bannerList['banner-list banner']['banner-list'])):?>
<section class="hero-slider">
    <ul class="banner owl-carousel owl-theme">
        <?php
            foreach($this->bannerList['banner-list banner']['banner-list'] as $k => $b):
                $image = json_decode($b['image'], true);
                if(!empty($image)) {
                    $imageFirst = array_shift($image);
                }
                ?>
            <li>
                <figure class="lazy banner-image" data-src="<?= !empty($imageFirst) ? $imageFirst:null ?>">
                    <div>
                        <h2><?= $b['title'] ?></h2>
                        <p><?= $b['description'] ?></p>
                        <a href="<?= $b['url'] ?>">Xem</a>
                    </div>
                </figure>
            </li>
        <?php endforeach;?>
    </ul>
</section>
<?php endif;?>