<?php if(!empty($this->tabProductLayout['tab-product1 product']['tab-product1']) || !empty($this->tabProductLayout['tab-product2 product']['tab-product3']) || !empty($this->tabProductLayout['tab-product3 product']['tab-product3'])):?>
<section class="tab-product product">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <ul class="tab-product__title nav nav-products nav-tabs " role="tablist">
                    <?php if(!empty($this->tabProductLayout['tab1-title text']['value'])):?>
                        <li role="presentation" class="active">
                            <a  href="#tab1-<?=$this->id?>" aria-controls="tab1-<?=$this->id?>" role="tab" data-toggle="tab"><?= $this->tabProductLayout['tab1-title text']['value']?></a>
                        </li>
                    <?php endif;?>
                    <?php if(!empty($this->tabProductLayout['tab2-title text']['value'])):?>
                        <li role="presentation">
                            <a href="#tab2-<?=$this->id?>" aria-controls="tab2-<?=$this->id?>" role="tab" data-toggle="tab"><?= $this->tabProductLayout['tab2-title text']['value']?></a>
                        </li>
                    <?php endif;?>
                    <?php if(!empty($this->tabProductLayout['tab3-title text']['value'])):?>
                        <li role="presentation">
                            <a href="#tab3-<?=$this->id?>" aria-controls="tab3-<?=$this->id?>" role="tab" data-toggle="tab"><?= $this->tabProductLayout['tab3-title text']['value']?></a>
                        </li>
                    <?php endif;?>
                </ul>
                <div class="tab-content">
                    <div id="tab1-<?=$this->id?>" role="tabpanel" class="tab-pane fade in active">
                        <ul class="lP feature-product__list">
                            <?php foreach($this->tabProductLayout['tab-product1 product']['tab-product1'] as $k => $p):
                                $image = json_decode($p['image'], true);
                                if(!empty($image)){
                                    $imageFirst = array_shift($image);
                                }
                                $imgs = array_slice(json_decode($p['image'], true), 0, 2);
                                ?>
                                <li class="feature-product__item">
                                    <div class="feature-product__item--wrapper">
                                        <a href="<?= $p['url'] ?>">
                                            <figure class="lazy two-up__product-image" data-src="<?= !empty($imgs) ? $imgs['0']:null ?>"></figure>
                                            <figure class="lazy two-up__product-image two-up__product-image__two" data-src="<?= !empty($imgs) ? $imgs['1']:null ?>"></figure>
                                        </a>
                                    </div>
                                    <h3 class="feature-product__item--title"><?= $p['title'] ?></h3>
                                    <p class="price"><?= $p['priceOld'] ? number_format($p['priceOld']).' đ<i>'.number_format($p['price']).' đ</i>':number_format($p['price']).' đ' ?></p>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                    <div id="tab2-<?=$this->id?>" role="tabpanel" class="tab-pane fade">
                        <ul class="lP feature-product__list">
                            <?php foreach($this->tabProductLayout['tab-product2 product']['tab-product2'] as $k => $p):
                                $image = json_decode($p['image'], true);
                                if(!empty($image)){
                                    $imageFirst = array_shift($image);
                                }
                                $imgs = array_slice(json_decode($p['image'], true), 0, 2);
                                ?>
                                <li class="feature-product__item">
                                    <div class="feature-product__item--wrapper">
                                        <a href="<?= $p['url'] ?>">
                                            <figure class="lazy two-up__product-image" data-src="<?= !empty($imgs) ? $imgs['0']:null ?>"></figure>
                                            <figure class="lazy two-up__product-image two-up__product-image__two" data-src="<?= !empty($imgs) ? $imgs['1']:null ?>"></figure>
                                        </a>
                                    </div>
                                    <h3 class="feature-product__item--title"><?= $p['title'] ?></h3>
                                    <p class="price"><?= $p['priceOld'] ? number_format($p['priceOld']).' đ<i>'.number_format($p['price']).' đ</i>':number_format($p['price']).' đ' ?></p>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                    <div id="tab3-<?=$this->id?>" role="tabpanel" class="tab-pane fade">
                        <ul class="lP feature-product__list">
                            <?php foreach($this->tabProductLayout['tab-product3 product']['tab-product3'] as $k => $p):
                                $image = json_decode($p['image'], true);
                                if(!empty($image)){
                                    $imageFirst = array_shift($image);
                                }
                                $imgs = array_slice(json_decode($p['image'], true), 0, 2);
                                ?>
                                <li class="feature-product__item">
                                    <div class="feature-product__item--wrapper">
                                        <a href="<?= $p['url'] ?>">
                                            <figure class="lazy two-up__product-image" data-src="<?= !empty($imgs) ? $imgs['0']:null ?>"></figure>
                                            <figure class="lazy two-up__product-image two-up__product-image__two" data-src="<?= !empty($imgs) ? $imgs['1']:null ?>"></figure>
                                        </a>
                                    </div>
                                    <h3 class="feature-product__item--title"><?= $p['title'] ?></h3>
                                    <p class="price"><?= $p['priceOld'] ? number_format($p['priceOld']).' đ<i>'.number_format($p['price']).' đ</i>':number_format($p['price']).' đ' ?></p>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>

<?php endif;?>