<?php

    $this->headMeta()->appendName('description', ('Dịch vụ quản lý nội dung website, quảng cáo facebook ads giá rẻ, quảng cáo adwords, dịch vụ seo seongon'));
    $this->headMeta()->appendName('keywords', ('Quản lý nội dung website, quảng cáo facebook, quảng cáo adwords, dịch vụ seo'));

    $this->headMeta()->appendProperty('fb:app_id', '1697190970583102');
    $this->headMeta()->appendProperty('article:author', 'https://www.facebook.com/dwebvietnam');
    $this->headMeta()->appendProperty('og:locale', 'vi_VN');
    $this->headMeta()->appendProperty('og:image', 'http://dweb.vn/tp/dweb/image/dweb-thumbnail.png');
    $this->headMeta()->appendProperty('og:url', 'http://dweb.vn');
    $this->headMeta()->appendProperty('og:title', 'DWEB, công cụ tạo website, Thiet ke website gia re, Thiết kế website giá rẻ, thiết kế website 300k, thiết kế website chuyên nghiệp, thiết kế website bán hàng, thiết kế website độc quyền, thiết kế website thương hiệu độc quyền,');
    $this->headMeta()->appendProperty('og:description', ('Thiet ke website gia re, Thiết kế website giá rẻ, thiết kế website 300k, thiết kế website chuyên nghiệp, thiết kế website bán hàng, thiết kế website độc quyền, thiết kế website thương hiệu độc quyền, DWEB là công cụ tạo website, bán hàng, giới thiệu công ty, thời trang, mỹ phẩm, kiến trúc ... Chúng tôi luôn quan tâm tới từng sản phẩm & lắng nghe khách hàng'));

    $this->headMeta()->appendProperty('twitter:card', 'DWEB.VN');
    $this->headMeta()->appendProperty('twitter:title', 'DWEB, công cụ tạo website, Thiet ke website gia re, Thiết kế website giá rẻ, thiết kế website 300k, thiết kế website chuyên nghiệp, thiết kế website bán hàng, thiết kế website độc quyền, thiết kế website thương hiệu độc quyền,');
    $this->headMeta()->appendProperty('twitter:image', 'http://dweb.vn/tp/dweb/image/dweb-thumbnail.png');
    $this->headMeta()->appendProperty('twitter:description', 'Thiet ke website gia re, Thiết kế website giá rẻ, thiết kế website 300k, thiết kế website chuyên nghiệp, thiết kế website bán hàng, thiết kế website độc quyền, thiết kế website thương hiệu độc quyền, DWEB là công cụ tạo website, bán hàng, giới thiệu công ty, thời trang, mỹ phẩm, kiến trúc ... Chúng tôi luôn quan tâm tới từng sản phẩm & lắng nghe khách hàng');
    $optionPage = $this->home()->optionPage();
?>

<section class="hero">
    <div id="large-header" class="hero-inner">
        <canvas id="demo-canvas" width="1366" height="341"></canvas>
        <div class="main-title">
            <h2 class="hero-title wp1">Bạn đã sẵn sàng<br/>Giới thiệu dịch vụ kinh doanh của mình ?</h2>
            <p class="hero-description wp2">Dưới đây là các bước để bạn thiết lập các bước cần thiết để tiếp cận khách hàng lớn, những dịch vụ.</p>
            <a class="hero-button_link wp3">Tiếp theo</a>
            <a class="hero-mouse_scroll"></a>
        </div>
    </div>
</section>

<section class="service-content">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-md-offset-6">
                <h2 class="service-content__headline"><span>Dịch vụ</span><br/>quản lý nội dung website</h2>
                <div class="service-content__description">
                    <p>Nếu bạn không biết nhiều về quản lý website thì đây là dịch vụ cho bạn, chỉ với <strong>1.000.000</strong> tr.</p>
                    <p>Bạn đã có những cài đặt cơ bản và đầu tiên về sản phẩm dịch vụ của mình.
                    Logo, banner, giới thiệu thông tin về dịch vụ công ty, sản phẩm, hướng dẫn hỗ trợ quản lý website.</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="service-content__list">
                    <div class="service-content__item">
                        <h3 class="service-content__title">Thiết kế logo</h3>
                        <div class="service-content__sub">
                            Brand name, nếu bạn đã từng đọc qua định nghĩa này thì logo là một phần trong đó, một trong những bước mà chắc chắn rằng bạn là doanh nghiệp nhỏ hay lớn đều phải quan tâm.
                        </div>
                    </div>
                    <div class="service-content__item">
                        <h3 class="service-content__title">Thiết kế banner</h3>
                        <div class="service-content__sub">
                            Nếu bạn muốn khách hàng quan tâm tới dịch vụ hay sản phẩm của mình thì những slider giới thiệu ngay ngoài trang chủ sẽ điều hướng tới dịch vụ của bạn nhanh hơn.
                        </div>
                    </div>
                    <div class="service-content__item">
                        <h3 class="service-content__title">Cập nhật website</h3>
                        <div class="service-content__sub">
                            Cập nhật những thông tin cần thiết của một doanh nghiệp, chúng tôi sẽ hỗ trợ bạn cập nhật logo, banner, giới thiệu về công ty, liên hệ.
                        </div>
                    </div>
                    <div class="service-content__item">
                        <h3 class="service-content__title">Hướng dẫn quản lý</h3>
                        <div class="service-content__sub">
                            Việc sau này bạn muốn chủ động quản lý nhưng khó khăn, thì đây là lần đầu tiên và duy nhất bạn cần bỏ ra số tiền nhỏ để về sau có thể chủ động hơn.
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="facebook-ads">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <h2 class="service-content__headline"><span>Quảng cáo</span><br/>Facebook Ads</h2>
                <div class="service-content__description">
                    <p>
                        Việc mẫu quảng cáo của bạn được tiếp cận tới <strong>30.000.000</strong> triệu người dùng trên toàn Việt Nam hoặc khu vực bạn đang cung cấp dịch vụ với số lượng người nhỏ hơn, thời gian sử dụng Facebook của người Việt đang là <strong>2.5h</strong>/ ngày, ngay từ bây giờ bạn cũng có thể bỏ số tiền tối thiểu <strong>50.000</strong> đ/ ngày để tiếp cận <strong>~10.000</strong> người dùng Facebook đang online.
                    </p>
                    <p>
                        Nếu dịch vụ hay sản phẩm bạn đang cung cấp thuộc nhóm hàng mua hàng theo cảm xúc thì Facebook là một kênh mà bạn chắc chắn không thể bỏ qua.
                    </p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="service-content__list">
                    <div class="service-content__item">
                        <h3 class="service-content__title">Dự kiến chi phí</h3>
                        <div class="service-content__sub">
                            Ví dụ bạn chạy hết <= 5.000.000 tr thì chúng tôi nhận khoảng 20% trên tổng ngân sách bạn chạy, nếu lớn hơn 15.000.000/ tháng thì là 15%. Bên cạnh đây chúng tôi sẽ đưa ra tại sao bạn nên chọn chúng tôi.
                        </div>
                    </div>
                    <div class="service-content__item">
                        <h3 class="service-content__title">Thiết kế ảnh bìa</h3>
                        <div class="service-content__sub">
                            Thỉng thoảng bạn hay nhìn thấy cái ảnh xuất hiện trên Facebook mà nó ghi phía dưới là tài trợ tức là họ đang quảng cáo đấy, ảnh và nội dung quyết định khách hàng có click vào quảng cáo của bạn không.
                        </div>
                    </div>
                    <div class="service-content__item">
                        <h3 class="service-content__title">Target tối ưu</h3>
                        <div class="service-content__sub">
                            Bọn tôi chạy nhiều cho khách, vậy nên kinh nghiệm để target đối tượng và tệp khách hàng cũng khác bọt hơn, cùng với số tiền đó mà các bạn tự chạy thay vào sử dụng dịch vụ của chúng tôi, chúng tôi cam kết có kết quả tốt hơn.
                        </div>
                    </div>
                    <div class="service-content__item">
                        <h3 class="service-content__title">Báo cáo</h3>
                        <div class="service-content__sub">
                          Ở một nơi nào đó việc bạn bỏ ra 5tr chạy Facebook nhưng không biết chiến dịch của mình chạy có hiệu quả không, tương tác tốt không ... bạn không nhìn thấy được báo cáo tài chính, kết quả . Chúng tôi sẽ add bạn vào một tài khoản quảng cáo, ở đó bạn có thể nhìn thấy tất cả.
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="google-ads">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-md-offset-6">
                <h2 class="google-ads__headline"><span>Quảng cáo</span><br/>Google Adwords</h2>
                <div class="service-content__description">
                    <p>
                        Facebook ads hay Google adwords ?
                    </p>
                    <p>
                        Facebook thuộc nhóm đối tượng khách hàng mua hàng theo cảm xúc, tức họ thể mua hàng không có dự tính trước, kiểu như quần áo, giày dép, đồ ăn, mỹ phẩm, trang sức ...
                        <br/>
                        Với Google thì sao, là nhóm đối tượng mua hàng khi có nhu cầu phát sinh, đại loại kiểu như xây nhà, thiết kế nội thất, bán thuốc hôi nách, thuốc mọc tóc, yếu sinh lý.
                    </p>
                    <p>
                        Vai trò của chúng tôi sẽ vẫn giống như trên Facebook, đánh giá và phân tích khách hàng giúp bạn, lên chiến dịch và tạo ra chương trình quảng cáo tuỳ ngân sách của bạn, ngân sách nhỏ cũng hỗ trợ bạn luôn, quan trọng nhất là doanh nghiệp tồn tại và bán được hàng.
                    </p>
                    <p>
                        Một cái nữa là chúng tôi là Partner Google
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="service-seo">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <h2 class="service-seo__headline"><span>Dịch vụ</span><br/>Seo</h2>
                <div class="service-content__description">
                    <p>
                        Nếu bạn sử dụng dịch vụ seo của chúng tôi thì được chính các anh chàng kĩ thuật của <strong>SEONGON.COM</strong> làm việc để đẩy dần dần các từ khoá của bạn lên top, <strong>DWEB.VN</strong> là nền tảng tạo website duy nhất tại Việt Nam được chuyên gia seo <strong>Mai Xuân Đạt</strong> chứng nhận chuẩn seo.
                    </p>
                    <p>
                        Lợi ích ? bạn có thể đọc về dịch vụ seo chi tiết của chúng tôi tại đây, trong quá trình làm việc được DWEB.VN hỗ trợ về những kỹ thuật website chuẩn seo sẽ giúp bạn tiết kiệm chi phí hơn.
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>

<section style="margin: 0;" class="client lazy" data-src="/tp/dweb/image/alert-bg.jpg" >
    <div class="container">
        <span class="client__icon"></span>
        <div class="client__description">
            Tất cả những gì chúng tôi đang làm vì mục đích tồn tại và phát triển doanh nghiệp, để gíup các bạn có thể tiếp cận được những đối tượng khách hàng lớn, ở đó có người dùng. Gần đây nhất trên mạng có những khoá học online kinh doanh làm giàu, bản chất công việc trên
        </div>
    </div>
</section>