<?php
    $this->translate('Trang chủ');
    $this->headMeta()->appendName('description', ('Thiet ke website gia re, Thiết kế website giá rẻ, thiết kế website 300k, thiết kế website chuyên nghiệp, thiết kế website bán hàng, thiết kế website độc quyền, thiết kế website thương hiệu độc quyền, DWEB công cụ tạo website, bán hàng, giới thiệu công ty, thời trang, mỹ phẩm, kiến trúc ... Chúng tôi luôn quan tâm tới từng sản phẩm & lắng nghe khách hàng'));
    $this->headMeta()->appendName('keywords', ('DWEB, công cụ tạo website, Thiet ke website gia re, Thiết kế website giá rẻ, thiết kế website 300k, thiết kế website chuyên nghiệp, thiết kế website bán hàng, thiết kế website độc quyền, thiết kế website thương hiệu độc quyền,'));

    $this->headMeta()->appendProperty('fb:app_id', '1697190970583102');
    $this->headMeta()->appendProperty('article:author', 'https://www.facebook.com/dwebvietnam');
    $this->headMeta()->appendProperty('og:locale', 'vi_VN');
    $this->headMeta()->appendProperty('og:image', 'http://dweb.vn/tp/dweb/image/dweb-thumbnail.png');
    $this->headMeta()->appendProperty('og:url', 'http://dweb.vn');
    $this->headMeta()->appendProperty('og:title', 'DWEB, công cụ tạo website, Thiet ke website gia re, Thiết kế website giá rẻ, thiết kế website 300k, thiết kế website chuyên nghiệp, thiết kế website bán hàng, thiết kế website độc quyền, thiết kế website thương hiệu độc quyền,');
    $this->headMeta()->appendProperty('og:description', ('Thiet ke website gia re, Thiết kế website giá rẻ, thiết kế website 300k, thiết kế website chuyên nghiệp, thiết kế website bán hàng, thiết kế website độc quyền, thiết kế website thương hiệu độc quyền, DWEB là công cụ tạo website, bán hàng, giới thiệu công ty, thời trang, mỹ phẩm, kiến trúc ... Chúng tôi luôn quan tâm tới từng sản phẩm & lắng nghe khách hàng'));

    $this->headMeta()->appendProperty('twitter:card', 'DWEB.VN');
    $this->headMeta()->appendProperty('twitter:title', 'DWEB, công cụ tạo website, Thiet ke website gia re, Thiết kế website giá rẻ, thiết kế website 300k, thiết kế website chuyên nghiệp, thiết kế website bán hàng, thiết kế website độc quyền, thiết kế website thương hiệu độc quyền,');
    $this->headMeta()->appendProperty('twitter:image', 'http://dweb.vn/tp/dweb/image/dweb-thumbnail.png');
    $this->headMeta()->appendProperty('twitter:description', 'Thiet ke website gia re, Thiết kế website giá rẻ, thiết kế website 300k, thiết kế website chuyên nghiệp, thiết kế website bán hàng, thiết kế website độc quyền, thiết kế website thương hiệu độc quyền, DWEB là công cụ tạo website, bán hàng, giới thiệu công ty, thời trang, mỹ phẩm, kiến trúc ... Chúng tôi luôn quan tâm tới từng sản phẩm & lắng nghe khách hàng');
    $optionPage = $this->home()->optionPage();

?>

<section class="hero">
    <div id="large-header" class="hero-inner">
        <canvas id="demo-canvas" width="1366" height="341"></canvas>
        <div class="main-title">
            <h2 class="hero-title wp1">Nền tảng website <span>chuẩn seo</span><br/> <p>duy nhất tại Việt Nam, do <a href="http://seongon.com" target="_blank"><i class="slider__icon"></i></a> Phát triển</p></h2>
            <a class="hero-button_link wp3" data-toggle="modal" data-target="#modalRegisterDWEB">Dùng thử miễn phí</a>
            <a class="hero-mouse_scroll"></a>
        </div>
    </div>
</section>

<section class="about lazy" data-src="/tp/dweb/image/about-bg.png">
    <div class="container about-container">
        <div class="about-inner">
            <h2 class="about-title wp1">Về <span>chúng tôi</span></h2>
            <div class="about-description_sub wp2">
                <p>DWEB được viết tắt trong từ Difference Web, chúng tôi áp dụng những kỹ năng, sự khéo léo và tỉ mỉ đến từng dự án và phấn đấu để cung cấp giải pháp thiết kế sáng tạo, luôn muốn mang đến sự trải nghiệm khách hàng trong những sản phẩm mà chúng tôi tạo nên</p>
                <p>Từ những bản thiết kế, những dòng code sáng, điểm ảnh hoàn hảo trong style, sự đơn giản trong Website mà vẫn đảm bảo được người dùng có những trải nghiệm trực quan khi sử dụng</p>
            </div>
            <a class="btn-d about-button wp2" href="">Đọc tiếp</a>
        </div>
    </div>
</section>

<section class="video lazy" data-src="/tp/dweb/image/back.jpg">
    <div class="container">
        <div class="pulsation wp1">
            <a class="video__button" data-video-id="<?= $optionPage['video'] ? $optionPage['video']:'8Ux3NCnE3Lk' ?>"></a>
        </div>
    </div>
</section>

<section class="our-selection">
    <div class="container">
        <h2 class="title-h2 our-selection__headline"><span>Tại sao bạn chọn</span> chúng tôi</h2>
        <div class="our-selection__inner">
            <div class="our-selection__row wp1">
                <i class="fa fa-pencil" aria-hidden="true"></i>
                <h3 class="our-selection__title">SEONGON chuẩn seo</h3>
                <p class="our-selection__description">Nhiều năm làm việc cho nhiều khách hàng lớn nhỏ, SEONGON đã phát triển lên một hệ thống DWEB giúp khách hàng doanh nghiệp tối ưu và giảm bớt chi phí khi phát triển website tại đây.</p>
            </div>

            <div class="our-selection__row wp2">
                <i class="fa fa-sun-o" aria-hidden="true"></i>
                <h3 class="our-selection__title">SEONGON Marketing</h3>
                <p class="our-selection__description">Với một website mới với nội dung và hình ảnh hấp dẫn là chưa đủ, để tiếp cận một đối tượng khách hàng lớn thì chúng ta phải đầu tư Quảng cáo, SEO, các kênh truyền thông. Chúng tôi sẽ tư vấn với ngân sách của khách hàng để tiếp cận được những tệp khách hàng phù hợp.</p>
            </div>

            <div class="our-selection__row wp3">
                <i class="fa fa-html5" aria-hidden="true"></i>
                <h2 class="our-selection__title">Chúng tôi làm chủ về Công nghệ</h2>
                <p class="our-selection__description">Khác với những Nhà thiết kế khác bị lệ thuộc vào một ngôn ngữ hoặc một nền tảng CMS cố định, chúng tôi làm chủ nhiều công nghệ để có thể tự do đưa ra những lựa chọn công nghệ phù hợp với tính chất & quy mô Dự án.</p>
            </div>

            <div class="our-selection__row wp1">
                <i class="fa fa-user" aria-hidden="true"></i>
                <h3 class="our-selection__title">Chúng tôi am hiểu về Người dùng</h3>
                <p class="our-selection__description">Chúng tôi cho rằng một Website chỉ được thiết kế thành công khi nó am hiểu người dùng đến mức khiến họ không thể cưỡng lại việc thực hiện một cú điện thoại, đặt một đơn hàng, gửi một form yêu cầu ... ngay từ lượt truy cập đầu tiên.</p>
            </div>
            <div class="our-selection__row wp2">
                <i class="fa fa-line-chart" aria-hidden="true"></i>
                <h3 class="our-selection__title">Chúng tôi tận tâm với Dự án</h3>
                <p class="our-selection__description">Sau bàn giao, sự quan tâm của chúng tôi với Dự án không dừng lại. Trong quá trình website vận hành, phản ứng của người dùng luôn được chúng tôi theo dõi & đo lường nhằm đưa ra những cải tiến tiếp theo.</p>
            </div>
            <div class="our-selection__row wp3">
                <i class="fa fa-gift" aria-hidden="true"></i>
                <h3 class="our-selection__title">Chúng tôi xứng đáng & tin cậy</h3>
                <p class="our-selection__description">Sau 03 năm phục vụ thị trường nước ngoài và quan sát những Nhà thiết kế Web khác hoạt động tại thị trường Việt Nam ... Chúng tôi thành lập DWEB với sứ mệnh cung cấp cho Khách hàng trải nghiệm về một Dịch vụ Thiết kế Website thực sự.</p>
            </div>
        </div>
        <div class="our-selection__choose">
            <div class="our-selection__choose-img wp1">
                <figure class="our-selection__choose-image lazy" data-src="/tp/dweb/image/feature-bg.png"></figure>
            </div>
            <div class="our-selection__choose-list">
                <div class="our-selection__choose-item wp1">
                    <i class="fa fa-clock-o" aria-hidden="true"></i><h2>Tốc độ <span>tải trang</span></h2>
                </div>
                <div class="our-selection__choose-item wp2">
                    <i class="fa fa-tablet" aria-hidden="true"></i><h2>Hỗ trợ <span>Nhiều thiết bị</span></h2>
                </div>
                <div class="our-selection__choose-item wp3">
                    <i class="fa fa-camera" aria-hidden="true"></i><h2>Điểm ảnh <span>Hoàn hảo</span></h2>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="quote">
    <div class="container">
        <div class="quote__inner">
            <div class="quote__item">
                <h2 class="header-sologan"><span class="logo-first-key">D</span>WEB.</h2>
            </div>
            <div class="quote__item">
                <p>Giao diện đáp ứng với mọi phong cách <br/>
                    Duới đây là những giao diện bạn có thể dùng</p>
            </div>
            <div class="quote__item quote__item--right">
                <a class="btn-d quote__button" href="/kho-giao-dien.html">Xem</a>
            </div>
        </div>
    </div>
</section>

<?php if(!empty($optionPage['du-an-tieu-bieu'])): ?>
<section class="project">
    <div class="container">
        <h2 class="project-title title-h2 align-center">Giao diện</h2>
        <div class="project-description">
            Hãy lựa chọn một theme phù hợp với cửa hàng kinh doanh Online của bạn! <br/>
            Xem các website mẫu của khách hàng đã tin tưởng sử dụng DWEB.
        </div>
        <div class="project-list">

            <?php $i = 0; foreach ($optionPage['du-an-tieu-bieu'] as $p):
                $i++;
                $image = json_decode($p['image'], true);
                if(!empty($image)){
                    $imageFirst = array_shift($image);
                }
                $extraContent = json_decode($p['extraContent'], true);
            ?>
            <div class="project-item">
                <div class="project-inner">
                    <figure class="lazy project-image" data-src="<?= $imageFirst ?>"></figure>
                    <div class="project-control">
                        <a class="btn-d project__button-reviewer" target="_blank" href="<?= $p['intro'] ?>">Xem thử</a>
                        <a class="btn-d project__button-detail" href="/register-<?= vnString($p['title']) ?>.html">Tạo website</a>
                        <h3 class="project__title"><?= $p['title'] ?></h3>
                        <p class="project__description"><?= !empty($extraContent['mo-ta']) ? $extraContent['mo-ta']:null ?></p>
                    </div>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
        <div class="project__button-load-more">
            <div class="project__button-line"></div>
            <a class="project__button-link" href="/kho-giao-dien.html">Xem tất cả</a>
            <div class="project__button-line"></div>
        </div>
    </div>
</section>
<?php endif; ?>
<section class="client lazy" data-src="/tp/dweb/image/alert-bg.jpg">
    <div class="container">
        <span class="client__icon"></span>
        <div class="client__description">
            Sau 2 năm hình thành và phát triển, lợi thế lớn nhất của chúng tôi là luôn luôn lắng nghe và đáp ứng kịp thời những yêu cầu của khách hàng. Chính khách hàng, sự tin tưởng của họ là động lức để chúng tôi hoàn thiện và phát triển sản phẩm. Là sức mạnh để chúng tôi vươn xa trong lĩnh vực tạo website và thương mại điện tử tại Việt Nam.
        </div>
    </div>
</section>