<section class="hero hero__tet">
    <div id="large-header" class="hero-inner">
        <canvas id="demo-canvas" width="1366" height="341"></canvas>
        <div class="main-title">
            <h2 class="hero-title wp1">Chỉ với <span>500k</span> bạn đã có một<br/><span>Landing/ Website</span> bán hàng cuối năm </h2>
            <p class="hero-description wp2">Đẩy mạnh doanh số cuối năm, một landing page, website luôn cần một cửa hàng, doanh nghiệp.</p>
            <a class="hero-button_link wp3">Tiếp theo</a>
            <a class="hero-mouse_scroll"></a>
        </div>
    </div>
</section>
<section class="quote quote__tet">
    <div class="container">
        <div class="quote__inner">
            <div class="quote__item">
                <h2 style="margin: 0;text-align: center" class="title-h2 our-selection__headline"><span>Xả hàng cuối năm !</span> Bán hàng cùng hệ thống<br/>website chuẩn seo <span>SEONGON.</span></h2>
            </div>
        </div>
    </div>
</section>
<section class="our-selection our-selection__tet" style="padding: 60px 0 30px;background-color: #f9eded;background-image: url(/tp/dweb/image/background__our.png);background-size: 100%;background-position: center;">
    <div class="container">
        <h2 class="title-h2 our-selection__headline">Vô địch bán hàng <span>cuối năm.</span></h2>
        <div class="our-selection__inner">
            <div class="our-selection__row wp1">
                <i class="fa fa-pencil" aria-hidden="true"></i>
                <h3 class="our-selection__title">Quản lý danh sách sản phẩm</h3>
                <p class="our-selection__description">Một danh sách sản phẩm được khuyến mãi, giúp khách hàng có thể theo dõi chương trình khuyến mãi một cách trực quan hơn, những chi tiết về thông tin sản phẩm, bài viết, video ... sẽ giúp khách hàng có những thông tin về sản phẩm, từ đó khách hàng sẽ tin tưởng hơn, đặt hàng nhanh hơn.</p>
            </div>
            <div class="our-selection__row wp3">
                <i class="fa fa-html5" aria-hidden="true"></i>
                <h2 class="our-selection__title">Quảng cáo với Google hay Facebook</h2>
                <p class="our-selection__description">Một chiến dịch quảng cáo dịp cuối năm giải quyết bài toán tồn kho, những đối tượng khách hàng lớn từ Google hay Facebook là một trong những kênh mà doanh nghiệp không thể bỏ qua, việc có một Landing page/ Website giúp việc tỉ lệ chuyển đổi cao hơn.</p>
            </div>
            <div class="our-selection__row wp2">
                <i class="fa fa-sun-o" aria-hidden="true"></i>
                <h3 class="our-selection__title">Quản lý đơn hàng</h3>
                <p class="our-selection__description">Một đơn hàng của khách hàng hay một form thông tin khách hàng gửi, là những data mà bạn không nên bỏ qua, việc khách hàng đang bận rộn và mong muốn có những xử lý nhanh để được giải đáp nhanh về sản phẩm hay dịch vụ là điều mà khách hàng cần.</p>
            </div>
            <div class="our-selection__row wp2">
                <i class="fa fa-sun-o" aria-hidden="true"></i>
                <h3 class="our-selection__title">Nhận biết thương hiệu</h3>
                <p class="our-selection__description">Việc có một landing, website giúp khách hàng tăng nhận biết thương hiệu của bạn hơn, một chiến dịch tết chỉ với <strong>500k</strong> giúp truyền đạt được nhiều thông tin dịch vụ, sản phẩm chi tiết tới người tiêu dùng.</p>
            </div>
            <div class="our-selection__row wp2">
                <i class="fa fa-sun-o" aria-hidden="true"></i>
                <h3 class="our-selection__title">Nền tảng chuẩn seo</h3>
                <p class="our-selection__description">SEONGON là một trong những đơn vị hàng đầu tại Việt Nam về Digital Marketing với trọng tâm là Google, DWEB là nền tảng chuẩn seo duy nhất tại Việt Nam do SEONGON (Mai Xuân Đạt) nghiên cứu và phát triển. Landing, website chuẩn seo sẽ dễ dàng giúp website bạn index nhanh hơn.</p>
            </div>
            <div class="our-selection__row wp2">
                <i class="fa fa-sun-o" aria-hidden="true"></i>
                <h3 class="our-selection__title">Tư vấn Digital Marketing</h3>
                <p class="our-selection__description">SEONGON là đơn vị hàng đầu trong lĩnh vực Dizital Marketing online, việc lên chiến dịch quảng cáo phù hợp với ngân sách khách hàng, giúp khách hàng tìm kiếm được những lượng khách hàng lớn từ Facebook hay Google.</p>
            </div>
        </div>
    </div>
</section>

<section class="project">
    <div class="container">
        <h2 class="project-title title-h2 align-center">Giao diện</h2>
        <div class="project-description">
            Danh sách landing, website hỗ trợ bán hàng cuối năm.
        </div>
        <div class="project-list">

            <div class="project-item">
                <div class="project-inner">
                    <figure class="lazy project-image" data-src="/uploads/media/7/2017/08/thumbnailt005.png"></figure>
                    <div class="project-control">
                        <a class="btn-d project__button-reviewer" target="_blank" href="http://t005.dweb.vn">Xem thử</a>
                        <a class="btn-d project__button-detail" href="/register-thuong-mai-dien-tu-t005.html">Tạo website</a>
                        <h3 class="project__title">Thương mại điện tử T005</h3>
                        <p class="project__description">Giao diện phù hợp:  Mẹ và bé, thương mại điện tử, điện máy</p>
                    </div>
                </div>
            </div>

            <div class="project-item">
                <div class="project-inner">
                    <figure class="lazy project-image" data-src="/uploads/media/7/2017/09/thumbnaila009.jpg"></figure>
                    <div class="project-control">
                        <a class="btn-d project__button-reviewer" target="_blank" href="http://a009.dweb.vn">Xem thử</a>
                        <a class="btn-d project__button-detail" href="/register-tin-tuc-bai-viet-a009.html">Tạo website</a>
                        <h3 class="project__title">TIN TỨC - BÀI VIẾT A009</h3>
                        <p class="project__description">Giao diện phù hợp: Tin tức, bài viết, giới thiệu</p>
                    </div>
                </div>
            </div>

            <div class="project-item">
                <div class="project-inner">
                    <figure class="lazy project-image" data-src="/uploads/media/7/2017/07/thumbnailt004.png"></figure>
                    <div class="project-control">
                        <a class="btn-d project__button-reviewer" target="_blank" href="http://t004.dweb.vn">Xem thử</a>
                        <a class="btn-d project__button-detail" href="/register-thuong-mai-dien-tu-t004.html">Tạo website</a>
                        <h3 class="project__title">Thương mại điện tử T004</h3>
                        <p class="project__description">Giao diện phù hợp: Thương mại điện tử, siêu thị, điện máy, điện thoại</p>
                    </div>
                </div>
            </div>

            <div class="project-item">
                <div class="project-inner">
                    <figure class="lazy project-image" data-src="/uploads/media/7/2017/08/thumbnailt005.png"></figure>
                    <div class="project-control">
                        <a class="btn-d project__button-reviewer" target="_blank" href="http://t005.dweb.vn">Xem thử</a>
                        <a class="btn-d project__button-detail" href="/register-thuong-mai-dien-tu-t005.html">Tạo website</a>
                        <h3 class="project__title">Thương mại điện tử T005</h3>
                        <p class="project__description">Giao diện phù hợp:  Mẹ và bé, thương mại điện tử, điện máy</p>
                    </div>
                </div>
            </div>
            <div class="project-item">
                <div class="project-inner">
                    <figure class="lazy project-image" data-src="/uploads/media/7/2017/09/thumbnaila009.jpg"></figure>
                    <div class="project-control">
                        <a class="btn-d project__button-reviewer" target="_blank" href="http://a009.dweb.vn">Xem thử</a>
                        <a class="btn-d project__button-detail" href="/register-tin-tuc-bai-viet-a009.html">Tạo website</a>
                        <h3 class="project__title">TIN TỨC - BÀI VIẾT A009</h3>
                        <p class="project__description">Giao diện phù hợp: Tin tức, bài viết, giới thiệu</p>
                    </div>
                </div>
            </div>
            <div class="project-item">
                <div class="project-inner">
                    <figure class="lazy project-image" data-src="/uploads/media/7/2017/07/thumbnailt004.png"></figure>
                    <div class="project-control">
                        <a class="btn-d project__button-reviewer" target="_blank" href="http://t004.dweb.vn">Xem thử</a>
                        <a class="btn-d project__button-detail" href="/register-thuong-mai-dien-tu-t004.html">Tạo website</a>
                        <h3 class="project__title">Thương mại điện tử T004</h3>
                        <p class="project__description">Giao diện phù hợp: Thương mại điện tử, siêu thị, điện máy, điện thoại</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="project__button-load-more">
            <div class="project__button-line"></div>
            <a class="project__button-link" href="/kho-giao-dien.html">Xem tất cả</a>
            <div class="project__button-line"></div>
        </div>
    </div>
</section>
<section class="quote quote__tet" style="background-image: url(/tp/dweb/image/login/bg_service_ads_fb.jpg);">
    <div class="container">
        <div class="quote__inner">
            <div class="quote__item">
                <h2 style="margin: 0;text-align: center;color: #FFF;line-height: 58px" class="title-h2 our-selection__headline">Chỉ với <span>500k</span> bạn đã có một thương hiệu riêng với một <span>landing, website</span>.<br/><p style="font-size: 13px;color: #FFF;margin: 0;">Chương trình duy nhất dịp cuối năm do <a href="http://seongon.com" target="_blank"><i style="position: relative;top: 5px" class="slider__icon"></i></a> phát hành.</p></h2>
            </div>
        </div>
    </div>
</section>

<style>
    @media only screen and (max-width: 640px) and (min-width: 200px) {
        .hero-title {
            text-align: center;
            font-size: 26px !important;
            line-height: 40px !important;
        }
        .hero-title span {
            font-size: 32px !important;
        }
        .quote {
            padding: 60px 0 !important;
            display: block !important;
        }
        .title-h2, .about-title {
            font-size: 22px !important;
            line-height: 32px !important;
        }
        .our-selection {
            display: block !important;
        }
        .our-selection__row {
            margin: 0 !important;
        }
    }
</style>