<?php
    $paginator =  $this->paginator;
    $category = $this->category;
    use Home\Model\DateBase;
    $cs = [
        '/tp/MB001/css/n.css'
    ];
    echo '<link href="'.srcLink($cs,1).'" media="screen" rel="stylesheet" type="text/css">';
    $optionBasic = $this->home()->optionBasic();
    $optionPage = $this->home()->optionPage();
    $menuOption = $this->home()->getMenu();
    $image = json_decode($category->getImage(), true);
    $imageFirst = '';
    if(!empty($image)){
        $imageFirst = array_shift($image);
    }
?>
<?php
    $image = 'http://'.$_SERVER['HTTP_HOST'].$imageFirst;
    $imageInfo = getimagesize($image);
    /**** Start SEO DWEB *****/
    echo $this->headLink(['rel' => 'canonical', 'href' => 'http://'.$_SERVER['HTTP_HOST'].$category->getViewLink() ]);
    $this->headTitle(!empty($category->getMetaTitle()) ? $category->getMetaTitle():$category->getName());
    $this->headMeta()->appendName('description', (!empty($category->getMetaDescription()) ? $category->getMetaDescription():null));
    $this->headMeta()->appendName('keywords', (!empty($category->getMetaKeyword()) ? $category->getMetaKeyword():null));

    $this->headMeta()->appendProperty('og:title', !empty($category->getMetaTitle()) ? $category->getMetaTitle():$category->getName());
    $this->headMeta()->appendProperty('og:description', !empty($category->getMetaDescription()) ? $category->getMetaDescription():null);
    $this->headMeta()->appendProperty('og:image', !empty($imageFirst) ? 'http://'.$_SERVER['HTTP_HOST'].$imageFirst:null);
    $this->headMeta()->appendProperty('og:image:secure_url', !empty($imageFirst) ? 'http://'.$_SERVER['HTTP_HOST'].$imageFirst:null);
    $this->headMeta()->appendProperty('og:image:width', $imageInfo['0']);
    $this->headMeta()->appendProperty('og:image:height', $imageInfo['1']);
    $this->headMeta()->appendProperty('og:type', 'Category Article');
    $this->headMeta()->appendProperty('og:url', 'http://'.$_SERVER['HTTP_HOST'].$category->getViewLink());
    $this->headMeta()->appendProperty('og:site_name', $optionBasic['sologan']);

    $this->headMeta()->appendName('twitter:card', !empty($image) ? $image:'summary_large_image');
    $this->headMeta()->appendName('twitter:title', !empty($category->getMetaTitle()) ? $category->getMetaTitle():null);
    $this->headMeta()->appendName('twitter:description', (!empty($category->getMetaDescription()) ? $category->getMetaDescription():null));
    $this->headMeta()->appendName('twitter:image', !empty($image) ? $image:null);
    /**** End SEO DWEB *****/
?>

<div class="container">
    <div class="row">
        <?php
        if($category->getParentId()){
            $cc = $prodCategory->getId($category);
            if($cc->getParentId()){
                $ccc = $prodCategory->getId($cc);
                if($ccc->getParentId()){
                    $cccc = $prodCategory->getId($ccc);
                }
            }
        }
        ?>
        <ul class="breadcrumb breadcrumb-category">
            <li><a href="/">Trang chủ</a></li>
            <?= (isset($cccc) ? '<li><a href="'.$cccc->getViewLink().'">'.$cccc->getName().'</a></li>':null) ?>
            <?= (isset($ccc) ? '<li><a href="'.$ccc->getViewLink().'">'.$ccc->getName().'</a></li>':null) ?>
            <?= (isset($cc) ? '<li><a href="'.$cc->getViewLink().'">'.$cc->getName().'</a></li>':null) ?>
            <li><a href="<?= $category->getViewLink(); ?>"><?= $category->getName(); ?></a></li>
        </ul>
        <?php if(!empty($menuOption['news_sidebar']) || !empty($optionPage['view_danh-muc-sidebar-1']) || !empty($optionPage['view_danh-muc-sidebar-2']) || !empty($optionPage['view_banner-sidebar'])):
            echo '<div class="col-md-8">';
        else:
            echo '<div class="col-md-12">';
        endif;
        ?>
            <?php
                $n = $this->newsCategory()->getCategories();
               /* if(count($n)){
                    echo '<ul class="navNews">';
                    echo '<li><a href="/bai-viet.html">Tất cả</a></li>';
                    foreach($n as $b){
                        echo '<li><a '.($category->getId() == $b->getId() ? 'class="active"':'').' href="'.$b->getViewLink().'">'.$b->getName().'</a></li>';
                    }
                    echo '</ul>';
                }*/
            if(count($paginator)){
                echo '<ul class="lNCategory">';
                foreach($paginator as $n){
                    $image = json_decode($n->getImage(), true);
                    $imageFirst = '';
                    if(!empty($image)){
                        $imageFirst = array_shift($image);
                    }
                    echo '<li>
                        <a href="'.$n->getViewLink().'">
                        <figure class="lazy image-article" data-src="'.(!empty($imageFirst) ? $imageFirst : null).'"></figure>
                        </a>
                        <div class="article__content">
                            <h3><a href="'.$n->getViewLink().'">'.$n->getTitle().'</a></h3>
                            <p class="news__date">'.DateBase::toFormat($n->getCreatedDateTime(), 'M d, Y').'</p>
                            <p class="intro">'.$n->getDescription().'</p>
                        </div>
                    </li>';
                }
                echo '</ul>';
                echo '<div class="paginatorProduct">';
                echo $this->paginationControl($this->paginator, 'Elastic', 'partial/listPage');
                echo '</div>';
            }
            ?>
        </div>
    <?php
    if(!empty($menuOption['news_sidebar']) || !empty($optionPage['view_danh-muc-sidebar-1']) || !empty($optionPage['view_danh-muc-sidebar-2']) || !empty($optionPage['view_banner-sidebar'])){
        echo $this->render('news/news/sidebar');
    } ?>
    </div>
</div>
