<?php
    $view = $this->news;
    $current_page_URL = $_SERVER["SERVER_NAME"] . $_SERVER["REQUEST_URI"];
    $a = json_decode($view->getExtraContent());
    $cs = [
        '/tp/MB001/css/n.css'
    ];
    echo '<link href="'.srcLink($cs,1).'" media="screen" rel="stylesheet" type="text/css">';
    $js = [
        '/tp/MB001/js/n.js'
    ];
    echo '<script type="text/javascript" src="'.srcLink($js,1).'"></script>';
    $optionPage = $this->home()->optionPage();
    $optionBasic = $this->home()->optionBasic();
    $imageFirst = '';
    if(!empty(json_decode($view->getImage(), true))){
        $imageFirst = array_shift(json_decode($view->getImage(), true));
    }
    $menuOption = $this->home()->getMenu();
?>
<?php
    $image = 'http://'.$_SERVER['HTTP_HOST'].$imageFirst;
    $imageInfo = getimagesize($image);
    /**** Start SEO DWEB *****/
    echo $this->headLink(['rel' => 'canonical', 'href' => 'http://'.$_SERVER['HTTP_HOST'].$view->getViewLink() ]);
    $this->headTitle($this->escapeHtml($this->translate(!empty($view->getMetaTitle()) ? $view->getMetaTitle():$view->getTitle())));
    $this->headMeta()->appendName('description', (!empty($view->getMetaDescription()) ? $view->getMetaDescription():null));
    $this->headMeta()->appendName('keywords', (!empty($view->getMetaKeyword()) ? $view->getMetaKeyword():null));

    $this->headMeta()->appendProperty('og:title', !empty($view->getMetaTitle()) ? $view->getMetaTitle():$view->getTitle());
    $this->headMeta()->appendProperty('og:description', !empty($view->getMetaDescription()) ? $view->getMetaDescription():null);
    $this->headMeta()->appendProperty('og:image', !empty($imageFirst) ? 'http://'.$_SERVER['HTTP_HOST'].$imageFirst:null);
    $this->headMeta()->appendProperty('og:image:secure_url', !empty($imageFirst) ? 'http://'.$_SERVER['HTTP_HOST'].$imageFirst:null);
    $this->headMeta()->appendProperty('og:image:width', $imageInfo['0']);
    $this->headMeta()->appendProperty('og:image:height', $imageInfo['1']);
    $this->headMeta()->appendProperty('og:type', 'Article');
    $this->headMeta()->appendProperty('og:url', 'http://'.$_SERVER['HTTP_HOST'].$view->getViewLink());
    $this->headMeta()->appendProperty('og:site_name', $optionBasic['sologan']);

    $this->headMeta()->appendName('twitter:card', !empty($image) ? $image:'summary_large_image');
    $this->headMeta()->appendName('twitter:title', !empty($view->getMetaTitle()) ? $view->getMetaTitle():null);
    $this->headMeta()->appendName('twitter:description', (!empty($view->getMetaDescription()) ? $view->getMetaDescription():null));
    $this->headMeta()->appendName('twitter:image', !empty($image) ? $image:null);
    /**** End SEO DWEB *****/
?>

<div class="container">
    <div class="row">
        <?php
        if($category->getParentId()){
            $cc = $prodCategory->getId($category);
            if($cc->getParentId()){
                $ccc = $prodCategory->getId($cc);
                if($ccc->getParentId()){
                    $cccc = $prodCategory->getId($ccc);
                }
            }
        }
        ?>
        <ul class="breadcrumb breadcrumb-category">
            <li><a href="/">Trang chủ</a></li>
            <?= (isset($cccc) ? '<li><a href="'.$cccc->getViewLink().'">'.$cccc->getName().'</a></li>':null) ?>
            <?= (isset($ccc) ? '<li><a href="'.$ccc->getViewLink().'">'.$ccc->getName().'</a></li>':null) ?>
            <?= (isset($cc) ? '<li><a href="'.$cc->getViewLink().'">'.$cc->getName().'</a></li>':null) ?>
            <li><a href="<?= $category->getViewLink(); ?>"><?= $category->getName(); ?></a></li>
            <li><a href="<?= $view->getViewLink(); ?>"><?= $view->getTitle(); ?></a></li>
        </ul>
            <?php if(!empty($menuOption['news_sidebar']) || !empty($optionPage['view_danh-muc-sidebar-1']) || !empty($optionPage['view_danh-muc-sidebar-2']) || !empty($optionPage['view_banner-sidebar'])):
                echo '<div class="col-md-8">';
            else:
                echo '<div class="col-md-12">';
            endif;
            ?>
                <div class="detailNews">
                    <div>
                        <h1><?= html_entity_decode($view->getTitle()) ?></h1>
                    </div>
                    <?php
                        echo html_entity_decode($view->getContent());
                    ?>
                    <div class="social">
                        <?php
                        ?>
                        <div style="float: left;margin: 0 5px 0 0;" class="fb-like" data-href="<?= $current_page_URL.$view->getViewLink() ?>" data-layout="button" data-action="like" data-show-faces="false" data-share="true"></div>
                        <div class="g-plusone" data-size="medium"></div>
                    </div>
                    <script src="https://apis.google.com/js/platform.js" async defer>
                        {lang: 'vi'}
                    </script>
                </div>
                <div class="single-news__relation">
                    <?php
                    $relation = json_decode($view->getArticleRelated(), true);
                    if(!empty($relation)) {
                        echo '<h3 class="single-news__relation--title">Bài viết liên quan</h3>';
                        echo '<ul>';
                        foreach($relation as $r) {
                            ?>
                            <li><i class="fa fa-caret-right"></i><a href="<?= $r['url'] ?>"><?= $r['title'] ?></a></li>
                            <?php
                        }
                        echo '</ul>';
                    }
                    ?>
                </div>

        </div>
    <?php
    if(!empty($menuOption['news_sidebar']) || !empty($optionPage['view_danh-muc-sidebar-1']) || !empty($optionPage['view_danh-muc-sidebar-2']) || !empty($optionPage['view_banner-sidebar'])){
        echo $this->render('news/news/sidebar');
    } ?>
    </div>
</div>


