<?php
    $paginator =  $this->paginator;
    $category = $this->category;
    $image = json_decode($category->getImage(), true);
    $imageFirst = '';
    if(!empty($image)){
        $imageFirst = array_shift($image);
    }

$cs = [
        '/tp/F011/css/n.css'
    ];
    echo '<link href="'.srcLink($cs,1).'" media="screen" rel="stylesheet" type="text/css">';
    $menuOption = $this->home()->getMenu();
    $optionPage = $this->home()->optionPage();
    $optionBasic = $this->home()->optionBasic();
?>
<?php
    $image = 'http://'.$_SERVER['HTTP_HOST'].$imageFirst;
    $imageInfo = getimagesize($image);
    /**** Start SEO DWEB *****/
    echo $this->headLink(['rel' => 'canonical', 'href' => 'http://'.$_SERVER['HTTP_HOST'].$category->getViewLink() ]);
    $this->headTitle(!empty($category->getMetaTitle()) ? $category->getMetaTitle():null);
    $this->headMeta()->appendName('description', (!empty($category->getMetaDescription()) ? $category->getMetaDescription():null));
    $this->headMeta()->appendName('keywords', (!empty($category->getMetaKeyword()) ? $category->getMetaKeyword():null));

    $this->headMeta()->appendProperty('og:title', !empty($category->getMetaTitle()) ? $category->getMetaTitle():null);
    $this->headMeta()->appendProperty('og:description', !empty($category->getMetaDescription()) ? $category->getMetaDescription():null);
    $this->headMeta()->appendProperty('og:image', !empty($imageFirst) ? 'http://'.$_SERVER['HTTP_HOST'].$imageFirst:null);
    $this->headMeta()->appendProperty('og:image:secure_url', !empty($imageFirst) ? 'http://'.$_SERVER['HTTP_HOST'].$imageFirst:null);
    $this->headMeta()->appendProperty('og:image:width', $imageInfo['0']);
    $this->headMeta()->appendProperty('og:image:height', $imageInfo['1']);
    $this->headMeta()->appendProperty('og:type', 'Category Article');
    $this->headMeta()->appendProperty('og:url', 'http://'.$_SERVER['HTTP_HOST'].$category->getViewLink());
    $this->headMeta()->appendProperty('og:site_name', $optionBasic['sologan']);

    $this->headMeta()->appendName('twitter:card', !empty($image) ? $image:'summary_large_image');
    $this->headMeta()->appendName('twitter:title', !empty($category->getMetaTitle()) ? $category->getMetaTitle():null);
    $this->headMeta()->appendName('twitter:description', (!empty($category->getMetaDescription()) ? $category->getMetaDescription():null));
    $this->headMeta()->appendName('twitter:image', !empty($image) ? $image:null);
    /**** End SEO DWEB *****/
?>

<div class="container">
    <div class="row">
        <?php
            if(!empty($menuOption['sidebar_menu']) || !empty($optionPage['view_danh-muc-sidebar-1']) || !empty($optionPage['view_danh-muc-sidebar-2']) || !empty($optionPage['view_banner-sidebar'])):
                echo '<div class="col-md-8">';
            else:
                echo '<div class="col-md-12">';
            endif;
        ?>
            <?php
                $n = $this->newsCategory()->getCategories();
                
            if(count($paginator)){
                echo '<ul class="lNCategory">';
                foreach($paginator as $n){
                    $image = json_decode($n->getImage(), true);
                    if(!empty($image)){
                        $imageFirst = array_shift($image);
                    }

                    echo '<li>
                        <a href="'.$n->getViewLink().'"><figure class="lazy image-article" data-src="'. (!empty($imageFirst) ? $imageFirst:null).'"></figure></a>
                        <h2><a href="'.$n->getViewLink().'">'.$n->getTitle().'</a></h2>
                    </li>';
                }
                echo '</ul>';
                echo '<div class="paginatorProduct">';
                    echo $this->paginationControl($this->paginator, 'Elastic', 'partial/listPage');
                echo '</div>';
            }
            ?>
        </div>
    <?php echo $this->render('news/news/sidebar');?>
    </div>
</div>
