<?php if(!empty($this->bannerList['banner-list banner']['banner-list'])):?>
<section class="hero-slider">
    <?php
        echo '<ul class="banner owl-carousel owl-theme">';
        foreach($this->bannerList['banner-list banner']['banner-list'] as $k => $b):
            $image = json_decode($b['image'], true);
            if(!empty($image)) {
                $imageFirst = array_shift($image);
            }
            ?>
            <li>
                <figure class="owl-lazy banner-image" data-src="<?= !empty($imageFirst) ? $imageFirst:null ?>">
                    <div>
                        <div>
                            <h2><?= $b['title'] ?></h2>
                            <p><?= $b['description'] ?></p>
                            <a href="<?= $b['url'] ?>">Xem</a>
                        </div>
                    </div>
                </figure>
            </li>
    <?php endforeach;?>
</section>
<?php endif;?>
