<?php
$this->layout('layout/layout_created');
$this->headTitle('Đăng nhập');

$user = $this->user;
?>

<section class="created-website">
    <div class="created-website__inner">
        <div class="created-website__left">
            <figure class="created-website__image lazy" style="display: block; background-image: url(&quot;https://colorlib.com/etc/lf/Login_v18/images/bg-01.jpg&quot;);"></figure>
        </div>
        <div class="created-website__right">
            <div class="created-website__form">
                <div class="header-logo">
                    <a href="/"><h2 class="header-sologan" title="DWEB nền tảng website chuẩn seo của SEONGON"><span class="logo-first-key">D</span>WEB.</h2></a>
                </div>
                <h2 class="register__title">Quản lý tài khoản website.</h2>
                <?php $form = $this->form ?>
                <form method="post" class="form-horizontal m-t-20">
                    <div class="form-group">
                        <div class="col-xs-12">
                            <?=$this->formelement($form->get('username')->setAttributes(['class' => '','placeholder'=>'Tài khoản & Email']))?>
                            <?= $this->formelementerrors($form->get('username'),['class' => 'error'])?>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-12">
                            <?=$this->formelement($form->get('password')->setAttributes(['class' => '','placeholder'=>'Mật khẩu']))?>
                            <?= $this->formelementerrors($form->get('password'),['class' => 'error'])?>
                        </div>
                    </div>
                    <?php if($user): ?>
                        <div class="form-group">
                            <div class="col-xs-12">
                                <label class="signin-page__label">Đăng nhập vào website ?</label>
                                <ul class="signin-page__list">
                                    <?php foreach ($user as $u): ?>
                                        <li><a data-user="<?= $u->getUserName(); ?>"><?= $u->getUserName(); ?><?= '.'.$_SERVER['HTTP_HOST'] ?></a></li>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                        </div>
                    <?php endif; ?>
                    <div class="form-group text-center m-t-40">
                        <div class="col-xs-12">
                            <button class="" type="submit">Đăng nhập</button>
                        </div>
                    </div>
                    <div class="form-group m-t-30 m-b-0">
                        <div class="col-sm-12">
                            <a href="#" class="text-dark"><i class="fa fa-lock m-r-5"></i> Bạn quên mật khẩu ?</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
