<?php
$redirect = $this->redirect;
?>
<?php
echo $this->headtitle($this->escapehtml($this->translate('Đăng nhập không thành công')));
?>
<div class="account-pages"></div>
<div class="clearfix"></div>
<div class="wrapper-page">
    <div class="ex-page-content text-center">
        <div class="text-error"><span class="text-primary">4</span><i class="ti-face-sad text-pink"></i><span class="text-info">4</span></div>
        <h2>Đăng nhập không thành công</h2><br>
    </div>
</div>