<?php
    echo $this->doctype();
    $optionBasic = $this->home()->optionBasic();
?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
        <style>
            
        </style>
        <?php
        echo $this->headTitle()->setSeparator('')->setAutoEscape(false);
        $this->headMeta()->appendName('DC.language', 'scheme=utf-8 content=vi');
        echo $this->headMeta();

        echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $optionBasic['favicon'] ? $optionBasic['favicon']:null ]);
        $cs = [
            '/tp/F011/css/h.css',
            '/tp/F011/css/animate.min.css',
            '/assets/css/web/bootstrap.css',
            '/assets/css/web/font-awesome.min.css',
            '/assets/css/web/owl.carousel.css',
            '/tp/dweb/css/modal-video.min.css',
            '/assets/css/web/owl.transitions.css',
        ];
        echo '<link href="'.srcLink($cs,2).'" media="screen" rel="stylesheet" type="text/css">';
        $js = [
            '/assets/js/web/jquery-1.11.2.min.js',
        ];
        echo '<script type="text/javascript" src="'.srcLink($js,2).'"></script>';
        echo !empty($optionBasic['scriptHead']) ? '<script>'.$optionBasic['scriptHead'].'</script>' : null;
        ?>
    </head>

    <body>
        <?php
            echo $this->render('layout/header');
            echo $this->content;
            echo $this->render('layout/footer');
            echo $this->render('layout/modal');
            echo !empty($optionBasic['scriptBody']) ? '<script>'.$optionBasic['scriptBody'].'</script>' : null;
        ?>
    </body>
    <?php
        $r = [
            '/tp/F008/css/r.css',
        ];
        echo '<link href="'.srcLink($r,1).'" media="screen" rel="stylesheet" type="text/css">';
        if(!empty($optionBasic['styleFooter'])) echo '<style>'.$optionBasic['styleFooter'].'</style>';
        $js = [
            '/assets/js/web/bootstrap.min.js',
            '/assets/js/web/jquery.lazy.min.js',
            '/assets/js/web/owl.carousel.js',
            '/assets/js/web/jquery-ui-1.10.3.custom.min.js',
            '/tp/dweb/js/waypoint/jquery.waypoints.min.js',
            '/assets/plugins/parsleyjs/parsley.min.js',
            '/tp/F011/js/a.js',
            '/tp/dweb/js/jquery-modal-video.min.js',
        ];
        echo '<script type="text/javascript" src="'.srcLink($js,2).'"></script>';
        echo !empty($optionBasic['scriptFooter']) ? '<script>'.$optionBasic['scriptFooter'].'</script>' : null;
    ?>
</html>