<?php
$this->headTitle($this->escapeHtml($this->translate('Tạo website')));
$this->headMeta()->appendName('content', ('DWEB - là một cơ quan thiết kế website sáng tạo có trụ sở tại 295A Hoàng Mai, Hà Nội. Chúng tôi cung cấp dịch vụ thiết kế UI/UX layout Website/Mobile xây dựng thương hiệu'));
$this->headMeta()->appendName('keywords', ('Thiết kế website theo yêu cầu, UI/UX, Nhận dạng thương hiệu'));
$this->headMeta()->appendProperty('og:title', 'Difference Web');
$code = $this->code;
$key = $this->key;

$cs = [
    '/assets/css/components.css',
    '/tp/dweb/css/page.css',
    '/tp/dweb/css/contact.css',
];
echo '<link href="'.srcLink($cs, 2).'" media="screen" rel="stylesheet" type="text/css">';
$js = [
    '/assets/plugins/parsleyjs/parsley.min.js',
    '/tp/dweb/js/form.js',
];
$active = [];
if($code != true):
    $active = ['/tp/dweb/js/active.js'];
endif;

$main = array_merge_recursive($js, $active);

echo '<script type="text/javascript" src="'.srcLink($main, 5).'"></script>';
?>

<input type="hidden" class="keyActive" value="<?= $key ?>" />

<section class="">
    <div class="container">
        <div class="register__inner">
            <div class="row">
                <div class="col-md-8">
                    <div class="register__dk">
                        <?php if($code == true): ?>
                        <h2>Mã kích hoạt không tồn tại</h2>
                        <?php else: ?>
                        <h2 class="label-process">Đang tạo website ...</h2>
                        <?php endif; ?>
                    </div>
                </div>
                <div class="col-md-4">

                </div>
            </div>
        </div>
    </div>
</section>
