<?php
$optionBasic = $this->home()->optionBasic();
$optionPage = $this->home()->optionPage();
$url = $this->UriParams()->getRequest()->getRequestUri();
?>
<section class="head">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="head__inner">
                    <div class="head__row">
                        <div class="form-search">
                            <form id="search" action="/search" method="get">
                                <input type="text" name="q" placeholder="Tìm kiếm ..."/>
                                <a class="icon-font icon-magnifier" onclick="document.getElementById('search').submit();"></a>
                                <div id="searchFolding"></div>
                            </form>
                        </div>
                    </div>
                    <div class="head__row">
                        <div class="logo">
                            <a href="/">
                                <?php if(!empty($optionBasic['logo'])): ?>
                                    <img src="<?= $optionBasic['logo'] ?>" alt="Fashion" />
                                <?php endif; ?>
                            </a>
                        </div>
                    </div>
                    <div class="head__row">
                        <div class="head__user--cart">
                            <div class="head__user">
                                <ul class="head__user--inner">
                                    <?php
                                    if ($this->user()->hasIdentity()) {
                                        ?>
                                        <li>
                                            <a href="/admin"><i class="fa fa-user-o" aria-hidden="true"></i> Xin chào: <?= $this->user()->getUser()->getFullName() ? $this->user()->getUser()->getFullName():ucfirst($this->user()->getUser()->getUserName()) ?></a>
                                        </li>
                                        <li>
                                            <a href="/user/signout"><i class="fa fa-sign-out" aria-hidden="true"></i> Thoát</a>
                                        </li>
                                        <?php
                                    }else{
                                        ?>
                                        <li><a href="/user/signup"><i class="fa fa-key" aria-hidden="true"></i> Đăng ký</a></li>
                                        <li><a href="/user/signin"><i class="fa fa-sign-in" aria-hidden="true"></i> Đăng nhập</a></li>
                                        <?php
                                    }
                                    ?>
                                    <li><a href="/cart/checkout"><i class="fa fa-check-circle-o" aria-hidden="true"></i> Thanh toán</a></li>
                                </ul>
                            </div>
                            <?php
                            $cartService = $this->cart()->getServiceCart();
                            $products = $cartService->getProducts();
                            ?>
                            <div class="head__cart">
                                <a class="fa fa-shopping-bag" href="/cart"><span><?= $cartService->getTotalProducts() ?> Sản phẩm,</span><strong><?= number_format($cartService->getTotalMoney()) ?> đ</strong></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <?php
                $menuOption = $this->home()->getMenu();
                if(!empty($menuOption['head_menu'])):
                    ?>
                    <div class="navHome">
                        <ul>
                            <?php foreach($menuOption['head_menu'] as $m): ?>
                                <li <?= $url == $m['url'] ? 'class="active"':null ?>><a href="<?= $m['url'] ?>"><?= $m['name'] ?></a>
                                    <?php if(!empty($m['children'])): ?>
                                        <ul>
                                            <?php foreach($m['children'] as $mm): ?>
                                                <li><a href="<?= $mm['url'] ?>"><?= $mm['name'] ?></a>
                                                    <?php if(!empty($mm['children'])): ?>
                                                        <ul>
                                                            <?php foreach($mm['children'] as $mc): ?>
                                                            <li><a href="<?= $mc['url'] ?>"><?= $mc['name'] ?></a></li>
                                                            <?php endforeach;?>
                                                        </ul>
                                                    <?php endif;?>
                                                </li>
                                            <?php endforeach; ?>
                                        </ul>
                                    <?php endif; ?>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                    <div class="navMobile">
                        <a class="head__buttonMenu">Menu</a>
                        <ul class="head__navigation--m">
                            <?php foreach($menuOption['head_menu'] as $m): ?>
                                <li>
                                <?= $m['children'] ? '<button></button>' : null ?><a href="<?= $m['url'] ?>"><?= $m['name'] ?></a>
                                <?php
                                if($m['children']){

                                    echo '<ul class="nav2">';
                                    foreach($m['children'] as $mc){
                                        ?>
                                        <li><?= $mc['children'] ? '<button></button>' : null ?><a href="<?= $mc['url'] ?>"><?= $mc['name'] ?></a>
                                        <?php
                                        if($mc['children']){
                                            echo '<ul>';
                                            foreach($mc['children'] as $mcc){
                                                ?>
                                                <li><a href="<?= $mcc['url'] ?>"><?= $mcc['name'] ?></a></li>
                                                <?php
                                            }
                                            echo '</ul>';
                                        }
                                        ?>
                                        </li>
                                        <?php
                                    }
                                    echo '</ul>';
                                }
                                ?>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                <?php endif; ?>


            </div>
        </div>
    </div>
</section>
