<?php
    $data = $this->paginator;
    $breadcrumb = $this->breadcrumb;
    $data->setItemCountPerPage($this->uriParams()->getRequest()->getQuery('icpp') ? : 12);
    $category = $this->category;
    use Home\Model\DateBase;
    $category2 = $this->NewsCategory()->getCategories();
?>
<section class="category__breadcrumb">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <ul>
                    <li><a href="/">Trang chủ</a></li>
                    <?php
                        if(!empty($breadcrumb)) {
                            foreach(array_reverse($breadcrumb) as $b) {
                                echo '<li><a href="'.$b['url'].'">'.$b['name'].'</a></li>';
                            }
                        }
                    ?>
                </ul>
                <h1 class="category-news__title"><?= $category->getName() ?></h1>
            </div>
        </div>
    </div>
</section>
<section class="category-news category-news__grid">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <?php if(!empty($category->getDescription())): ?>
                <div class="category-news__description">
                    <?= $category->getDescription() ?>
                    <hr>
                </div>
                <?php endif; ?>
                <div class="category-news__inner">
                    <div class="news-grid__list">
                        <?php
                        foreach($data as $n):
                            $image = json_decode($n->getImage(), true);
                            $imageFirst = '';
                            if(!empty($image)) {
                                $imageFirst = array_shift($image);
                            }
                            ?>
                            <div class="news-grid__item">
                                <div class="news-grid__item--inner">
                                    <a href="<?= $n->getViewLink() ?>" title="<?= $n->getTitle() ?>"><figure class="lazy news-grid__image" title="<?= $n->getTitle() ?>" data-src="<?= $imageFirst ?>"></figure></a>
                                    <h2 class="news-grid__title"><a href="<?= $n->getViewLink() ?>"><?= $n->getTitle() ?></a></h2>
                                    <p class="new-grid__cate"><?= $n->getCateName() ?></p>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                    <div class="news__paginator">
                        <?php
                        echo $this->paginationControl($data, 'Elastic', 'partial/listPage');
                        ?>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>