<?php
    use Home\Model\DateBase;
    $optionBasic = $this->home()->optionBasic();
    $optionPage = $this->home()->optionPage();
    $homePage = $this->home()->homePage();
    $fileLogo = getimagesize('http://'.$_SERVER['HTTP_HOST'].$optionBasic['logo']);
?>
<?php
    /**** Start SEO DWEB *****/
    echo $this->headLink(['rel' => 'canonical', 'href' => 'http://'.$_SERVER['HTTP_HOST'] ]);
    $this->headTitle($this->escapeHtml($this->translate(!empty($optionBasic['sologan']) ? $optionBasic['sologan']:null)));
    $this->headMeta()->appendName('description', (!empty($optionBasic['metaDescription']) ? $optionBasic['metaDescription']:null));
    $this->headMeta()->appendName('keywords', (!empty($optionBasic['metaKeyword']) ? $optionBasic['metaKeyword']:null));
    $this->headMeta()->appendProperty('og:title', !empty($optionBasic['metaTitle']) ? $optionBasic['metaTitle']:null);
    $this->headMeta()->appendProperty('og:description', !empty($optionBasic['metaDescription']) ? $optionBasic['metaDescription']:null);
    $this->headMeta()->appendProperty('og:image', !empty($optionBasic['logo']) ? 'http://'.$_SERVER['HTTP_HOST'].$optionBasic['logo']:null);
    $this->headMeta()->appendProperty('og:image:secure_url', !empty($optionBasic['logo']) ? 'http://'.$_SERVER['HTTP_HOST'].$optionBasic['logo']:null);
    $this->headMeta()->appendProperty('og:image:width', $fileLogo['0']);
    $this->headMeta()->appendProperty('og:image:height', $fileLogo['1']);
    $this->headMeta()->appendProperty('og:type', 'Website');
    $this->headMeta()->appendProperty('og:url', 'http://'.$_SERVER['HTTP_HOST']);
    $this->headMeta()->appendProperty('og:site_name', $optionBasic['sologan']);

    $this->headMeta()->appendName('twitter:card', !empty($optionBasic['logo']) ? 'http://'.$_SERVER['HTTP_HOST'].$optionBasic['logo']:'summary_large_image');
    $this->headMeta()->appendName('twitter:title', !empty($optionBasic['metaTitle']) ? $optionBasic['metaTitle']:null);
    $this->headMeta()->appendName('twitter:description', (!empty($optionBasic['metaDescription']) ? $optionBasic['metaDescription']:null));
    $this->headMeta()->appendName('twitter:image', !empty($optionBasic['logo']) ? 'http://'.$_SERVER['HTTP_HOST'].$optionBasic['logo']:null);
    /**** End SEO DWEB *****/
?>
<?php
if(!empty($homePage)):
    $count = 0;
    foreach($homePage as $k => $v ):
        $layout = explode(' ',$k);
        switch ($layout[0]) {
            case "slider-layout":
                echo $this->partial('home/template/slider', ['bannerList' => $v]);
                break;
            case "small-banner-layout":
                echo $this->partial('home/template/small-banner-layout', ['smallBannerList' => $v]);
                break;
            case "product-layout":
                echo $this->partial('home/template/product-layout', ['productLayout' => $v]);
                break;
            case "product-layout-2":
                echo $this->partial('home/template/product-layout-2', ['productLayout2' => $v]);
                break;
            case "option-layout":
                echo $this->partial('home/template/option-layout', ['optionLayout' => $v]);
                break;
            case "news-layout":
                echo $this->partial('home/template/news-layout', ['newsLayout' => $v]);
                break;
            case "feedback-form-layout":
                echo $this->partial('home/template/feedback-form-layout', ['feedbackFormLayout' => $v]);
                break;
            case "html-layout":
                echo $this->partial('home/template/html-layout', ['htmlLayout' => $v]);
                break;
            case "gallery-layout":
                echo $this->partial('home/template/gallery-layout', ['galleryLayout' => $v]);
                break;
            case "image-layout":
                echo $this->partial('home/template/image-layout', ['imageLayout' => $v]);
                break;
            default:
                break;
        }
    endforeach;
        endif;

?>