<?php
    use Home\Model\DateBase;
    $optionBasic = $this->home()->optionBasic();
    $optionPage = $this->home()->optionPage();
    $homePage = $this->home()->homePage();
    $fileLogo = getimagesize('http://'.$_SERVER['HTTP_HOST'].$optionBasic['logo']);
?>
<?php
    /**** Start SEO DWEB *****/
    echo $this->headLink(['rel' => 'canonical', 'href' => 'http://'.$_SERVER['HTTP_HOST'] ]);
    $this->headTitle($this->escapeHtml($this->translate(!empty($optionBasic['metaTitle']) ? $optionBasic['metaTitle']:$optionBasic['sologan'])));
    $this->headMeta()->appendName('description', (!empty($optionBasic['metaDescription']) ? $optionBasic['metaDescription']:null));
    $this->headMeta()->appendName('keywords', (!empty($optionBasic['metaKeyword']) ? $optionBasic['metaKeyword']:null));
    $this->headMeta()->appendProperty('og:title', !empty($optionBasic['metaTitle']) ? $optionBasic['metaTitle']:$optionBasic['sologan']);
    $this->headMeta()->appendProperty('og:description', !empty($optionBasic['metaDescription']) ? $optionBasic['metaDescription']:null);
    $this->headMeta()->appendProperty('og:image', !empty($optionBasic['logo']) ? 'http://'.$_SERVER['HTTP_HOST'].$optionBasic['logo']:null);
    $this->headMeta()->appendProperty('og:image:secure_url', !empty($optionBasic['logo']) ? 'http://'.$_SERVER['HTTP_HOST'].$optionBasic['logo']:null);
    $this->headMeta()->appendProperty('og:image:width', $fileLogo['0']);
    $this->headMeta()->appendProperty('og:image:height', $fileLogo['1']);
    $this->headMeta()->appendProperty('og:type', 'Website');
    $this->headMeta()->appendProperty('og:url', 'http://'.$_SERVER['HTTP_HOST']);
    $this->headMeta()->appendProperty('og:site_name', $optionBasic['sologan']);

    $this->headMeta()->appendName('twitter:card', !empty($optionBasic['logo']) ? 'http://'.$_SERVER['HTTP_HOST'].$optionBasic['logo']:'summary_large_image');
    $this->headMeta()->appendName('twitter:title', !empty($optionBasic['metaTitle']) ? $optionBasic['metaTitle']:null);
    $this->headMeta()->appendName('twitter:description', (!empty($optionBasic['metaDescription']) ? $optionBasic['metaDescription']:null));
    $this->headMeta()->appendName('twitter:image', !empty($optionBasic['logo']) ? 'http://'.$_SERVER['HTTP_HOST'].$optionBasic['logo']:null);
    /**** End SEO DWEB *****/
?>
<?php
if(!empty($homePage)):
    $count = 0;
    foreach($homePage as $k => $v ):
        $layout = explode(' ',$k);
        switch ($layout[0]) {
            case "slider-layout":
                echo $this->partial('home/template/slider', ['bannerList' => $v]);
                break;
            case "option-layout":
                echo $this->partial('home/template/option-layout', ['optionLayout' => $v]);
                break;
            case "intro-layout":
                echo $this->partial('home/template/intro-layout',['introLayout' => $v]);
                break;
            case "news-layout":
                echo $this->partial('home/template/news-layout', ['newsLayout' => $v]);
                break;
            case "project-layout":
                echo $this->partial('home/template/project-layout', ['projectLayout' => $v]);
                break;
            case "html-layout":
                echo $this->partial('home/template/html-layout', ['htmlLayout' => $v]);
                break;
            case "image-layout":
                echo $this->partial('home/template/image-layout', ['imageLayout' => $v]);
                break;
            case "galery-layout":
                echo $this->partial('home/template/galery-layout', ['galeryLayout' => $v]);
                break;
            case "video-layout":
                echo $this->partial('home/template/video-layout', ['videoLayout' => $v]);
                break;
            case "support-layout":
                $count++;
                if($count < 2){
                    echo $this->partial('home/template/support-layout', ['supportLayout' => $v]);
                }
                break;
            default:
                break;
        }
    endforeach;
else:

?>
<?php
if(!empty($optionPage['view_banner'])):
?>
<section class="hero-slider banner-image">
    <ul id="banner" class="owl-carousel owl-theme">
        <?php
        if(!empty($optionPage['banner'])):
        foreach($optionPage['banner'] as $b):
            $imageFirst = '';
            $i = json_decode($b['image'], true);
            if(is_array($i) && !empty($i)) {
                $imageFirst = array_shift($i);
            }
            ?>
            <li>
                <a href="<?= $b['url'] ?>">
                    <figure class="slider-image" style="background-image: url(<?= $imageFirst ?>)">
                        <div class="hero-slider__content">
                            <h3 class="hero-slider__title"><?= $b['title'] ?></h3>
                            <div class="hero-slider__description"><?= $b['description'] ?></div>
                            <div class="button-default1">Chi tiết</div>
                        </div>
                    </figure>
                </a>
            </li>
        <?php
        endforeach;
        endif;
        ?>
    </ul>
</section>
<?php endif; ?>

<?php
if(!empty($optionPage['view_anh-gioi-thieu-ben-trai'])):
?>
<section class="two-post">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="two-post__inner">
                    <?php
                    if(!empty($optionPage['anh-gioi-thieu-ben-trai'])):
                        foreach($optionPage['anh-gioi-thieu-ben-trai'] as $b):
                            $image = json_decode($b['image'], true);
                            $imageFirst = '';
                            if(is_array($image) && !empty($image)) {
                                $imageFirst = array_shift($image);
                            }
                    ?>
                        <div class="two-post__left">
                            <figure class="lazy two-post__image" data-src="<?= $imageFirst ?>"></figure>
                        </div>
                    <?php
                        endforeach;
                        endif;
                    ?>
                    <div class="two-post__right">
                        <h2 class="two-post__title"><?= $optionPage['tieu-de-gioi-thieu'] ? $optionPage['tieu-de-gioi-thieu'] : ''?></h2>
                        <div class="two-post__intro">
                            <?= $optionPage['noi-dung-gioi-thieu'] ? $optionPage['noi-dung-gioi-thieu'] : '' ?>
                        </div>
                        <div class="two-post__button">
                            <a href="<?= $optionPage['duong-dan-gioi-thieu'] ? $optionPage['duong-dan-gioi-thieu'] : '#'?>" class="button-default1">Chi tiết</a>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>
<?php
    endif;
?>
<?php if(!empty($optionPage['view_tien-ich-du-an'])): ?>
<section class="feature-project">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2 class="headline-default feature-project__headline"><?= $optionPage['tieu-de-1-tien-ich-du-an'] ? $optionPage['tieu-de-1-tien-ich-du-an']:'' ?></h2>
                <?= $optionPage['tieu-de-2-tien-ich-du-an'] ? '<div class="four-post__intro"><span>'.$optionPage['tieu-de-2-tien-ich-du-an'].'</span></div>':'' ?>
            </div>
        </div>
    </div>
    <div class="feature-project__inner">
        <div class="feature-project__list owl-carousel owl-theme">
            <?php
            if(!empty($optionPage['tien-ich-du-an'])):
            foreach($optionPage['tien-ich-du-an'] as $b):
                $imageFirst = '';
                $i = json_decode($b['image'], true);
                if(is_array($i) && !empty($i)) {
                    $imageFirst = array_shift($i);
                }
                ?>
                <div class="feature-project__item">
                    <a href="<?= $b['url'] ?>">
                        <figure class="feature-project__image" style="background-image: url(<?= $imageFirst ?>)" data-src="<?= $imageFirst ?>"></figure>
                        <h3 class="feature-product__title"><?= $b['title'] ?></h3>
                    </a>
                </div>
                <?php
            endforeach;
            endif;
            ?>
        </div>
    </div>
</section>
<?php endif; ?>

<?php
$news = $optionPage['view_tin-tuc'];
if(!empty($news)):
?>
<section class="news">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2 class="headline-default news__headline"><?= $optionPage['tieu-de-tin-tuc'] ? $optionPage['tieu-de-tin-tuc']:'' ?></h2>
                <?= $optionPage['mo-ta-tin-tuc'] ? '<div class="four-post__intro"><span>'.$optionPage['mo-ta-tin-tuc'].'</span></div>':'' ?>
                <div class="news__inner">
                    <div class="news__list">
                        <?php
                        if(!empty($optionPage['tin-tuc'])):
                            foreach($optionPage['tin-tuc'] as $n):
                                $imageFirst = '';
                                $i = json_decode($n['image'], true);
                                if(is_array($i) && !empty($i)) {
                                    $imageFirst = array_shift($i);
                                }
                        ?>
                            <div class="news__item">
                                <div class="news__item--inner">
                                    <div class="news__item--right">
                                        <a href="<?= $n['url'] ?>"><figure class="news__image lazy" data-src="<?= $imageFirst ?>"></figure></a>
                                    </div>
                                    <div class="news__item--left" style="">
                                        <div class="news__date">
                                            <span>Ngày <?= DateBase::toFormat($n['date'], 'd/m/Y') ?></span>
                                        </div>
                                        <h3 class="news__title"><a href="<?= $n['url'] ?>"><?= $n['title'] ?></a></h3>
                                    </div>
                                </div>
                            </div>
                        <?php endforeach;
                        endif;?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<?php endif; ?>


<?php if(!empty($optionPage['view_banner-trai'])): ?>
<section class="four-post">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="four-post__inner">
                    <h2 class="headline-default news__headline"><?= $optionPage['tieu-de-banner-trai'] ? $optionPage['tieu-de-banner-trai']:'' ?></h2>
                    <?= $optionPage['mo-ta-banner-trai'] ? '<div class="four-post__intro"><span>'.$optionPage['mo-ta-banner-trai'].'</span></div>':'' ?>
                    <div class="four-post__item">
                        <div class="four-post__item--left">
                            <div class="four-post__slider owl-carousel owl-theme">
                                <?php
                                if(!empty($optionPage['banner-trai'])):
                                foreach($optionPage['banner-trai'] as $b):
                                    $imageFirst = '';
                                    $i = json_decode($b['image'], true);
                                    if(is_array($i) && !empty($i)) {
                                        $imageFirst = array_shift($i);
                                    }
                                    ?>
                                    <div class="four-post__slider--item">
                                        <a href="<?= $b['url'] ?>">
                                            <figure class="four-post__slider--image lazy" style="background-image: url(<?= $imageFirst ?>)"></figure>
                                        </a>
                                    </div>
                                    <?php
                                endforeach;
                                endif;
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<?php endif; ?>

<?php if(!empty($optionPage['view_video'])): ?>
<section class="video">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="video__inner">
                    <h2 class="headline-default"><?= $optionPage['tieu-de-video'] ? $optionPage['tieu-de-video'] : ''?></h2>
                    <?= $optionPage['mo-ta-video'] ? '<div class="four-post__intro"><span>'.$optionPage['mo-ta-video'].'</span></div>':'' ?>
                    <div class="video__item">
                        <iframe width="900" height="507" src="https://www.youtube.com/embed/<?= $optionPage['video'] ? $optionPage['video'] : '' ?>" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<?php endif; ?>

<?php if(!empty($optionPage['view_email'])): ?>
<section class="form">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="form__inner">
                    <h2 class="headline-default"><?= $optionPage['tieu-de-email'] ? $optionPage['tieu-de-email']:'' ?></h2>
                    <?= $optionPage['mo-ta-email'] ? '<div class="four-post__intro"><span>'.$optionPage['mo-ta-email'].'</span></div>':'' ?>
                    <form class="form__register" data-parsley-validate novalidate>
                        <div>
                            <input class="email" type="text" data-parsley-type="email" required="required" data-parsley-error-message="Email không được để trống" placeholder="Email *" />
                        </div>
                        <div>
                            <input class="phone" type="text" data-parsley-type="digits" data-parsley-length="[10,11]" required="required" data-parsley-error-message="Số điện thoại không được để trống" placeholder="Số điện thoại *" />
                        </div>
                        <div>
                            <button type="submit">Gửi</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<?php endif; ?>
<?php endif;?>

