<?php $this->layout('layout/admin');?>

<div class="container">

    <div class="wrapper-page">
        <div class="ex-page-content text-center">
            <div class="text-error">
                <span class="text-primary">4</span><i class="ti-face-sad text-pink"></i><span class="text-info">4</span>
            </div>
            <h2>Bạn không có quyền truy cập trang này</h2>
        </div>
    </div>
    <!-- end wrapper page -->

</div>