<?php if(!empty($this->galeryLayout)):?>
<section class="four-post">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="headline">
                        <h2 class="headline-default four-post__headline wp1"><span><?= $this->galeryLayout['galery-title text']['value'] ? $this->galeryLayout['galery-title text']['value']:'' ?></span></h2>
                        <?= $this->galeryLayout['galery-sub-title text']['value'] ? '<div class="headline-intro">'.$this->galeryLayout['galery-sub-title text']['value'].'</div>':null ?>
                    </div>
                    <div class="four-post__inner">
                        <div class="four-post__item">
                            <div class="four-post__item--left">
                                <div class="four-post__slider owl-carousel owl-theme">
                                    <?php
                                    if(!empty($this->galeryLayout['galery-1-list banner']['galery-1-list'])):
                                        foreach($this->galeryLayout['galery-1-list banner']['galery-1-list'] as $k => $b):
                                            $imageFirst = '';
                                            $i = json_decode($b['image'], true);
                                            if(is_array($i) && !empty($i)) {
                                                $imageFirst = array_shift($i);
                                            }
                                            ?>
                                            <div class="four-post__slider--item">
                                                <figure class="four-post__slider--image wp3 lazy" data-src="<?= $imageFirst ?>"></figure>
                                            </div>
                                        <?php
                                        endforeach;
                                    endif;
                                    ?>
                                </div>
                            </div>
                            <div class="four-post__item--right">
                                <h3 class="news__title"><?= $this->galeryLayout['galery-1-title text']['value'] ? $this->galeryLayout['galery-1-title text']['value'] :'' ?></h3>
                                <div class="four-post__description">
                                    <?= $this->galeryLayout['galery-1-description textarea']['value'] ? $this->galeryLayout['galery-1-description textarea']['value'] : '' ?>
                                </div>
                            </div>
                        </div>

                        <?php if(!empty($this->galeryLayout['galery-2-list banner']['galery-2-list'])): ?>
                            <div class="four-post__item">
                                <div class="four-post__item--left">
                                    <div class="four-post__slider owl-carousel owl-theme">
                                        <?php
                                        foreach($this->galeryLayout['galery-2-list banner']['galery-2-list'] as $k => $b):
                                            $imageFirst = '';
                                            $i = json_decode($b['image'], true);
                                            if(is_array($i) && !empty($i)) {
                                                $imageFirst = array_shift($i);
                                            }
                                            ?>
                                            <div class="four-post__slider--item">
                                                <figure class="four-post__slider--image wp3 lazy" data-src="<?= $imageFirst ?>"></figure>
                                            </div>
                                        <?php
                                        endforeach;
                                        ?>
                                    </div>
                                </div>
                                <div class="four-post__item--right">
                                    <h3 class="news__title"><?= $this->galeryLayout['galery-2-title text']['value'] ? $this->galeryLayout['galery-2-title text']['value'] :'' ?></h3>
                                    <div class="four-post__description">
                                        <?= $this->galeryLayout['galery-2-description textarea']['value'] ? $this->galeryLayout['galery-2-description textarea']['value'] : '' ?>
                                    </div>
                                </div>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </section>
<?php endif;?>