<?php if(!empty($this->introLayout)):?>
<section class="two-post">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="two-post__inner">
                    <div class="two-post__left">
                        <figure class="lazy two-post__image" data-src="<?= $this->introLayout['intro-image file']['value'] ?>"></figure>
                    </div>
                    <div class="two-post__right">
                        <h2 class="two-post__title wp1"><span><?= $this->introLayout['intro-title text']['value'] ? $this->introLayout['intro-title text']['value'] : ''?></span></h2>
                        <div class="two-post__intro wp2">
                            <?= $this->introLayout['intro-content textarea']['value'] ? $this->introLayout['intro-content textarea']['value'] : ''?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<?php endif;?>