<?php
$this->headTitle($this->escapeHtml($this->translate('Tạo website')));
$this->headMeta()->appendName('content', ('Tạo website miễn phí | DWEB'));
$this->headMeta()->appendName('keywords', ('Thiết kế website theo yêu cầu, UI/UX, Nhận dạng thương hiệu'));
$this->headMeta()->appendProperty('og:title', 'Difference Web');
$code = $this->code;
$key = $this->key;

$cs = [
    '/assets/css/components.css',
    '/tp/dweb/css/page.css',
    '/tp/dweb/css/contact.css',
];
echo '<link href="'.srcLink($cs, 2).'" media="screen" rel="stylesheet" type="text/css">';
$js = [
    '/assets/plugins/parsleyjs/parsley.min.js',
    '/tp/dweb_v2/js/form.js',
];
$active = [];
if($code != true):
    $active = ['/tp/dweb_v2/js/active.js'];
endif;

$main = array_merge_recursive($js, $active);
echo '<script type="text/javascript" src="'.srcLink($main, 5).'"></script>';
?>

<input type="hidden" class="keyActive" value="<?= $key ?>" />


<div id="clouds">
    <div class="cloud x1"></div>
    <div class="cloud x2"></div>
    <div class="cloud x3"></div>
    <div class="cloud x4"></div>
    <div class="cloud x5"></div>
    <div class="register__label">
        <?php if($code == true): ?>
            <h2>Mã kích hoạt không tồn tại</h2>
        <?php else: ?>
            <h2 class="label-process">Đang tạo website ...</h2>
        <?php endif; ?>
    </div>
</div>
<style>
    *{ margin: 0; padding: 0;}
    body {
        height: 100vh;
        overflow: hidden;
    }
    .register__label {
        position: absolute;
        top: 0;
        bottom: 0;
        display: flex;
        align-items: center;
        justify-content: center;
        margin: auto;
        left: 30px;
        right: 30px;
        text-align: center;
    }
    .register__label h2 {
        color: rgb(0, 188, 212);
        margin: 0;
        font-weight: 300;
        text-shadow: 0 1px 1px #FFF;
    }

    #clouds{
        padding: 100px 0;
        background: #c9dbe9;
        background: -webkit-linear-gradient(top, #9dd2d8 0%, #e4fcff 100%);
        background: -linear-gradient(top, #9dd2d8 0%, #e4fcff 100%);
        background: -moz-linear-gradient(top, #9dd2d8 0%, #e4fcff 100%);
        height: 100vh;
    }

    /*Time to finalise the cloud shape*/
    .cloud {
        width: 200px; height: 60px;
        background: #fff;

        border-radius: 200px;
        -moz-border-radius: 200px;
        -webkit-border-radius: 200px;

        position: relative;
    }

    .cloud:before, .cloud:after {
        content: '';
        position: absolute;
        background: #fff;
        width: 100px; height: 80px;
        position: absolute; top: -15px; left: 10px;

        border-radius: 100px;
        -moz-border-radius: 100px;
        -webkit-border-radius: 100px;

        -webkit-transform: rotate(30deg);
        transform: rotate(30deg);
        -moz-transform: rotate(30deg);
    }

    .cloud:after {
        width: 120px; height: 120px;
        top: -55px; left: auto; right: 15px;
    }

    /*Time to animate*/
    .x1 {
        top: 100px;
        -webkit-animation: moveclouds 15s linear infinite;
        -moz-animation: moveclouds 15s linear infinite;
        -o-animation: moveclouds 15s linear infinite;
    }

    /*variable speed, opacity, and position of clouds for realistic effect*/
    .x2 {
        left: 200px; top: 150px;

        -webkit-transform: scale(0.6);
        -moz-transform: scale(0.6);
        transform: scale(0.6);
        opacity: 0.6; /*opacity proportional to the size*/

        /*Speed will also be proportional to the size and opacity*/
        /*More the speed. Less the time in 's' = seconds*/
        -webkit-animation: moveclouds 25s linear infinite;
        -moz-animation: moveclouds 25s linear infinite;
        -o-animation: moveclouds 25s linear infinite;
    }

    .x3 {
        left: -250px; top: 200px;

        -webkit-transform: scale(0.8);
        -moz-transform: scale(0.8);
        transform: scale(0.8);
        opacity: 0.8; /*opacity proportional to the size*/

        -webkit-animation: moveclouds 20s linear infinite;
        -moz-animation: moveclouds 20s linear infinite;
        -o-animation: moveclouds 20s linear infinite;
    }

    .x4 {
        left: 470px; top: 250px;

        -webkit-transform: scale(0.75);
        -moz-transform: scale(0.75);
        transform: scale(0.75);
        opacity: 0.75; /*opacity proportional to the size*/

        -webkit-animation: moveclouds 18s linear infinite;
        -moz-animation: moveclouds 18s linear infinite;
        -o-animation: moveclouds 18s linear infinite;
    }

    .x5 {
        left: -150px; top: 300px;

        -webkit-transform: scale(0.8);
        -moz-transform: scale(0.8);
        transform: scale(0.8);
        opacity: 0.8; /*opacity proportional to the size*/

        -webkit-animation: moveclouds 20s linear infinite;
        -moz-animation: moveclouds 20s linear infinite;
        -o-animation: moveclouds 20s linear infinite;
    }

    @-webkit-keyframes moveclouds {
        0% {margin-left: 1000px;}
        100% {margin-left: -1000px;}
    }
    @-moz-keyframes moveclouds {
        0% {margin-left: 1000px;}
        100% {margin-left: -1000px;}
    }
    @-o-keyframes moveclouds {
        0% {margin-left: 1000px;}
        100% {margin-left: -1000px;}
    }
</style>