<?php if(!empty($this->galeryLayout['galery-list banner']['galery-list'])):?>
<section class="four-post">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="four-post__inner">
                    <h2 class="headline-default news__headline"><?= $this->galeryLayout['galery-title text']['value'] ? $this->galeryLayout['galery-title text']['value']:'' ?></h2>
                    <?= $this->galeryLayout['galery-sub-title text']['value'] ? '<div class="four-post__intro"><span>'.$this->galeryLayout['galery-sub-title text']['value'].'</span></div>':'' ?>
                    <div class="four-post__item">
                        <div class="four-post__item--left">
                            <div class="four-post__slider owl-carousel owl-theme">
                                <?php
                                    foreach($this->galeryLayout['galery-list banner']['galery-list'] as $k => $b):
                                        $imageFirst = '';
                                        $i = json_decode($b['image'], true);
                                        if(is_array($i) && !empty($i)) {
                                            $imageFirst = array_shift($i);
                                        }
                                        ?>
                                        <div class="four-post__slider--item">
                                            <a href="<?= $b['url'] ?>">
                                                <figure class="four-post__slider--image lazy" style="background-image: url(<?= $imageFirst ?>)"></figure>
                                            </a>
                                        </div>
                                    <?php
                                    endforeach;
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<?php endif;?>