<?php
    $optionBasic = $this->home()->optionBasic();
    if($optionBasic['commentFacebookArticle'] || $optionBasic['commentFacebookProduct']):
    $url = $this->url;
    $style = $this->style;
?>
    <style>
        <?= $style ?>
    </style>
<?php
    $cs = [
        '/assets/css/web/commentFacebook.css',
    ];
    echo '<link href="'.srcLink($cs,4).'" media="screen" rel="stylesheet" type="text/css">';
?>
<div class="commentFacebook">
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = 'https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v3.2&appId=1138345072867205&autoLogAppEvents=1';
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>
    <div class="fb-comments" data-href="<?= $url ?>" data-width="100%" data-numposts="5"></div>
</div>
<?php endif; ?>