<?php echo $this->doctype(); ?>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Hệ thống quản lý nội dung, tạo website DWEB.VN">
    <meta name="author" content="DWEB">

    <link rel="shortcut icon" href="/assets/images/favicon_1.ico">
    <?php
    echo $this->headLink()
//        ->prependStylesheet('http://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css')
        ->prependStylesheet('/assets/css/responsive.css')
        ->prependStylesheet('/assets/css/pages.css')
        ->prependStylesheet('/assets/css/icons.css')
        ->prependStylesheet('/assets/css/core.css')
        ->prependStylesheet('/assets/css/components.css')
        ->prependStylesheet('/assets/css/bootstrap.min.css');

    ?>

</head>

<body class="error-404 widescreen">
    <?= $this->content; ?>
</body>
</html>
