<?php if(!empty($this->newsLayout['news-list article']['news-list'])):?>
    <section class="news">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <?= $this->newsLayout['news-title text']['value'] ? '<h2 class="product__title">'.$this->newsLayout['news-title text']['value'].'</h2>': ''?>
                    <?php $slider = $this->newsLayout['news-slider-checkbox checkbox']['value']?>
                    <ul class="<?= $slider ? 'news-slider owl-carousel owl-theme' : 'lN' ?> news__list">
                        <?php
                            $c = 0;
                            foreach($this->newsLayout['news-list article']['news-list'] as $k => $n):
                                $c++;
                            $image = json_decode($n['image'], true);
                            if(!empty($image)){
                                $imageFirst = array_shift($image);
                            }
                        ?>
                            <li>
                                <a href="<?= $n['url'] ?>"><figure class="lazy news-image" data-src="<?= !empty($imageFirst) ? $imageFirst:'' ?>"></figure></a>
                                <?= $c != 1 ? '<div class="news__right">':null ?>
                                <h3><a href="<?= $n['url'] ?>"><?= $n['title'] ?></a></h3>
                                <div class="news__intro"><?= $n['intro'] ?></div>
                                <?= $c != 1 ? '</div>':null ?>
                            </li>
                        <?php
                        endforeach;
                        ?>
                    </ul>
                </div>
            </div>
        </div>
    </section>
<?php endif;?>