<?php
$form = $this->form;
echo $this->headtitle($this->escapehtml($this->translate('Sửa tên miền')));
?>

<form method="post" enctype="multipart/form-data" data-parsley-validate novalidate>
    <div class="row">
        <div class="col-sm-8">
            <div class="card-box">
                <div class="portlet-title">
                    <h4 class="m-t-0 header-title m-b-20"><b>Sửa tên miền</b></h4>
                </div>
                <div class="portlet-body form">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label class="control-label" for="firstName">Tên miền hệ thống</label>
                                <?= $this->formelement($form->get('name')->setAttributes(['class' => 'form-control', 'placeholder'=>'Tên miền hệ thống', 'required' => 'required', 'data-parsley-error-message' => 'Không được để trống'])) ?>
                                <?= $this->formelementerrors($form->get('name'),['class' => 'parsley-errors-list filled'])?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label class="control-label" for="firstName">Tên miền</label>
                                <?= $this->formelement($form->get('alias')->setAttributes(['class' => 'form-control', 'placeholder'=>'Tên miền',])) ?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label class="control-label" for="firstName">Store</label>
                                <?= $this->formelement($form->get('storeId')->setAttributes(['class' => 'form-control select-ajax-store', 'multiple'=>'multiple'])) ?>
                                <?= $this->formelementerrors($form->get('storeId'),['class' => 'parsley-errors-list filled'])?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label class="control-label" for="firstName">Tên giao diện</label>
                                <?= $this->formelement($form->get('uitemplateId')->setAttributes(['class' => 'form-control select-ajax-template', 'multiple'=>'multiple'])) ?>
                                <?= $this->formelementerrors($form->get('uitemplateId'),['class' => 'parsley-errors-list filled'])?>
                            </div>
                        </div>
                    </div>
                    <div class="form-actions">
                        <?=$this->formelement($form->get('submit')->setAttributes(['class' => 'btn btn-default']))?>
                        <?=$this->formelement($form->get('reset')->setAttributes(['class' => 'btn']))?>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-sm-4">
        </div>
        <!-- End col-sm-8 -->

    </div>
</form>


