<?php if(!empty($this->optionLayout['option-html texteditor']['value']) || !empty($this->optionLayout['option-button text']['value'])):?>
<section class="text-editor">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="text-editor__inner">
                    <?= $this->optionLayout['option-html texteditor']['value'] ?>
                    <?=$this->optionLayout['option-link text']['value'] ? '<a class="btn2" href="'.$this->optionLayout['option-link text']['value'].'">'.$this->optionLayout['option-button text']['value'].'</a>' : '' ?>
                </div>
            </div>
        </div>
    </div>
</section>
<?php endif;?>