<?php if(!empty($this->bannerList['banner-list banner']['banner-list'])):?>
<section class="slider">
    <?php
        echo '<ul class="banner owl-carousel owl-theme">';
        foreach($this->bannerList['banner-list banner']['banner-list'] as $k => $b):
            $image = json_decode($b['image'], true);
            if(!empty($image)) {
                $imageFirst = array_shift($image);
            }
            ?>
            <li>
                <a href="<?= $b['url'] ?>">
                    <figure class="slider-image" style="background-image: url(<?= $imageFirst ?>)">
                        <div class="slider__content">
                            <div>
                                <h3><?= $b['title'] ?></h3>
                                <p><?= $b['description'] ?></p>
                                <span>Đọc tiếp</span>
                            </div>
                        </div>
                    </figure>
                </a>
            </li>
        <?php endforeach;?>
        </ul>
    <?php if(!empty($this->bannerList['info-title-1 text']['value']) || !empty($this->bannerList['info-content-1 text']['value']) || !empty($this->bannerList['info-title-2 text']['value']) || !empty($this->bannerList['info-content-2 text']['value']) || !empty($this->bannerList['info-title-3 text']['value']) || !empty($this->bannerList['info-content-3 text']['value'])):?>
        <div class="three-feature">
            <div class="three-feature__inner">
                <?php if(!empty($this->bannerList['info-title-1 text']['value']) || !empty($this->bannerList['info-content-1 text']['value'])):?>
                <div class="three-feature__item">
                    <div><i class="fa fa-angle-right"></i></div>
                    <div>
                        <h3><?= $this->bannerList['info-title-1 text']['value'] ? $this->bannerList['info-title-1 text']['value']  : ''?></h3>
                        <span><?= $this->bannerList['info-content-1 text']['value'] ? $this->bannerList['info-content-1 text']['value'] : ''?></span>
                    </div>
                </div>
                <?php endif;?>
                <?php if(!empty($this->bannerList['info-title-2 text']['value']) || !empty($this->bannerList['info-content-2 text']['value'])):?>
                <div class="three-feature__item">
                    <div><i class="fa fa-angle-right"></i></div>
                    <div>
                        <h3><?= $this->bannerList['info-title-2 text']['value'] ? $this->bannerList['info-title-2 text']['value'] : ''?></h3>
                        <span><?= $this->bannerList['info-content-2 text']['value'] ? $this->bannerList['info-content-2 text']['value'] : ''?></span>
                    </div>
                </div>
                <?php endif;?>
                <?php if(!empty($this->bannerList['info-title-3 text']['value']) || !empty($this->bannerList['info-content-3 text']['value'])):?>
                <div class="three-feature__item">
                    <div><i class="fa fa-angle-right"></i></div>
                    <div>
                        <h3><?= $this->bannerList['info-title-3 text']['value'] ? $this->bannerList['info-title-3 text']['value'] : ''?></h3>
                        <span><?= $this->bannerList['info-content-3 text']['value'] ? $this->bannerList['info-content-3 text']['value'] : ''?></span>
                    </div>
                </div>
                <?php endif;?>
            </div>
        </div>
    <?php endif;?>
</section>
<?php endif;?>
