<?php
    $theme = $this->NewsCategory()->featchTreeCategory(20);
    $data = $this->paginator;
    $data->setItemCountPerPage($this->uriParams()->getRequest()->getQuery('icpp') ? : 8);
    $category = $this->category;
    $image = json_decode($category->getImage(), true);
    $imageFirst = '';
    if(!empty($image)){
        $imageFirst = array_shift($image);
    }
    $cs = [
        '/tp/A009/css/n.css'
    ];
    echo '<link href="'.srcLink($cs,1).'" media="screen" rel="stylesheet" type="text/css">';
    $optionPage = $this->home()->optionPage();
    $menuOption = $this->home()->getMenu();
    $optionBasic = $this->home()->optionBasic();
    use Home\Model\DateBase;
?>
<?php
    $image = 'http://'.$_SERVER['HTTP_HOST'].$imageFirst;
    $imageInfo = getimagesize($image);
    /**** Start SEO DWEB *****/
    echo $this->headLink(['rel' => 'canonical', 'href' => 'http://'.$_SERVER['HTTP_HOST'].$category->getViewLink() ]);
    $this->headTitle(!empty($category->getMetaTitle()) ? $category->getMetaTitle():$category->getName());
    $this->headMeta()->appendName('description', (!empty($category->getMetaDescription()) ? $category->getMetaDescription():null));
    $this->headMeta()->appendName('keywords', (!empty($category->getMetaKeyword()) ? $category->getMetaKeyword():null));

    $this->headMeta()->appendProperty('og:title', !empty($category->getMetaTitle()) ? $category->getMetaTitle():$category->getName());
    $this->headMeta()->appendProperty('og:description', !empty($category->getMetaDescription()) ? $category->getMetaDescription():null);
    $this->headMeta()->appendProperty('og:image', !empty($imageFirst) ? 'http://'.$_SERVER['HTTP_HOST'].$imageFirst:null);
    $this->headMeta()->appendProperty('og:image:secure_url', !empty($imageFirst) ? 'http://'.$_SERVER['HTTP_HOST'].$imageFirst:null);
    $this->headMeta()->appendProperty('og:image:width', $imageInfo['0']);
    $this->headMeta()->appendProperty('og:image:height', $imageInfo['1']);
    $this->headMeta()->appendProperty('og:type', 'Category Article');
    $this->headMeta()->appendProperty('og:url', 'http://'.$_SERVER['HTTP_HOST'].$category->getViewLink());
    $this->headMeta()->appendProperty('og:site_name', $optionBasic['sologan']);

    $this->headMeta()->appendName('twitter:card', !empty($image) ? $image:'summary_large_image');
    $this->headMeta()->appendName('twitter:title', !empty($category->getMetaTitle()) ? $category->getMetaTitle():null);
    $this->headMeta()->appendName('twitter:description', (!empty($category->getMetaDescription()) ? $category->getMetaDescription():null));
    $this->headMeta()->appendName('twitter:image', !empty($image) ? $image:null);
    /**** End SEO DWEB *****/
?>

<?php
if(!empty($data)):
    $category2 = $this->NewsCategory()->getCategories();
    ?>

    <section class="main">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="main__inner">
                        <?php /*if(!empty($optionPage['view_banner-quang-cao'])): */?><!--
                            <div class="main__adv-top">

                                <?php
/*                                if(!empty($optionPage['banner'])):
                                foreach($optionPage['banner'] as $b):
                                    $image = json_decode($b['image'], true);
                                    $imageFirst = '';
                                    if(!empty($image)){
                                        $imageFirst = array_shift($image);
                                    }
                                    */?>
                                    <a href="<?/*= $b['url'] */?>">
                                        <img class="slider-image lazy" data-src="<?/*= $imageFirst */?>" />
                                    </a>
                                    <?php
/*                                endforeach; endif;
                                */?>
                            </div>
                        --><?php /*endif; */?>
                        <div class="main__left">

                            <div class="category-news__inner">
                                <h2 class="category-news__title"><?= $category->getName() ?></h2>
                                <div class="news__list">
                                    <?php
                                    $i = 0;
                                    foreach($data as $n):
                                        $i++;
                                        $image = json_decode($n->getImage(), true);
                                        $imageFirst = '';
                                        if(!empty($image)) {
                                            $imageFirst = array_shift($image);
                                        }
                                        ?>
                                        <div class="news__item">
                                            <div class="news__item--inner">
                                                <div class="category-news__wrapper--image">
                                                    <a href="<?= $n->getViewLink() ?>" title="<?= $n->getTitle() ?>"><figure class="lazy news__image" title="<?= $n->getTitle() ?>" data-src="<?= $imageFirst ?>"></figure></a>
                                                </div>
                                                <div class="news__intro">
                                                    <h3 class="news__title"><a href="<?= $n->getViewLink() ?>"><?= $n->getTitle() ?></a></h3>
                                                    <p class="category-news__date"><?= DateBase::toFormat($n->getCreatedDateTime(), 'M d, Y') ?></p>
                                                    <div class="news__intro--sub">
                                                        <?= $n->getDescription() ?>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    <?php endforeach; ?>
                                </div>
                                <div class="news__paginator">
                                    <?php
                                    echo $this->paginationControl($data, 'Elastic', 'partial/listPage');
                                    ?>
                                </div>
                            </div>

                        </div>
                        <?php if(!empty($optionPage['view_banner-sidebar']) || !empty($optionPage['view_danh-muc-tin-tuc-sidebar']) || !empty($optionPage['view_muc-bai-viet-1']) || !empty($optionPage['view_muc-bai-viet-2'])): ?>
                            <div class="main__right">
                                <?php echo $this->render('layout/sidebar');?>
                            </div>
                        <?php endif;?>
                    </div>
                </div>
            </div>
        </div>
    </section>


<?php endif; ?>