<?php
    use Home\Model\DateBase;
    $optionBasic = $this->home()->optionBasic();
    $optionPage = $this->home()->optionPage();
    $homePage = $this->home()->homePage();
    $fileLogo = getimagesize('http://'.$_SERVER['HTTP_HOST'].$optionBasic['logo']);
?>
<?php
    /**** Start SEO DWEB *****/
    echo $this->headLink(['rel' => 'canonical', 'href' => 'http://'.$_SERVER['HTTP_HOST'] ]);
    $this->headTitle($this->escapeHtml($this->translate(!empty($optionBasic['metaTitle']) ? $optionBasic['metaTitle']:$optionBasic['sologan'])));
    $this->headMeta()->appendName('description', (!empty($optionBasic['metaDescription']) ? $optionBasic['metaDescription']:null));
    $this->headMeta()->appendName('keywords', (!empty($optionBasic['metaKeyword']) ? $optionBasic['metaKeyword']:null));
    $this->headMeta()->appendProperty('og:title', !empty($optionBasic['metaTitle']) ? $optionBasic['metaTitle']:$optionBasic['sologan']);
    $this->headMeta()->appendProperty('og:description', !empty($optionBasic['metaDescription']) ? $optionBasic['metaDescription']:null);
    $this->headMeta()->appendProperty('og:image', !empty($optionBasic['logo']) ? 'http://'.$_SERVER['HTTP_HOST'].$optionBasic['logo']:null);
    $this->headMeta()->appendProperty('og:image:secure_url', !empty($optionBasic['logo']) ? 'http://'.$_SERVER['HTTP_HOST'].$optionBasic['logo']:null);
    $this->headMeta()->appendProperty('og:image:width', $fileLogo['0']);
    $this->headMeta()->appendProperty('og:image:height', $fileLogo['1']);
    $this->headMeta()->appendProperty('og:type', 'Website');
    $this->headMeta()->appendProperty('og:url', 'http://'.$_SERVER['HTTP_HOST']);
    $this->headMeta()->appendProperty('og:site_name', $optionBasic['sologan']);

    $this->headMeta()->appendName('twitter:card', !empty($optionBasic['logo']) ? 'http://'.$_SERVER['HTTP_HOST'].$optionBasic['logo']:'summary_large_image');
    $this->headMeta()->appendName('twitter:title', !empty($optionBasic['metaTitle']) ? $optionBasic['metaTitle']:'Trang chủ');
    $this->headMeta()->appendName('twitter:description', (!empty($optionBasic['metaDescription']) ? $optionBasic['metaDescription']:null));
    $this->headMeta()->appendName('twitter:image', !empty($optionBasic['logo']) ? 'http://'.$_SERVER['HTTP_HOST'].$optionBasic['logo']:null);
    /**** End SEO DWEB *****/
?>

<?php
if(!empty($homePage)):
    $count = 0;
    foreach($homePage as $k => $v ):
        $layout = explode(' ',$k);
        switch ($layout[0]) {
            case "slider-layout":
                echo $this->partial('home/template/slider', ['bannerList' => $v]);
                break;
            case "product-layout":
                echo $this->partial('home/template/product-layout', ['productLayout' => $v]);
                break;
            case "option-layout":
                echo $this->partial('home/template/option-layout', ['optionLayout' => $v]);
                break;
            case "news-layout":
                echo $this->partial('home/template/news-layout', ['newsLayout' => $v]);
                break;
            case "small-banner-layout":
                echo $this->partial('home/template/small-banner-layout', ['smallBannerList' => $v]);
                break;
            case "html-layout":
                echo $this->partial('home/template/html-layout', ['htmlLayout' => $v]);
                break;
            case "tab-product-layout":
                $count++;
                echo $this->partial('home/template/tab-product-layout', ['tabProductLayout' => $v, 'id' => $count]);
                break;
            case "image-layout":
                echo $this->partial('home/template/image-layout', ['imageLayout' => $v]);
                break;
            default:
                break;
        }
    endforeach;
else: ?>

<!--<editor-fold desc="Description">-->
<div class="NavBannerAds">
    <?php
        if(!empty($optionPage['view_banner'])){
            echo '<ul id="banner" class="owl-carousel owl-theme">';
            if(!empty($optionPage['banner'])) {
                foreach ($optionPage['banner'] as $b) {
                    $imageFirst = '';
                    if (!empty(json_decode($b['image'], true))) {
                        $imageFirst = array_shift(json_decode($b['image'], true));
                    }
                    ?>
                    <li>
                        <a href="<?= $b['url'] ?>">
                            <figure class="lazy banner-image" data-src="<?= $imageFirst ?>"></figure>
                        </a>
                    </li>
                    <?php
                }
            }
            echo '</ul>';
        }
    ?>
</div>
<?php if(!empty($optionPage['view_3-banner-nho'])):
?>
<div class="three-banner">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="three-banner__list">
                    <?php
                    if(!empty($optionPage['3-banner'])):
                        foreach($optionPage['3-banner'] as $b):
                        $imageFirst = '';
                        if(!empty(json_decode($b['image'], true))){
                            $imageFirst = array_shift(json_decode($b['image'], true));
                        }
                    ?>
                    <div class="three-banner__item">
                        <a href="<?= $b['url'] ?>">
                            <figure class="lazy three-banner__image" data-src="<?= $imageFirst ?>"></figure>
                        </a>
                    </div>
                    <?php endforeach; endif; ?>
                </div>
            </div>
        </div>
    </div>
</div>
<?php
    endif; ?>
<?php if(!empty($optionPage['view_4-tab-san-pham'])): ?>
<div class="ProductOptionHome">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="ProductOptionHomeContent">
                    <ul class="NavProductOption">
                        <?php if(!empty($optionPage['tieu-de-tab-1'])): ?>
                            <li><a class="active" data-tab="#tab1"><?= $optionPage['tieu-de-tab-1'] ?></a></li>
                        <?php endif; ?>
                        <?php if(!empty($optionPage['tieu-de-tab-2'])): ?>
                            <li><a  data-tab="#tab2"><?= $optionPage['tieu-de-tab-2'] ?></a></li>
                        <?php endif; ?>
                        <?php if(!empty($optionPage['tieu-de-tab-3'])): ?>
                            <li><a data-tab="#tab3"><?= $optionPage['tieu-de-tab-3'] ?></a></li>
                        <?php endif; ?>
                        <?php if(!empty($optionPage['tieu-de-tab-4'])): ?>
                            <li><a  data-tab="#tab4"><?= $optionPage['tieu-de-tab-4'] ?></a></li>
                        <?php endif; ?>
                    </ul>
                    <div id="tab1" class="tab newHome active">
                        <?php if(!empty($optionPage['san-pham-tab-1']) && !empty($optionPage['tieu-de-tab-1'])): ?>
                            <div class="product-list">
                                <?php foreach($optionPage['san-pham-tab-1'] as $p):
                                    $imgs = !empty(json_decode($p['image'], true)) ? array_slice(json_decode($p['image'], true), 0, 2):null; ?>
                                    <div class="product-item">
                                        <div class="product-item__inner">
                                            <div class="product_image-wrapper">
                                                <a href="<?= $p['url'] ?>">
                                                    <figure class="lazy product_image" data-src="<?= !empty($imgs) ? $imgs['0']:null ?>"></figure>
                                                </a>
                                            </div>
                                            <h3 class="product-title"><?= $p['title'] ?></h3>
                                            <p class="product-price"><?= $p['priceOld'] ? '<i>'.number_format($p['price']).' đ</i>'.number_format($p['priceOld']).' đ':number_format($p['price']).' đ' ?></p>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                        <?php endif; ?>
                    </div>
                    <div id="tab2" class="tab">
                        <?php if(!empty($optionPage['san-pham-tab-2']) && !empty($optionPage['tieu-de-tab-2'])): ?>
                            <div class="product-list">
                            <?php foreach($optionPage['san-pham-tab-2'] as $p):
                                $imgs = !empty(json_decode($p['image'], true)) ? array_slice(json_decode($p['image'], true), 0, 2):null; ?>
                                <div class="product-item">
                                    <div class="product-item__inner">
                                        <div class="product_image-wrapper">
                                            <a href="<?= $p['url'] ?>">
                                                <figure class="lazy product_image" data-src="<?= !empty($imgs) ? $imgs['0']:null ?>"></figure>
                                            </a>
                                        </div>
                                        <h3 class="product-title"><?= $p['title'] ?></h3>
                                        <p class="product-price"><?= $p['priceOld'] ? '<i>'.number_format($p['price']).' đ</i>'.number_format($p['priceOld']).' đ':number_format($p['price']).' đ' ?></p>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                            </div>
                        <?php endif; ?>
                    </div>
                    <div id="tab3" class="tab">
                        <?php if(!empty($optionPage['san-pham-tab-3']) && !empty($optionPage['tieu-de-tab-3'])): ?>
                            <div class="product-list">
                                <?php foreach($optionPage['san-pham-tab-3'] as $p):
                                    $imgs = !empty(json_decode($p['image'], true)) ? array_slice(json_decode($p['image'], true), 0, 2):null; ?>
                                    <div class="product-item">
                                        <div class="product-item__inner">
                                            <div class="product_image-wrapper">
                                                <a href="<?= $p['url'] ?>">
                                                    <figure class="lazy product_image" data-src="<?= !empty($imgs) ? $imgs['0']:null ?>"></figure>
                                                </a>
                                            </div>
                                            <h3 class="product-title"><?= $p['title'] ?></h3>
                                            <p class="product-price"><?= $p['priceOld'] ? '<i>'.number_format($p['price']).' đ</i>'.number_format($p['priceOld']).' đ':number_format($p['price']).' đ' ?></p>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                        <?php endif; ?>
                    </div>
                    <div id="tab4" class="tab">
                        <?php if(!empty($optionPage['san-pham-tab-4']) && !empty($optionPage['tieu-de-tab-4'])): ?>
                            <div class="product-list">
                                <?php foreach($optionPage['san-pham-tab-4'] as $p):
                                    $imgs = !empty(json_decode($p['image'], true)) ? array_slice(json_decode($p['image'], true), 0, 2):null; ?>
                                    <div class="product-item">
                                        <div class="product-item__inner">
                                            <div class="product_image-wrapper">
                                                <a href="<?= $p['url'] ?>">
                                                    <figure class="lazy product_image" data-src="<?= !empty($imgs) ? $imgs['0']:null ?>"></figure>
                                                </a>
                                            </div>
                                            <h3 class="product-title"><?= $p['title'] ?></h3>
                                            <p class="product-price"><?= $p['priceOld'] ? '<i>'.number_format($p['price']).' đ</i>'.number_format($p['priceOld']).' đ':number_format($p['price']).' đ' ?></p>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                        <?php endif; ?>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
<?php endif;?>
<?php if(!empty($optionPage['view_danh-muc-san-pham-1'])):
?>
    <div class="category">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <?php
                        if(!empty($optionPage['danh-muc-san-pham-1'])){
                            foreach($optionPage['danh-muc-san-pham-1'] as $c){
                            $imageFirst = '';
                            if(!empty(json_decode($c['image'], true))){
                                $imageFirst = array_shift(json_decode($c['image'], true));
                            }
                    ?>
                    <div class="category__title">
                        <h2><img src="<?= $imageFirst ?>" /><a href="<?= $c['url'] ?>"><?= $c['title'] ?></a></h2>
                        <?php
                            if(!empty($c['child'])){
                        ?>
                            <ul>
                                <?php
                                    foreach($c['child'] as $cc){
                                        echo '<li><a href="'.$cc['url'].'">'.$cc['title'].'</a></li>';
                                    }
                                ?>
                            </ul>
                        <?php
                            }
                        ?>
                    </div>
                        <?php
                            $product = $this->product()->search(['categoryId' => $c['id'], 'limit' => 4]);
                            if(!empty($product)):
                                echo '<div class="product-list">';
                                foreach($product as $p):
                                $imageFirst = !empty(json_decode($p->getImage(), true)) ? array_shift(json_decode($p->getImage(), true)):null;
                        ?>
                                <div class="product-item">
                                    <div class="product-item__inner">
                                        <div class="product_image-wrapper">
                                            <a href="<?= $p->getViewLink() ?>">
                                                <figure class="lazy product_image" data-src="<?= !empty($imageFirst) ? $imageFirst:null ?>"></figure>
                                            </a>
                                        </div>
                                        <h3 class="product-title"><?= $p->getTitle() ?></h3>
                                        <p class="product-price"><?= $p->getPriceOld() ? '<i>'.number_format($p->getPrice()).' đ</i>'.number_format($p->getPriceOld()).' đ':number_format($p->getPrice()).' đ' ?></p>
                                    </div>
                                </div>
                        <?php
                            endforeach;
                            echo '</div>';
                            echo '<div class="category__viewall"><a href="'.$c['url'].'">Xem tất cả sản phẩm '.$c['title'].'</a></div>';
                            endif;
                        ?>
                    <?php } }?>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
<?php if(!empty($optionPage['view_2-banner-giua-1'])):
    ?>
    <div class="two-banner">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="three-banner__list">
                        <?php
                        if(!empty($optionPage['2-banner-giua-1'])):
                        foreach($optionPage['2-banner-giua-1'] as $b):
                            $imageFirst = '';
                            if(!empty(json_decode($b['image'], true))){
                                $imageFirst = array_shift(json_decode($b['image'], true));
                            }
                            ?>
                            <div class="two-banner__item three-banner__item">
                                <a href="<?= $b['url'] ?>">
                                    <figure class="lazy three-banner__image" data-src="<?= $imageFirst ?>"></figure>
                                </a>
                            </div>
                        <?php endforeach; endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php
endif; ?>
<?php if(!empty($optionPage['view_danh-muc-san-pham-2'])):
    ?>
    <div class="category">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <?php
                    if(!empty($optionPage['danh-muc-san-pham-2'])){
                    foreach($optionPage['danh-muc-san-pham-2'] as $c){
                        ?>
                        <div class="category__title">
                            <h2><a href="<?= $c['url'] ?>"><?= $c['title'] ?></a></h2>
                            <?php
                            if(!empty($c['child'])){
                                ?>
                                <ul>
                                    <?php
                                    foreach($c['child'] as $cc){
                                        echo '<li><a href="'.$cc['url'].'">'.$cc['title'].'</a></li>';
                                    }
                                    ?>
                                </ul>
                                <?php
                            }
                            ?>
                        </div>
                        <?php
                        $product = $this->product()->search(['categoryId' => $c['id'], 'limit' => 4]);
                        if(!empty($product)):
                            echo '<div class="product-list">';
                            foreach($product as $p):
                                $imageFirst = !empty(json_decode($p->getImage(), true)) ? array_shift(json_decode($p->getImage(), true)):null;
                                ?>
                                <div class="product-item">
                                    <div class="product-item__inner">
                                        <div class="product_image-wrapper">
                                            <a href="<?= $p->getViewLink() ?>">
                                                <figure class="lazy product_image" data-src="<?= !empty($imageFirst) ? $imageFirst:null ?>"></figure>
                                            </a>
                                        </div>
                                        <h3 class="product-title"><?= $p->getTitle() ?></h3>
                                        <p class="product-price"><?= $p->getPriceOld() ? '<i>'.number_format($p->getPrice()).' đ</i>'.number_format($p->getPriceOld()).' đ':number_format($p->getPrice()).' đ' ?></p>
                                    </div>
                                </div>
                                <?php
                            endforeach;
                            echo '</div>';
                            echo '<div class="category__viewall"><a href="'.$c['url'].'">Xem tất cả sản phẩm '.$c['title'].'</a></div>';
                        endif;
                        ?>
                    <?php }} ?>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
<?php if(!empty($optionPage['view_danh-muc-san-pham-3'])):
    ?>
    <div class="category">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <?php
                    if(!empty($optionPage['danh-muc-san-pham-3'])){
                    foreach($optionPage['danh-muc-san-pham-3'] as $c){
                        ?>
                        <div class="category__title">
                            <h2><a href="<?= $c['url'] ?>"><?= $c['title'] ?></a></h2>
                            <?php
                            if(!empty($c['child'])){
                                ?>
                                <ul>
                                    <?php
                                    foreach($c['child'] as $cc){
                                        echo '<li><a href="'.$cc['url'].'">'.$cc['title'].'</a></li>';
                                    }
                                    ?>
                                </ul>
                                <?php
                            }
                            ?>
                        </div>
                        <?php
                        $product = $this->product()->search(['categoryId' => $c['id'], 'limit' => 4]);
                        if(!empty($product)):
                            echo '<div class="product-list">';
                            foreach($product as $p):
                                $imageFirst = !empty(json_decode($p->getImage(), true)) ? array_shift(json_decode($p->getImage(), true)):null;
                                ?>
                                <div class="product-item">
                                    <div class="product-item__inner">
                                        <div class="product_image-wrapper">
                                            <a href="<?= $p->getViewLink() ?>">
                                                <figure class="lazy product_image" data-src="<?= !empty($imageFirst) ? $imageFirst:null ?>"></figure>
                                            </a>
                                        </div>
                                        <h3 class="product-title"><?= $p->getTitle() ?></h3>
                                        <p class="product-price"><?= $p->getPriceOld() ? '<i>'.number_format($p->getPrice()).' đ</i>'.number_format($p->getPriceOld()).' đ':number_format($p->getPrice()).' đ' ?></p>
                                    </div>
                                </div>
                                <?php
                            endforeach;
                            echo '</div>';
                            echo '<div class="category__viewall"><a href="'.$c['url'].'">Xem tất cả sản phẩm '.$c['title'].'</a></div>';
                        endif;
                        ?>
                    <?php } }?>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
<?php if(!empty($optionPage['view_danh-muc-san-pham-4'])):
    ?>
    <div class="category">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <?php
                    if(!empty($optionPage['danh-muc-san-pham-4'])){
                        foreach($optionPage['danh-muc-san-pham-4'] as $c) {
                    ?>
                        <div class="category__title">
                            <h2><a href="<?= $c['url'] ?>"><?= $c['title'] ?></a></h2>
                            <?php if(!empty($c['child'])) : ?>
                                <ul>
                                    <?php
                                    foreach($c['child'] as $cc){
                                        echo '<li><a href="'.$cc['url'].'">'.$cc['title'].'</a></li>';
                                    }
                                    ?>
                                </ul>
                            <?php endif; ?>
                        </div>
                        <?php
                        $product = $this->product()->search(['categoryId' => $c['id'], 'limit' => 4]);
                        if(!empty($product)):
                            echo '<div class="product-list">';
                            foreach($product as $p):
                                $imageFirst = !empty(json_decode($p->getImage(), true)) ? array_shift(json_decode($p->getImage(), true)):null;
                                ?>
                                <div class="product-item">
                                    <div class="product-item__inner">
                                        <div class="product_image-wrapper">
                                            <a href="<?= $p->getViewLink() ?>">
                                                <figure class="lazy product_image" data-src="<?= !empty($imageFirst) ? $imageFirst:null ?>"></figure>
                                            </a>
                                        </div>
                                        <h3 class="product-title"><?= $p->getTitle() ?></h3>
                                        <p class="product-price"><?= $p->getPriceOld() ? '<i>'.number_format($p->getPrice()).' đ</i>'.number_format($p->getPriceOld()).' đ':number_format($p->getPrice()).' đ' ?></p>
                                    </div>
                                </div>
                                <?php
                            endforeach;
                            echo '</div>';
                            echo '<div class="category__viewall"><a href="'.$c['url'].'">Xem tất cả sản phẩm '.$c['title'].'</a></div>';
                        endif;
                        ?>
                    <?php }} ?>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
<?php if(!empty($optionPage['view_2-banner-giua-2'])): ?>
    <div class="two-banner">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="three-banner__list">
                            <?php
                            if(!empty($optionPage['2-banner-giua-2'])):
                                foreach($optionPage['2-banner-giua-2'] as $b):
                                    $imageFirst = '';
                                    if(!empty(json_decode($b['image'], true))){
                                        $imageFirst = array_shift(json_decode($b['image'], true));
                                    }
                                    ?>
                                    <div class="two-banner__item three-banner__item">
                                        <a href="<?= $b['url'] ?>">
                                            <figure class="lazy three-banner__image" data-src="<?= $imageFirst ?>"></figure>
                                        </a>
                                    </div>
                                <?php endforeach; endif;?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
<?php endif; ?>
<?php if(!empty($optionPage['view_tin-tuc'])): ?>
    <div class="two-post">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="two-post__inner">
                        <div class="two-post__headline">
                            <h2><?= $optionPage['tieu-de-tin-tuc'] ?></h2>
                        </div>
                        <div class="two-post__list">
                            <?php
                            if(!empty($optionPage['tin-tuc'])):
                                foreach($optionPage['tin-tuc'] as $n):
                                    $imageFirst = '';
                                    if(!empty(json_decode($n['image'], true))){
                                        $imageFirst = array_shift(json_decode($n['image'], true));
                                    }
                                    ?>
                                    <div class="two-post__item">
                                        <div class="two-post__image-wrapper">
                                            <a href="<?= $n['url'] ?>">
                                                <figure class="lazy two-post__image" data-src="<?= !empty($imageFirst) ? $imageFirst:null ?>"></figure>
                                            </a>
                                        </div>
                                        <div class="two-post__description">
                                            <p class="two-post__date"><i class="fa fa-clock-o"></i><?= DateBase::toFormat($n['date'], 'd/m/Y') ?></p>
                                            <h3 class="two-post__title"><a href="<?= $n['url'] ?>"><?= $n['title'] ?></a></h3>
                                            <div class="two-post__intro">
                                                <p><?php echo substr($n['intro'],0,100)?>
                                                    <?php
                                                    if(strlen($n['intro']) > 100) {
                                                        echo '...';
                                                    }
                                                    ?>
                                                </p>
                                            </div>
                                            <a class="two-post__link" href="<?= $n['url'] ?>">Đọc tiếp</a>
                                        </div>
                                    </div>
                                <?php endforeach; endif;?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
<!--</editor-fold>-->

<?php endif; ?>