    <?php
    $optionBasic = $this->home()->optionBasic();
    $optionPage = $this->home()->optionPage();
    $url = $this->UriParams()->getRequest()->getRequestUri();
    $cartService = $this->cart()->getServiceCart();
    $products = $cartService->getProducts();
    $menuOption = $this->home()->getMenu();
?>
<div class="head">
    <?php if(!empty($optionPage['view_header-1'])):?>
        <div class="head1">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="head1__inner">
                            <div class="head1__logo">
                                <a class="logo" href="/">
                                    <?php if(!empty($optionBasic['logo'])): ?>
                                        <img src="<?= $optionBasic['logo'] ?>" alt="<?= !empty($optionBasic['sologan']) ? $optionBasic['sologan']:null ?>" />
                                    <?php endif; ?>
                                </a>
                            </div>
                            <div class="head1__formsearch">
                                <form id="search" action="/search" method="get">
                                    <div class="search-box">
                                        <input type="text" name="q" placeholder="Tìm kiếm..."/>
                                        <button type="submit">
                                            Tìm kiếm
                                        </button>
                                    </div>
                                    <div id="searchFolding"></div>
                                    <?php if(!empty($optionPage['tu-khoa-tim-kiem'])): ?>
                                        <p>
                                            <?php
                                            $key = explode(',', $optionPage['tu-khoa-tim-kiem']);
                                            foreach($key as $k) {
                                                echo '<a href="/search?q='.trim(strtolower($k)).'">'.trim($k).'</a>';
                                            }
                                            ?>
                                        </p>
                                    <?php endif; ?>
                                </form>
                            </div>
                            <div class="head1__tel">
                                <a href="tel:<?= $optionPage['ho-tro'] ?>">
                                    <img src="tp/T008/img/customer_service.png" > <span>Tư vấn & hỗ trợ</span>
                                </a>
                            </div>
                            <div class="head1__user">
                                <ul class="RegisterLogin">
                                    <?php
                                        if ($this->user()->hasIdentity()) {
                                    ?>
                                        <li><a>Xin chào: <?= $this->user()->getUser()->getFullName() ? $this->user()->getUser()->getFullName():ucfirst($this->user()->getUser()->getUserName()) ?></a></li>
                                        <li><a href="/user/signout">Thoát</a></li>
                                    <?php
                                        }else{
                                    ?>
                                        <li><a href="/user/signin">Đăng nhập</a></li> |
                                        <li><a href="/user/signup">Đăng ký</a></li>
                                    <?php
                                        }
                                    ?>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php endif;?>
    <?php if(!empty($optionPage['view_header-2'])): ?>
        <div class="head2">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="head2__inner">
                            <div class="head2__left navbar-header">
                                <ul class="nav">
                                    <?php
                                    if(!empty($menuOption['header_menu'])):
                                        foreach($menuOption['header_menu'] as $m):?>
                                            <li <?= (!empty($m['image']) && $m['image']!= "undefined")
                                                ? ''
                                                : "class='text-center'" ?>
                                                >
                                                <a href="<?= $m['url'] ?>">
                                                    <?php if(!empty($m['image']) && $m['image']!= "undefined"): ?>
                                                        <figure class="lazy" data-src="<?= $m['image'] ?>"></figure>
                                                    <?php endif; ?>
                                                    <span><?= $m['name'] ?></span>
                                                </a>
                                                <?= $m['children']
                                                    ? '<i class="fa fa-caret-down" aria-hidden="true"></i>'
                                                    : '' ?>
                                                <?php if($m['children']): ?>
                                                    <ul class="nav2">
                                                        <!-- <h2>Danh mục</h2> -->
                                                        <?php foreach($m['children'] as $mc):?>
                                                            <li><a href="<?= $mc['url'] ?>"><?= $mc['name'] ?></a></li>
                                                        <?php endforeach; ?>
                                                    </ul>
                                                <?php endif; ?>
                                            </li>
                                        <?php endforeach;endif;?>
                                </ul>
                                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#mobileNav">
                                    <i class="fa fa-bars" aria-hidden="true"></i>
                                    <i class="fa fa-times" aria-hidden="true"></i>
                                </button>
                                <div class="collapse navbar-collapse" id="mobileNav">
                                    <ul class="mobile-nav nav navbar-nav">
                                        <?php
                                        if(!empty($menuOption['header_menu'])):
                                            foreach($menuOption['header_menu'] as $m):?>
                                                <li <?= (!empty($m['image']) && $m['image']!= "undefined")
                                                    ? ''
                                                    : "class='text-center'" ?>
                                                    >
                                                    <a class="dropdown-toggle" data-toggle="dropdown" href="<?= $m['url'] ?>">
                                                        <?php if(!empty($m['image']) && $m['image']!= "undefined"): ?>
                                                            <figure class="lazy" data-src="<?= $m['image'] ?>"></figure>
                                                        <?php endif; ?>
                                                        <span><?= $m['name'] ?></span>
                                                        <?= $m['children']
                                                            ? '<i class="fa fa-caret-down" aria-hidden="true"></i>'
                                                            : '' ?>
                                                    </a>
                                                    <?php if($m['children']): ?>
                                                        <ul class="nav2 dropdown-menu">
                                                            <!-- <h2>Danh mục</h2> -->
                                                            <?php foreach($m['children'] as $mc):?>
                                                                <li><a href="<?= $mc['url'] ?>"><?= $mc['name'] ?></a></li>
                                                            <?php endforeach; ?>
                                                        </ul>
                                                    <?php endif; ?>
                                                </li>
                                            <?php endforeach;
                                                endif;?>
                                    </ul>
                                </div>
                            </div>
                            <div class="head2__right">
                                <div class="head2__favorite">
                                    <a href="">
                                        <i class="fa fa-heartbeat" aria-hidden="true">
                                        </i>
                                        <span>Yêu thích</span>
                                    </a>
                                </div>
                                <div class="head2__cart">
                                    <?php
                                        $cartService = $this->cart()->getServiceCart();
                                        $products = $cartService->getProducts();
                                    ?>
                                    <a class="totalCart" href="/cart">
                                        <i class="fa fa-shopping-bag">
                                            <span><?= $cartService->getTotalProducts() ?></span>
                                        </i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php endif; ?>
</div>

<div class="slide-right">
    <div class="slide-right__inner">
        <a class="slide-right__close"></a>
        <a class="slide-right__cart"><i class="fa fa-shopping-bag" aria-hidden="true"></i><p>Giỏ hàng</p><span><?= $cartService->getTotalProducts() ?></span></a>
    </div>
    <div class="slider-right__content">
        <div class="slider-right__content--inner">
            <?php
                if(!empty($products)):
            ?>
                <h2>Giỏ hàng của tôi (<?= $cartService->getTotalProducts() ?>)</h2>
                <div class="slider-right__money">
                    <p><a href="/cart">Xem giỏ hàng</a></p>
                    <span>Tổng tiền: </span>
                    <strong><?= number_format($cartService->getTotalMoney()).'đ'; ?></strong>
                </div>
                <ul class="slider-right__product">
                    <?php
                        foreach ($products as $p):
                        $imageFirst = '';
                        if(!empty(json_decode($p->getImage(), true))){
                            $imageFirst = array_shift(json_decode($p->getImage(), true));
                        }
                    ?>
                        <li>
                            <a href="<?= $p->getViewLink() ?>">
                                <div class="slider-right__product--left">
                                    <figure class="lazy slider-right__product--image" data-src="<?= $imageFirst ?>"></figure>
                                </div>
                                <h3><?=$p->getTitle() ?>
                                    <p><strong><?= number_format($p->getPriceOld() ? $p->getPriceOld():$p->getPrice()).' đ' ?></strong> x <?= $p->getQuantity() ?></p>
                                </h3>
                            </a>
                            <?= '<span class="deleteCart fa fa-trash-o" data-id="'.$p->getId().'" data-color="'.(isset($p->getOptions()['dataColor']) ? $p->getOptions()['dataColor']->getId():'').'" data-size="'.(isset($p->getOptions()['dataSize']) ? $p->getOptions()['dataSize']->getId():'').'"></span>' ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
                <div class="slider-right__money">
                    <span>Tổng tiền: </span>
                    <strong><?= number_format($cartService->getTotalMoney()).'đ'; ?></strong>
                </div>
                <a class="slider-right__order" href="/cart/checkout">Đặt hàng</a>
            <?php
                endif;
            ?>
        </div>
    </div>
</div>