<?php
$q = $this->request->getQuery('q');

$this->headTitle($this->escapeHtml($this->translate('Tìm kiếm sản phẩm "'.$q.'"')));
$this->headMeta()->appendName('description', ('Tìm kiếm sản phẩm "'.$q.'"'));
$this->headMeta()->appendName('keywords', ('Tìm kiếm sản phẩm "'.$q.'"'));
$this->headMeta()->appendProperty('og:title', 'Tìm kiếm sản phẩm "'.$q.'"');
$menuOption = $this->home()->getMenu();
$optionPage = $this->home()->optionPage();
$optionBasic = $this->home()->optionBasic();
$cs = [
    '/tp/F010/css/p.css'
];
echo '<link href="'.srcLink($cs,1).'" media="screen" rel="stylesheet" type="text/css">';

$product = $this->paginator;
?>
<div class="main">
    <div class="container">

        <div class="row">
            <ul class="breadcrumb breadcrumb-category">
                <li><a href="/">Trang chủ</a></li>
                <li><a href="/product">Tìm kiếm</a></li>
            </ul>
            <?php
            if(!empty($menuOption['product_sidebar']) || !empty($optionPage['view_danh-muc-san-pham-1']) || !empty($optionPage['view_danh-muc-san-pham-2'])):
                echo $this->render('product/product/sidebar');
                echo '<div class="col-md-9">';
            else:
                echo '<div class="col-md-12">';
            endif;
            ?>
            <?php
            $show = $this->request->getQuery('show');

            if(count($product)){
                echo '<div class="right">
                               <div class="productCategory">';
                echo '<div class="titlePaginator"><h1 class="title">Tìm kiếm với từ khóa "'.(isset($q) ? $q:null).'"</h1>';
                echo '    <select onchange="location = this.options[this.selectedIndex].value;">
                                        <option value="' . $this->product()->removeFilter('show') . '">Mới cập nhật</option>
                                        <option value="' . $this->product()->addFilter('show', 'priceAsc',2) . '" '.($show == 'priceAsc' ? 'selected':'').'>Giá tăng dần</option>
                                        <option value="' . $this->product()->addFilter('show', 'priceDesc',2) . '" '.($show == 'priceDesc' ? 'selected':'').'>Giá giảm dần</option>
                                        <option value="' . $this->product()->addFilter('show', 'SaleOff',2) . '" '.($show == 'SaleOff' ? 'selected':'').'>Giảm giá</option>
                                  </select></div>';
                                    echo '<ul class="lPC product__list">';
                                    foreach($product as $p){
                                        $image = json_decode($p->getImage(), true);
                                        if(!empty($image)){
                                            $imageFirst = array_shift($image);
                                        }
                                        echo '<li>
                                        <div class="product-item__inner">
                                                <div class="product-image__wrapper">
                                                    <a class="pI" href="'.$p->getViewLink().'"><figure class="lazy image-product" data-src="'.(!empty($imageFirst) ? $imageFirst :'').'"></figure></a>
                                                </div>
                                                <div class="product-item__info">
                                                    <h3><a href="'.$p->getViewLink().'">'.$p->getTitle().'</a></h3>
                                                    <p class="price '.($p->getPriceOld() ? 'priceOld':null) .'">
                                                       '.(!empty($p->getPriceOld()) ? '<span>'.number_format($p->getPriceOld()).'</span><i>'.number_format($p->getPrice()).'</i>':number_format($p->getPrice()) ).'
                                                    </p>
                                                    <a class="btnAddCart" data-quantity="1" data-id="'.$p->getId().'">Giỏ hàng</a>
                                                </div>
                                            </div>
                                    </li>';
                }
                echo '</ul>';
                echo '<div class="paginatorProduct">';
                echo $this->paginationControl($this->paginator, 'Elastic', 'partial/listPage');
                echo '</div>';
                echo '</div></div>';
            }
            ?>
        </div>
        </div>
    </div>
</div>
