
<?php
$view = $this->page;
$current_page_URL = $_SERVER["SERVER_NAME"] . $_SERVER["REQUEST_URI"];
$this->headTitle($this->escapeHtml($this->translate($view->getName())));
$this->headMeta()->appendName('url', ('http://'.$current_page_URL));
$this->headMeta()->appendName('description', (!empty($view->getDescription()) ? $view->getDescription():null));
$this->headMeta()->appendName('keywords', (!empty($view->getMetaKeyword()) ? $view->getMetaKeyword():null));
$this->headMeta()->appendProperty('og:title', (!empty($view->getMetaTitle()) ? $view->getMetaTitle():null));
$cs = [
    '/tp/F001/css/n.css'
];
echo '<link href="'.srcLink($cs,1).'" media="screen" rel="stylesheet" type="text/css">';
$js = [
    '/tp/F001/js/n.js'
];
echo '<script type="text/javascript" src="'.srcLink($js,1).'"></script>';
?>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="detailNews">
                <div class="pageView">
                    <h1><?= $view->getName() ?></h1>
                    <div class="social">
                        <?php
                        ?>
                        <div style="float: left;margin: 0 5px 0 0;" class="fb-like" data-href="<?= $current_page_URL.$view->getViewLink() ?>" data-layout="button" data-action="like" data-show-faces="false" data-share="true"></div>
                        <div class="g-plusone" data-size="medium"></div>
                    </div>
                    <script src="https://apis.google.com/js/platform.js" async defer>
                        {lang: 'vi'}
                    </script>
                </div>
                <?php
                    echo $view->getDescription();
                ?>
            </div>
        </div>
    </div>
</div>


