<?php
    $paginator =  $this->paginator;
    $paginator->setItemCountPerPage($this->uriParams()->getRequest()->getQuery('icpp') ? : 15);

    $category = $this->category;

    $image = json_decode($category->getImage(), true);
    $imageFirst = '';
    if(!empty($image)){
        $imageFirst = array_shift($image);
    }
    $cs = [
        '/tp/A002/css/n.css'
    ];
    echo '<link href="'.srcLink($cs,1).'" media="screen" rel="stylesheet" type="text/css">';
    $optionPage = $this->home()->optionPage();
    $optionBasic = $this->home()->optionBasic();
?>
<?php
    $image = 'http://'.$_SERVER['HTTP_HOST'].$imageFirst;
    $imageInfo = getimagesize($image);
    /**** Start SEO DWEB *****/
    echo $this->headLink(['rel' => 'canonical', 'href' => 'http://'.$_SERVER['HTTP_HOST'].$category->getViewLink() ]);
    $this->headTitle(!empty($category->getMetaTitle()) ? $category->getMetaTitle():null);
    $this->headMeta()->appendName('description', (!empty($category->getMetaDescription()) ? $category->getMetaDescription():null));
    $this->headMeta()->appendName('keywords', (!empty($category->getMetaKeyword()) ? $category->getMetaKeyword():null));

    $this->headMeta()->appendProperty('og:title', !empty($category->getMetaTitle()) ? $category->getMetaTitle():null);
    $this->headMeta()->appendProperty('og:description', !empty($category->getMetaDescription()) ? $category->getMetaDescription():null);
    $this->headMeta()->appendProperty('og:image', !empty($imageFirst) ? 'http://'.$_SERVER['HTTP_HOST'].$imageFirst:null);
    $this->headMeta()->appendProperty('og:image:secure_url', !empty($imageFirst) ? 'http://'.$_SERVER['HTTP_HOST'].$imageFirst:null);
    $this->headMeta()->appendProperty('og:image:width', $imageInfo['0']);
    $this->headMeta()->appendProperty('og:image:height', $imageInfo['1']);
    $this->headMeta()->appendProperty('og:type', 'Category Article');
    $this->headMeta()->appendProperty('og:url', 'http://'.$_SERVER['HTTP_HOST'].$category->getViewLink());
    $this->headMeta()->appendProperty('og:site_name', $optionBasic['sologan']);

    $this->headMeta()->appendName('twitter:card', !empty($image) ? $image:'summary_large_image');
    $this->headMeta()->appendName('twitter:title', !empty($category->getMetaTitle()) ? $category->getMetaTitle():null);
    $this->headMeta()->appendName('twitter:description', (!empty($category->getMetaDescription()) ? $category->getMetaDescription():null));
    $this->headMeta()->appendName('twitter:image', !empty($image) ? $image:null);
    /**** End SEO DWEB *****/
?>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <?php
                $n = $this->newsCategory()->getCategories();
                if(count($n)){
                    echo '<ul class="navNews">';
                    foreach($n as $b){
                        echo '<li><a '.($category->getId() == $b->getId() ? 'class="active"':'').' href="'.$b->getViewLink().'">'.$b->getName().'</a></li>';
                    }
                    echo '</ul>';
                }
            if(!empty($paginator)){
                ?>

                <div class="post-last__list post-last__list--category">
                    <?php
                    foreach($paginator as $n):
                        $extraContent = json_decode($n->getExtracontent(), true);

                        $image = json_decode($n->getImage(), true);
                        $imageFirst = '';
                        if(!empty($image)){
                            $imageFirst = array_shift($image);
                        }
                        ?>
                        <div class="post-last__item">
                            <div class="post-last__image">
                                <a href="<?= $n->getViewLink(); ?>">
                                    <figure class="lazy" data-src="<?= $imageFirst ?>"></figure>
                                </a>
                            </div>
                            <div class="post-last__content">
                                <?= !empty($extraContent['nam']) ? '<span class="post-last__date">'.$extraContent['nam'].'</span>':null ?>
                                <h2 class="post-last__title"><a href="<?= $n->getViewLink() ?>"><?= $n->getTitle() ?></a></h2>
                                <div class="post-last__intro"><?= $n->getDescription() ?></div>
                                <a class="post-last__link" href="<?= $n->getViewLink() ?>">Xem thêm <span class="icon-row"></span></a>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>

                <?php
                echo '<div class="category__paginator">';
                echo $this->paginationControl($this->paginator, 'Elastic', 'partial/listPage');
                echo '</div>';
            }
            ?>
        </div>
    </div>
</div>
