<?php
    echo $this->headtitle($this->escapehtml($this->translate('Thêm')));
    $form = $this->form;
    $dep = $this->dependencies;
    $admin = $this->supperAdmin;
?>


<form method="post" class="form-horizontal" enctype="multipart/form-data" data-parsley-validate novalidate>
    <div class="row">
        <div class="col-sm-12">
        <div class="card-box">
            <div class="row">
                <div class="col-sm-4">
                    <h5><b>Tài khoản</b></h5>
                    <p class="text-muted font-13 m-b-30">
                        Thông tin tài khoản
                    </p>
                    <div class="portlet-body form">
                        <div class="form-group">
                            <label class="col-sm-3 control-label" for="Username">Tài khoản</label>
                            <div class="col-sm-8">
                                <?= $this->formelement($form->get('username')->setAttributes(['class' => 'form-control', 'placeholder'=>'Tài khoản', 'required' => 'required', 'data-parsley-error-message' => 'Tài khoản không được để trống'])) ?>
                                <?= $this->formelementerrors($form->get('username'),['class' => 'parsley-errors-list filled']) ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label" for="Password">Mật khẩu</label>
                            <div class="col-sm-8">
                                <?= $this->formelement($form->get('password')->setAttributes(['class' => 'form-control', 'placeholder'=>'Mật khẩu', 'required' => 'required', 'data-parsley-minlength' => '6', 'data-parsley-error-message' => 'Mật khẩu không được để trống, tối thiểu 6 ký tự'])) ?>
                                <?= $this->formelementerrors($form->get('password'),['class' => 'parsley-errors-list filled']) ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label" for="Email">Email</label>
                            <div class="col-sm-8">
                                <?= $this->formelement($form->get('email')->setAttributes(['class' => 'form-control', 'placeholder'=>'Email', 'required' => 'required', 'data-parsley-type' => 'email', 'data-parsley-error-message' => 'Email không được để trống'])) ?>
                                <?= $this->formelementerrors($form->get('email'),['class' => 'parsley-errors-list filled']) ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label" for="Email">Điện thoại</label>
                            <div class="col-sm-8">
                                <?= $this->formelement($form->get('mobile')->setAttributes(['class' => 'form-control', 'placeholder'=>'Điện thoại', 'required' => 'required', 'data-parsley-type' => 'digits', 'data-parsley-length' => '[10,11]', 'data-parsley-error-message' => 'Điện thoại không được để trống'])) ?>
                                <?= $this->formelementerrors($form->get('mobile'),['class' => 'parsley-errors-list filled']) ?>
                            </div>
                        </div>
                        <?php if($admin): ?>
                        <div class="form-group">
                            <label class="col-sm-3 control-label" for="Email">Store</label>
                            <div class="col-sm-8">
                                <?= $this->formelement($form->get('storeId')->setAttributes(['class' => 'form-control select-ajax-store', 'multiple'=>'multiple'])) ?>
                                <?= $this->formelementerrors($form->get('storeId'),['class' => 'parsley-errors-list filled'])?>
                            </div>
                        </div>
                        <?php endif; ?>
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-9 m-t-15">
                                <?=$this->formelement($form->get('submit')->setAttributes(['class' => 'btn btn-default']))?>
                                <?=$this->formelement($form->get('reset')->setAttributes(['class' => 'btn']))?>
                            </div>
                        </div>

                    </div>
                </div>

                <div class="col-sm-8">
                    <h5><b>Phân quyền</b></h5>
                    <p class="text-muted font-13 m-b-30">
                        Chi tiết phân quyền
                    </p>
                    <div class="row">
                    <?php
                        if(!empty($dep)):
                        foreach($dep as $k => $d):
                    ?>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label class="col-sm-3 control-label"><?= $k ?>
                                        <?php if($k == 'Tài khoản'):  ?>
                                            <p class="text-muted font-13 font-light"> Khuyến cáo không lựa chọn cho tài khoản thường </p>
                                        <?php endif; ?>
                                    </label>
                                    <div class="col-sm-9">
                                        <?php
                                            if(!empty($d)):
                                            foreach($d as $text => $v):
                                        ?>
                                        <div class="checkbox checkbox-custom">
                                            <?php if($k == 'Tài khoản'): ?>
                                                <input id="remember-2" name="<?= vnString($k).' '.$v ?>" type="checkbox" >
                                            <?php else: ?>
                                                <input id="remember-2" checked name="<?= vnString($k).' '.$v ?>" type="checkbox" >
                                            <?php endif; ?>
                                            <label for="remember-2"> <?= $text ?> </label>
                                        </div>
                                        <?php
                                            endforeach;
                                            endif;
                                        ?>
                                    </div>
                                </div>
                            </div>
                    <?php
                        endforeach;
                        endif;
                    ?>
                    </div>
                </div>
            </div>


        </div>
        </div>
    </div>
</form>