<?php
$form = $this->form;
echo $this->headtitle($this->escapehtml($this->translate('Thêm website')));
?>

<form method="post" enctype="multipart/form-data" data-parsley-validate novalidate>
    <div class="row">
        <div class="col-sm-8">
            <div class="card-box">
                <div class="portlet-title">
                    <h4 class="m-t-0 header-title m-b-20"><b>Thêm website</b></h4>
                </div>
                <div class="portlet-body form">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label class="control-label" for="firstName">Tên miền</label>
                                <p class="text-muted m-b-15 font-13">
                                    Tài khoản đăng nhập, và tên miền http://name.dweb.vn. Bạn có thể trỏ về tên miền của bạn http://domain.com
                                </p>
                                <?= $this->formelement($form->get('store')->setAttributes(['class' => 'form-control', 'placeholder'=>'Tên doanh nghiệp', 'required' => 'required', 'data-parsley-error-message' => 'Không được để trống'])) ?>
                                <?= $this->formelementerrors($form->get('store'),['class' => 'parsley-errors-list filled'])?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label class="control-label" for="firstName">Password</label>
                                <?= $this->formelement($form->get('password')->setAttributes(['class' => 'form-control', 'placeholder'=>'Password','required' => 'required',])) ?>
                                <?= $this->formelementerrors($form->get('password'),['class' => 'parsley-errors-list filled'])?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label class="control-label" for="firstName">Tên giao diện</label>
                                <?= $this->formelement($form->get('uitemplateId')->setAttributes(['class' => 'form-control select-ajax-template', 'multiple'=>'multiple'])) ?>
                                <?= $this->formelementerrors($form->get('uitemplateId'),['class' => 'parsley-errors-list filled'])?>
                            </div>
                        </div>
                    </div>
                    <div class="form-actions">
                        <?=$this->formelement($form->get('submit')->setAttributes(['class' => 'btn btn-default']))?>
                        <?=$this->formelement($form->get('reset')->setAttributes(['class' => 'btn']))?>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-sm-4">
        </div>
        <!-- End col-sm-8 -->

    </div>
</form>


