<?php
echo $this->headtitle($this->escapehtml($this->translate('Liên hệ')));
use Home\Model\DateBase;
$view = $this->view;
?>
<div class="row layout_pc" style="">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="pull-left m-t-50">
                            <address>
                                <p><strong><?= $view->getName() ? $view->getName():'' ?></strong></p>
                                <p class="m-t-10">Số điện thoại: <?= $view->getPhone(); ?></p>
                                <p class="m-t-10">Email: <?= $view->getEmail(); ?></p>
                            </address>
                        </div>
                        <div class="pull-right m-t-50">
                            <p><strong>Ngày tạo: </strong> <?= DateBase::toFormat($view->getCreatedDateTime(),'H:i d/m/Y') ?></p>
                        </div>
                    </div>
                </div>
                <hr/>
                <div class="row m-b-50">
                    <div class="col-md-12">
                        <?= $view->getContent() ? $view->getContent():'' ?>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>