<?php
$optionBasic = $this->home()->optionBasic();
$optionPage = $this->home()->optionPage();
?>
<div class="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <ul class="f1">
                    <li>
                        <h2>Đồng hành cùng chúng tôi</h2>
                        <ul class="social">
                            <li><a href="<?= !empty($optionBasic['facebook']) ? $optionBasic['facebook']:null ?>"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                            <li><a href="<?= !empty($optionBasic['twitter']) ? $optionBasic['twitter']:null ?>"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                            <li><a href="<?= !empty($optionBasic['youtube']) ? $optionBasic['youtube']:null ?>"><i class="fa fa-youtube" aria-hidden="true"></i></a></li>
                        </ul>
                    </li>
                    <li>
                        <h2>Đăng ký nhận tin</h2>
                        <p>Đăng ý Email của bạn để trở thành khách hàng đầu tiên được nhận thông tin ưu đãi mới nhất</p>
                        <form>
                            <input type="text" placeholder="Email" />
                            <button data-gender="1" class="btn">Gửi</button>
                        </form>
                    </li>
                    <li>
                        <h2>Cửa hàng</h2>
                        <?= !empty($optionPage['cua-hang']) ? $optionPage['cua-hang']:null ?>
                    </li>
                </ul>

                <ul class="f2">
                    <li>
                        <h2>Chính sách mua hàng online</h2>
                        <?= !empty($optionPage['chinh-sach-mua-hang']) ? $optionPage['chinh-sach-mua-hang']:null ?>
                    </li>
                    <li>
                        <h2>Danh mục</h2>
                        <?php
                            $category = $this->category()->getCategories();
                            if(count($category)){
                            echo '<ul>';
                            foreach($category as $c){
                        ?>
                                <li>
                                    <a href="<?= $c->getViewLink() ?>"><i class="fa fa-angle-right"></i> <?= $c->getName() ?></a>
                                </li>
                        <?php
                            }
                        echo '</ul>';
                        }
                        ?>
                    </li>
                    <li>
                        <h2>Liên hệ với chúng tôi</h2>
                        <?= !empty($optionPage['lien-he-voi-chung-toi']) ? $optionPage['lien-he-voi-chung-toi']:null ?>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>