<?php
    echo $this->doctype();
    $optionBasic = $this->home()->optionBasic();
?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
        <?php
        echo $this->headTitle()->setSeparator('')->setAutoEscape(false);
        $this->headMeta()->appendName('DC.language', 'scheme=utf-8 content=vi');
        echo $this->headMeta();

        echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $optionBasic['favicon'] ? $optionBasic['favicon']:null ]);
        $cs = [
            '/assets/css/web/bootstrap.css',
            '/assets/css/web/font-awesome.min.css',
            '/assets/css/web/owl.carousel.css',
            '/tp/F006/css/h.css',
        ];
        echo '<link href="'.srcLink($cs,1).'" media="screen" rel="stylesheet" type="text/css">';
        $js = [
            '/assets/js/web/jquery-1.11.2.min.js',
        ];
        echo '<script type="text/javascript" src="'.srcLink($js,2).'"></script>';
        echo !empty($optionBasic['scriptHead']) ? '<script>'.$optionBasic['scriptHead'].'</script>' : null;
        ?>

    </head>

    <body>
        <?php
            echo $this->render('layout/header');
            echo $this->content;
            echo $this->render('layout/footer');
            echo $this->render('layout/modal');
            echo !empty($optionBasic['scriptBody']) ? '<script>'.$optionBasic['scriptBody'].'</script>' : null;
        ?>
    </body>
    <?php
        $r = [
            '/tp/F006/css/r.css',
        ];
        echo '<link href="'.srcLink($r,1).'" media="screen" rel="stylesheet" type="text/css">';
        if(!empty($optionBasic['styleFooter'])) echo '<style>'.$optionBasic['styleFooter'].'</style>';
        $js = [
            '/assets/js/web/bootstrap.min.js',
            '/assets/js/web/jquery.lazy.min.js',
            '/assets/js/web/owl.carousel.js',
            '/assets/js/web/jquery-ui-1.10.3.custom.min.js',
            '/tp/F006/js/a.js',
        ];
        echo '<script type="text/javascript" src="'.srcLink($js,2).'"></script>';
        echo !empty($optionBasic['scriptFooter']) ? '<script>'.$optionBasic['scriptFooter'].'</script>' : null;
    ?>
</html>