<?php
    use Home\Model\DateBase;
    $optionBasic = $this->home()->optionBasic();
    $optionPage = $this->home()->optionPage();
    $homePage = $this->home()->homePage();
    $fileLogo = getimagesize('http://'.$_SERVER['HTTP_HOST'].$optionBasic['logo']);
?>
<?php
    /**** Start SEO DWEB *****/
    echo $this->headLink(['rel' => 'canonical', 'href' => 'http://'.$_SERVER['HTTP_HOST'] ]);
    $this->headTitle($this->escapeHtml($this->translate(!empty($optionBasic['metaTitle']) ? $optionBasic['metaTitle']:$optionBasic['sologan'])));
    $this->headMeta()->appendName('description', (!empty($optionBasic['metaDescription']) ? $optionBasic['metaDescription']:null));
    $this->headMeta()->appendName('keywords', (!empty($optionBasic['metaKeyword']) ? $optionBasic['metaKeyword']:null));
    $this->headMeta()->appendProperty('og:title', !empty($optionBasic['metaTitle']) ? $optionBasic['metaTitle']:$optionBasic['sologan'] );
    $this->headMeta()->appendProperty('og:description', !empty($optionBasic['metaDescription']) ? $optionBasic['metaDescription']:null);
    $this->headMeta()->appendProperty('og:image', !empty($optionBasic['logo']) ? 'http://'.$_SERVER['HTTP_HOST'].$optionBasic['logo']:null);
    $this->headMeta()->appendProperty('og:image:secure_url', !empty($optionBasic['logo']) ? 'http://'.$_SERVER['HTTP_HOST'].$optionBasic['logo']:null);
    $this->headMeta()->appendProperty('og:image:width', $fileLogo['0']);
    $this->headMeta()->appendProperty('og:image:height', $fileLogo['1']);
    $this->headMeta()->appendProperty('og:type', 'Website');
    $this->headMeta()->appendProperty('og:url', 'http://'.$_SERVER['HTTP_HOST']);
    $this->headMeta()->appendProperty('og:site_name', $optionBasic['sologan']);

    $this->headMeta()->appendName('twitter:card', !empty($optionBasic['logo']) ? 'http://'.$_SERVER['HTTP_HOST'].$optionBasic['logo']:'summary_large_image');
    $this->headMeta()->appendName('twitter:title', !empty($optionBasic['metaTitle']) ? $optionBasic['metaTitle']:null);
    $this->headMeta()->appendName('twitter:description', (!empty($optionBasic['metaDescription']) ? $optionBasic['metaDescription']:null));
    $this->headMeta()->appendName('twitter:image', !empty($optionBasic['logo']) ? 'http://'.$_SERVER['HTTP_HOST'].$optionBasic['logo']:null);
    /**** End SEO DWEB *****/
?>
<?php
if(!empty($homePage)):
    $count = 0;
    foreach($homePage as $k => $v ):
        $layout = explode(' ',$k);
        switch ($layout[0]) {
            case "slider-layout":
                echo $this->partial('home/template/slider', ['bannerList' => $v]);
                break;
            case "intro-layout":
                echo $this->partial('home/template/intro-layout', ['introLayout' => $v]);
                break;
            case "option-layout":
                echo $this->partial('home/template/option-layout', ['optionLayout' => $v]);
                break;
            case "news-layout-1":
                echo $this->partial('home/template/news-layout-1', ['newsLayout1' => $v]);
                break;
            case "news-layout-2":
                echo $this->partial('home/template/news-layout-2', ['newsLayout2' => $v]);
                break;
            case "html-layout":
                echo $this->partial('home/template/html-layout', ['htmlLayout' => $v]);
                break;
            case "image-layout":
                echo $this->partial('home/template/image-layout', ['imageLayout' => $v]);
                break;
            case "galery-layout":
                echo $this->partial('home/template/galery-layout', ['galeryLayout' => $v]);
                break;
            default:
                break;
        }
    endforeach;
else:

?>
    <?php if(!empty($optionPage['view_banner'])):

        ?>
        <section class="slider">
            <ul id="banner" class="owl-carousel owl-theme">
                <?php
                foreach($optionPage['banner'] as $b):
                    $image = json_decode($b['image'], true);
                    $imageFirst = '';
                    if(!empty($image)){
                        $imageFirst = array_shift($image);
                    }
                    ?>
                    <li>
                        <a href="">
                            <figure class="slider-image" style="background-image: url(<?= $imageFirst ?>)">
                                <div class="slider__content">
                                    <h3><?= $b['title'] ?></h3>
                                    <p><?= $b['description'] ?></p>
                                    <span>Đọc tiếp</span>
                                </div>
                            </figure>
                        </a>
                    </li>
                <?php
                endforeach;
                ?>
            </ul>
        </section>

    <?php endif; ?>

    <?php
    if(!empty($optionPage['view_tin-tuc-1'])):
        ?>
        <section class="three-post">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="three-post__inner">
                            <div class="three-post__list">
                                <?php
                                foreach($optionPage['3-bai-viet'] as $n):
                                    $image = json_decode($n['image'], true);
                                    if(!empty($image)) {
                                        $imageFirst = array_shift($image);
                                    }
                                    ?>
                                    <div class="three-post__item">
                                        <div class="three-post__item--inner">
                                            <h3 class="three-post__title"><a href="<?= $n['url'] ?>"><?= $n['title'] ?></a></h3>
                                            <a href="<?= $n['url'] ?>"><figure class="three-post__image lazy" data-src="<?= $imageFirst ?>"></figure></a>
                                            <div class="three-post__intro">
                                                <?= $n['intro'] ?>
                                                <a href="<?= $n['url'] ?>">Đọc tiếp <i class="fa fa-caret-right"></i></a>
                                            </div>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    <?php endif ?>
    <?php
    if(!empty($optionPage['view_dong-chu-quang-cao-1'])):
        ?>
        <section class="one-post">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="one-post__headline">
                            <?= !empty($optionPage['dong-chu-quang-cao-1']) ? $optionPage['dong-chu-quang-cao-1']:''; ?>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    <?php endif ?>

    <?php
    if(!empty($optionPage['view_tin-tuc-2'])):
        ?>
        <section class="five-post">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="five-post__inner">
                            <div class="five-post__list">
                                <?php
                                foreach($optionPage['4-bai-viet'] as $n):
                                    $image = json_decode($n['image'], true);
                                    if(!empty($image)) {
                                        $imageFirst = array_shift($image);
                                    }
                                    ?>
                                    <div class="five-post__item">
                                        <div class="five-post__item--inner">
                                            <h3 class="five-post__title"><a href="<?= $n['url'] ?>"><?= $n['title'] ?></a></h3>
                                            <a href="<?= $n['url'] ?>"><figure class="five-post__image lazy" data-src="<?= $imageFirst ?>"></figure></a>
                                            <div class="five-post__intro">
                                                <?= $n['intro'] ?>
                                                <a href="<?= $n['url'] ?>">Đọc tiếp <i class="fa fa-caret-right"></i></a>
                                            </div>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    <?php endif ?>
    <?php
    if(!empty($optionPage['view_cau-hoi-thuong-gap'])):
        ?>
        <section class="choose">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="choose__inner">
                            <div class="choose__left">
                                <h3 class="choose__title"><?= $optionPage['tieu-de-cot-thong-tin-ben-trai'] ? $optionPage['tieu-de-cot-thong-tin-ben-trai'] : '' ?></h3>
                                <div class="choose__intro">
                                    <?= $optionPage['noi-dung-cot-thong-tin-ben-trai'] ? $optionPage['noi-dung-cot-thong-tin-ben-trai'] : '' ?>
                                </div>
                                <ul class="choose__list">
                                    <li><i class="fa fa-angle-right"></i><?= $optionPage['dong-1'] ? $optionPage['dong-1'] : ''?></li>
                                    <li><i class="fa fa-angle-right"></i><?= $optionPage['dong-2'] ? $optionPage['dong-2'] : ''?></li>
                                    <li><i class="fa fa-angle-right"></i><?= $optionPage['dong-3'] ? $optionPage['dong-3'] : ''?></li>
                                    <li><i class="fa fa-angle-right"></i><?= $optionPage['dong-4'] ? $optionPage['dong-4'] : ''?></li>
                                    <li><i class="fa fa-angle-right"></i><?= $optionPage['dong-5'] ? $optionPage['dong-5'] : ''?></li>
                                </ul>
                            </div>
                            <div class="choose__right">
                                <h3 class="choose__title"><?= $optionPage['tieu-de-cau-hoi-thuong-gap'] ? $optionPage['tieu-de-cau-hoi-thuong-gap'] : ''?></h3>
                                <div class="choose__accordion">
                                    <h3><?= $optionPage['cau-hoi-1'] ? $optionPage['cau-hoi-1'] : ''?></h3>
                                    <div class="choose__accordion--content"><?= $optionPage['cau-tra-loi-1'] ? $optionPage['cau-tra-loi-1'] : ''?></div>
                                    <h3><?= $optionPage['cau-hoi-2'] ? $optionPage['cau-hoi-2'] : ''?></h3>
                                    <div class="choose__accordion--content"><?= $optionPage['cau-tra-loi-2'] ? $optionPage['cau-tra-loi-2'] : ''?></div>
                                    <h3><?= $optionPage['cau-hoi-3'] ? $optionPage['cau-hoi-3'] : ''?></h3>
                                    <div class="choose__accordion--content"><?= $optionPage['cau-tra-loi-3'] ? $optionPage['cau-tra-loi-3'] : ''?></div>
                                    <h3><?= $optionPage['cau-hoi-4'] ? $optionPage['cau-hoi-4'] : ''?></h3>
                                    <div class="choose__accordion--content"><?= $optionPage['cau-tra-loi-4'] ? $optionPage['cau-tra-loi-4'] : ''?></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    <?php endif ?>
    <?php if(!empty($optionPage['view_3-cot-thong-tin-1'])): ?>
        <section class="three-post-2">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="three-post-2__inner">
                            <div class="three-post-2__headline">

                                <h2><?=$optionPage['tieu-de-3-cot-thong-tin-1'] ? $optionPage['tieu-de-3-cot-thong-tin-1'] : ''?></h2>
                                <div class="three-post-2__intro">
                                    <?=$optionPage['mo-ta-3-cot-thong-tin-1'] ? $optionPage['mo-ta-3-cot-thong-tin-1'] : ''?>
                                </div>
                            </div>
                            <div class="three-post-2__list">
                                <div class="three-post-2__item">
                                    <i class="fa fa-area-chart"></i>
                                    <h2><?= $optionPage['tieu-de-cot-1'] ? $optionPage['tieu-de-cot-1'] : ''?></h2>
                                    <div><?= $optionPage['noi-dung-cot-1'] ? $optionPage['noi-dung-cot-1'] :'' ?></div>
                                </div>
                                <div class="three-post-2__item">
                                    <i class="fa fa-snowflake-o"></i>
                                    <h2><?= $optionPage['tieu-de-cot-2'] ? $optionPage['tieu-de-cot-3'] : ''?></h2>
                                    <div><?= $optionPage['noi-dung-cot-2'] ? $optionPage['noi-dung-cot-3'] : '' ?></div>
                                </div>
                                <div class="three-post-2__item">
                                    <i class="fa fa-handshake-o"></i>
                                    <h2><?= $optionPage['tieu-de-cot-2'] ? $optionPage['tieu-de-cot-3'] : ''?></h2>
                                    <div><?= $optionPage['noi-dung-cot-2'] ? $optionPage['noi-dung-cot-3'] : ''?></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    <?php endif; ?>
    <?php if(!empty($optionPage['view_3-cot-thong-tin-2'])):?>
    <section class="three-post-image">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="three-post-image__inner">
                        <div class="three-post-image__headline">
                            <span><?= $optionPage['tieu-de-3-cot-thong-tin-2'] ? $optionPage['tieu-de-3-cot-thong-tin-2'] : ''?></span>
                            <h2><?= $optionPage['mo-ta-3-cot-thong-tin-2'] ? $optionPage['mo-ta-3-cot-thong-tin-2'] : ''?></h2>
                        </div>
                        <div class="three-post-image__list">
                            <div class="three-post-image__item">
                                <img src="http://success.commercegurus.com/wp-content/uploads/2016/03/success_award_02.png" />
                                <h3><?= $optionPage['noi-dung-cot-thong-tin-1'] ? $optionPage['noi-dung-cot-thong-tin-1'] : ''?></h3>
                            </div>
                            <div class="three-post-image__item">
                                <img src="http://success.commercegurus.com/wp-content/uploads/2016/03/success_award_01.png" />
                                <h3><?= $optionPage['noi-dung-cot-thong-tin-2'] ? $optionPage['noi-dung-cot-thong-tin-2'] : ''?></h3>
                            </div>
                            <div class="three-post-image__item">
                                <img src="http://success.commercegurus.com/wp-content/uploads/2016/03/success_award_03.png" />
                                <h3><?= $optionPage['noi-dung-cot-thong-tin-3'] ? $optionPage['noi-dung-cot-thong-tin-3'] : ''?></h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <?php endif; ?>
    <?php if(!empty($optionPage['view_dong-chu-quang-cao-2'])):?>
    <section class="book">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="book__inner">
                        <h2><?=$optionPage['dong-chu-quang-cao-2'] ? $optionPage['dong-chu-quang-cao-2'] : '' ?></h2>
                        <a href="<?=$optionPage['duong-dan-button'] ? $optionPage['duong-dan-button']: '' ?>"><?=$optionPage['button'] ? $optionPage['button'] : '' ?></a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <?php endif; ?>
<?php endif;?>