<?php
$q = $this->request->getQuery('q');

$this->headTitle($this->escapeHtml($this->translate('Tìm kiếm sản phẩm "'.$q.'"')));
$this->headMeta()->appendName('description', ('Tìm kiếm sản phẩm "'.$q.'"'));
$this->headMeta()->appendName('keywords', ('Tìm kiếm sản phẩm "'.$q.'"'));
$this->headMeta()->appendProperty('og:title', 'Tìm kiếm sản phẩm "'.$q.'"');
$cs = [
    '/tp/T001/css/p.css',
];
echo '<link href="'.srcLink($cs,1).'" media="screen" rel="stylesheet" type="text/css">';
$product = $this->paginator;
?>

<div class="main product">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <ul class="breadcrumb breadcrumb-category">
                    <li><a href="/">Trang chủ</a></li>
                    <li><a href="/san-pham.html">Sản phẩm</a></li>
                </ul>

                <div class="product__search">
                    <div class="box">
                        <h3>Danh mục</h3>
                        <ul class="product__search--category">
                            <?php
                            $categorys = $this->category()->getCategories();
                            ?>
                            <?php if(!empty($categorys)): ?>
                                <?php foreach ($categorys as $c): ?>
                                    <li><a href="<?= $c->getViewLink() ?>"><?= $c->getName() ?></a></li>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </ul>
                    </div>
                    <div class="box">
                        <h3>Giá </h3>
                        <ul class="product__search--price">
                            <?php
                            $this->product()->removeFilter('price');
                            $price = [];
                            if (is_array($this->price)) {
                                $price = $this->price;
                            }
                            if (in_array(array(0, 100000), $price)) {
                                echo '<li><a class="active" rel="nofollow" href="' . $this->product()->removeFilter('price', '0:100000') . '">Dưới 100k</a></li>';
                            }else{
                                echo '<li><a rel="nofollow" href="' . $this->product()->addFilter('price', '0:100000') . '">Dưới 100k</a></li>';
                            }
                            if (in_array(array(100000, 200000), $price)) {
                                echo '<li><a class="active" href="' . $this->product()->removeFilter('price', '100000:200000') . '">100k - 200k</a></li>';
                            }else{
                                echo '<li><a href="' . $this->product()->addFilter('price', '100000:200000') . '">100k - 200k</a></li>';
                            }
                            if (in_array(array(200000, 300000), $price)) {
                                echo '<li><a class="active" href="' . $this->product()->removeFilter('price', '200000:300000') . '">200k - 300k</a></li>';
                            }else{
                                echo '<li><a href="' . $this->product()->addFilter('price', '200000:300000') . '">200k - 300k</a></li>';
                            }
                            if (in_array(array(300000, 400000), $price)) {
                                echo '<li><a class="active" href="' . $this->product()->removeFilter('price', '300000:400000') . '">300k - 400k</a></li>';
                            }else{
                                echo '<li><a href="' . $this->product()->addFilter('price', '300000:400000') . '">300k - 400k</a></li>';
                            }
                            if (in_array(array(400000, 500000), $price)) {
                                echo '<li><a class="active" href="' . $this->product()->removeFilter('price', '400000:500000') . '">400k - 500k</a></li>';
                            }else{
                                echo '<li><a href="' . $this->product()->addFilter('price', '400000:500000') . '">400k - 500k</a></li>';
                            }
                            if (in_array(array(500000), $price)) {
                                echo '<li><a class="active" href="' . $this->product()->removeFilter('price', '500000') . '">Trên 500k</a></li>';
                            }else{
                                echo '<li><a href="' . $this->product()->addFilter('price', '500000') . '">Trên 500k</a></li>';
                            }
                            echo (isset($this->price) ? '<li><a class="removeAttr" href="'.$this->product()->removeFilter('price').'" title="Xóa lựa chọn Giá">x</a></li>':null);
                            ?>
                        </ul>
                    </div>

                    <div class="box">
                        <h3>Màu</h3>
                        <?php
                        $request = $this->requestColor;
                        $requests = explode(',',$request);
                        $attr = $this->home()->getAttr(['type' => 1, 'group' => true]);
                        if(count($attr)){
                            echo '<ul class="product__search--attr product__search--color">';
                            foreach($attr as $at){
                                if(in_array($at->getProductAttrId(),$requests)){
                                    echo '<li><a class="active" href="' . $this->product()->removeFilter('color', $at->getProductAttrId()) . '" style="background-color: '.$at->getColorCode().'" title="'.$at->getName().'">'.$at->getName().'</a></li>';
                                }else{
                                    echo '<li><a href="' . $this->product()->addFilter('color', $at->getProductAttrId()) . '" style="background-color: '.$at->getColorCode().'" title="'.$at->getName().'">'.$at->getName().'</a></li>';
                                }
                            }
                            echo (isset($this->requestColor) ? '<li><a class="removeAttr" href="'.$this->product()->removeFilter('color').'" title="Xóa lựa chọn Color">x</a></li>':null);
                            echo '</ul>';
                        }
                        ?>
                    </div>

                    <div class="box">
                        <h3>Size </h3>
                        <?php
                        $request = $this->requestSize;
                        $requests = explode(',',$request);
                        $attr = $this->home()->getAttr(['type' => 2, 'group' => true]);
                        if(count($attr)){
                            echo '<ul class="product__search--attr">';
                            foreach($attr as $at){
                                if(in_array($at->getProductAttrId(),$requests)){
                                    echo '<li><a href="' . $this->product()->removeFilter('size', $at->getProductAttrId()) . '" class="active" title="'.$at->getName().'">'.$at->getName().'</a></li>';
                                }else{
                                    echo '<li><a href="' . $this->product()->addFilter('size', $at->getProductAttrId()) . '" title="'.$at->getName().'">'.$at->getName().'</a></li>';
                                }
                            }
                            echo (isset($this->requestSize) ? '<li><a class="removeAttr" href="'.$this->product()->removeFilter('size').'" title="Xóa lựa chọn Size">x</a></li>':null);
                            echo '</ul>';
                        }
                        ?>
                    </div>
                </div>
                <div class="product__order">
                    <?php
                    echo '<a><span>Tìm kiếm với từ khóa "'.(isset($q) ? $q:null).'"</span></a>';
                    $show = $this->request->getQuery('show');
                    ?>
                    <a <?= empty($show) ? 'class="active"':null ?> href="<?= $this->product()->removeFilter('show') ?>">Mới cập nhật</a>
                    <a <?= $show == 'priceAsc' ? 'class="active"':null ?> href="<?= $this->product()->addFilter('show', 'priceAsc',2) ?>">Giá tăng dần</a>
                    <a <?= $show == 'priceDesc' ? 'class="active"':null ?> href="<?= $this->product()->addFilter('show', 'priceDesc',2) ?>">Giá giảm dần</a>
                    <a <?= $show == 'SaleOff' ? 'class="active"':null ?> href="<?= $this->product()->addFilter('show', 'SaleOff',2) ?>">Giảm giá</a>
                </div>
            </div>
            <div class="col-md-12">
                <div class="productCategory">
                    <?php
                    if(count($product)){
                        echo '<div class="titlePaginator">';
                        echo '</div>';
                        echo '<ul class="lPC">';
                        foreach($product as $p){
                            ?>
                            <?php
                            $imgs = array_slice(json_decode($p->getImage(), true), 0, 2);
                            ?>
                            <li class="product-item">
                                <div class="product-item__inner">
                                    <div class="product_image-wrapper">
                                        <a href="<?= $p->getViewLink() ?>">
                                            <figure class="lazy product_image" data-src="<?= !empty($imgs) ? $imgs['0']:null ?>"></figure>
                                        </a>
                                    </div>
                                    <p class="product-price"><?= $p->getPriceOld() ? number_format($p->getPriceOld()).' đ<i>'.number_format($p->getPrice()).' đ</i>':number_format($p->getPrice()).' đ' ?></p>
                                    <h3 class="product-title"><?= $p->getTitle() ?></h3>
                                </div>
                            </li>

                            <?php
                        }
                        echo '</ul>';
                        echo '<div class="paginatorProduct">';
                        echo $this->paginationControl($this->paginator, 'Elastic', 'partial/listPage');
                        echo '</div>';
                    }else{
                        echo '<p style="margin: 10px 0 0 0;text-align: center">Đang được cập nhật</p>';
                    }
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>