<?php
$paginator = $this->paginator;
$paginator->setItemCountPerPage($this->uriParams()->getRequest()->getQuery('icpp') ? : 12);
$cs = [
    '/tp/A011/css/n.css'
];
echo '<link href="'.srcLink($cs,1).'" media="screen" rel="stylesheet" type="text/css">';
$optionPage = $this->home()->optionPage();
?>

<?php
/**** Start SEO DWEB *****/
echo $this->headLink(['rel' => 'canonical', 'href' => 'http://'.$_SERVER['HTTP_HOST'].$view->getViewLink() ]);
$this->headTitle($this->escapeHtml($this->translate('Danh sách tin tức')));
$this->headMeta()->appendName('description', '');
$this->headMeta()->appendName('keywords', '');

$this->headMeta()->appendProperty('og:title', 'Danh sách tin tức');
$this->headMeta()->appendProperty('og:description', 'Danh sách tin tức');
$this->headMeta()->appendProperty('og:image', '');
$this->headMeta()->appendProperty('og:image:secure_url', '');
$this->headMeta()->appendProperty('og:image:width', '');
$this->headMeta()->appendProperty('og:image:height', '');
$this->headMeta()->appendProperty('og:type', 'Page');
$this->headMeta()->appendProperty('og:url', 'http://'.$_SERVER['HTTP_HOST'].'/bai-viet.html');
$this->headMeta()->appendProperty('og:site_name', $optionBasic['sologan']);

$this->headMeta()->appendName('twitter:card', '');
$this->headMeta()->appendName('twitter:title', 'Danh sách tin tức');
$this->headMeta()->appendName('twitter:description', 'Danh sách tin tức');
$this->headMeta()->appendName('twitter:image', '');
/**** End SEO DWEB *****/
?>


<section class="lazy hero-news" data-src="https://ir.vinhomes.vn/dizi/themes/vinhome/assets/images/banner-quan-he-co-dong.jpg">
    <h1 class="title-page">Tin tức</h1>
</section>

<div class="page-news">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <?php
                if(count($paginator)){
                    $n = $this->newsCategory()->getCategories();
                    if(count($n)){
                        echo '<ul class="navNews">';
                        foreach($n as $b){
                            echo '<li><a href="'.$b->getViewLink().'">'.$b->getName().'</a></li>';
                        }
                        echo '</ul>';
                    }
                    ?>

                    <div class="post-last__list post-last__list--category">
                        <?php
                        foreach($paginator as $n):
                            $extraContent = json_decode($n->getExtracontent(), true);

                            $image = json_decode($n->getImage(), true);
                            $imageFirst = '';
                            if(!empty($image)){
                                $imageFirst = array_shift($image);
                            }
                            ?>
                            <div class="post-last__item">
                                <div class="post-last__item--inner">
                                    <div class="">
                                        <a href="<?= $n->getViewLink(); ?>">
                                            <figure class="post-last__image lazy" data-src="<?= $imageFirst ?>"></figure>
                                        </a>
                                    </div>
                                    <div class="post-last__content">
                                        <h3 class="post-last__title"><a href="<?= $n->getViewLink() ?>"><?= $n->getTitle() ?></a></h3>
                                        <div class="post-last__intro"><?= $n->getDescription() ?></div>
                                    </div>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>

                    <?php
                    echo '<div class="category__paginator">';
                    echo $this->paginationControl($this->paginator, 'Elastic', 'partial/listPage');
                    echo '</div>';
                }
                ?>
            </div>
        </div>
    </div>
</div>

<?php if(!empty($optionPage['tieu-de-email'])): ?>
    <section class="form">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2 class="headline-default"><?= $optionPage['tieu-de-email'] ? $optionPage['tieu-de-email']:'Email' ?></h2>
                    <form class="form__register" data-parsley-validate novalidate>
                        <div>
                            <input class="email" type="text" data-parsley-type="email" required="required" data-parsley-error-message="Email không được để trống" placeholder="Email *" />
                        </div>
                        <div>
                            <input class="phone" type="text" data-parsley-type="digits" data-parsley-length="[10,11]" required="required" data-parsley-error-message="Số điện thoại không được để trống" placeholder="Số điện thoại *" />
                        </div>
                        <div>
                            <button type="submit">Gửi</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
<?php endif; ?>