<?php
    $theme = $this->NewsCategory()->featchTreeCategory(20);
    $data = $this->paginator;
    $data->setItemCountPerPage($this->uriParams()->getRequest()->getQuery('icpp') ? : 12);
    $category = $this->category;
    $image = json_decode($category->getImage(), true);
    $imageFirst = '';
    if(!empty($image)){
        $imageFirst = array_shift($image);
    }
    $cs = [
        '/tp/A003/css/page.css'
    ];
    echo '<link href="'.srcLink($cs,1).'" media="screen" rel="stylesheet" type="text/css">';
    $optionPage = $this->home()->optionPage();
    $menuOption = $this->home()->getMenu();
    $optionBasic = $this->home()->optionBasic();
?>
<?php
    $image = 'http://'.$_SERVER['HTTP_HOST'].$imageFirst;
    $imageInfo = getimagesize($image);
    /**** Start SEO DWEB *****/
    echo $this->headLink(['rel' => 'canonical', 'href' => 'http://'.$_SERVER['HTTP_HOST'].$category->getViewLink() ]);
    $this->headTitle(!empty($category->getMetaTitle()) ? $category->getMetaTitle():null);
    $this->headMeta()->appendName('description', (!empty($category->getMetaDescription()) ? $category->getMetaDescription():null));
    $this->headMeta()->appendName('keywords', (!empty($category->getMetaKeyword()) ? $category->getMetaKeyword():null));

    $this->headMeta()->appendProperty('og:title', !empty($category->getMetaTitle()) ? $category->getMetaTitle():null);
    $this->headMeta()->appendProperty('og:description', !empty($category->getMetaDescription()) ? $category->getMetaDescription():null);
    $this->headMeta()->appendProperty('og:image', !empty($imageFirst) ? 'http://'.$_SERVER['HTTP_HOST'].$imageFirst:null);
    $this->headMeta()->appendProperty('og:image:secure_url', !empty($imageFirst) ? 'http://'.$_SERVER['HTTP_HOST'].$imageFirst:null);
    $this->headMeta()->appendProperty('og:image:width', $imageInfo['0']);
    $this->headMeta()->appendProperty('og:image:height', $imageInfo['1']);
    $this->headMeta()->appendProperty('og:type', 'Category Article');
    $this->headMeta()->appendProperty('og:url', 'http://'.$_SERVER['HTTP_HOST'].$category->getViewLink());
    $this->headMeta()->appendProperty('og:site_name', $optionBasic['sologan']);

    $this->headMeta()->appendName('twitter:card', !empty($image) ? $image:'summary_large_image');
    $this->headMeta()->appendName('twitter:title', !empty($category->getMetaTitle()) ? $category->getMetaTitle():null);
    $this->headMeta()->appendName('twitter:description', (!empty($category->getMetaDescription()) ? $category->getMetaDescription():null));
    $this->headMeta()->appendName('twitter:image', !empty($image) ? $image:null);
    /**** End SEO DWEB *****/
?>
<?php
if(!empty($data)):
    $category = $this->NewsCategory()->getCategories();
    ?>
    <section class="news">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="news__inner">
                        <div class="news__list">
                            <?php
                                $i = 0;
                                foreach($data as $n):
                                $i++;
                                $image = json_decode($n->getImage(), true);
                                $imageFirst = '';
                                if(!empty($image)){
                                    $imageFirst = array_shift($image);
                                }
                                if($i == 7):
                                ?>
                                <div class="adv-middle">
                                    <a href="http://dweb.vn/thiet-ke-web-gia-re-n356.html" title="thiet ke web gia re">
                                        <figure style="background-image: url('/tp/blog/image/thiet-ke-web-gia-re-1.png');">
                                            <div class="landing-head-hero__content">
                                                <h2 class="">Thiết kế <span>web giá rẻ</span></h2>
                                                <p class=""><?= !empty($optionPage['tieu-de-khuyen-mai-danh-muc']) ? $optionPage['tieu-de-khuyen-mai-danh-muc']:'Chỉ với <span>3000k</span>/ ngày bạn đã có ngay một website.' ?> </p>
                                                <span>Dùng thử miễn phí</span>
                                            </div>
                                        </figure>
                                    </a>
                                </div>

                                <?php endif; ?>
                                <div class="news__item">
                                    <div class="news__item--inner">
                                        <a href="<?= $n->getViewLink() ?>" title="<?= $n->getTitle() ?>">
                                            <figure class="lazy news__image" title="<?= $n->getTitle() ?>" data-src="<?= $imageFirst ?>"></figure>
                                        </a>
                                        <div class="news__intro">
                                            <a href="<?= $n->getViewLink() ?>">
                                                <h2 class="news__title"><?= $n->getTitle() ?></h2>
                                            </a>
                                            <div class="news__intro--sub">
                                                <?= $n->getDescription() ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        </div>
                        <div class="news__paginator">
                            <?php
                            echo $this->paginationControl($data, 'Elastic', 'partial/listPage');
                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
<?php endif; ?>