<?php
echo $this->doctype();
$optionBasic = $this->home()->optionBasic();
$optionPage = $this->home()->optionPage();
?>
<html lang="en">
    <head>
        <?php
            echo $this->headTitle('Dịch vụ')->setSeparator(' - ')->setAutoEscape(false);
            $this->headMeta()->appendName('DC.language', 'scheme=utf-8 content=vi');
            $this->headMeta()->appendName('author', 'DWEB.VN');
            $this->headMeta()->appendName('format-detection', 'telephone=no');
            $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1, maximum-scale=1');
            echo $this->headMeta();
            echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $optionBasic['favicon'] ? $optionBasic['favicon']:null ]);
        ?>

        <meta name="robots" content="noindex,nofollow">

        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,600" rel="stylesheet">
        <link href='https://fonts.googleapis.com/css?family=Roboto:300,500,700' rel='stylesheet' type='text/css'>
        
        <?php
            $cs = [
                '/tp/seongon/css/bootstrap.css',
                '/tp/seongon/css/font-awesome.min.css',
                '/tp/seongon/css/animate.min.css',
                '/tp/seongon/css/a.css',
                '/tp/seongon/css/modal-video.min.css',
                '/assets/css/icons.css',
                '/tp/seongon/css/r.css',
                '/assets/css/web/owl.carousel.css',
                '/assets/css/web/owl.theme.css',
                '/assets/css/web/owl.transitions.css',
                '/assets/css/components.css',
                '/tp/seongon/css/page.css',
            ];
            echo '<link href="'.srcLink($cs,7).'" media="screen" rel="stylesheet" type="text/css">';
            $js = [
                '/assets/js/web/jquery-1.11.2.min.js',
            ];
            echo '<script type="text/javascript" src="'.srcLink($js,4).'"></script>';
        ?>
        <!-- Facebook Pixel Code -->
        <script>
            !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
                n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
                n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
                t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
                document,'script','https://connect.facebook.net/en_US/fbevents.js');
            fbq('init', '1971198599778175'); // Insert your pixel ID here.
            fbq('track', 'PageView');
        </script>
        <noscript><img height="1" width="1" style="display:none"
                       src="https://www.facebook.com/tr?id=1971198599778175&ev=PageView&noscript=1"
            /></noscript>
        <!-- DO NOT MODIFY -->
        <!-- End Facebook Pixel Code -->

    </head>
    <?php
        $url = $this->UriParams()->getRequest()->getRequestUri();
        $url2 = $this->home()->getMcaName('action');
        $classPage = substr($url, 1, -5);
    ?>
    <body <?= $url == '/' | $url2 == 'view' | $url2 == 'landing' | $url2 == 'viewall' ? 'class="home-page single-news"':'class="'.$classPage.'"' ?>>
        <?php
            echo $this->render('layout/header');
            echo $this->content;
            echo $this->render('layout/footer');
        ?>
    </body>
    <?php
        $cs = [
            '/tp/seongon/css/r.css',
        ];
        echo '<link href="'.srcLink($cs,3).'" media="screen" rel="stylesheet" type="text/css">';
        $js = [
//            '/tp/dweb/js/jquery-1.10.1.min.js',
            '/tp/seongon/js/bootstrap.min.js',
            '/assets/js/web/jquery.lazy.min.js',
//            '/assets/js/web/owl.carousel.js',
            '/tp/seongon/js/waypoint/jquery.waypoints.min.js',
            '/tp/seongon/js/a.js',
//            '/tp/seongon/js/hero-slider/TweenLite.min.js',
//            '/tp/seongon/js/hero-slider/rAF.js',
//            '/tp/seongon/js/hero-slider/EasePack.min.js',
//            '/tp/seongon/js/hero-slider/demo-1.js',
//            '/tp/seongon/js/jquery-modal-video.min.js',
            '/assets/plugins/parsleyjs/parsley.min.js',
            '/tp/seongon/js/form.js',
        ];
        echo '<script type="text/javascript" src="'.srcLink($js,7).'"></script>';
    ?>

    <!-- Load Facebook SDK for JavaScript -->
    <div id="fb-root"></div>

    <script>
        setTimeout(function(){
            $.getScript(fb());
        }, 5000);
        function fb () {
            (function(d, s, id) {
                var js, fjs = d.getElementsByTagName(s)[0];
                if (d.getElementById(id)) return;
                js = d.createElement(s); js.id = id;
                js.src = 'https://connect.facebook.net/vi_VN/sdk/xfbml.customerchat.js#xfbml=1&version=v2.12&autoLogAppEvents=1';
                fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));
        }
    </script>

    <!-- Your customer chat code -->
    <div class="fb-customerchat"
         attribution=setup_tool
         page_id="125813488001003" theme_color="#07aabe">
    </div>

    <?= $this->render('layout/modal'); ?>


</html>