<?php
    $data = $this->results;
    $name = $this->UserName;
    echo $this->headtitle($this->escapehtml($this->translate('Bảng điều khiển')));
    $optionPage = $this->home()->optionPage(23);
//    $optionPage = $this->home()->optionPage(15);
    $newsDashboard = $optionPage['bai-viet-dashboard'];
?>
<style>
    .video__item {
        margin: 20px auto 0;
        position: relative;
        padding-bottom: 55.6%;
        height: 0;
    }
    .video__item iframe {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
    }
</style>
<div class="row">
    <div class="col-lg-8 col-md-offset-2">
        <h3 class="page-header m-t-0">Xin chào: <?= strtoupper($name) ?></h3>
    </div>
</div>
<div class="row">
    <div class="col-lg-8 col-md-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">DÀNH CHO NGƯỜI MỚI BẮT ĐẦU</h3>
            </div>
            <div class="panel-body">
                <ul class="p-l-r-10 m-b-30">
                    <li class="m-b-10"><a class="text-primary" href="/admin/setup">Cài đặt logo, favicon, tiêu đề trang</a></li>
                    <li class="m-b-10"><a class="text-primary" href="/admin/page/homepage">Cài đặt tuỳ chỉnh khác Head/ Footer</a></li>
                    <li class="m-b-10"><a class="text-primary" href="/admin/setup/template">Cài đặt hiển thị trang chủ</a></li>
                    <li class="m-b-10"><a class="text-primary" href="/admin/setup/other">Cài đặt tên miền riêng</a></li>
                    <li class="m-b-10"><a class="text-primary" href="/admin/user">Thêm tài khoản quản lý/ phân quyền hiển thị tính năng</a></li>
                </ul>
                <div class="admin-dashboard__support">
                    <figure class="admin-dashboard__support--icon"></figure>
                    <p>
                        Nếu bạn cần thêm sự hỗ trợ, hãy liên hệ với chúng tôi
                        <br/>
                        Hotline: <b>0986 174 666</b>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-8 col-md-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Xem video hướng dẫn</h3>
            </div>
            <div class="panel-body">
                <div class="video__item">
                    <iframe width="900" height="507" src="https://www.youtube.com/embed/1OqFDkPnqH4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-8 col-md-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Có thể bạn quan tâm</h3>
            </div>
            <div class="panel-body">
                <div class="dashboard__news">
                    <div class="dashboard__news--list">
                        <?php
                        foreach($newsDashboard as $n):
                            $image = json_decode($n['image'], true);
                            $imageFirst = '';
                            if(!empty($image)){
                                $imageFirst = array_shift($image);
                            }
                            ?>
                            <div class="dashboard__news--item">
                                <div class="dashboard__news--left">
                                    <a target="_blank" href="http://blog.dweb.vn<?= $n['url'] ?>">
                                        <figure class="dashboard__news--image lazy" data-src="http://blog.dweb.vn<?= $imageFirst ?>"></figure>
                                    </a>
                                </div>
                                <div class="dashboard__news--right">
                                    <h4 class="dashboard__news--title"><a class="text-primary" target="_blank" href="http://blog.dweb.vn<?= $n['url'] ?>"><?= $n['title'] ?></a></h4>
                                    <h3 class="dashboard__news--intro"><?= $n['category'] ?></h3>
                                </div>
                            </div>
                            <?php
                        endforeach;
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-8 col-md-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Dịch vụ</h3>
            </div>
            <div class="panel-body">
                <p>
                    Chúng tôi nhận thấy các doanh nghiệp đang vận hành một cửa hàng trên internet chưa đủ bài bản thuyết phục, tin tưởng người mua hàng. Từ việc làm nội dung, hình ảnh,
                    và những chiến dịch quảng cáo nhằm tiếp cận được những lượng khách hàng lớn từ người dùng Facebook, Google. Chúng tôi có cung cấp 1 số dịch vụ giành cho khách hàng, giúp bạn có những chiến lược dõ dàng hơn khi vận hành 1 Website.
                </p>
            </div>
            <ul class="list-group">
                <li class="list-group-item"><a href="http://dweb.vn/dich-vu.html" target="_blank" class="btn btn-primary btn-custom btn-rounded waves-effect waves-light">Chi tiết</a></li>
            </ul>
        </div>
    </div>
</div>
