<?php
echo $this->headtitle($this->escapehtml($this->translate('Danh sách trang')));
$domainUrl = $this->home()->getDomain();
$domainUrl ? $_SERVER['HTTP_HOST'] = $domainUrl:$_SERVER['HTTP_HOST'];
?>
<input type="hidden" class="updateHomepage" />
<div class="row">
    <div class="col-sm-12">
        <div class="card-box">
            <div class="portlet-body">
                <div id="sample_editable_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
                    <div class="btn-toolbar">
                        <div class="btn-group focus-btn-group">
                            <a href="/admin/page/add" class="btn btn-default waves-effect waves-light">Thêm trang</a>
                        </div>
                        <div class="btn-group dropdown-btn-group pull-right">
                            <div class="dataTables_filter mb-15">
                                <form action="" method="get" name="ProductSearch" class="form-inline" id="ProductSearch">
                                    <?php
                                    $form = $this->fFilter;
                                    ?>
                                    <div class="form-group">
                                        <?=$this->formelement($form->get('id')->setAttributes(['class' => 'form-control','placeholder'=>'Id']))?>
                                    </div>
                                    <div class="form-group">
                                        <?=$this->formelement($form->get('name')->setAttributes(['class' => 'form-control','placeholder'=>'Tiêu đề']))?>
                                    </div>
                                    <div class="form-group"><input name="submit" type="submit" class="btn btn-default " value="Tìm Kiếm"></div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <?php
                        echo $dg = new \Admin\Dg\DgPage ( array (
                            'data' => $this->results->getData (),
                            'paging' => $this->results->getPaging (),
                            'rowCount' => $this->results->getRowCount (),
                            'rowInPage' => $this->results->getRowInPage (),
                            'uri' => $this->url,
                        ));
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>

