<?php
use Home\Model\DateBase;
if(!empty($this->newsLayout['news-list article']['news-list'])):?>
<section class="post-course">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="post-course__inner">
                        <div class="post-course__headline">
                            <h2><?= $this->newsLayout['news-title text']['value'] ? $this->newsLayout['news-title text']['value'] : ''?></h2>
                            <div>
                                <?= $this->newsLayout['news-sub-title text']['value'] ? $this->newsLayout['news-sub-title text']['value'] : '' ?>
                            </div>
                            <span><img src="/tp/A008/img/learn.svg" /></span>
                        </div>
                        <?php $slider = $this->newsLayout['news-slider-checkbox checkbox']['value']?>
                        <ul class="<?=$slider ? 'post-course__slider owl-carousel owl-theme' : 'news__list' ?> ">
                            <?php
                            if(!empty($this->newsLayout['news-list article']['news-list'])):
                                foreach($this->newsLayout['news-list article']['news-list'] as $k => $n):
                                    $image = json_decode($n['image'], true);
                                    if(!empty($image)) {
                                        $imageFirst = array_shift($image);
                                    }
                                    ?>
                                    <li class="post-course__item">
                                        <div class="post-course__item--inner">
                                            <a href="<?= $n['url'] ?>"><figure class="post-course__image lazy" data-src="<?= $imageFirst ?>"><span>Chi tiết</span></figure></a>
                                            <div>
                                                <h3 class="post-course__title"><a href="<?= $n['url'] ?>"><?= $n['title'] ?></a></h3>
                                                <div class="post-course__intro"><?= $n['intro'] ?></div>
                                                <div class="post-course__category"><i class="fa fa-graduation-cap"></i><?= $n['category'] ?></div>
                                            </div>
                                        </div>
                                    </li>
                                <?php endforeach; endif;?>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
<?php endif;?>