<?php if(!empty($this->supportLayout)):?>

<section class="newlatter">
    <div class="newlatter__inner">
        <h4><?= $this->supportLayout['support-title text']['value'] ? $this->supportLayout['support-title text']['value'] : ''?></h4>
        <form class="form__register" data-parsley-validate novalidate>
            <label class="fa fa-envelope-o"></label>
            <div>
                <input class="email" type="text" data-parsley-type="email" required="required" data-parsley-error-message="Email không được để trống" placeholder="Email *" />
            </div>
            <div>
                <input class="phone" type="text" data-parsley-type="digits" data-parsley-length="[10,11]" required="required" data-parsley-error-message="Số điện thoại không được để trống" placeholder="Số điện thoại *" />
            </div>
            <button type="submit">Gửi</button>
        </form>
    </div>
</section>
<?php endif;?>