<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="irstheme">

    <title> Jolly - Wedding & Wedding Planner HTML Template </title>

    <link href="/tp/mienle/assets/css/themify-icons.css" rel="stylesheet">
    <link href="/tp/mienle/assets/css/flaticon.css" rel="stylesheet">
    <link href="/tp/mienle/assets/css/bootstrap.min.css" rel="stylesheet">
    <link href="/tp/mienle/assets/css/animate.css" rel="stylesheet">
    <link href="/tp/mienle/assets/css/owl.carousel.css" rel="stylesheet">
    <link href="/tp/mienle/assets/css/owl.theme.css" rel="stylesheet">
    <link href="/tp/mienle/assets/css/slick.css" rel="stylesheet">
    <link href="/tp/mienle/assets/css/slick-theme.css" rel="stylesheet">
    <link href="/tp/mienle/assets/css/swiper.min.css" rel="stylesheet">
    <link href="/tp/mienle/assets/css/owl.transitions.css" rel="stylesheet">
    <link href="/tp/mienle/assets/css/jquery.fancybox.css" rel="stylesheet">
    <link href="/tp/mienle/assets/css/magnific-popup.css" rel="stylesheet">
    <link href="/tp/mienle2/assets/css/style.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400&display=swap" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- start page-wrapper -->
    <div class="page-wrapper flower-fixed-body">

        <!-- start preloader -->
        <div class="preloader">
            <div class="middle">
                <i class="fi flaticon-favorite-heart-button"></i>
                <i class="fi flaticon-favorite-heart-button"></i>
                <i class="fi flaticon-favorite-heart-button"></i>
                <i class="fi flaticon-favorite-heart-button"></i>
            </div>
        </div>
        <!-- end preloader -->

        <!-- Start header -->
        <header id="header" class="site-header header-style-1">
            <div class="topbar">
                <div class="container">
                    <div class="row">
                        <div class="col col-xs-12">
                            <div class="site-logo">
                                <a href="/">
                                    <h1>MienLe <span style="color: #DDD;margin: 0 5px 0 15px;">&</span> NgocNhan</h1>
                                    <span>Just Married</span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- end of header -->


        <!-- start of hero -->
        <section class="hero-slider hero-style-1">
            <div class="swiper-container">
                <div class="slide-main-text">
                    <div class="container">
                        <div class="slide-title">
                            <h2>MienLe & NgocNhan</h2>
                        </div>
                        <div class="wedding-date">
                            <span>24-05, 2020</span>
                        </div>
                        <div class="clearfix"></div>
                        <div class="count-down-clock">
                            <div id="clock"></div>
                        </div>
                    </div>
                    <div class="pattern">
                        <span></span>
                        <span></span>
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </div>
                <div class="swiper-wrapper">
                    <div class="swiper-slide">
                        <div class="slide-inner slide-bg-image" data-background="/tp/mienle/assets/images/07.jpg"></div>
                    </div>

                    <div class="swiper-slide">
                        <div class="slide-inner slide-bg-image" data-background="/tp/mienle/assets/images/55.jpg"></div>
                    </div>

                    <div class="swiper-slide">
                        <div class="slide-inner slide-bg-image" data-background="/tp/mienle/assets/images/05.jpg"></div>
                    </div>
                    <!-- end swiper-slide -->
                </div>
                <!-- end swiper-wrapper -->

                <!-- swipper controls -->
                <div class="swiper-pagination"></div>
                <div class="swiper-button-next"></div>
                <div class="swiper-button-prev"></div>
            </div>
        </section>
        <!-- end of hero slider -->


        <!-- start invitation-section -->
        <section class="invitation-section section-padding">
            <div class="container">
                <div class="row">
                    <div class="col col-xs-12">
                        <div class="invitation-box">
                            <div class="left-vec"></div>
                            <div class="right-vec"></div>
                            <div class="inner">
                                <h2>Save the Date</h2>
                                <span>Đám cưới của chúng tôi</span>
                                <h3>Miền Lê & Ngọc Nhàn</h3>
                                <p>Khu 8 thôn Phần Thạch, Đồng Tĩnh, Tam Dương, Vĩnh Phúc</p>
                                <a href="#rsvp" class="theme-btn" id="scroll">Tham dự</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end container -->
        </section>
        <!-- end invitation-section -->

        <!-- start event-section -->
        <section class="event-section section-padding p-t-0">
            <div class="top-area">
                <h2>Celebrate Our Love</h2>
                <p class="date">24 - 5 - 2020</p>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col col-xs-12">
                        <div class="event-grids clearfix">
                            <div class="grid">
                                <h3>The Reception</h3>
                                <p>14h-17h, 23-5-2020 <br>Khu 8 thôn Phần Thạch, Đồng Tĩnh, Tam Dương, Vĩnh Phúc</p>
                                <p class="phone">Điện thoại: 0962320451‬‬</p>
                                <a href="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d41948.237288840326!2d105.52477343928636!3d21.413176904511705!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3134e924d02ad2af%3A0xd3719a02e765acd8!2zxJDhu5NuZyBUxKluaCwgVGFtIETGsMahbmcsIFbEqW5oIFBow7pjLCBWaeG7h3QgTmFt!5e0!3m2!1svi!2s!4v1589645523236!5m2!1svi!2s"
                                    class="location popup-gmaps">Bản đồ</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end container -->
        </section>
        <!-- end event-section -->


        <!-- start partners-section -->
        <!-- end partners-section -->


        <!-- start blog-section -->

        <!-- end blog-section -->


        <!-- start site-footer -->
        <footer class="site-footer footer-style-1">
            <div class="inner">
                <div class="couple-pic">
                    <img src="/tp/mienle/assets/images/footer.jpg" alt>
                </div>
                <h2>Thank you</h2>
                <ul class="social-links">
                </ul>
            </div>
        </footer>
        <!-- end site-footer -->


    </div>
    <!-- end of page-wrapper -->



    <!-- All JavaScript files
    ================================================== -->
    <script src="/tp/mienle/assets/js/jquery.min.js"></script>
    <script src="/tp/mienle/assets/js/bootstrap.min.js"></script>

    <!-- Plugins for this template -->
    <script src="/tp/mienle/assets/js/jquery-plugin-collection.js"></script>

    <!-- Custom script for this template -->
    <script src="/tp/mienle/assets/js/script.js"></script>
</body>

</html>