<?php
    $paginator =  $this->paginator;
    $paginator->setItemCountPerPage($this->uriParams()->getRequest()->getQuery('icpp') ? : 12);

    $category = $this->category;

    $image = json_decode($category->getImage(), true);
    $imageFirst = '';
    if(!empty($image)){
        $imageFirst = array_shift($image);
    }

    $cs = [
        '/tp/A015/css/n.css'
    ];
    echo '<link href="'.srcLink($cs,1).'" media="screen" rel="stylesheet" type="text/css">';
    $optionPage = $this->home()->optionPage();
    $optionBasic = $this->home()->optionBasic();
    $menuOption = $this->home()->getMenu();
    use Home\Model\DateBase;
?>
<?php
    $image = 'http://'.$_SERVER['HTTP_HOST'].$imageFirst;
    $imageInfo = getimagesize($image);
    /**** Start SEO DWEB *****/
    echo $this->headLink(['rel' => 'canonical', 'href' => 'http://'.$_SERVER['HTTP_HOST'].$category->getViewLink() ]);

    $this->headTitle(!empty($category->getMetaTitle()) ? $category->getMetaTitle():$category->getName());
    $this->headMeta()->appendName('description', (!empty($category->getMetaDescription()) ? $category->getMetaDescription():null));
    $this->headMeta()->appendName('keywords', (!empty($category->getMetaKeyword()) ? $category->getMetaKeyword():null));

    $this->headMeta()->appendProperty('og:title', !empty($category->getMetaTitle()) ? $category->getMetaTitle():$category->getName());
    $this->headMeta()->appendProperty('og:description', !empty($category->getMetaDescription()) ? $category->getMetaDescription():null);
    $this->headMeta()->appendProperty('og:image', !empty($imageFirst) ? 'http://'.$_SERVER['HTTP_HOST'].$imageFirst:null);
    $this->headMeta()->appendProperty('og:image:secure_url', !empty($imageFirst) ? 'http://'.$_SERVER['HTTP_HOST'].$imageFirst:null);
    $this->headMeta()->appendProperty('og:image:width', $imageInfo['0']);
    $this->headMeta()->appendProperty('og:image:height', $imageInfo['1']);
    $this->headMeta()->appendProperty('og:type', 'Category Article');
    $this->headMeta()->appendProperty('og:url', 'http://'.$_SERVER['HTTP_HOST'].$category->getViewLink());
    $this->headMeta()->appendProperty('og:site_name', $optionBasic['sologan']);

    $this->headMeta()->appendName('twitter:card', !empty($image) ? $image:'summary_large_image');
    $this->headMeta()->appendName('twitter:title', !empty($category->getMetaTitle()) ? $category->getMetaTitle():null);
    $this->headMeta()->appendName('twitter:description', (!empty($category->getMetaDescription()) ? $category->getMetaDescription():null));
    $this->headMeta()->appendName('twitter:image', !empty($image) ? $image:null);
    /**** End SEO DWEB *****/

?>
<div class="page-news">
    <div class="container">
        <div class="row">
            <?php
                if(!empty($menuOption['sidebar_menu']) || !empty($optionPage['view_danh-muc-sidebar-1']) || !empty($optionPage['view_danh-muc-sidebar-2']) || !empty($optionPage['view_banner-sidebar'])):
                    echo '<div class="col-md-8">';
                else:
                    echo '<div class="col-md-12">';
                endif;
            ?>
                <?php
                    $n = $this->newsCategory()->getCategories();
                    /*if(count($n)){
                        echo '<ul class="navNews">';
                        foreach($n as $b){
                            echo '<li><a '.($category->getId() == $b->getId() ? 'class="active"':'').' href="'.$b->getViewLink().'">'.$b->getName().'</a></li>';
                        }
                        echo '</ul>';
                    }*/
                if(!empty($paginator)){
                    ?>
                    <h1 class="title-page"><?= $category->getName(); ?></h1>
                    <div class="post-last__list post-last__list--category">
                        <?php
                        foreach($paginator as $n):
                            $extraContent = json_decode($n->getExtracontent(), true);

                            $image = json_decode($n->getImage(), true);
                            $imageFirst = '';
                            if(!empty($image)){
                                $imageFirst = array_shift($image);
                            }
                            ?>
                            <div class="post-last__item">
                                <div class="post-last__item--inner">
                                    <div class="post-last__left">
                                        <a href="<?= $n->getViewLink(); ?>">
                                            <figure class="post-last__image lazy" data-src="<?= $imageFirst ?>"></figure>
                                        </a>
                                    </div>
                                    <div class="post-last__content">
                                        <h3 class="post-last__title"><a href="<?= $n->getViewLink() ?>" title="<?=$n->getTitle();?>">
                                                <?php
                                                $s = substr($n->getDescription(),0,100);
                                                $rs = substr($s,0,strrpos($s, ' '));
                                                if(strlen($n->getDescription()) > 100):
                                                    echo $rs;
                                                    echo '...';
                                                else:
                                                    echo $n->getDescription();
                                                endif;
                                                ?>
                                            </a>
                                        </h3>
                                        <div class="post-last__intro">
                                            <?php
                                            $s = substr($n->getDescription(),0,180);
                                            $rs = substr($s,0,strrpos($s, ' '));
                                            if(strlen($n->getDescription()) > 180):
                                                echo $rs;
                                                echo '...';
                                            else:
                                                echo $n->getDescription();
                                            endif;

                                            ?>
                                        </div>
                                        <p><?= DateBase::toFormat($n->getCreatedDateTime(), 'M d, Y') ?></p>
                                    </div>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>

                    <?php
                    echo '<div class="category__paginator">';
                    echo $this->paginationControl($this->paginator, 'Elastic', 'partial/listPage');
                    echo '</div>';
                }
                ?>
            </div>
        <?php echo $this->render('layout/sidebar');?>
        </div>
    </div>
</div>
