<?php if(!empty($this->newsLayout['news-list article']['news-list'])):?>
    <section class="news">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <?= $this->newsLayout['news-title text']['value'] ? '<h2 class="titleHome"><span>'.$this->newsLayout['news-title text']['value'].'</span></h2>' : ''?>
                    <?= $this->newsLayout['news-sub-title text']['value'] ? '<span class="titleHome-sub">'.$this->newsLayout['news-sub-title text']['value'].'</span>' : ''?>
                    <?php $slider = $this->newsLayout['news-slider-checkbox checkbox']['value']?>
                    <ul class="<?= $slider ? 'news-slider owl-carousel owl-theme' : 'lN' ?> news__list">
                        <?php
                        foreach($this->newsLayout['news-list article']['news-list'] as $k => $n):
                            $image = json_decode($n['image'], true);
                            if(!empty($image)){
                                $imageFirst = array_shift($image);
                            }
                            ?>
                            <li>
                                <a href="<?= $n['url'] ?>"><figure class="lazy image-article" data-src="<?= !empty($imageFirst) ? $imageFirst:'' ?>"></figure></a>
                                <p class="category"><?= $n['category'] ?></p>
                                <h3><a href="<?= $n['url'] ?>"><?= $n['title'] ?></a></h3>
                                <p class="intro"><?= $n['intro'] ?></p>
                            </li>
                        <?php
                        endforeach;
                        ?>
                    </ul>
                </div>
            </div>
        </div>
    </section>
<?php endif;?>