<?php if(!empty($this->smallBannerList['small-banner-list banner']['small-banner-list'])):?>
<section class="three-banner">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <ul class="three-banner__list">
                <?php
                    foreach($this->smallBannerList['small-banner-list banner']['small-banner-list'] as $k => $b):
                        $image = json_decode($b['image'], true);
                        if (!empty($image)) {
                            $imageFirst = array_shift($image);
                        }
                        ?>
                    <li class="three-banner__item">
                        <a href="<?= $b['url'] ?>">
                            <figure class="lazy three-banner__image" data-src="<?= !empty($imageFirst) ? $imageFirst:null ?>">
                                <div>
                                    <h3><?= $b['title'] ?></h3>
                                </div>
                            </figure>
                        </a>
                    </li>
                    <?php endforeach;?>
                </ul>
            </div>
        </div>
    </div>
</section>
<?php endif;?>