<?php if(!empty($this->sevenProductLayout)): ?>
    <div class="seven-post">
        <div class="col-md-12">
            <div class="product-title">
                <h2>
                    <a href="#">
                        <?= $this->sevenProductLayout['product-title text']['value'] ? $this->sevenProductLayout['product-title text']['value'] : ''?>
                    </a>
                </h2>
            </div>
            <div class="seven-post__list">
                <?php
                if(!empty($this->sevenProductLayout['feature-product product']['feature-product'])):
                    foreach ($this->sevenProductLayout['feature-product product']['feature-product'] as $p):
                        $imgs = !empty($p['image']) ? array_slice(json_decode($p['image'], true), 0, 2):null;
                    ?>
                <div class="seven-post__item--first">
                    <div class="product__item--inner">
                        <a class="pI" href="<?= $p['url'] ?>">
                            <figure class="lazy product_image product_image--two" data-src="<?= !empty($imgs) ? $imgs['0']:null ?>"></figure>
                        </a>
                        <?php
                        if(!empty($p['image'])):
                            echo '<ul class="seven-post__thumbnail-list">';
                            $count = 0;
                            foreach(json_decode($p['image'], true) as $i):
                                $count++;
                                if($count > 0 && $count < 5):
                                ?>
                                <li><img src="<?= $i ?>" style="width: 50px" alt="" /></li>
                            <?php endif; endforeach; echo '</ul>'; endif; ?>
                        <h3 class="product__item--title"><a href="<?= $p['url'] ?>"><?= $p['title'] ?></a></h3>
                        <p class="product-horizontal__price"><?= $p['priceOld'] ? number_format($p['priceOld']).' đ<i>'.number_format($p['price']).' đ</i>':number_format($p['price']).' đ' ?></p>
                        <a class="btnAddCart" data-quantity="1" data-id="<?= $p['id'] ?>">Giỏ hàng</a>
                    </div>
                </div>
                <?php endforeach; endif;?>
                <div class="seven-post__item--small">
                    <ul class="<?=$this->sevenProductLayout['feature-product product']['feature-product'] ? 'six-post__list' : 'product__list'?>" >
                         <?php
                            if(!empty($this->sevenProductLayout['product-list product']['product-list'])):
                                foreach($this->sevenProductLayout['product-list product']['product-list'] as $p):
                                $imgs = !empty($p['image']) ? array_slice(json_decode($p['image'], true), 0, 2):null;
                            ?>
                            <li class="seven-post__item product__item">
                                <div class="product__item--inner">
                                    <a class="pI" href="<?= $p['url'] ?>">
                                        <figure class="lazy product_image product_image--two" data-src="<?= !empty($imgs) ? $imgs['0']:null ?>"></figure>
                                    </a>
                                    <h3 class="product__item--title"><a href="<?= $p['url'] ?>"><?= $p['title'] ?></a></h3>
                                    <p class="product-horizontal__price"><?= $p['priceOld'] ? number_format($p['priceOld']).' đ<i>'.number_format($p['price']).' đ</i>':number_format($p['price']).' đ' ?></p>
                                    <a class="btnAddCart" data-quantity="1" data-id="<?= $p['id'] ?>">Giỏ hàng</a>
                                </div>
                            </li>
                        <?php endforeach; endif;?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
<?php endif;?>