<?php if(!empty($this->columnProductLayout)): ?>
    <div class="slider-product">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="slider-product__inner">
                        <div class="slider-product__row">
                            <div class="slider-product__slider">
                                <?php if(!empty($this->columnProductLayout['col-product1 product']['col-product1'])): ?>
                                    <h3 class="slider-product__title--category"><?= $this->columnProductLayout['col1-title text']['value'] ?></h3>
                                <?php endif; ?>
                                <?php if(!empty($this->columnProductLayout['col-product1 product'])): ?>
                                    <ul class="slider-product__list">
                                        <?php
                                        if(!empty($this->columnProductLayout['col-product1 product'])):
                                            foreach($this->columnProductLayout['col-product1 product']['col-product1'] as $p):
                                                $imgs = !empty($p['image']) ? array_slice(json_decode($p['image'], true), 0, 2):null;
                                                ?>
                                                <li class="slider-product__item">
                                                    <div class="slider-product____item-inner">
                                                        <div class="slider-product__image-wrapper">
                                                            <a href="<?= $p['url'] ?>">
                                                                <figure class="lazy slider-product__image" data-src="<?= !empty($imgs) ? $imgs['0']:null ?>"></figure>
                                                            </a>
                                                        </div>
                                                        <div class="slider-product____content">
                                                            <h3 class="slider-product__title"><a href="<?= $p['url'] ?>"><?= $p['title'] ?></a></h3>
                                                            <p class="product-horizontal__price">
                                                                <?= $p['priceOld']
                                                                    ? '<span>'.number_format($p['priceOld']).' đ</span><i>'.number_format($p['price']).' đ</i>'
                                                                    : '<span>'.number_format($p['price']).' đ</span><i></i>' ?>
                                                            </p>
                                                        </div>
                                                    </div>
                                                </li>
                                            <?php
                                            endforeach;
                                        endif;
                                        ?>
                                    </ul>
                                <?php endif; ?>
                            </div>
                        </div>
                        <div class="slider-product__row">
                            <div class="slider-product__slider">
                                <?php if(!empty($this->columnProductLayout['col-product2 product']['col-product2'])): ?>
                                    <h3 class="slider-product__title--category"><?= $this->columnProductLayout['col2-title text']['value'] ?></h3>
                                <?php endif; ?>
                                <?php if(!empty($this->columnProductLayout['col-product2 product'])): ?>
                                    <ul class="slider-product__list">
                                        <?php
                                        if(!empty($this->columnProductLayout['col-product2 product'])):
                                            foreach($this->columnProductLayout['col-product2 product']['col-product2'] as $p):
                                                $imgs = !empty($p['image']) ? array_slice(json_decode($p['image'], true), 0, 2):null;
                                                ?>
                                                <li class="slider-product__item">
                                                    <div class="slider-product____item-inner">
                                                        <div class="slider-product__image-wrapper">
                                                            <a href="<?= $p['url'] ?>">
                                                                <figure class="lazy slider-product__image" data-src="<?= !empty($imgs) ? $imgs['0']:null ?>"></figure>
                                                            </a>
                                                        </div>
                                                        <div class="slider-product____content">
                                                            <h3 class="slider-product__title"><a href="<?= $p['url'] ?>"><?= $p['title'] ?></a></h3>
                                                            <p class="product-horizontal__price">
                                                                <?= $p['priceOld']
                                                                    ? '<span>'.number_format($p['priceOld']).' đ</span><i>'.number_format($p['price']).' đ</i>'
                                                                    : '<span>'.number_format($p['price']).' đ</span><i></i>' ?>
                                                            </p>
                                                        </div>
                                                    </div>
                                                </li>
                                            <?php
                                            endforeach; endif;
                                        ?>
                                    </ul>
                                <?php endif; ?>
                            </div>
                        </div>
                        <div class="slider-product__row">
                            <div class="slider-product__slider">
                                <?php if(!empty($this->columnProductLayout['col-product3 product']['col-product3'])): ?>
                                    <h3 class="slider-product__title--category"><?= $this->columnProductLayout['col3-title text']['value'] ?></h3>
                                <?php endif; ?>
                                <?php if(!empty($this->columnProductLayout['col-product3 product'])): ?>
                                    <ul class="slider-product__list">
                                        <?php
                                        if(!empty($this->columnProductLayout['col-product3 product'])):
                                            foreach($this->columnProductLayout['col-product3 product']['col-product3'] as $p):
                                                $imgs = !empty($p['image']) ? array_slice(json_decode($p['image'], true), 0, 2):null;
                                                ?>
                                                <li class="slider-product__item">
                                                    <div class="slider-product____item-inner">
                                                        <div class="slider-product__image-wrapper">
                                                            <a href="<?= $p['url'] ?>">
                                                                <figure class="lazy slider-product__image" data-src="<?= !empty($imgs) ? $imgs['0']:null ?>"></figure>
                                                            </a>
                                                        </div>
                                                        <div class="slider-product____content">
                                                            <h3 class="slider-product__title"><a href="<?= $p['url'] ?>"><?= $p['title'] ?></a></h3>
                                                            <p class="product-horizontal__price">
                                                                <?= $p['priceOld']
                                                                    ? '<span>'.number_format($p['priceOld']).' đ</span><i>'.number_format($p['price']).' đ</i>'
                                                                    : '<span>'.number_format($p['price']).' đ</span><i></i>' ?>
                                                            </p>
                                                        </div>
                                                    </div>
                                                </li>
                                            <?php
                                            endforeach;
                                        endif;
                                        ?>
                                    </ul>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php endif;?>