<?php
$q = $this->request->getQuery('n');
$this->headTitle($this->escapeHtml('Kho giao diện'));
$this->headMeta()->appendName('description', 'Kho giao diện, Thời trang, Kiến Trúc - Nội Thất, Công ty, Mỹ Phẩm - Làm Đẹp, Ẩm Thực - Ăn Uống, Mẹ và Bé, Siêu thị nhiều mặt hàng, Công nghệ');
$this->headMeta()->appendName('keywords', ('Thời trang, Kiến Trúc - Nội Thất, Công ty, Mỹ Phẩm - Làm Đẹp, Ẩm Thực - Ăn Uống, Mẹ và Bé, Siêu thị nhiều mặt hàng, Công nghệ'));
$this->headMeta()->appendProperty('og:title', 'Kho giao diện');

$cs = [
    '/tp/dweb/css/page.css'
];
echo '<link href="'.srcLink($cs,2).'" media="screen" rel="stylesheet" type="text/css">';
$theme = $this->NewsCategory()->featchTreeCategory(20);
$data = $this->paginator;
$data->setItemCountPerPage($this->uriParams()->getRequest()->getQuery('icpp') ? : 15);
?>

<section class="m-t-100 theme">
    <div class="price__hero theme__hero">
        <div class="price__hero-inner">
            <h1 class="price__hero-title theme__hero-title">Kho <span>giao diện</span></h1>
            <p class="price__hero-description">Với kho giao diện chất lượng, chúng tôi hi vọng định hình thương hiệu của bạn</p>
        </div>
    </div>
    <div class="container">
        <div class="theme__inner">

            <form id="search" action="/kho-giao-dien.html" class="theme__search" method="get">
                <input type="text" name="n" placeholder="Tìm ..."/>
                <a href="javascript:{}" onclick="document.getElementById('search').submit();"><i class="fa fa-search" aria-hidden="true"></i></a>
            </form>

            <ul class="theme__list-category">
                <?php if(!empty($theme)): ?>
                    <?php foreach($theme as $t): ?>
                        <li><a href="<?= $t->getViewLink() ?>"><?= $t->getName() ?></a></li>
                    <?php endforeach; ?>
                <?php endif; ?>
            </ul>
            <?= !empty($q) ? '<p class="theme__result">Bạn đang tìm kiếm với từ khoá: <span>'.$q.'</span></p>':null ?>
            <?php if(!empty($data)): ?>
            <div class="project-list">
                <?php foreach ($data as $p):
                    $image = json_decode($p->getImage(), true);
                    if(!empty($image)){
                        $imageFirst = array_shift($image);
                    }
                    $extraContent = json_decode($p->getExtraContent(), true);
                    ?>
                    <div class="project-item">
                        <div class="project-inner">
                            <figure class="project-image lazy" data-src="<?= $imageFirst ?>"></figure>
                            <div class="project-control">
                                <a class="btn-d project__button-reviewer" target="_blank" href="<?= $p->getDescription() ?>">Xem thử</a>
                                <a class="btn-d project__button-detail" href="/register-<?= vnString($p->getTitle()) ?>.html">Tạo website</a>
                                <h3 class="project__title"><?= $p->getTitle(); ?></h3>
                                <p class="project__description"><?= !empty($extraContent['mo-ta']) ? $extraContent['mo-ta']:null ?></p>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>

            <?php
                echo '<div class="news__paginator">';
                echo $this->paginationControl($this->paginator, 'Elastic', 'partial/listPage');
                echo '</div>';
                endif;
            ?>

            <div class="single-news__button">
                <span>Nếu bạn chưa tìm thấy giao diện phù hợp, bạn có thể gửi cho chúng tôi mẫu website bạn cần<br/>chúng tôi sẽ cố gắng bổ sung giao diện bạn gửi lên kho giao diện trong thời gian sớm nhất. </span><a class="btn-d" href="/lien-he.html">Gửi mẫu giao diện</a>
            </div>

        </div>
    </div>
</section>

<section class="support-module">
    <div class="container">
        <div class="support-module__inner">
            <h2 class="support-module__headline">Tư vấn miễn phí</h2>
            <div class="support-module__sub">Chúng tôi sẽ liên hệ với bạn trong thời gian sớm nhất. Tư vấn website, bán hàng, quảng cáo adwords, facebook. Bạn có thể đọc kinh nghiệm bán hàng với <a href="http://blog.dweb.vn" target="_blank">blog</a> dweb</div>
            <form class="support-module__form" data-parsley-validate novalidate>
                <div>
                    <input type="text" data-parsley-type="digits" data-parsley-length="[10,11]" required="required" placeholder="Số điện thoại *" />
                </div>
                <div>
                    <button type="submit">Gửi</button>
                </div>
            </form>
        </div>
    </div>
</section>
