<?php
    $optionBasic = $this->home()->optionBasic();
    if($optionBasic['displayAppendixArticle'] || $this->display):
?>
<div class="appendix">
    <style>
        .appendix {
            margin: 0 0 15px;
            background-color: #f9f9f9;
            border: 1px solid #DDD;
        }
        .appendix__title {
            margin: 0 0 10px;
            text-transform: uppercase;
            border-bottom: 1px solid #DDD;
            padding: 0 0 10px;
            font-size: 18px;
        }
        .appendix li {
            list-style: none;
            margin: 5px 0;
        }
        .appendix li:last-child {
            margin: 5px 0 0;
        }
        .appendix a {
            color: #1c95d2;
            font-size: 14px;
        }
        .appendix a.tree {
            color: #666;
            padding: 0 0 0 10px;
            font-size: 13px;
        }
        .appendix a:hover {
            text-decoration: underline;
        }
        <?= $this->style; ?>
    </style>

    <script>
        $(function() {
            function ChangeToSlug(a)
            {
                var title, slug;
                title = a;
                slug = title.toLowerCase();
                slug = slug.replace(/á|à|ả|ạ|ã|ă|ắ|ằ|ẳ|ẵ|ặ|â|ấ|ầ|ẩ|ẫ|ậ/gi, 'a');
                slug = slug.replace(/é|è|ẻ|ẽ|ẹ|ê|ế|ề|ể|ễ|ệ/gi, 'e');
                slug = slug.replace(/i|í|ì|ỉ|ĩ|ị/gi, 'i');
                slug = slug.replace(/ó|ò|ỏ|õ|ọ|ô|ố|ồ|ổ|ỗ|ộ|ơ|ớ|ờ|ở|ỡ|ợ/gi, 'o');
                slug = slug.replace(/ú|ù|ủ|ũ|ụ|ư|ứ|ừ|ử|ữ|ự/gi, 'u');
                slug = slug.replace(/ý|ỳ|ỷ|ỹ|ỵ/gi, 'y');
                slug = slug.replace(/đ/gi, 'd');
                slug = slug.replace(/\`|\~|\!|\@|\#|\||\$|\%|\^|\&|\*|\(|\)|\+|\=|\,|\.|\/|\?|\>|\<|\'|\"|\:|\;|_/gi, '');
                slug = slug.replace(/ /gi, "-");
                slug = slug.replace(/\-\-\-\-\-/gi, '-');
                slug = slug.replace(/\-\-\-\-/gi, '-');
                slug = slug.replace(/\-\-\-/gi, '-');
                slug = slug.replace(/\-\-/gi, '-');
                slug = '@' + slug + '@';
                slug = slug.replace(/\@\-|\-\@|\@/gi, '');
                return slug;
            }
            var a = $('.content_appendix');
            var element = a.find('h2, h3');
            if(element.length > 0) {
                var list = [];
                var appendix = $('.appendix');
                var c = 0;
                var b = 0;
                element.each(function(e, v){
                    var t = $(this);
                    var tag = t.prop('tagName');
                    if(tag == 'H2') {
                        c++;
                        b = 0;
                    }
                    if(tag == 'H3') {
                        b++;
                    }
                    var textSlug = t.attr('id', ChangeToSlug(t.text()));

                    if(t.text() != '') {
                        list += '<li><a class="'+(tag == 'H3' ? 'tree':'')+'" href="#'+ChangeToSlug(t.text())+'">'+ c + (tag == 'H3' ? '.' + b:'') + '. ' + t.text()+'</a></li>';
                    }
                });
                appendix.css({'padding': '30px'});
                appendix.append('<h3 class="appendix__title">Nội dung chính</h3>');
                appendix.append(list);
            }
        });
    </script>
</div>
<?php endif; ?>