<?php
echo $this->doctype();
$optionBasic = $this->home()->optionBasic();
?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
        <?php
        echo $this->headTitle()->setSeparator('')->setAutoEscape(false);
        $this->headMeta()->appendName('DC.language', 'scheme=utf-8 content=vi');
        echo $this->headMeta();

        echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $optionBasic['favicon'] ? $optionBasic['favicon']:null ]);
        $cs = [
            '/tp/TP002/css/bootstrap.css',
            '/assets/css/web/font-awesome.min.css',
            '/tp/TP002/css/simple-line-icons.css',
            '/assets/css/web/owl.carousel.css',
            '/assets/css/web/owl.theme.css',
            '/assets/css/web/owl.transitions.css',
            '/tp/TP002/css/h.css',
        ];
        echo '<link href="'.srcLink($cs,2).'" media="screen" rel="stylesheet" type="text/css">';
        $js = [
            '/assets/js/web/jquery-1.11.2.min.js',
        ];
        echo '<script type="text/javascript" src="'.srcLink($js,1).'"></script>';
        echo !empty($optionBasic['scriptHead']) ? '<script>'.$optionBasic['scriptHead'].'</script>' : null;
        ?>

    </head>
    <body>
        <?php
            echo $this->render('layout/header');
            echo $this->content;
            echo $this->render('layout/footer');
            echo !empty($optionBasic['scriptBody']) ? '<script>'.$optionBasic['scriptBody'].'</script>' : null;
        ?>

        <div class="modal fade" id="myModal" role="dialog">
            <div class="modal-dialog">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Giỏ hàng</h4>
                    </div>
                    <div class="modal-body"></div>
                </div>
            </div>
        </div>
    </body>
    <?php
        $r = [
            '/tp/TP002/css/r.css',
        ];
        echo '<link href="'.srcLink($r,1).'" media="screen" rel="stylesheet" type="text/css">';
    $js = [
        '/assets/js/web/bootstrap.min.js',
        '/assets/js/web/jquery.lazy.min.js',
        '/assets/js/web/owl.carousel.js',
        '/assets/js/web/jquery-ui-1.10.3.custom.min.js',
        '/assets/plugins/parsleyjs/parsley.min.js',
        '/assets/js/jquery.carouFredSel-6.2.1-packed.js',
        '/tp/TP002/js/a.js',
    ];
    echo '<script type="text/javascript" src="'.srcLink($js,1).'"></script>';
    echo !empty($optionBasic['scriptFooter']) ? '<script>'.$optionBasic['scriptFooter'].'</script>' : null;
    ?>
    <?= $this->render('layout/modal'); ?>
</html>