<?php
echo $this->headtitle($this->escapehtml($this->translate('Danh sách tin tức')));
$domainUrl = $this->home()->getDomain();
$domainUrl ? $_SERVER['HTTP_HOST'] = $domainUrl:$_SERVER['HTTP_HOST'];
$option = $this->option;
?>
<input type="hidden" class="updateHomepage" />
<div class="row">
    <div class="col-sm-12">
        <div class="card-box">
            <div class="portlet-body">
                <div id="sample_editable_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
                    <div class="btn-toolbar">
                        <div class="btn-group focus-btn-group">
                            <a href="/admin/article/add" class="btn btn-default waves-effect waves-light">Thêm bài viết</a>
                        </div>
                        <div class="btn-group dropdown-btn-group pull-right">
                            <div class="dataTables_filter mb-15">
                                <form action="" method="get" name="ProductSearch" class="form-inline" id="ProductSearch">
                                    <?php
                                        $form = $this->fFilter;
                                    ?>
                                    <div class="form-group">
                                        <?=$this->formelement($form->get('id')->setAttributes(['class' => 'form-control','placeholder'=>'Id']))?>
                                    </div>
                                    <div class="form-group">
                                        <?=$this->formelement($form->get('title')->setAttributes(['class' => 'form-control','placeholder'=>'Tiêu đề']))?>
                                    </div>
                                    <div class="form-group"><input name="submit" type="submit" class="btn btn-default " value="Tìm Kiếm"></div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <?php
                    echo $dg = new \Admin\Dg\DgArticle ( array (
                        'data' => $this->results->getData (),
                        'paging' => $this->results->getPaging (),
                        'rowCount' => $this->results->getRowCount (),
                        'rowInPage' => $this->results->getRowInPage (),
                        'setup' => true,
                        'url' => $this->url,
                    ));
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="global-admin-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="full-width-modalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <ul class="nav nav-tabs navtab-bg nav-justified">
                <li class="active">
                    <a href="#tab1" data-toggle="tab" aria-expanded="false">
                        <span class="">Danh sách bài viết</span>
                    </a>
                </li>
                <li class="">
                    <a href="#tab2" data-toggle="tab" aria-expanded="false">
                        <span class="">Chi tiết bài viết</span>
                    </a>
                </li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="tab1">
                    <form class="formArticle">
                        <div class="row">

                            <div class="col-sm-12">
                                <div class="form-group">
                                    <input type="hidden" name="pageArticle" value="1" />
                                    <label class="control-label" for="metaNameArticle">Tên trang</label>
                                    <input type="text" name="metaNameArticle" class="form-control" placeholder="Tên trang" value="<?= $option['metaNameArticle'] ?>">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label class="control-label" for="metaTitleArticle">Tiêu đề</label>
                                    <input type="text" name="metaTitleArticle" class="form-control" placeholder="Tiêu đề" value="<?= $option['metaTitleArticle'] ?>">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label class="control-label" for="sologan">Từ khoá chính</label>
                                    <input type="text" name="metaKeywordArticle" placeholder="Từ khoá chính" data-role="tagsinput" value="<?= $option['metaKeywordArticle'] ?>" />
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label class="control-label" for="sologan">Mô tả</label>
                                    <textarea name="metaDescriptionArticle" class="form-control" placeholder="Mô tả"><?= $option['metaDescriptionArticle'] ?></textarea>
                                </div>
                            </div>
                        </div>
                        <hr/>
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label class="control-label" for="metaNameArticle">Số bài viết trên trang</label>
                                    <input type="text" name="postPerPageArticle" data-parsley-type="digits" data-parsley-length="[1,30]" data-parsley-error-message="Định dạng số" class="form-control" placeholder="Số bài viết trên trang" value="<?= $option['postPerPageArticle'] ?>">
                                </div>
                            </div>
                        </div>
                        <div class="form-actions m-t-10 m-b-20">
                            <input name="submit" type="submit" id="btnSubmit" class="btn btn-default" value="Lưu">
                        </div>
                    </form>
                </div>
                <div class="tab-pane" id="tab2">
                    <form class="formArticle">
                        <div class="row">
                            <div class="col-sm-10">
                                <p class="text-muted m-b-20">Hiển thị mục lục</p>
                            </div>
                            <div class="col-sm-2">
                                <div class="form-group m-b-20">
                                    <input type="checkbox" <?= $option['displayAppendixArticle'] ? 'checked':'' ?> name="displayAppendixArticle" data-plugin="switchery" data-color="#5fbeaa" data-size="small">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-10">
                                <p class="text-muted m-b-20">Hiển thị danh sách tags trong chi tiết bài viết</p>
                            </div>
                            <div class="col-sm-2">
                                <div class="form-group m-b-20">
                                    <input type="checkbox" <?= $option['displayTagArticle'] ? 'checked':'' ?> name="displayTagArticle" data-plugin="switchery" data-color="#5fbeaa" data-size="small">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-10">
                                <p class="text-muted m-b-20">Hiển thị icon social chia sẻ (Facebook, Google)</p>
                            </div>
                            <div class="col-sm-2">
                                <div class="form-group m-b-20">
                                    <input type="hidden" name="singleArticle" value="1" />
                                    <input type="checkbox" <?= $option['shareArticle'] ? 'checked':'' ?> name="shareArticle" data-plugin="switchery" data-color="#5fbeaa" data-size="small">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-10">
                                <p class="text-muted m-b-20">Hiển thị bình luận Facebook.</p>
                            </div>
                            <div class="col-sm-2">
                                <div class="form-group m-b-20">
                                    <input type="checkbox" <?= $option['commentFacebookArticle'] ? 'checked':'' ?> name="commentFacebookArticle" data-plugin="switchery" data-color="#5fbeaa" data-size="small">
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-10">
                                <p class="text-muted m-b-20">Bình luận tài khoản.</p>
                            </div>
                            <div class="col-sm-2">
                                <div class="form-group m-b-20">
                                    <input type="checkbox" <?= $option['commentArticle'] ? 'checked':'' ?> name="commentArticle" data-plugin="switchery" data-color="#5fbeaa" data-size="small">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-10">
                                <p class="text-muted m-b-20">Duyệt comment <br/>ON: Cho hiển thị comment khi người dùng comment. <br/>OFF: Người dùng comment chờ duyệt từ quản lý Website.</p>
                            </div>
                            <div class="col-sm-2">
                                <div class="form-group m-b-20">
                                    <input type="checkbox" <?= $option['statusCommentArticle'] ? 'checked':'' ?> name="statusCommentArticle" data-plugin="switchery" data-color="#5fbeaa" data-size="small">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-10">
                                <p class="text-muted m-b-20">Hiển thị đánh giá trong bài viết.</p>
                            </div>
                            <div class="col-sm-2">
                                <div class="form-group m-b-20">
                                    <input type="checkbox" <?= $option['ratingArticle'] ? 'checked':'' ?> name="ratingArticle" data-plugin="switchery" data-color="#5fbeaa" data-size="small">
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-10">
                                <p class="text-muted m-b-20">Hiển thị danh sách bài viết liên quan trong bài viết. </p>
                            </div>
                            <div class="col-sm-2">
                                <div class="form-group m-b-20">
                                    <input type="checkbox" <?= $option['displayRelationArticle'] ? 'checked':'' ?> name="displayRelationArticle" data-plugin="switchery" data-color="#5fbeaa" data-size="small">
                                </div>
                            </div>
                        </div>

                        <div class="form-actions m-t-10 m-b-20">
                            <input name="submit" type="submit" id="btnSubmit" class="btn btn-default" value="Lưu">
                        </div>
                    </form>
                </div>
            </div>

            <div class="modal-footer">
                <input type="hidden" data-value="1" id="pageImage">
                <button type="button" class="btn" data-dismiss="modal">Đóng</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

