<?php
    echo $this->headtitle($this->escapehtml($this->translate('Tuỳ chỉnh trang')));
    $field = $this->field;
    $value = $this->value;
    if(!empty($field)):
    $c = 0;
    $i = 0;
    $homePage = $this->home()->homePage();
    if($homePage) {
        array_shift($field);
    }
?>
<style>
    .card-box__option--background, .card-box__option--background .nav.nav-tabs+.tab-content{
        background-color: #f9f9f9;
    }
    .portlet .collapsed .ion-minus-round:before {
        content: "\f217" !important;
    }
    .portlet .portlet-heading {
        cursor: pointer;
    }
</style>
<div class="row">
    <div class="col-sm-12">
        <div class="card-box card-box__option--background">
            <ol class="breadcrumb p-t-0 m-b-0">
                <li>
                    <a class="header-title" href="/admin/setup/template"><i class="ion-reply"></i> Giao diện</a>
                </li>
            </ol>
            <p class="text-muted m-b-15 font-13">
                Các tuỳ chỉnh khác, Header, Footer.
            </p>
            <hr/>

            <div class="portlet-body">
                <ul class="nav nav-tabs navtab-bg nav-justified">
                    <?php foreach($field as $k => $f): $c++;
                    ?>
                    <li class="<?= $c == 1 ? 'active':'' ?>">
                        <a href="#<?= strtolower(str_replace(' ', '', $k)) ?>" data-toggle="tab" aria-expanded="<?= $c == 1 ? 'true':'false' ?>">
                            <span><?= $k ?></span>
                        </a>
                    </li>
                    <?php endforeach; ?>
                </ul>

                <div class="tab-content">
                    <?php foreach($field as $k => $f): $i++;
                    ?>
                    <div class="tab-pane <?= $i == 1 ? 'active':'' ?>" id="<?= strtolower(str_replace(' ', '', $k)) ?>">
                        <?php if(is_array($f)){
                            echo '<form class="formHomepage form-horizontal" method="post" enctype="multipart/form-data" data-parsley-validate novalidate>';
                                foreach($f as $i => $v) {
                                    ?>
                                    <?php if($v['type'] == 'startmodule'): ?>
                                    <div class="portlet">
                                    <div class="portlet-heading portlet-default collapsed" data-toggle="collapse" data-parent="#accordion1" class="" href="#<?= vnString($v['label']) ?>">
                                        <h3 class="portlet-title">  <?= $v['label'] ?> </h3>
                                        <div class="portlet-widgets">
                                            <a class="btn__view-module" data-module="view_<?= vnString($v['label']) ?>"><i class="<?= $value['view_'.vnString($v['label'])] == 1 ? 'ion-eye':'ion-eye-disabled' ?>"></i></a>
                                            <span class="divider"></span>
                                            <a class=""><i class="ion-minus-round"></i></a>
                                        </div>
                                        <input type="hidden" name="view_<?= vnString($v['label']) ?>" value="<?= $value['view_'.vnString($v['label'])] ?>" >
                                        <div class="clearfix"></div>
                                    </div>
                                    <div id="<?= vnString($v['label']) ?>" class="panel-collapse collapse">
                                    <div class="portlet-body">
                                    <?php endif; ?>

                                    <?php if($v['type'] != 'startmodule' && $v['type'] != 'endmodule'): ?>
                                    <div class="form-group">
                                        <label class="col-md-2 control-label"><?= $v['type'] != 'hr' ? ucfirst($i):null ?></label>
                                        <div class="col-md-10">
                                            <?= !empty($v['description']) ? '<p class="text-muted font-13 m-b-10">'.$v['description'].'</p>':null ?>
                                            <?php if($v['type'] == 'text'): ?>
                                                <input type="text" name="text <?= vnString($i) ?>" class="form-control" value="<?= $value[vnString($i)] ?>" placeholder="<?= $i ?>">
                                            <?php elseif ($v['type'] == 'textarea'): ?>
                                                <textarea name="textarea <?= vnString($i) ?>" class="form-control"><?= $value[vnString($i)] ?></textarea>
                                            <?php elseif ($v['name'] == 'product'): ?>
                                                <div class="row">
                                                    <div class="col-md-10">
                                                        <select name="<?= 'product '. vnString($i).'[]' ?>" class="form-control select-ajax-product select2-hidden-accessible" data-placeholder="<?= $i ?>" data-length="<?= $v['limit'] ? $v['limit']:5 ?>" multiple="multiple">
                                                            <?php
                                                            $product = $value[vnString($i)];
                                                            if(!empty($product)) {
                                                                foreach($product as $u => $p) {
                                                                    echo '<option value="'.$u.'" selected="selected">'.$p['title'].'</option>';
                                                                }
                                                            }
                                                            ?>
                                                        </select>
                                                    </div>
                                                    <div class="col-md-2">
                                                        <a href="http://<?= $_SERVER['HTTP_HOST'] ?>/admin/product" target="_blank" class="text-muted control-label">Quản lý Sản phẩm</a>
                                                    </div>
                                                </div>
                                            <?php elseif ($v['name'] == 'news'): ?>
                                                <div class="row">
                                                    <div class="col-md-10">
                                                        <select name="<?= 'article '. vnString($i).'[]' ?>" class="form-control select-ajax-article select2-hidden-accessible" data-placeholder="<?= $i ?>" data-length="<?= $v['limit'] ? $v['limit']:5 ?>" multiple="multiple">
                                                            <?php
                                                            $article = $value[vnString($i)];
                                                            if(!empty($article)) {
                                                                foreach($article as $o => $n) {
                                                                    echo '<option value="'.$o.'" selected="selected">'.$n['title'].'</option>';
                                                                }
                                                            }
                                                            ?>
                                                        </select>
                                                    </div>
                                                    <div class="col-md-2">
                                                        <a href="http://<?= $_SERVER['HTTP_HOST'] ?>/admin/article" target="_blank" class="text-muted control-label">Quản lý Bài viết</a>
                                                    </div>
                                                </div>
                                            <?php elseif ($v['name'] == 'page'): ?>
                                                <div class="row">
                                                    <div class="col-md-10">
                                                        <select name="<?= 'page '. vnString($i).'[]' ?>" class="form-control select-ajax-page select2-hidden-accessible" data-placeholder="<?= $i ?>" data-length="<?= $v['limit'] ? $v['limit']:5 ?>" multiple="multiple">
                                                            <?php
                                                            $page = $value[vnString($i)];
                                                            if(!empty($page)) {
                                                                foreach($page as $o => $n) {
                                                                    echo '<option value="'.$o.'" selected="selected">'.$n['title'].'</option>';
                                                                }
                                                            }
                                                            ?>
                                                        </select>
                                                    </div>
                                                    <div class="col-md-2">
                                                        <a href="http://<?= $_SERVER['HTTP_HOST'] ?>/admin/page" target="_blank" class="text-muted control-label">Quản lý Trang</a>
                                                    </div>
                                                </div>
                                            <?php elseif ($v['name'] == 'banner'): ?>
                                                <div class="row">
                                                    <div class="col-md-10">
                                                        <select name="<?= 'banner '. vnString($i).'[]' ?>" class="form-control select-ajax-banner select2-hidden-accessible" data-placeholder="<?= $i ?>" data-length="<?= $v['limit'] ? $v['limit']:5 ?>" multiple="multiple">
                                                            <?php
                                                            $banner = $value[vnString($i)];
                                                            if(!empty($banner)) {
                                                                foreach($banner as $o => $n) {
                                                                    echo '<option value="'.$o.'" selected="selected">'.$n['title'].'</option>';
                                                                }
                                                            }
                                                            ?>
                                                        </select>
                                                    </div>
                                                    <div class="col-md-2"><a href="http://<?= $_SERVER['HTTP_HOST'] ?>/admin/media/banner" target="_blank" class="text-muted control-label">Quản lý Banner</a></div>
                                                </div>

                                            <?php elseif ($v['name'] == 'categoryproduct'): ?>
                                                <div class="row">
                                                    <div class="col-md-10">
                                                        <select name="<?= 'categoryproduct '. vnString($i).'[]' ?>" class="form-control select-ajax-productcategory select2-hidden-accessible" data-placeholder="<?= $i ?>" data-length="<?= $v['limit'] ? $v['limit']:5 ?>" multiple="multiple">
                                                            <?php
                                                            $categoryProduct = $value[vnString($i)];
                                                            if(!empty($categoryProduct)) {
                                                                foreach($categoryProduct as $o => $n) {
                                                                    echo '<option value="'.$o.'" selected="selected">'.$n['title'].'</option>';
                                                                }
                                                            }
                                                            ?>
                                                        </select>
                                                    </div>
                                                    <div class="col-md-2">
                                                        <a href="http://<?= $_SERVER['HTTP_HOST'] ?>/admin/product/category" target="_blank" class="text-muted control-label">Danh mục sản phẩm</a>
                                                    </div>
                                                </div>

                                            <?php elseif ($v['name'] == 'categoryarticle'): ?>
                                                <div class="row">
                                                    <div class="col-md-10">
                                                        <select name="<?= 'categoryarticle '. vnString($i).'[]' ?>" class="form-control select-ajax-articlecategory select2-hidden-accessible" data-placeholder="<?= $i ?>" data-length="<?= $v['limit'] ? $v['limit']:5 ?>" multiple="multiple">
                                                            <?php
                                                            $categoryArticle = $value[vnString($i)];
                                                            if(!empty($categoryArticle)) {
                                                                foreach($categoryArticle as $o => $n) {
                                                                    echo '<option value="'.$o.'" selected="selected">'.$n['title'].'</option>';
                                                                }
                                                            }
                                                            ?>
                                                        </select>
                                                    </div>
                                                    <div class="col-md-2">
                                                        <a href="http://<?= $_SERVER['HTTP_HOST'] ?>/admin/article/category" target="_blank" class="text-muted control-label">Danh mục bài viết</a>
                                                    </div>
                                                </div>

                                            <?php endif; ?>
                                        </div>
                                    </div>
                                    <?php endif; ?>

                                    <?php if($v['type'] == 'endmodule'): ?>
                                        </div>
                                        </div>
                                        </div>
                                    <?php endif; ?>

                                <?php
                                }
                                echo '<div class="form-group">
                                        <div class="col-sm-offset-2 col-sm-10">
                                            <button type="submit" class="btn btn-primary waves-effect waves-light">Lưu</button>
                                        </div>
                                    </div>';
                            echo '</form>';
                        }
                        ?>
                    </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
</div>

<?php endif; ?>