<?php if(!empty($this->galleryLayout['gallery-1-list banner']['gallery-1-list']) || !empty($this->galleryLayout['gallery-2-list banner']['gallery-2-list'])):?>
    <section class="four-post">
         <div class="four-post__inner">
             <?= $this->galleryLayout['gallery-title text']['value'] ? '<h2 class="headline-default news__headline">'.$this->galleryLayout['gallery-title text']['value'].'</h2>' : '' ?>
             <?= $this->galleryLayout['gallery-sub-title text']['value'] ? '<div class="four-post__intro"><span>'.$this->galleryLayout['gallery-sub-title text']['value'].'</span></div>' : null ?>
             <?php if(!empty($this->galleryLayout['gallery-1-list banner']['gallery-1-list'])):?>
                    <div class="four-post__item">
                        <div class="four-post__item--left">
                            <div class="four-post__slider owl-carousel owl-theme">
                                <?php
                                foreach($this->galleryLayout['gallery-1-list banner']['gallery-1-list'] as $k => $b):
                                    $imageFirst = '';
                                    $i = json_decode($b['image'], true);
                                    if(is_array($i) && !empty($i)) {
                                        $imageFirst = array_shift($i);
                                    }
                                    ?>
                                    <div class="four-post__slider--item">
                                        <a href="<?= $b['url'] ?>">
                                            <figure class="four-post__slider--image lazy" style="background-image: url(<?= $imageFirst ?>)"></figure>
                                        </a>
                                    </div>
                                <?php
                                endforeach;
                                ?>
                            </div>
                        </div>
                        <div class="four-post__item--right">
                            <?= $this->galleryLayout['gallery-1-title text']['value'] ? '<h2 class="four-post__title">'.$this->galleryLayout['gallery-1-title text']['value'].'</h2>' :'' ?>
                            <?= $this->galleryLayout['gallery-1-description textarea']['value'] ? '<div class="four-post__description">'.$this->galleryLayout['gallery-1-description textarea']['value'].'</div>' : '' ?>
                            <?php if(!empty($this->galleryLayout['gallery-1-link text']['value'])):?>
                                <div class="four-post__button">
                                    <a class="btn-default1" href="<?= $this->galleryLayout['gallery-1-link text']['value'] ?>">Chi tiết</a>
                                </div>
                            <?php endif;?>
                        </div>
                    </div>
                <?php endif;?>
                <?php if(!empty($this->galleryLayout['gallery-2-list banner']['gallery-2-list'])):?>
                    <div class="four-post__item">
                        <div class="four-post__item--right">
                            <?= $this->galleryLayout['gallery-2-title text']['value'] ? '<h2 class="four-post__title">'.$this->galleryLayout['gallery-2-title text']['value'].'</h2>' :'' ?>
                            <?= $this->galleryLayout['gallery-2-description textarea']['value'] ? '<div class="four-post__description">'.$this->galleryLayout['gallery-2-description textarea']['value'].'</div>' : '' ?>
                            <?php if(!empty($this->galleryLayout['gallery-2-link text']['value'])):?>
                                <div class="four-post__button">
                                    <a class="btn-default1" href="<?= $this->galleryLayout['gallery-2-link text']['value'] ?>">Chi tiết</a>
                                </div>
                            <?php endif;?>
                        </div>
                        <div class="four-post__item--left">
                            <div class="four-post__slider owl-carousel owl-theme">
                                <?php
                                foreach($this->galleryLayout['gallery-2-list banner']['gallery-2-list'] as $k => $b):
                                    $imageFirst = '';
                                    $i = json_decode($b['image'], true);
                                    if(is_array($i) && !empty($i)) {
                                        $imageFirst = array_shift($i);
                                    }
                                    ?>
                                    <div class="four-post__slider--item">
                                        <a href="<?= $b['url'] ?>">
                                            <figure class="four-post__slider--image lazy" style="background-image: url(<?= $imageFirst ?>)"></figure>
                                        </a>
                                    </div>
                                <?php
                                endforeach;
                                ?>
                            </div>
                        </div>

                    </div>
                <?php endif;?>
            </div>
    </section>
<?php endif;?>