<?php if(!empty($this->bannerList['banner-list banner']['banner-list'])):?>
<section class="slider">
    <?php
        echo '<ul class="banner owl-carousel owl-theme">';
        foreach($this->bannerList['banner-list banner']['banner-list'] as $k => $b):
            $image = json_decode($b['image'], true);
            if(!empty($image)) {
                $imageFirst = array_shift($image);
            }
            ?>
            <li>
                <a href="<?= $b['url'] ?>">
                    <figure class="owl-lazy slider-image" data-src="<?= $imageFirst ?>">

                    </figure>
                </a>
            </li>
        <?php endforeach;?>
        </ul>
</section>
<?php endif;?>
