<?php
    $paginator = $this->paginator;
    $optionPage = $this->home()->optionPage();
    $menuOption = $this->home()->getMenu();
    $optionBasic = $this->home()->optionBasic();
    $cs = [
        '/tp/F005/css/n.css'
    ];
    echo '<link href="'.srcLink($cs,1).'" media="screen" rel="stylesheet" type="text/css">';
?>
<?php
    /**** Start SEO DWEB *****/
    $this->headTitle($this->escapeHtml($this->translate('Danh sách tin tức')));
    $this->headMeta()->appendName('description', '');
    $this->headMeta()->appendName('keywords', '');

    $this->headMeta()->appendProperty('og:title', 'Danh sách tin tức');
    $this->headMeta()->appendProperty('og:description', 'Danh sách tin tức');
    $this->headMeta()->appendProperty('og:image', '');
    $this->headMeta()->appendProperty('og:image:secure_url', '');
    $this->headMeta()->appendProperty('og:image:width', '');
    $this->headMeta()->appendProperty('og:image:height', '');
    $this->headMeta()->appendProperty('og:type', 'Page');
    $this->headMeta()->appendProperty('og:url', 'http://'.$_SERVER['HTTP_HOST'].'/bai-viet.html');
    $this->headMeta()->appendProperty('og:site_name', $optionBasic['sologan']);

    $this->headMeta()->appendName('twitter:card', '');
    $this->headMeta()->appendName('twitter:title', 'Danh sách tin tức');
    $this->headMeta()->appendName('twitter:description', 'Danh sách tin tức');
    $this->headMeta()->appendName('twitter:image', '');
    /**** End SEO DWEB *****/
?>
<div class="container">
    <div class="row">
        <?php
        if(!empty($menuOption['news_sidebar']) || !empty($optionPage['view_danh-muc-sidebar-1']) || !empty($optionPage['view_danh-muc-sidebar-2']) || !empty($optionPage['view_banner-sidebar'])):
            echo '<div class="col-md-8">';
        else:
            echo '<div class="col-md-12">';
        endif;
        ?>
        <h1 class="page-title">Tin tức</h1>
        <?php
        if(count($paginator)){
            $n = $this->newsCategory()->getCategories();
            /*if(count($n)){
                echo '<ul class="navNews">';
                echo '<li><a class="active" href="/news">Tất cả</a></li>';
                foreach($n as $b){
                    echo '<li><a href="'.$b->getViewLink().'">'.$b->getName().'</a></li>';
                }
                echo '</ul>';
            }*/
            echo '<ul class="lNCategory">';
            foreach($paginator as $n){
                $image = json_decode($n->getImage(), true);
                $imageFirst = '';
                if(!empty($image)){
                    $imageFirst = array_shift($image);
                }
                echo '<li>
                        <a href="'.$n->getViewLink().'">
                        <figure class="lazy image-article" data-src="'.(!empty($imageFirst) ? $imageFirst : null).'"></figure>
                        </a>
                        
                        <div class="article__content">
                            <p class="category">'.$n->getCateName().'</p>
                            <h3><a href="'.$n->getViewLink().'">'.$n->getTitle().'</a></h3>
                            <p>'.$n->getDescription().'</p>
                        </div>
                    </li>';
            }
            echo '</ul>';
            echo '<div class="paginatorProduct">';
            echo $this->paginationControl($this->paginator, 'Elastic', 'partial/listPage');
            echo '</div>';
        }
        ?>
    </div>
    <?php  echo $this->render('news/news/sidebar');?>
</div>
</div>
