<?php  use Home\Model\DateBase;
    if(!empty($this->newsLayout['news-list article']['news-list'])):
?>
<section class="news">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="titleHome"><span><?= $this->newsLayout['news-title text']['value'] ?></span></h1>
                <?php $slider = $this->newsLayout['news-slider-checkbox checkbox']['value']?>
                <ul class="<?= $slider ? 'news-slider owl-carousel owl-theme' : 'lN' ?> news__list">
                    <?php
                    foreach($this->newsLayout['news-list article']['news-list'] as $k => $n):
                        $image = json_decode($n['image'], true);
                        if(!empty($image)){
                            $imageFirst = array_shift($image);
                        }
                        ?>
                        <li>
                            <p><span class="lN__date"><?= DateBase::toFormat($n['date'], 'M d, Y') ?></span></p>
                            <h2><a href="<?= $n['url'] ?>"><?= $n['title'] ?></a></h2>
                            <a href="<?= $n['url'] ?>"><figure class="lazy image-article" data-src="<?= !empty($imageFirst) ? $imageFirst:'' ?>">

                                </figure></a>
                        </li>
                        <?php
                    endforeach;
                    ?>
                </ul>
            </div>
        </div>
    </div>
</section>
<?php endif;?>