<?php
$cs = [
    '/tp/F010/css/p.css',
];
echo '<link href="'.srcLink($cs,1).'" media="screen" rel="stylesheet" type="text/css">';

$product = $this->paginator;
$product->setItemCountPerPage($this->uriParams()->getRequest()->getQuery('icpp') ? : 12);
$menuOption = $this->home()->getMenu();
$optionPage = $this->home()->optionPage();
$optionBasic = $this->home()->optionBasic();
?>
<?php
/**** Start SEO DWEB *****/
$this->headTitle($this->escapeHtml($this->translate('Danh sách sản phẩm')));
$this->headMeta()->appendName('description', '');
$this->headMeta()->appendName('keywords', '');

$this->headMeta()->appendProperty('og:title', 'Danh sách sản phẩm');
$this->headMeta()->appendProperty('og:description', 'Danh sách sản phẩm');
$this->headMeta()->appendProperty('og:image', '');
$this->headMeta()->appendProperty('og:image:secure_url', '');
$this->headMeta()->appendProperty('og:image:width', '');
$this->headMeta()->appendProperty('og:image:height', '');
$this->headMeta()->appendProperty('og:type', 'Page');
$this->headMeta()->appendProperty('og:url', 'http://'.$_SERVER['HTTP_HOST'].'/san-pham.html');
$this->headMeta()->appendProperty('og:site_name', $optionBasic['sologan']);

$this->headMeta()->appendName('twitter:card', '');
$this->headMeta()->appendName('twitter:title', 'Danh sách sản phẩm');
$this->headMeta()->appendName('twitter:description', 'Danh sách sản phẩm');
$this->headMeta()->appendName('twitter:image', '');
/**** End SEO DWEB *****/
?>
<div class="main">
    <div class="container">
        <div class="row">
            <ul class="breadcrumb breadcrumb-category">
                <li><a href="/">Trang chủ</a></li>
                <li><a href="/san-pham.html">Sản phẩm</a></li>
            </ul>

            <div class="category-inner">
                <?php
                if(!empty($menuOption['product_sidebar']) || !empty($optionPage['view_danh-muc-san-pham-1']) || !empty($optionPage['view_danh-muc-san-pham-2'])):
                    echo $this->render('product/product/sidebar');
                    echo '<div class="col-md-9">';
                else:
                    echo '<div class="col-md-12">';
                endif;
                ?>

                    <div class="right">
                        <div class="productCategory">
                            <?php
                            $show = $this->request->getQuery('show');
                            if(count($product)){
                                echo '<div class="titlePaginator">';
                                echo '<h1 class="title">Sản phẩm</h1>';
                                echo '<select onchange="location = this.options[this.selectedIndex].value;">
                                                    <option value="' . $this->product()->removeFilter('show') . '">Mới cập nhật</option>
                                                    <option value="' . $this->product()->addFilter('show', 'priceAsc',2) . '" '.($show == 'priceAsc' ? 'selected':'').'>Giá tăng dần</option>
                                                    <option value="' . $this->product()->addFilter('show', 'priceDesc',2) . '" '.($show == 'priceDesc' ? 'selected':'').'>Giá giảm dần</option>
                                                    <option value="' . $this->product()->addFilter('show', 'SaleOff',2) . '" '.($show == 'SaleOff' ? 'selected':'').'>Giảm giá</option>
                                              </select></div>';
                                echo '<ul class="lPC product__list ">';
                                foreach($product as $p){
                                    ?>
                                    <?php

                                    $image = json_decode($p->getImage(), true);
                                    if(!empty($image)){
                                        $imageFirst = array_shift($image);
                                    }
                                    ?>
                                    <li>
                                        <div class="product-item__inner">
                                            <div class="product-image__wrapper">
                                                <a class="pI" href="<?= $p->getViewLink() ?>"><figure class="lazy image-product" data-src="<?= !empty($imageFirst) ? $imageFirst:'' ?>"></figure></a>
                                            </div>
                                            <div class="product-item__info">
                                                <h3><a href="<?= $p->getViewLink() ?>"><?= $p->getTitle() ?></a></h3>
                                                <p class="price <?= ($p->getPriceOld() ? 'priceOld':null) ?>">
                                                    <?=  (!empty($p->getPriceOld()) ? '<span>'.number_format($p->getPriceOld()).'</span><i>'.number_format($p->getPrice()).'</i>':number_format($p->getPrice()) ) ?>
                                                </p>
                                                <a class="btnAddCart" data-quantity="1" data-id="<?= $p->getId()?>">Giỏ hàng</a>
                                            </div>
                                        </div>
                                    </li>
                                    <?php
                                }
                                echo '</ul>';
                                echo $this->paginationControl($this->paginator, 'Elastic', 'partial/listPage');
                            }else{
                                echo '<p style="margin: 10px 0 0 0;text-align: center">Đang được cập nhật</p>';
                            }
                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>