<?php
    $view = $this->news;

    $imageFirst = '';
    if(!empty(json_decode($view->getImage(), true))){
        $imageFirst = array_shift(json_decode($view->getImage(), true));
    }

    $current_page_URL = $_SERVER["SERVER_NAME"] . $_SERVER["REQUEST_URI"];
    $a = json_decode($view->getExtraContent());
    $this->headTitle($this->escapeHtml(html_entity_decode($this->translate($view->getTitle()))));

    $this->headMeta()->appendName('description', ($view->getMetaDescription() ? $view->getMetaDescription():$view->getTitle()));
    $this->headMeta()->appendName('keywords', ($view->getMetaKeyword() ? $view->getMetaKeyword():$view->getTitle()));

    $this->headMeta()->appendProperty('og:locale', 'vi_VN');
    $this->headMeta()->appendProperty('og:image', 'http://'.$_SERVER["SERVER_NAME"].$imageFirst);
    $this->headMeta()->appendProperty('og:url', 'http://'.$current_page_URL);
    $this->headMeta()->appendProperty('og:title', $view->getMetaTitle() ? $view->getMetaTitle():$view->getTitle());
    $this->headMeta()->appendProperty('og:description', ($view->getMetaDescription() ? $view->getMetaDescription():$view->getTitle()));

    $this->headMeta()->appendProperty('twitter:card', 'http://'.$_SERVER["SERVER_NAME"]);
    $this->headMeta()->appendProperty('twitter:title', $view->getMetaTitle() ? $view->getMetaTitle():$view->getTitle());
    $this->headMeta()->appendProperty('twitter:image', 'http://'.$_SERVER["SERVER_NAME"].$imageFirst);
    $this->headMeta()->appendProperty('twitter:description', $view->getMetaDescription() ? $view->getMetaDescription():$view->getTitle());

    $cs = [
        '/tp/A001/css/n.css'
    ];
    echo '<link href="'.srcLink($cs,1).'" media="screen" rel="stylesheet" type="text/css">';
    $js = [
        '/tp/A001/js/n.js'
    ];
    echo '<script type="text/javascript" src="'.srcLink($js,1).'"></script>';
?>
<?php if($view->getType() == 2): ?>
<?php
    echo $this->render('news/news/gallery');
?>
<?php else: ?>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="detailNews">
                <h1 class="detail-news__title"><?= html_entity_decode($view->getTitle()) ?></h1>
                <?php
                    echo $view->getContent();
                ?>
                <div class="social">
                    <div style="float: left;margin: 0 5px 0 0;" class="fb-like" data-href="<?= $current_page_URL.$view->getViewLink() ?>" data-layout="button" data-action="like" data-show-faces="false" data-share="true"></div>
                    <div class="g-plusone" data-size="medium"></div>
                </div>
                <script src="https://apis.google.com/js/platform.js" async defer>
                    {lang: 'vi'}
                </script>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>



