<?php
    $theme = $this->NewsCategory()->featchTreeCategory(20);
    $data = $this->paginator;
    $data->setItemCountPerPage($this->uriParams()->getRequest()->getQuery('icpp') ? : 12);
    $category = $this->category;

    $cs = [
        '/tp/blog/css/page.css'
    ];
    echo '<link href="'.srcLink($cs,1).'" media="screen" rel="stylesheet" type="text/css">';

    $this->headTitle($this->escapeHtml($this->translate($category->getName())));
    $this->headMeta()->appendName('description', ($category->getName()));
    $this->headMeta()->appendName('keywords', ($category->getName()));
    $this->headMeta()->appendProperty('og:title', $category->getName());
    $optionPage = $this->home()->optionPage();
?>

<section class="m-t-100 blog">
    <div class="price__hero">
        <div class="price__hero-inner">
            <h2 class="price__hero-title">Blog <span>DWEB</span></h2>
            <p class="price__hero-description">Chia sẻ kinh nghiệm ý tưởng kinh doanh online thiết thực nhất</p>
        </div>
    </div>
</section>

<?php
if(!empty($data)):
    $category = $this->NewsCategory()->getCategories();
    ?>
    <section class="news">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="news__inner">
                        <div class="news__category">
                            <ul class="news__list-category">
                                <?php $url = $this->UriParams()->getRequest()->getRequestUri(); ?>
                                <?php if(!empty($category)): ?>
                                    <?php foreach($category as $t): ?>
                                        <li><a <?= $url == $t->getViewLink() ? 'class="active"':null ?> href="<?= $t->getViewLink() ?>"><?= $t->getName() ?></a></li>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </ul>
                        </div>
                        <div class="news__list">
                            <?php
                                $i = 0;
                                foreach($data as $n):
                                $i++;
                                $image = json_decode($n->getImage(), true);
                                $imageFirst = '';
                                if(!empty($image)){
                                    $imageFirst = array_shift($image);
                                }
                                if($i == 7):
                                ?>
                                <div class="adv-middle">
                                    <a href="http://dweb.vn/thiet-ke-web-gia-re-n356.html" title="thiet ke web gia re">
                                        <figure style="background-image: url('/tp/blog/image/thiet-ke-web-gia-re-1.png');">
                                            <div class="landing-head-hero__content">
                                                <h2 class="">Thiết kế <span>web giá rẻ</span></h2>
                                                <p class=""><?= !empty($optionPage['tieu-de-khuyen-mai-danh-muc']) ? $optionPage['tieu-de-khuyen-mai-danh-muc']:'Chỉ với <span>3000k</span>/ ngày bạn đã có ngay một website.' ?> </p>
                                                <span>Dùng thử miễn phí</span>
                                            </div>
                                        </figure>
                                    </a>
                                </div>

                                <?php endif; ?>
                                <div class="news__item">
                                    <div class="news__item--inner">
                                        <a href="<?= $n->getViewLink() ?>" title="<?= $n->getTitle() ?>">
                                            <figure class="lazy news__image" title="<?= $n->getTitle() ?>" data-src="<?= $imageFirst ?>"></figure>
                                        </a>
                                        <div class="news__intro">
                                            <a href="<?= $n->getViewLink() ?>">
                                                <h2 class="news__title"><?= $n->getTitle() ?></h2>
                                            </a>
                                            <div class="news__intro--sub">
                                                <?= $n->getDescription() ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        </div>
                        <div class="news__paginator">
                            <?php
                            echo $this->paginationControl($data, 'Elastic', 'partial/listPage');
                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
<?php endif; ?>