<?php
    use Home\Model\DateBase;
    $view = $this->news;
    $optionPage = $this->home()->optionPage();
    $optionBasic = $this->home()->optionBasic();
    $url = $this->UriParams()->getRequest()->getRequestUri();
    $image = json_decode($view->getImage(), true);
    $imageFirst = '';
    if(!empty($image)){
        $imageFirst = array_shift($image);
    }
    $category = $this->NewsCategory()->getCategories();
?>

<?php
$image = 'https://'.$_SERVER['HTTP_HOST'].$imageFirst;
$imageInfo = getimagesize($image);
/**** Start SEO DWEB *****/
echo $this->headLink(['rel' => 'canonical', 'href' => 'https://'.$_SERVER['HTTP_HOST'].$view->getViewLink() ]);
$this->headTitle($this->escapeHtml($this->translate(!empty($view->getMetaTitle()) ? $view->getMetaTitle():null)));
$this->headMeta()->appendName('description', (!empty($view->getMetaDescription()) ? $view->getMetaDescription():null));
$this->headMeta()->appendName('keywords', (!empty($view->getMetaKeyword()) ? $view->getMetaKeyword():null));

$this->headMeta()->appendProperty('og:title', !empty($view->getMetaTitle()) ? $view->getMetaTitle():$view->getTitle());
$this->headMeta()->appendProperty('og:description', !empty($view->getMetaDescription()) ? $view->getMetaDescription():null);
$this->headMeta()->appendProperty('og:image', !empty($imageFirst) ? 'https://'.$_SERVER['HTTP_HOST'].$imageFirst:null);
$this->headMeta()->appendProperty('og:image:secure_url', !empty($imageFirst) ? 'https://'.$_SERVER['HTTP_HOST'].$imageFirst:null);
$this->headMeta()->appendProperty('og:image:width', $imageInfo['0']);
$this->headMeta()->appendProperty('og:image:height', $imageInfo['1']);
$this->headMeta()->appendProperty('og:type', 'Article');
$this->headMeta()->appendProperty('og:url', 'http://'.$_SERVER['HTTP_HOST'].$view->getViewLink());
$this->headMeta()->appendProperty('og:site_name', $optionBasic['sologan']);

$this->headMeta()->appendName('twitter:card', !empty($image) ? $image:'summary_large_image');
$this->headMeta()->appendName('twitter:title', !empty($view->getMetaTitle()) ? $view->getMetaTitle():$view->getTitle());
$this->headMeta()->appendName('twitter:description', (!empty($view->getMetaDescription()) ? $view->getMetaDescription():null));
$this->headMeta()->appendName('twitter:image', !empty($image) ? $image:null);
/**** End SEO DWEB *****/
?>

<link href="https://fonts.googleapis.com/css?family=Noto+Serif" rel="stylesheet">
<!-- 
<section class="m-t-100 blog">
    <div class="price__hero">
        <div class="price__hero-inner">
            <h2 class="price__hero-title">Blog <span>DWEB</span></h2>
            <p class="price__hero-description">Chia sẻ kinh nghiệm ý tưởng kinh doanh online thiết thực nhất</p>
        </div>
    </div>
</section> -->

<section class="news-category">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="news__category">
                    <ul class="news__list-category">
                        <?php if(!empty($category)): ?>
                            <?php foreach($category as $t): ?>
                                <li><a <?= $view->getCategoryId() == $t->getId() ? 'class="active"':null ?> href="<?= $t->getViewLink() ?>"><?= $t->getName() ?></a></li>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="single-news">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <figure class="lazy single-news__image" data-src="<?= $imageFirst ?>"></figure>
                <div class="single-news__detail">
                    <h1 class="single-news__title"><?= $view->getTitle() ?></h1>
                    <div class="single-news__profile">
                        <span><i class="fa fa-clock-o"></i><?= DateBase::toFormat($view->getCreatedDateTime(), 'd/m/Y') ?></span><span><i class="fa fa-folder-o"></i><?= $view->getCateName() ?></span><span><i class="fa fa-eye"></i><?= $view->getView() ?></span>
                    </div>
                    <div class="single-news__content">
                        <?php
                            echo html_entity_decode($view->getContent());
                        ?>
                    </div>
                    <div class="single-news__button">
                        <span><?= !empty($optionPage['tieu-de-khuyen-mai']) ? $optionPage['tieu-de-khuyen-mai']:null ?></span><a class="btn-d" href="http://dweb.vn/kho-giao-dien.html"><?= !empty($optionPage['tieu-de-button']) ? $optionPage['tieu-de-button']:'Đăng ký ngay' ?></a>
                    </div>
                    <div class="single-news__relation">
                        <?php
                            $relation = json_decode($view->getArticleRelated(), true);
                            if(!empty($relation)) {
                                echo '<h2 class="single-news__relation--title">Bài viết liên quan</h2>';
                                echo '<ul>';
                                echo '<li><i class="fa fa-caret-right"></i><a href="http://dweb.vn/thiet-ke-web-gia-re-n356.html">Thiết kế website giá rẻ</a></li>';
                                echo '<li><i class="fa fa-caret-right"></i><a href="http://dweb.vn/lam-website-chuyen-nghiep-n390.html">Làm website chuyên nghiệp</a></li>';
                                echo '<li><i class="fa fa-caret-right"></i><a href="http://dweb.vn/huong-dan-tao-website-ban-hang-n398.html">Tạo website bán hàng</a></li>';
                                foreach($relation as $r) {
                        ?>
                            <li><i class="fa fa-caret-right"></i><a href="<?= $r['url'] ?>"><?= $r['title'] ?></a></li>
                        <?php
                                }
                            echo '</ul>';
                            }
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>



