<?php
    $optionBasic = $this->home()->optionBasic();
    $optionPage = $this->home()->optionPage();
    $url = $this->UriParams()->getRequest()->getRequestUri();
?>
<div class="head__top">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="head__top--inner">
                    <div class="leftInfo">
                        <?=$optionPage['hotline'] ? '<span class="top-hotline">HotLine: <a href="tel:'.$optionPage['hotline'].'">'.$optionPage['hotline'].'</a></span>' : ''?>
                        <?=$optionPage['email'] ? '<span class="top-email">Email: <a href="mailto:'.$optionPage['email'].'">'.$optionPage['email'].'</a></span>' : ''?>
                    </div>
                    <div class="rightInfo">
                        <ul class="RegisterLogin">
                            <?php
                            if ($this->user()->hasIdentity()) {
                                ?>
                                <li><a>Xin chào: <?= $this->user()->getUser()->getFullName() ? $this->user()->getUser()->getFullName():ucfirst($this->user()->getUser()->getUserName()) ?></a></li>
                                <li><a href="/user/signout">Thoát</a></li>
                                <?php
                            }else{
                                ?>
                                <li><a href="/user/signup">Đăng ký</a></li>
                                <li><a href="/user/signin">Đăng nhập</a></li>
                                <?php
                            }
                            ?>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
<div class="head__logo">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="head__logo--inner">
                    <div class="head__col">
                        <h1>
                            <?php if(!empty($optionBasic['logo'])): ?>
                                <div class="logo">
                                    <a href="/">
                                        <img src="<?= $optionBasic['logo'] ?>" alt="<?= !empty($optionBasic['sologan']) ? $optionBasic['sologan']:null ?>" />
                                    </a>
                                </div>
                            <?php else: ?>
                                <div class="logo">
                                    <a class="logo-text" href="/">FASHION<p>Make of style</p></a>
                                </div>
                            <?php endif; ?>
                        </h1>
                    </div>
                    <?php if(!empty($optionPage['view_thong-tin-cot-header-1'])):?>
                    <div class="head__col">
                        <div class="head__col--title">
                            <?= $optionPage['tieu-de-cot-1'] ? '<p>'.$optionPage['tieu-de-cot-1'].'</p>' : ''?>
                        </div>
                        <div class="head__col--content">
                            <?= $optionPage['noi-dung-cot-1'] ? '<p>'.$optionPage['noi-dung-cot-1'].'</p>' : ''?>
                        </div>
                    </div>
                    <?php endif;?>
                    <?php if(!empty($optionPage['view_thong-tin-cot-header-2'])):?>
                    <div class="head__col">
                        <div class="head__col--title">
                            <?= $optionPage['tieu-de-cot-2'] ? '<p>'.$optionPage['tieu-de-cot-2'].'</p>' : ''?>
                        </div>
                        <div class="head__col--content">
                            <?= $optionPage['noi-dung-cot-2'] ? '<p>'.$optionPage['noi-dung-cot-2'].'</p>' : ''?>
                        </div>
                    </div>
                    <?php endif;?>
                    <?php if(!empty($optionPage['view_thong-tin-cot-header-3'])):?>
                    <div class="head__col">
                        <div class="head__col--title">
                            <?= $optionPage['tieu-de-cot-3'] ? '<p>'.$optionPage['tieu-de-cot-3'].'</p>' : ''?>
                        </div>
                        <div class="head__col--content">
                            <?= $optionPage['noi-dung-cot-3'] ? '<p>'.$optionPage['noi-dung-cot-3'].'</p>' : ''?>
                        </div>
                    </div>
                    <?php endif;?>
                    <a id="menuMobile">
                        <i class="icon-menu icons" aria-hidden="true"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="head__nav">
    <div class="container">
        <div class="row">
            <?php
            $menuOption = $this->home()->getMenu();
            ?>
            <div class="col-md-9">
                <div class="nav__left">
                    <ul>
                        <?php foreach($menuOption['head_menu'] as $m): ?>
                            <li class="<?= $url == $m['url'] ? 'active ' : null?><?= $m['children'] ? 'navIsset':null ?>"><a href="<?= $m['url'] ?>"><?= $m['name'] ?><?= $m['children'] ? '<i class="fa fa-caret-down"></i>' : null ?></a>
                                <?php if(!empty($m['children'])): ?>
                                    <ul class="navHome__list">
                                        <?php foreach($m['children'] as $mm): ?>
                                            <li <?= $mm['children'] ? 'class="navIsset"':null ?>><a href="<?= $mm['url'] ?>"><?= $mm['name'] ?></a>
                                                <?php if(!empty($mm['children'])): ?>
                                                    <ul class="ul-level-3">
                                                        <?php foreach ($mm['children'] as $mcc):?>
                                                            <li><a href="<?= $mcc['url'] ?>"><?= $mcc['name'] ?></a></li>
                                                        <?php endforeach;?>
                                                    </ul>
                                                <?php endif;?>
                                            </li>
                                        <?php endforeach; ?>
                                    </ul>
                                <?php endif; ?>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>
            <div class="col-md-3">

                <div class="nav__right">
                    <div class="search-box">
                        <div class="search-form">

                            <form id="search" action="/search" method="get">
                                <input type="text" name="q" placeholder="Tìm kiếm ..."/>
                                <a href="javascript:{}" onclick="document.getElementById('search').submit();"><i class="fa fa-search" aria-hidden="true"></i></a>
                                <div id="searchFolding"></div>
                            </form>
                        </div>
                    </div>
                    <div class="cart-label">
                        <?php
                        $cartService = $this->cart()->getServiceCart();
                        $products = $cartService->getProducts();
                        ?>
                        <a class="totalCart" href="/cart"><i class="fa fa-shopping-bag" aria-hidden="true"></i><span><?= $cartService->getTotalProducts() ?></span></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="navMobile">
    <ul class="navMobile__list">
        <?php foreach($menuOption['head_menu'] as $m): ?>
            <li <?= $url == $m['url'] ? 'class="active"':null ?>><?= $m['children'] ? '<button><i class="fa fa-caret-down"></i></button>' : null ?><a href="<?= $m['url'] ?>"><?= $m['name'] ?></a>
                <?php if(!empty($m['children'])): ?>
                    <ul class="nav2">
                        <?php foreach($m['children'] as $mm): ?>
                            <li><?= $mm['children'] ? '<button><i class="fa fa-caret-down"></i></button>' : null ?><a href="<?= $mm['url'] ?>"><?= $mm['name'] ?></a>
                                <?php if(!empty($mm['children'])): ?>
                                    <ul>
                                        <?php foreach ($mm['children'] as $mcc):?>
                                            <li><a href="<?= $mcc['url'] ?>"><?= $mcc['name'] ?></a></li>
                                        <?php endforeach;?>
                                    </ul>
                                <?php endif;?>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
</div>