<?php
$products = $this->products;
if(count($products)){
    ?>
    <?php
    $c = 0;
    $d = 0;
    foreach($products as $p){
        $c++;
        $t = (($p->getPriceOld() ? $p->getPriceOld():$p->getPrice())-$p->getOptions()['priceOff'] )*$p->getQuantity();
        $image = json_decode($p->getImage(), true);
        if(is_array($image)){
            $imageFirst = array_shift($image);
        }
        $d += $t;
    }
}
?>


<div class="form-group">
    <label class="control-label">Khách hàng</label>
    <div class="row">
        <div class="col-md-10">
            <input class="clientId" type="hidden" >
            <form id="search" action="/search" method="get">
                <input class="form-control" type="text" name="q" placeholder="Tìm tên hoặc số điện thoại"/>
                <div id="searchFolding"></div>
            </form>
        </div>
        <div class="col-md-2">
            <a class="btn btn-icon waves-effect waves-light btn-default btn-add-client" data-toggle="modal" data-target=".modal-client"><i class="fa fa-plus"></i></a>
        </div>
    </div>
</div>
<div class="form-group">
    <div class="control-group">
        <label class="control-label" for="firstName">Thanh toán</label>
        <div class="radio radio-custom">
            <input type="radio" name="paymentMethod" id="article" value="1" checked="" data-parsley-multiple="paymentMethod" data-parsley-id="12">
            <label for="article">Trực tiếp</label>
        </div>
        <div class="radio radio-custom">
            <input type="radio" name="paymentMethod" id="gallery" value="2" data-parsley-multiple="paymentMethod">
            <label for="gallery">Thẻ/COD</label>
        </div>
    </div>
</div>

<?php if(count($products) > 0) : ?>
    <div class="form-group">
        <div class="row">
            <div class="col-md-12">
                <hr>
                <h3 class="text-center">Tổng: <?= !empty($d) ? number_format($d):'0' ?> VNĐ</h3>
            </div>
        </div>
    </div>
    <a class="sale__button-print  btn btn-block btn-lg btn-default waves-effect waves-light">Thanh toán</a>
<?php endif; ?>
