<?php
    echo $this->headtitle($this->escapehtml($this->translate('Bán hàng')));
?>
<div class="row height100 ">
    <div class="col-sm-9 height100">
        <div class="card-box sale-main ">
            <div class="portlet-body">
                <form action role="form" class="sale__form-product">
                    <div class="form-group contact-search m-b-10">
                        <input name="title" type="text" id="search" class="form-control" placeholder="Tìm kiếm tên sản phẩm">
                        <button type="submit" class="btn btn-white"><i class="fa fa-search"></i></button>
                    </div> <!-- form-group -->
                </form>
                <div class="table-responsive">
                    <table class="table table-hover mails m-0 table table-actions-bar">
                        <thead>
                            <tr>
                                <th style="width: 35px;"></th>
                                <th>Tên sản phẩm</th>
                                <th>Giá</th>
                                <th>Số lượng</th>
                                <th>Tổng</th>
                                <th style="width: 20px;"></th>
                            </tr>
                        </thead>
                        <tbody class="sale__list-order"></tbody>

                    </table>

                    <div id="printableArea" style="display: none">
                        <html>
                        <body>
                        <head>
                            <title></title>
                            <style>
                                body {
                                    font-family: Arial, "Helvetica Neue", "Helvetica", Tahoma, Verdana, sans-serif;
                                }
                                .client__headline {
                                    padding: 0 0 10px;
                                    text-align: center;
                                    border-bottom: 1px solid #DDD;
                                    text-transform: uppercase;
                                }
                                .client__info {
                                    padding: 0;
                                }
                                .client__info li {
                                    list-style: none;
                                    margin: 5px 0;
                                }
                                .client__item-product {
                                    padding: 10px 0;
                                    display: flex;
                                    border-bottom: 1px solid #DDD;
                                    justify-content: space-between;
                                    flex-wrap: wrap;
                                    align-items: center;
                                }
                                .client__item-product>div:nth-child(1) {
                                    width: 50%;
                                    font-weight: 700;
                                }
                                .client__item-product>div:nth-child(1) span {
                                    margin: 5px 0 0;
                                    display: block;
                                    font-size: 13px;
                                    font-weight: 400;
                                }
                                .client__toltalmoney h4 {
                                    text-align: right;
                                }
                            </style>
                        </head>
                        <div class="client">
                            <h3 class="client__headline">Đơn hàng</h3>
                            <ul class="client__info">
                                <li><span>Tên khách hàng: </span><strong class="client__name"></strong></li>
                                <li><span>Số điện thoại: </span><strong class="client__phone"></strong></li>
                            </ul>
                            <div class="client__list"></div>
                        </div>
                        </body>
                        </html>
                    </div>


                </div>

                <div class="sale__product">
                    <div class="sale__button-close"><a><i class="fa fa-angle-down"></i></a></div>

                    <?php if($this->totalPage > 1): ?>
                    <div class="sale__pagination">
                        <label>Sử dụng phím điều hướng</label>
                        <a class="sale__button-prev"><i class="fa fa-angle-left"></i></a>
                        <a class="sale__button-next"><i class="fa fa-angle-right"></i></a>
                    </div>
                    <?php endif; ?>

                    <div class="sale__inner">
                        <input type="hidden" class="currentPage" data-value="1">
                        <input type="hidden" class="totalPage" data-value="<?= $this->totalPage ?>">
                        <div class="pagination__label">
                            <p><span><?= $this->currentPage; ?></span><?= '/'.$this->totalPage ?></p>
                        </div>
                        <div class="sale__product-list">
                            <?php
                                foreach($this->results->getData () as $p):
                                $imageFirst = '';
                                $i = json_decode($p->getImage(), true);
                                if(is_array($i) && !empty($i)) {
                                    $imageFirst = array_shift($i);
                                }
                            ?>
                                <div class="sale__item">
                                    <div class="sale__item--inner" data-title="<?= $p->getTitle(); ?>" data-price="<?= $p->getPriceOld() ? $p->getPriceOld():$p->getPrice() ?>" data-image="<?= $imageFirst ?>" data-quantity="1" data-quantity-total="<?= $p->getQuantity() ? $p->getQuantity():0 ?>" data-id="<?= $p->getId() ?>">
                                        <a data-id="<?= $p->getId() ?>">
                                            <figure data-src="<?= $imageFirst ?>" class="lazy sale__image"></figure>
                                            <p><?= $p->getTitle() ?></p>
                                            <span>SL: <?= $p->getQuantity() ? $p->getQuantity():0 ?></span>
                                            <div>
                                                <?= number_format($p->getPriceOld() ? $p->getPriceOld():$p->getPrice()); ?>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-3">
        <div class="card-box">
            <div class="portlet-body">
                <div class="sale__right">
                    <div class="form-group">
                        <label class="control-label">Khách hàng</label>
                        <div class="row">
                            <div class="col-md-10">
                                <input class="clientId" type="hidden" >
                                <form id="search" action="/search" method="get">
                                    <input class="form-control" type="text" name="q" placeholder="Tìm tên hoặc số điện thoại"/>
                                    <div id="searchFolding"></div>
                                </form>
                            </div>
                            <div class="col-md-2">
                                <a class="btn btn-icon waves-effect waves-light btn-default btn-add-client" data-toggle="modal" data-target=".modal-client"><i class="fa fa-plus"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="control-group">
                            <label class="control-label" for="firstName">Thanh toán</label>
                            <div class="radio radio-custom">
                                <input type="radio" name="paymentMethod" id="article" value="1" checked="" data-parsley-multiple="paymentMethod" data-parsley-id="12">
                                <label for="article">Trực tiếp</label>
                            </div>
                            <div class="radio radio-custom">
                                <input type="radio" name="paymentMethod" id="gallery" value="2" data-parsley-multiple="paymentMethod">
                                <label for="gallery">Thẻ/COD</label>
                            </div>
                        </div>
                    </div>

                    <div class="sale__right--button">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<div id="modal-general" class="modal-general modal-bell modal fade" tabindex="-1" role="dialog" aria-labelledby="full-width-modalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Thông báo</h4>
            </div>
            <div class="modal-body">
                <p class="modal-general__content text-muted"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn" data-dismiss="modal">Đóng</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div id="modal-client" class="modal-client modal-bell modal fade" tabindex="-1" role="dialog" aria-labelledby="full-width-modalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Thêm khách hàng</h4>
            </div>
            <div class="modal-body">
                <form id="form-add-client" method="post" enctype="multipart/form-data" data-parsley-validate novalidate>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="field-1" class="control-label">Tên khách hàng</label>
                                <input type="text" class="client-name form-control" id="field-1" placeholder="Tên khách hàng">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="field-2" class="control-label">Số điện thoại <span class="text-danger">*</span></label>
                                <input  type="text" required="required" data-parsley-type="digits" data-parsley-length="[10,11]" data-parsley-error-message="Không được để trống, chưa đúng định dạng" class="client-phone form-control" id="field-2" placeholder="Số điện thoại">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="field-3" class="control-label">Địa chỉ</label>
                                <input type="text" class="client-address form-control" id="field-3" placeholder="Địa chỉ">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="field-4" class="control-label">Email</label>
                                <input type="text" data-parsley-type="email" class="client-email form-control" data-parsley-error-message="Định dạng email chưa đúng" id="field-4" placeholder="Email">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="field-5" class="control-label">Ngày sinh</label>
                                <input type="text" class="client-birthday form-control" placeholder="mm/dd/yyyy" id="datepicker-autoclose">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="field-6" class="m-b-15 control-label" style="display: block">Giới tính</label>
                                <div class="radio radio-custom radio-inline">
                                    <input type="radio" id="inlineRadio1" value="male" name="radioInline">
                                    <label for="inlineRadio1"> Nam </label>
                                </div>
                                <div class="radio radio-custom radio-inline">
                                    <input type="radio" id="inlineRadio2" value="female" name="radioInline">
                                    <label for="inlineRadio2"> Nữ </label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <button class="btn btn-default waves-effect waves-light" type="submit">Lưu</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn" data-dismiss="modal">Đóng</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->



