<?php
$optionBasic = $this->home()->optionBasic();
$optionPage = $this->home()->optionPage();
$url = $this->UriParams()->getRequest()->getRequestUri();
?>
<div class="head">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="head1">
                    <div class="head1__social">
                        <ul>
                            <?=$optionPage['dia-chi'] ? '<li><i class="fa fa-map-marker"></i>'.$optionPage['dia-chi'].'</li>' : ''?>
                            <?=$optionPage['so-dien-thoai'] ? '<li><i class="fa fa-phone-square"></i>'.$optionPage['so-dien-thoai'].'</li>' : ''?>
                        </ul>
                    </div>

                    <div class="head1__user">
                        <ul class="head1__user--inner">
                            <?php
                            if ($this->user()->hasIdentity()) {
                                ?>
                                <li>
                                    <a href="/admin">Xin chào: <?= $this->user()->getUser()->getFullName() ? $this->user()->getUser()->getFullName():ucfirst($this->user()->getUser()->getUserName()) ?></a>
                                </li>
                                <li>
                                    <a href="/user/signout">Thoát</a>
                                </li>
                                <?php
                            }else{
                                ?>
                                <li><a href="/user/signup">Đăng ký</a></li>
                                <li><a href="/user/signin">Đăng nhập</a></li>
                                <?php
                            }
                            ?>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="head2">
                    <div class="logo">
                        <a href="/">
                            <?php if(!empty($optionBasic['logo'])): ?>
                                <img src="<?= $optionBasic['logo'] ?>" alt="Fashion" />
                            <?php endif; ?>
                        </a>
                    </div>
                    <?php
                    $menuOption = $this->home()->getMenu();
                    if(!empty($menuOption['head_menu'])):
                        ?>
                        <div class="navHome">
                            <?php
                            $menuOption = $this->home()->getMenu();
                            if(!empty($menuOption['head_menu'])) {
                                ?>
                                <ul>
                                    <?php
                                    if(!empty($menuOption['head_menu'])){
                                        foreach($menuOption['head_menu'] as $m){
                                            ?>
                                            <li>
                                            <a href="<?= $m['url'] ?>"><?= $m['name'] ?></a>
                                            <?php
                                            if($m['children']){
                                                echo '<div>';
                                                echo '<ul class="nav3">';
                                                foreach($m['children'] as $mc){
                                                    ?>
                                                    <li><a href="<?= $mc['url'] ?>"><?= $mc['name'] ?></a>
                                                    <?php
                                                    if($mc['children']){
                                                        echo '<ul>';
                                                        foreach($mc['children'] as $mcc){
                                                            ?>
                                                            <li><a href="<?= $mcc['url'] ?>"><?= $mcc['name'] ?></a>
                                                            <?php
                                                        }
                                                        echo '</ul>';
                                                    }
                                                    ?>
                                                    </li>
                                                    <?php
                                                }
                                                echo '</div>';
                                            }
                                            ?>
                                            </li>
                                            <?php
                                        }
                                    }
                                    ?>
                                </ul>
                            <?php } ?>
                        </div>
                        <div class="navMobile">
                            <ul>
                                <?php
                                foreach ($menuOption['head_menu'] as $m):
                                    ?>
                                    <li>
                                        <?= $m['children'] ? '<button></button>':null ?><a href="<?= $m['url'] ?>"><?= $m['name'] ?></a>
                                        <?php if(!empty($m['children'])): ?>
                                            <ul class="nav2">
                                                <?php foreach($m['children'] as $mm): ?>
                                                    <li <?= $mm['children'] ? 'class="navIsset"':null ?>><?= $mm['children'] ? '<button></button>':null ?><a href="<?= $mm['url'] ?>"><?= $mm['name'] ?></a>
                                                        <?php if(!empty($mm['children'])): ?>
                                                            <ul>
                                                                <?php foreach($mm['children'] as $mmm): ?>
                                                                    <li><a href="<?= $mmm['url'] ?>"><?= $mmm['name'] ?></a></li>
                                                                <?php endforeach; ?>
                                                            </ul>
                                                        <?php endif; ?>
                                                    </li>
                                                <?php endforeach; ?>
                                            </ul>
                                        <?php endif; ?>
                                    </li>
                                <?php endforeach;?>
                            </ul>
                        </div>
                        <?php
                    endif;
                    ?>
                    <div class="navTool">
                        <a id="menuMobile">
                            <i class="icon-menu icons" aria-hidden="true"></i>
                        </a>
                        <div class="formSearch">
                            <a class="icon-font icon-magnifier open-search"></a>
                            <div class="form-search">
                                <form id="search" action="/search" method="get">
                                    <input type="text" name="q" placeholder="Tìm kiếm ..."/>
                                    <a class="icon-font icon-magnifier" onclick="document.getElementById('search').submit();"></a>
                                    <div id="searchFolding"></div>
                                </form>
                            </div>
                        </div>
                        <?php
                        $cartService = $this->cart()->getServiceCart();
                        $products = $cartService->getProducts();
                        ?>
                        <div class="cart">
                            <a class="icon-font icon-basket" href="/cart"><span><?= $cartService->getTotalProducts() ?></span></a>
                            <a href="/cart"><span><?= number_format($cartService->getTotalMoney()) ?> đ</span></a>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>
</div>
