<?php
    $optionBasic = $this->home()->optionBasic();
    if($optionBasic['shareArticle'] || $optionBasic['shareProduct']):
    $url = $this->url;
?>
<?php
    $cs = [
        '/assets/css/web/comment.css',
    ];
    echo '<link href="'.srcLink($cs,4).'" media="screen" rel="stylesheet" type="text/css">';
?>

<script>
    (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v2.6";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>

<div class="social-share">
    <div class="social">
        <div style="float: left;margin: 0 5px 0 0;" class="fb-like" data-href="<?= $url ?>" data-layout="button" data-action="like" data-show-faces="true" data-share="true"></div>
        <div class="g-plusone" style="" data-size="medium"></div>
    </div>
    <script src="https://apis.google.com/js/platform.js" async defer>
        {lang: 'vi'}
    </script>
</div>
<?php endif; ?>