<?php
    $optionBasic = $this->home()->optionBasic();
    if($optionBasic['displayTagArticle']):
    $this->tag;
    if(!empty($this->tag)) {
        $this->tag = explode(',', $this->tag);
    }
    $host = 'http://'.$_SERVER['HTTP_HOST'].'/bai-viet.html?tag=';
?>
<?php
    $cs = [
        '/assets/css/web/tagArticle.css',
    ];
    echo '<link href="'.srcLink($cs,4).'" media="screen" rel="stylesheet" type="text/css">';
?>
<?php if(!empty($this->tag)): ?>
    <div class="tag-list">
        <?php foreach ($this->tag as $t): ?>
            <a href="<?= $host.$t?>" target="_blank"><?= '#'.$t ?></a>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
<?php endif; ?>