<?php if(!empty($this->galeryLayout['galery-list banner']['galery-list'])):?>
    <section class="gallery">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <?= $this->galeryLayout['galery-title text']['value'] ? '<h1 class="news-last__headline--black">' .$this->galeryLayout['galery-title text']['value'].'</h1>' : ''?>
                    <div class="gallery__list">
                        <?php
                            foreach($this->galeryLayout['galery-list banner']['galery-list'] as $k => $b):
                                $image = json_decode($b['image'], true);
                                $imageFirst = '';
                                if(!empty($image)){
                                    $imageFirst = array_shift($image);
                                }
                                ?>
                                <div class="gallery__item">
                                    <a class="gallery__button" data-url="<?= $imageFirst ?>">
                                        <figure class="gallery__image lazy" data-src="<?= $imageFirst ?>">
                                            <h3>Xem</h3>
                                        </figure>
                                    </a>
                                </div>
                            <?php
                            endforeach;
                        ?>
                    </div>

                    <div class="modal fade" id="imagemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-body">
                                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                                    <img src="" class="imagepreview" style="width: 100%;" >
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>
<?php endif;?>