<?php
//echo $this->headScript()->prependFile($this->basePath() . '/js/product/product.js', 'text/javascript');
echo $this->headtitle($this->escapehtml($this->translate('Danh sách thuộc tính')));
?>
<div class="row">
    <div class="col-sm-8">
        <div class="card-box">
            <div class="portlet-body">
                <div id="sample_editable_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
                    <div class="btn-toolbar">
                        <div class="btn-group focus-btn-group">
                            <a href="#" class="btn btn-default waves-effect waves-light">Danh sách</a>
                        </div>
                    </div>
                    <?php
                    echo $dg = new \Admin\Dg\DgAttr ( array (
                        'data' => $this->results->getData (),
                        'paging' => $this->results->getPaging (),
                        'rowCount' => $this->results->getRowCount (),
                        'rowInPage' => $this->results->getRowInPage (),
//                        'uri' => $this->url,
                    ));
                    ?>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="card-box">
            <div class="portlet-body">
                <div id="sample_editable_1_wrapper" class="dataTables_wrapper" role="grid">
                    <div class="btn-toolbar">
                        <div class="btn-group focus-btn-group">
                            <a href="/admin/product/addattr" class="btn btn-default waves-effect waves-light">Thêm thuộc tính</a>
                        </div>
                    </div>

                    <ul class="nav nav-tabs navtab-bg nav-justified">
                        <li class="tab active" >
                            <a href="#home-2" data-toggle="tab" aria-expanded="false" class="active">
                                <span class="">Size</span>
                            </a>
                        </li>
                        <li class="tab" >
                            <a href="#profile-2" data-toggle="tab" aria-expanded="true" class="">
                                <span class="">Màu sắc</span>
                            </a>
                        </li>
                        <li class="tab" >
                            <a href="#profile-3" data-toggle="tab" aria-expanded="true" class="">
                                <span class="">Chất liệu</span>
                            </a>
                        </li>
                        <div class="indicator" style=""></div>
                    </ul>

                    <div class="tab-content tab-content__option">
                        <div class="tab-pane active" id="home-2">
                            <form id="addSize" method="post" enctype="multipart/form-data" data-parsley-validate="" novalidate="">
                                <div class="form-group text-size">
                                    <label for="size">Tên Size</label>
                                    <input type="text" id="size" name="size" parsley-trigger="change" required="" placeholder="Tên size" data-parsley-error-message="Tên size không được để trống" class="form-control" >
                                </div>
                                <div class="form-group text-right m-b-0">
                                    <button class="btn btn-primary waves-effect waves-light" type="submit">Lưu</button>
                                    <button class="btn btn-default waves-effect">Huỷ</button>
                                </div>
                            </form>
                        </div>
                        <div class="tab-pane" id="profile-2">
                            <form id="addColor" method="post" enctype="multipart/form-data" data-parsley-validate="" novalidate="">
                                <div class="form-group group-color">
                                    <label for="color">Tên Màu</label>
                                    <input type="text" id="nameColor" name="size" parsley-trigger="change" required="" placeholder="Tên màu" data-parsley-error-message="Tên màu không được để trống" class="form-control" >
                                </div>
                                <div class="form-group group-code">
                                    <label for="codeColor">Mã Màu</label>
                                    <input type="text" id="nameCode" name="size" parsley-trigger="change" required="" placeholder="Mã màu" data-parsley-error-message="Mã màu không được để trống" class="colorpicker-default form-control colorpicker-element" >
                                </div>
                                <div class="form-group text-right m-b-0">
                                    <button class="btn btn-primary waves-effect waves-light" type="submit">Lưu</button>
                                    <button class="btn btn-default waves-effect">Huỷ</button>
                                </div>
                            </form>
                        </div>
                        <div class="tab-pane" id="profile-3">
                            <form id="addMaterial" method="post" enctype="multipart/form-data" data-parsley-validate="" novalidate="">
                                <div class="form-group group-material">
                                    <label for="color">Tên chất liệu</label>
                                    <input type="text" id="nameMaterial" name="size" parsley-trigger="change" required="" placeholder="Tên chất liệu" data-parsley-error-message="Tên chất liệu không được để trống" class="form-control" >
                                </div>

                                <div class="form-group text-right m-b-0">
                                    <button class="btn btn-primary waves-effect waves-light" type="submit">Lưu</button>
                                    <button class="btn btn-default waves-effect">Huỷ</button>
                                </div>
                            </form>
                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>
</div>


