<?php
    echo $this->headtitle($this->escapehtml($this->translate('Đơn hàng')));
    use Home\Model\DateBase;
    $p = $this->result;
    if(!empty($p)):
?>

<div class="row layout_pc" style="">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="pull-left m-t-50">
                            <address>
                                <p><strong><?= (!empty($p->getCustomerName())) ? $p->getCustomerName():null; ?></strong></p>
                                <p class="m-t-10">Số điện thoại: <?= $p->getCustomerMobile(); ?></p>
                                <p class="m-t-10">Địa chỉ:</> <?= $p->getCustomerAddress() ? $p->getCustomerAddress():null ; ?></p>
                                <p class="m-t-10">Email: <?= $p->getCustomerEmail(); ?></p>
                            </address>
                        </div>
                        <div class="pull-right m-t-50">
                            <p><strong>Ngày đặt hàng: </strong> <?= DateBase::toFormat($p->getCreatedDateTime(),'H:i d/m/Y') ?></p>
                            <p class="m-t-10"><strong>Trạng thái: </strong>
                                <?php
                                    if($p->getShippingType() == 1){
                                        echo '<span class="label label-primary">Mới</span>';
                                    }elseif ($p->getShippingType() == 2) {
                                        echo '<span class="label label-success">Đã xử lý</span>';
                                    }
                                ?>
                            </p>
                            <p class="m-t-10"><strong>Đơn hàng: </strong> #<?= $p->getOrderId(); ?></p>
                        </div>
                    </div>
                </div>
                <?php
                    if(!empty($p->getProduct())):
                ?>
                <div class="m-h-50"></div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="table-responsive" style="border: none">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Tên</th>
                                        <th>Màu</th>
                                        <th>Size</th>
                                        <th>Số lượng</th>
                                        <th>Giá</th>
                                        <th>Giá huyến mại</th>
                                        <th>Thành tiền</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php
                                            $data = json_decode($p->getProduct(), true);
                                            $price = 0;
                                            $priceOld = 0;
                                            foreach($data as $k => $v) {
                                                if(is_array($v)){
                                                    $priceOld += $v['quantity'] * ($v['priceOld'] ? $v['priceOld']:$v['price']);
                                    ?>
                                                <tr>
                                                    <td><?= $v['name'] ?></td>
                                                    <td><?= $v['colorName'] ?></td>
                                                    <td><?= $v['sizeName'] ?></td>
                                                    <td><?= $v['quantity'] ?></td>
                                                    <td><?= number_format($v['price']) ?></td>
                                                    <td><?= number_format($v['priceOld']) ?></td>
                                                    <td><?= number_format($v['quantity'] * ($v['priceOld'] ? $v['priceOld']:$v['price'])) ?></td>
                                                </tr>
                                    <?php
                                                }
                                            }
                                    ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

                <div class="row" style="border-radius: 0px;">
                    <div class="col-md-3 col-md-offset-9">
                        <hr>
                        <h3 class="text-right">Tổng: <?= number_format($priceOld) ?> VNĐ</h3>
                    </div>
                </div>
                <?php endif; ?>

                <hr>
                <div class="hidden-print">
                    <div class="pull-right">
                        <a href="/admin/product/order" class="btn btn-default waves-effect waves-light">Quay lại</a>
                        <?php if($p->getShippingType() == 1): ?>
                            <a style="display: none" href="#" data-id="<?= $p->getId(); ?>" class="orderSuccess btn btn-danger waves-effect waves-light">Đã gửi hàng</a>
                        <?php endif; ?>
                        <a style="" href="javascript:window.print()" class="btn btn-inverse waves-effect waves-light"><i class="fa fa-print"></i> In đơn hàng</a>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

<?php
    if(!empty($p->getProduct())):
?>
        <div class="print_layout">
            <p><strong><?= (!empty($p->getCustomerName())) ? $p->getCustomerName():null; ?></strong></p>
            <p class="m-t-10">Số điện thoại: <?= $p->getCustomerMobile(); ?></p>
            <p style="border-bottom: 1px solid #111;padding: 0 0 15px;">Địa chỉ:</> <?= $p->getCustomerAddress() ? $p->getCustomerAddress():null ; ?></p>
            <?php
                $data = json_decode($p->getProduct(), true);
                $price = 0;
                $priceOld = 0;
                foreach($data as $k => $v) {
                    if(is_array($v)){
                        $priceOld += $v['quantity'] * ($v['priceOld'] ? $v['priceOld']:$v['price']);
                        ?>
                        <div style="border-bottom: 1px solid #111;">
                            <p><strong><?= $v['name'] ?></strong></p>
                            <p><strong>Số lượng:</strong> <?= $v['quantity'] ?></p>
                            <p><strong>Giá:</strong> <?= number_format($v['price']) ?></p>
                            <p><strong>Giá khuyến mại:</strong> <?= number_format($v['priceOld']) ?></p>
                            <p><strong><?= number_format($v['quantity'] * ($v['priceOld'] ? $v['priceOld']:$v['price'])) ?></strong></p>
                        </div>
                        <?php
                    }
                }
                ?>
            <h3 class="text-right">Tổng: <?= number_format($priceOld) ?> VNĐ</h3>
        </div>
<?php endif; ?>

<?php endif; ?>
<style>
    .print_layout {
        display: none;
    }
    @media print {
        .topbar, .layout_pc, .footer {
            display: none;
        }
        .left.side-menu {
            display: none;
        }
        .side-bar {
            display: none;
        }
        .print_layout {
            display: block;
            max-width: 100%;
        }
        @page {
            margin: 15px 0;
            size: 100mm 200mm; /* landscape */
        }
        body { margin: 1.6cm; }
        @font-face {
            font-family: Arial, "Times New Roman", "Bitstream Charter", Times, serif;
        }
    }
</style>
