<?php echo $this->doctype(); ?>
<html lang="en" class="height100">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Hệ thống quản lý nội dung, tạo website DWEB.VN">
    <meta name="author" content="DWEB">

    <link rel="shortcut icon" href="/assets/images/favicon_1.ico">
    <?php

    $cs = [
        '/assets/css/bootstrap.min.css',
        '/assets/css/core.css',
        '/assets/css/icons.css',
        '/assets/plugins/select2/css/select2.min.css',
        '/assets/plugins/bootstrap-colorpicker/css/bootstrap-colorpicker.min.css',
        '/assets/plugins/bootstrap-select/css/bootstrap-select.min.css',
        '/assets/plugins/bootstrap-tagsinput/css/bootstrap-tagsinput.css',
        '/assets/plugins/x-editable/css/bootstrap-editable.css',
        '/assets/plugins/nestable/jquery.nestable.css',
        '/assets/css/pages.css',
        '/assets/css/responsive.css',
        '/assets/plugins/responsive-table/css/rwd-table.min.css',
        '/assets/plugins/switchery/css/switchery.min.css',
        '/assets/plugins/summernote/summernote.css',
        '/assets/css/upload.css',
        '/assets/css/components.css',
    ];
    echo '<link href="'.srcLink($cs,3).'" media="screen" rel="stylesheet" type="text/css">';
?>
<style>
    .height100 {
        height: 100%;
    }
    .url__website {
        display: flex !important;
        align-items: center;
    }
    .url__website i.ion-earth {
        margin: 0 5px 0 0;
        font-size: 20px;
    }
</style>
</head>

<body class="fixed-left fixed-left-void height100">


<!-- Begin page -->
<div id="wrapper" class="forced enlarged height100">

<!-- Top Bar Start -->
<div class="topbar">

    <!-- LOGO -->
    <div class="topbar-left">
        <div class="text-center">
            <a href="/admin" class="logo"><i class="ti-layout-cta-btn-left icon-c-logo"></i><span>Admin</span></a>
            <!-- Image Logo here -->
        </div>
    </div>

    <!-- Button mobile view to collapse sidebar menu -->
    <div class="navbar navbar-default" role="navigation">
        <div class="container">
            <div class="">
                <div class="pull-left">
                    <button class="button-menu-mobile open-left waves-effect waves-light">
                        <i class="md md-menu"></i>
                    </button>
                    <span class="clearfix"></span>
                </div>

                <ul class="nav navbar-nav hidden-xs">
<!--                    <li class="dropdown">-->
<!--                        <a href="#" class="dropdown-toggle waves-effect waves-light" data-toggle="dropdown"-->
<!--                           role="button" aria-haspopup="true" aria-expanded="false">Tùy chọn nhanh <span-->
<!--                                class="caret"></span></a>-->
<!--                        <ul class="dropdown-menu">-->
<!--                            <li><a href="#">Thêm sản phẩm</a></li>-->
<!--                            <li><a href="#">Thêm bài viết</a></li>-->
<!--                        </ul>-->
<!--                    </li>-->
                    <li>
                        <a class="url__website" href="http://<?= $_SERVER['HTTP_HOST'] ?>/admin"><i class="ion-earth"></i> Quản lý website</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right pull-right">
                    <li style="display: none" class="dropdown top-menu-item-xs">
                        <a href="#" data-target="#" class="dropdown-toggle waves-effect waves-light" data-toggle="dropdown" aria-expanded="true">
                            <i class="icon-bell"></i> <span class="badge badge-xs badge-danger">3</span>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-lg">
                            <li class="notifi-title"><span class="label label-default pull-right">New 3</span>Notification</li>
                            <li class="list-group slimscroll-noti notification-list">
                                <!-- list item-->
                                <a href="javascript:void(0);" class="list-group-item">
                                    <div class="media">
                                        <div class="pull-left p-r-10">
                                            <em class="fa fa-diamond noti-primary"></em>
                                        </div>
                                        <div class="media-body">
                                            <h5 class="media-heading">A new order has been placed A new order has been placed</h5>
                                            <p class="m-0">
                                                <small>There are new settings available</small>
                                            </p>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:void(0);" class="list-group-item text-right">
                                    <small class="font-600">See all notifications</small>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="hidden-xs">
                        <a href="#" id="btn-fullscreen" class="waves-effect waves-light"><i class="icon-size-fullscreen"></i></a>
                    </li>
                    <li style="display: none" class="hidden-xs">
                        <a href="#" class="right-bar-toggle waves-effect waves-light"><i class="icon-settings"></i></a>
                    </li>
                    <li class="dropdown top-menu-item-xs">
                        <a href="" class="dropdown-toggle profile waves-effect waves-light" data-toggle="dropdown" aria-expanded="true">
                            <i class="icon-user" class="img-circle"></i>
                        </a>
                        <ul class="dropdown-menu">
                            <?php $optionBasic = $this->user()->getUser(); ?>
                            <li><a href="/admin/user/edit/<?= $optionBasic->getId() ?>"><i class="ti-user m-r-10 text-custom"></i> Thông tin</a></li>
                            <li><a href="/admin/setup"><i class="ti-settings m-r-10 text-custom"></i> Cấu hình</a></li>
                            <li><a href="/huongdan"><i class="ti-user m-r-10 text-custom icon-book-open"></i> Hướng dẫn</a></li>
                            <li class="divider"></li>
                            <li><a href="/user/signout"><i class="ti-power-off m-r-10 text-danger"></i> Thoát</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
    </div>
</div>
<!-- Top Bar End -->


<!-- ========== Left Sidebar Start ========== -->

<div class="left side-menu">
    <div class="sidebar-inner slimscrollleft">
        <!--- Divider -->
        <div id="sidebar-menu">
            <?php $this->navigation()->menu()->setPartial("layout/admin_menu_order")?>
            <?= $this->navigation()->menu(new \Menu\Order())->setUlClass('nav') ?>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<!-- Left Sidebar End -->



<!-- ============================================================== -->
<!-- Start right Content here -->
<!-- ============================================================== -->
<div class="content-page height100">
<!-- Start content -->
<div class="content height100">
    <div class="container height100">
        <?= $this->content; ?>
    </div> <!-- container -->
</div> <!-- content -->

<!--<footer class="footer text-right">-->
<!--    © --><?//= date('Y') ?><!--. DWEB.VN.-->
<!--</footer>-->

</div>


<!-- ============================================================== -->
<!-- End Right content here -->
<!-- ============================================================== -->


<!-- Right Sidebar -->
<div class="side-bar right-bar nicescroll">
    <h4 class="text-center">Chat</h4>
    <div class="contact-list nicescroll">
        <ul class="list-group contacts-list">
            <li class="list-group-item">
                <a href="#">
                    <div class="avatar">
                        <img src="/assets/images/users/avatar-1.jpg" alt="">
                    </div>
                    <span class="name">Chadengle</span>
                    <i class="fa fa-circle online"></i>
                </a>
                <span class="clearfix"></span>
            </li>
        </ul>
    </div>
</div>
<!-- /Right-bar -->

</div>
<!-- END wrapper -->
<script>
    var resizefunc = [];
</script>
<?php
    echo $this->headScript()

        ->prependFile($this->basePath() . '/assets/plugins/moment/moment.js')
        ->prependFile($this->basePath() . '/assets/plugins/x-editable/js/bootstrap-editable.min.js')
        ->prependFile($this->basePath() . '/assets/pages/jquery.xeditable.js')

        ->prependFile($this->basePath() . '/assets/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js')

        ->prependFile($this->basePath() . '/assets/plugins/bootstrap-select/js/bootstrap-select.min.js')
        ->prependFile($this->basePath() . '/assets/plugins/jquery-knob/jquery.knob.js')
        ->prependFile($this->basePath() . '/assets/plugins/switchery/js/switchery.min.js')
        ->prependFile($this->basePath() . '/assets/plugins/bootstrap-filestyle/js/bootstrap-filestyle.min.js')

        ->prependFile($this->basePath() . '/assets/plugins/raphael/raphael-min.js')

        ->prependFile($this->basePath() . '/assets/plugins/multiselect/js/jquery.multi-select.js')
        ->prependFile($this->basePath() . '/assets/plugins/select2/js/select2.min.js')

        ->prependFile($this->basePath() . '/assets/plugins/counterup/jquery.counterup.min.js')
        ->prependFile($this->basePath() . '/assets/plugins/waypoints/lib/jquery.waypoints.js')

        ->prependFile($this->basePath() . '/assets/plugins/peity/jquery.peity.min.js')
        ->prependFile($this->basePath() . '/assets/plugins/bootstrap-tagsinput/js/bootstrap-tagsinput.min.js')

        ->prependFile($this->basePath() . '/assets/js/jquery.scrollTo.min.js')
        ->prependFile($this->basePath() . '/assets/js/jquery.nicescroll.js')
        ->prependFile($this->basePath() . '/assets/js/wow.min.js')
        ->prependFile($this->basePath() . '/assets/js/waves.js')
        ->prependFile($this->basePath() . '/assets/js/jquery.blockUI.js')
        ->prependFile($this->basePath() . '/assets/js/jquery.slimscroll.js')

        ->prependFile($this->basePath() . '/assets/plugins/autoNumeric/autoNumeric.js')

        ->prependFile($this->basePath() . '/assets/plugins/summernote/lang/summernote-vi-VN.js')
        ->prependFile($this->basePath() . '/assets/plugins/summernote/summernote.min.js')

        ->prependFile($this->basePath() . '/assets/js/fastclick.js')
        ->prependFile($this->basePath() . '/assets/js/detect.js')
        ->prependFile($this->basePath() . '/assets/pages/nestable.js')
        ->prependFile($this->basePath() . '/assets/plugins/nestable/jquery.nestable.js')
        ->prependFile($this->basePath() . '/assets/plugins/timepicker/bootstrap-timepicker.js')
        ->prependFile($this->basePath() . '/assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js')
        ->prependFile($this->basePath() . '/assets/plugins/clockpicker/js/bootstrap-clockpicker.min.js')
        ->prependFile($this->basePath() . '/assets/plugins/bootstrap-daterangepicker/daterangepicker.js')
        ->prependFile($this->basePath() . '/assets/pages/jquery.form-pickers.init.js')


        ->prependFile($this->basePath() . '/assets/js/jquery-ui.min.js')
        ->prependFile($this->basePath() . '/tp/food/js/jquery-ui-1.10.3.custom.min.js')
        ->prependFile($this->basePath() . '/assets/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/assets/js/jquery-1.10.1.min.js');

        $js1 = [
            '/assets/plugins/parsleyjs/parsley.min.js',
            '/assets/js/product.js',
            '/assets/js/web/jquery.lazy.min.js',
            '/assets/js/jquery.core.js',
            '/assets/js/jquery.app.js',
            '/assets/pages/jquery.form-advanced.init.js',
            '/assets/js/sale.js',
            '/assets/js/jquery.shoppingcart.js',
            '/assets/js/excel/shim.js',
            '/assets/js/excel/jszip.js',
            '/assets/js/excel/xlsx.js',
        ];
        $js2 = [
            '/assets/pages/jquery.option.js',
            '/assets/js/excel/ods.js',
        ];
echo '<script type="text/javascript" src="'.srcLink($js1,5).'"></script>';
echo '<script type="text/javascript" src="'.srcLink($js2,5).'"></script>';
?>

</body>
</html>
