<?php echo $this->doctype(); ?>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Hệ thống quản lý nội dung, tạo website DWEB.VN">
    <meta name="author" content="DWEB">

    <link rel="shortcut icon" href="/assets/images/favicon_1.ico">
    <?php

    $cs = [
        '/assets/css/bootstrap.min.css',
        '/assets/css/core.css',
        '/assets/css/components.css',
        '/assets/css/icons.css',
        '/assets/plugins/select2/css/select2.min.css',
        '/assets/plugins/bootstrap-colorpicker/css/bootstrap-colorpicker.min.css',
        '/assets/plugins/bootstrap-select/css/bootstrap-select.min.css',
        '/assets/plugins/bootstrap-tagsinput/css/bootstrap-tagsinput.css',
        '/assets/plugins/nestable/jquery.nestable.css',
        '/assets/css/pages.css',
        '/assets/css/responsive.css',
        '/assets/plugins/responsive-table/css/rwd-table.min.css',
        '/assets/plugins/switchery/css/switchery.min.css',
        '/assets/plugins/summernote/summernote.css',
        '/assets/css/upload.css',
    ];
    echo '<link href="'.srcLink($cs,3).'" media="screen" rel="stylesheet" type="text/css">';


    ?>
</head>

<body class="fixed-left">


<!-- Begin page -->
<div id="wrapper">

<!-- Top Bar Start -->
<div class="topbar">

    <!-- LOGO -->
    <div class="topbar-left">
        <div class="text-center">
            <a href="/admin" class="logo"><i class="ti-layout-cta-btn-left icon-c-logo"></i><span>Guide</span></a>
            <!-- Image Logo here -->
        </div>
    </div>

    <!-- Button mobile view to collapse sidebar menu -->
    <div class="navbar navbar-default" role="navigation">
        <div class="container">
            <div class="">
                <div class="pull-left">
                    <span class="clearfix"></span>
                </div>
            </div>
            <!--/.nav-collapse -->
        </div>
    </div>
</div>
<!-- Top Bar End -->


<!-- ========== Left Sidebar Start ========== -->

<!-- ============================================================== -->
<!-- Start right Content here -->
<!-- ============================================================== -->
<style>
    .sidebar__menu {
        padding: 0;
    }
    .title__headline {
        margin: 0 0 10px;
        text-transform: uppercase;
        font-size: 24px;
    }
    img {
        max-width: 100%;
    }
    a {
        color: #5fbeaa;
    }
    .guide__item {
        margin: 0 0 30px;
    }
    .guide__item h3 {
        font-size: 18px;
    }

</style>
<div class="content-page" style="margin-left: 0;">
<!-- Start content -->
<div class="content">
    <div class="container">
        <div class="guide" style="max-width: 1000px;margin: 0 auto">
            <div class="row">
                <div class="col-sm-12">
                    <div class="card-box">
                        <?= $this->content; ?>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- container -->
</div> <!-- content -->

<footer class="footer text-right">
    © <?= date('Y') ?>. DWEB.VN.
</footer>

</div>


<!-- ============================================================== -->
<!-- End Right content here -->
<!-- ============================================================== -->


<!-- Right Sidebar -->
<div class="side-bar right-bar nicescroll">
    <h4 class="text-center">Chat</h4>
    <div class="contact-list nicescroll">
        <ul class="list-group contacts-list">
            <li class="list-group-item">
                <a href="#">
                    <div class="avatar">
                        <img src="/assets/images/users/avatar-1.jpg" alt="">
                    </div>
                    <span class="name">Chadengle</span>
                    <i class="fa fa-circle online"></i>
                </a>
                <span class="clearfix"></span>
            </li>
        </ul>
    </div>
</div>
<!-- /Right-bar -->

</div>
<!-- END wrapper -->
<script>
    var resizefunc = [];
</script>
<?php
    echo $this->headScript()
        ->prependFile($this->basePath() . '/assets/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js')

        ->prependFile($this->basePath() . '/assets/plugins/bootstrap-select/js/bootstrap-select.min.js')
        ->prependFile($this->basePath() . '/assets/plugins/jquery-knob/jquery.knob.js')
        ->prependFile($this->basePath() . '/assets/plugins/switchery/js/switchery.min.js')
        ->prependFile($this->basePath() . '/assets/plugins/bootstrap-filestyle/js/bootstrap-filestyle.min.js')

        ->prependFile($this->basePath() . '/assets/plugins/raphael/raphael-min.js')

        ->prependFile($this->basePath() . '/assets/plugins/multiselect/js/jquery.multi-select.js')
        ->prependFile($this->basePath() . '/assets/plugins/select2/js/select2.min.js')

        ->prependFile($this->basePath() . '/assets/plugins/counterup/jquery.counterup.min.js')
        ->prependFile($this->basePath() . '/assets/plugins/waypoints/lib/jquery.waypoints.js')

        ->prependFile($this->basePath() . '/assets/plugins/peity/jquery.peity.min.js')
        ->prependFile($this->basePath() . '/assets/plugins/bootstrap-tagsinput/js/bootstrap-tagsinput.min.js')

        ->prependFile($this->basePath() . '/assets/js/jquery.scrollTo.min.js')
        ->prependFile($this->basePath() . '/assets/js/jquery.nicescroll.js')
        ->prependFile($this->basePath() . '/assets/js/wow.min.js')
        ->prependFile($this->basePath() . '/assets/js/waves.js')
        ->prependFile($this->basePath() . '/assets/js/jquery.blockUI.js')
        ->prependFile($this->basePath() . '/assets/js/jquery.slimscroll.js')

        ->prependFile($this->basePath() . '/assets/plugins/autoNumeric/autoNumeric.js')

        ->prependFile($this->basePath() . '/assets/plugins/summernote/lang/summernote-vi-VN.js')
        ->prependFile($this->basePath() . '/assets/plugins/summernote/summernote.min.js')

        ->prependFile($this->basePath() . '/assets/js/fastclick.js')
        ->prependFile($this->basePath() . '/assets/js/detect.js')
        ->prependFile($this->basePath() . '/assets/pages/nestable.js')
        ->prependFile($this->basePath() . '/assets/plugins/nestable/jquery.nestable.js')

        ->prependFile($this->basePath() . '/assets/js/jquery-ui.min.js')
        ->prependFile($this->basePath() . '/assets/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/assets/js/jquery-1.10.1.min.js');

        $js1 = [
            '/assets/plugins/parsleyjs/parsley.min.js',
            '/assets/js/product.js',
            '/assets/js/web/jquery.lazy.min.js',
            '/assets/js/jquery.core.js',
            '/assets/js/jquery.app.js',
            '/assets/pages/jquery.form-advanced.init.js',
            '/assets/js/upload.js',
            '/assets/js/excel/shim.js',
            '/assets/js/excel/jszip.js',
            '/assets/js/excel/xlsx.js',
        ];
        $js2 = [
            '/assets/pages/jquery.option.js',
            '/assets/js/excel/ods.js',
        ];
echo '<script type="text/javascript" src="'.srcLink($js1,5).'"></script>';
echo '<script type="text/javascript" src="'.srcLink($js2,5).'"></script>';
?>

</body>
</html>
