<?php echo $this->doctype(); ?>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Login">
        <meta name="author" content="Mienlv">
        <link rel="shortcut icon" href="assets/images/favicon_1.ico">
        <title>Đăng nhập</title>
        <?php
        echo $this->headLink()
            ->prependStylesheet('/assets/css/pages.css')
            ->prependStylesheet('/assets/css/core.css')
            ->prependStylesheet('/assets/css/components.css')
            ->prependStylesheet('/assets/css/bootstrap.min.css');

        ?>
        <script type="text/javascript" src="/assets/js/jquery-1.10.1.min.js"></script>
    </head>
    <script>
        $(function(){
             var username = $('input[name="username"]');
            $('.signin-page__list li').each(function(){
               var a = $(this).find('a');
                a.click(function(){
                    username.val($(this).text());
                });
            });
        });
    </script>
<body>

<?= $this->content; ?>