<?php
$optionBasic = $this->home()->optionBasic();
$optionPage = $this->home()->optionPage();
$menuOption = $this->home()->getMenu();
?>
<div class="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <?php if(!empty($optionPage['view_footer-1'])):?>
                <ul class="f1">
                    <?php
                    if(!empty($optionPage['view_gioi-thieu'])):
                        ?>
                        <li>
                            <a class="logo" href="/">
                                <?php if(!empty($optionBasic['logo'])): ?>
                                    <img src="<?= $optionBasic['logo'] ?>" alt="<?= !empty($optionBasic['sologan']) ? $optionBasic['sologan']:null ?>" />
                                <?php endif; ?>
                            </a>
                            <div class="footer__content">
                                <?php if(!empty($optionPage['noi-dung-gioi-thieu'])): ?>
                                    <?= $optionPage['noi-dung-gioi-thieu'] ?>
                                <?php endif; ?>
                            </div>
                        </li>
                    <?php endif; ?>
                    <?php if(!empty($optionPage['view_danh-sach-lien-ket-1'])):?>
                        <li>
                            <h3 class="footer__title"><?= $optionPage['tieu-de-danh-sach-lien-ket-1'] ?></h3>
                            <div class="footer__content">
                                <ul>
                                    <?php foreach($menuOption['footer_menu1'] as $m): ?>
                                        <li <?= $url == $m['url'] ? 'class="active"':null ?>><a href="<?= $m['url'] ?>"><?= $m['name'] ?></a>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                        </li>
                    <?php endif;?>
                    <?php if(!empty($optionPage['view_danh-sach-lien-ket-2'])):?>
                        <li>
                            <h3 class="footer__title"><?= $optionPage['tieu-de-danh-sach-lien-ket-2'] ?></h3>
                            <div class="footer__content">
                                <ul>
                                    <?php foreach($menuOption['footer_menu2'] as $m): ?>
                                        <li <?= $url == $m['url'] ? 'class="active"':null ?>><a href="<?= $m['url'] ?>"><?= $m['name'] ?></a>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                        </li>
                    <?php endif;?>
                    <?php if(!empty($optionPage['view_thong-tin-dia-chi'])):?>
                        <li>
                            <h3 class="footer__title"><?= $optionPage['tieu-de-thong-tin'] ?></h3>
                            <div class="footer__content">
                                <?= $optionPage['dia-chi'] ? $optionPage['dia-chi'] : ''?>
                            </div>
                        </li>
                    <?php endif;?>
                </ul>
                <?php endif;?>
                <?php if(!empty($optionPage['view_footer-2'])):?>

                <?php endif;?>
            </div>
        </div>
    </div>
</div>
<?php if(!empty($optionPage['view_copyright'])):?>
    <div class="footer-copyright">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="footer-copyright__inner">
                        <p><?= $optionPage['copyright'] ? $optionPage['copyright'] : ''?></p>

                        <div class="social">
                            <?= !empty($optionPage['facebook']) ? '<li><a href="'.$optionPage['facebook'].'"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>': null ?>
                            <?= !empty($optionPage['instagram']) ? '<li><a href="'.$optionPage['instagram'].'"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>':null ?>
                            <?= !empty($optionPage ['youtube']) ? '<li><a href="'.$optionPage['youtube'].'"><i class="fa fa-youtube" aria-hidden="true"></i></a></li>' : null ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php endif;?>