<?php
    $optionBasic = $this->home()->optionBasic();
    $optionPage = $this->home()->optionPage();
?>

<div class="head">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="head__inner">
                    <div class="logo">
                        <a href="/">
                            <?php if(!empty($optionBasic['logo'])): ?>
                                <img src="<?= $optionBasic['logo'] ?>" alt="Fashion" />
                            <?php endif; ?>
                        </a>
                        <a id="menuMobile">
                            <i class="icon-menu icons" aria-hidden="true"></i>
                        </a>
                    </div>
                    <?php
                    $menuOption = $this->home()->getMenu();
                    if(!empty($menuOption['head_menu'])):
                        ?>
                        <div class="navHome">
                            <ul>
                                <?php foreach($menuOption['head_menu'] as $m): ?>
                                    <li <?= $url == $m['url'] ? 'class="active"':null ?>><a href="<?= $m['url'] ?>"><?= $m['name'] ?></a>
                                        <?php if(!empty($m['children'])): ?>
                                            <ul class="navHome__list">
                                                <?php foreach($m['children'] as $mm): ?>
                                                    <li><a href="<?= $mm['url'] ?>"><?= $mm['name'] ?></a>
                                                        <?php if(!empty($mm['children'])): ?>
                                                            <ul>
                                                                <?php foreach ($mm['children'] as $mcc):?>
                                                                    <li><a href="<?= $mcc['url'] ?>"><?= $mcc['name'] ?></a></li>
                                                                <?php endforeach;?>
                                                            </ul>
                                                        <?php endif;?>
                                                    </li>
                                                <?php endforeach; ?>
                                            </ul>
                                        <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                        <div class="head-top__inner">
                            <ul class="RegisterLogin">
                                <?php
                                if ($this->user()->hasIdentity()) {
                                    ?>
                                    <li><a><?= $this->user()->getUser()->getFullName() ? $this->user()->getUser()->getFullName():ucfirst($this->user()->getUser()->getUserName()) ?></a></li>
                                    <li><a href="/user/signout">Thoát</a></li>
                                    <?php
                                }else{
                                    ?>
                                    <li><a href="/user/signup">Đăng ký</a></li>
                                    <li><a href="/user/signin">Đăng nhập</a></li>
                                    <?php
                                }
                                ?>
                                <?php
                                $cartService = $this->cart()->getServiceCart();
                                $products = $cartService->getProducts();
                                ?>
                                <li><a class="totalCart" href="/cart"><i class="fa fa-shopping-cart" aria-hidden="true"></i><span><?= $cartService->getTotalProducts() ?></span></a></li>
                                <li class="">
                                    <div class="formSearch">
                                        <a class="icon-font icon-magnifier open-search"></a>
                                        <div class="form-search">
                                            <form id="search" action="/search" method="get">
                                                <input type="text" name="q" placeholder="Tìm kiếm ..."/>
                                                <a class="icon-font icon-magnifier" onclick="document.getElementById('search').submit();"></a>
                                                <div id="searchFolding"></div>
                                            </form>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        <div class="navMobile">
                            <ul>
                                <?php
                                foreach ($menuOption['head_menu'] as $m):
                                    ?>
                                    <li>
                                        <?= $m['children'] ? '<button></button>':null ?><a href="<?= $m['url'] ?>"><?= $m['name'] ?></a>
                                        <?php if(!empty($m['children'])): ?>
                                            <ul class="nav2">
                                                <?php foreach($m['children'] as $mm): ?>
                                                    <li <?= $mm['children'] ? 'class="navIsset"':null ?>><?= $mm['children'] ? '<button></button>':null ?><a href="<?= $mm['url'] ?>"><?= $mm['name'] ?></a>
                                                        <?php if(!empty($mm['children'])): ?>
                                                            <ul>
                                                                <?php foreach($mm['children'] as $mmm): ?>
                                                                    <li><a href="<?= $mmm['url'] ?>"><?= $mmm['name'] ?></a></li>
                                                                <?php endforeach; ?>
                                                            </ul>
                                                        <?php endif; ?>
                                                    </li>
                                                <?php endforeach; ?>
                                            </ul>
                                        <?php endif; ?>
                                    </li>
                                <?php endforeach;?>
                            </ul>
                        </div>
                    <?php
                    endif;
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>