<?php
    use Home\Model\DateBase;
    $optionBasic = $this->home()->optionBasic();
    $optionPage = $this->home()->optionPage();
    $homePage = $this->home()->homePage();
    $fileLogo = getimagesize('http://'.$_SERVER['HTTP_HOST'].$optionBasic['logo']);
?>
<?php
    /**** Start SEO DWEB *****/
    echo $this->headLink(['rel' => 'canonical', 'href' => 'http://'.$_SERVER['HTTP_HOST'] ]);
    $this->headTitle($this->escapeHtml($this->translate(!empty($optionBasic['metaTitle']) ? $optionBasic['metaTitle']:$optionBasic['sologan'])));
    $this->headMeta()->appendName('description', (!empty($optionBasic['metaDescription']) ? $optionBasic['metaDescription']:null));
    $this->headMeta()->appendName('keywords', (!empty($optionBasic['metaKeyword']) ? $optionBasic['metaKeyword']:null));
    $this->headMeta()->appendProperty('og:title', !empty($optionBasic['metaTitle']) ? $optionBasic['metaTitle']:$optionBasic['sologan']);
    $this->headMeta()->appendProperty('og:description', !empty($optionBasic['metaDescription']) ? $optionBasic['metaDescription']:null);
    $this->headMeta()->appendProperty('og:image', !empty($optionBasic['logo']) ? 'http://'.$_SERVER['HTTP_HOST'].$optionBasic['logo']:null);
    $this->headMeta()->appendProperty('og:image:secure_url', !empty($optionBasic['logo']) ? 'http://'.$_SERVER['HTTP_HOST'].$optionBasic['logo']:null);
    $this->headMeta()->appendProperty('og:image:width', $fileLogo['0']);
    $this->headMeta()->appendProperty('og:image:height', $fileLogo['1']);
    $this->headMeta()->appendProperty('og:type', 'Website');
    $this->headMeta()->appendProperty('og:url', 'http://'.$_SERVER['HTTP_HOST']);
    $this->headMeta()->appendProperty('og:site_name', $optionBasic['sologan']);

    $this->headMeta()->appendName('twitter:card', !empty($optionBasic['logo']) ? 'http://'.$_SERVER['HTTP_HOST'].$optionBasic['logo']:'summary_large_image');
    $this->headMeta()->appendName('twitter:title', !empty($optionBasic['metaTitle']) ? $optionBasic['metaTitle']:null);
    $this->headMeta()->appendName('twitter:description', (!empty($optionBasic['metaDescription']) ? $optionBasic['metaDescription']:null));
    $this->headMeta()->appendName('twitter:image', !empty($optionBasic['logo']) ? 'http://'.$_SERVER['HTTP_HOST'].$optionBasic['logo']:null);
    /**** End SEO DWEB *****/
?>
<?php
if(!empty($homePage)):
    $count = 0;
    foreach($homePage as $k => $v ):
        $layout = explode(' ',$k);
        switch ($layout[0]) {
            case "slider-layout":
                echo $this->partial('home/template/slider', ['bannerList' => $v]);
                break;
            case "product-layout":
                echo $this->partial('home/template/product-layout', ['productLayout' => $v]);
                break;
            case "option-layout":
                echo $this->partial('home/template/option-layout', ['optionLayout' => $v]);
                break;
            case "news-layout":
                echo $this->partial('home/template/news-layout', ['newsLayout' => $v]);
                break;
            case "small-banner-layout":
                echo $this->partial('home/template/small-banner-layout', ['smallBannerList' => $v]);
                break;
            case "html-layout":
                echo $this->partial('home/template/html-layout', ['htmlLayout' => $v]);
                break;
            case "tab-product-layout":
                $count++;
                echo $this->partial('home/template/tab-product-layout', ['tabProductLayout' => $v, 'id' => $count]);
                break;
            case "image-layout":
                echo $this->partial('home/template/image-layout', ['imageLayout' => $v]);
                break;
            default:
                break;
        }
    endforeach;
else:

?>
    <div class="main">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <?php if(!empty($optionPage['view_banner'])): ?>
                    <ul class="banner owl-carousel owl-theme">
                        <?php
                        if(!empty($optionPage['banner'])):
                            foreach($optionPage['banner'] as $b):
                            $image = json_decode($b['image'], true);
                            if(!empty($image)){
                                $imageFirst = array_shift($image);
                            }
                        ?>
                        <li>
                            <a>
                                <figure class="lazy banner-image" data-src="<?= !empty($imageFirst) ? $imageFirst:null ?>"></figure>
                            </a>
                        </li>
                        <?php endforeach; endif; ?>
                    </ul>
                    <?php endif; ?>

                    <?php if(!empty($optionPage['view_3-banner-nho'])): ?>
                    <?php if(!empty($optionPage['3-banner-nho'])): ?>
                    <div class="feature2">
                        <?php
                            $i = 0;
                            foreach($optionPage['3-banner-nho'] as $b):
                            $i++;

                            $image = json_decode($b['image'], true);
                            if(!empty($image)){
                                $imageFirst = array_shift($image);
                            }
                            if($i == 1):
                        ?>
                        <div class="w40">
                            <figure class="lazy banner-image10" data-src="<?= !empty($imageFirst) ? $imageFirst:null ?>">
                                <div>
                                    <h3><?= $b['title'] ?></h3>
                                    <p><?= $b['description'] ?></p>
                                    <a href="<?= $b['url'] ?>">Xem</a>
                                </div>
                            </figure>
                        </div>
                        <?php endif; ?>
                        <?php endforeach; ?>


                        <div class="w60">
                            <?php
                                $i = 0;
                                foreach($optionPage['3-banner-nho'] as $b):
                                $i++;
                                $image = json_decode($b['image'], true);
                                if(!empty($image)){
                                    $imageFirst = array_shift($image);
                                }
                                if($i > 1):
                            ?>
                            <figure class="lazy banner-image5" data-src="<?= !empty($imageFirst) ? $imageFirst:null ?>">
                                <div>
                                    <h3><?= $b['title'] ?></h3>
                                    <a href="<?= $b['url'] ?>">Xem</a>
                                </div>
                            </figure>
                            <?php endif; ?>
                            <?php endforeach; ?>
                        </div>
                    </div>
                    <?php endif; ?>
                    <?php endif;?>
                </div>
            </div>
        </div>
    </div>
<?php endif;?>