<?php
if(!empty($this->newsLayout['news-list article']['news-list'])):?>
<section class="news-slider">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <?= $this->newsLayout['news-title text']['value']
                    ? '<h2 class="headline-default news__headline">'
                        . $this->newsLayout['news-title text']['value']
                        . '</h2>'
                    : '' ?>
                <?= $this->newsLayout['news-sub-title text']['value'] ? '<div class="four-post__intro"><span>'.$this->newsLayout['news-sub-title text']['value'].'</span></div>':'' ?>
                <div class="news__inner">
                    <ul class="news__slider owl-carousel owl-theme">
                        <?php foreach($this->newsLayout['news-list article']['news-list'] as $k => $n):
                            $imageFirst = '';
                            $i = json_decode($n['image'], true);
                            if(is_array($i) && !empty($i)) {
                                $imageFirst = array_shift($i);
                            }
                            ?>
                            <li class="news__item">
                                <div class="news-item__inner">
                                    <figure class="news__image owl-lazy" data-src="<?= $imageFirst ?>">
                                        <a class="news-image__inner" href="<?= $n['url'] ?>">
                                            <h3 class="news__title">
                                                <?= $n['title'] ?>
                                            </h3>
                                            <p class="news__intro">
                                                <?= $n['intro'] ?>
                                            </p>
                                        </a>
                                    </figure>
                                </div>
                            </li>
                        <?php endforeach;?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
<?php endif;?>