<?php
echo $this->doctype();
$optionBasic = $this->home()->optionBasic();
$optionPage = $this->home()->optionPage();
?>
<html lang="vi">
    <head>
        <?php
            echo $this->headTitle()->setSeparator(' | ')->setAutoEscape(false);
            $this->headMeta()->appendName('DC.language', 'scheme=utf-8 content=vi');
            $this->headMeta()->appendName('author', 'DWEB.VN');
            $this->headMeta()->appendName('format-detection', 'telephone=no');
            $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1, maximum-scale=1');
            echo $this->headMeta();
            echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $optionBasic['favicon'] ? $optionBasic['favicon']:null ]);
        ?>

        <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,600" rel="stylesheet">
        <link href='https://fonts.googleapis.com/css?family=Roboto:300,500,700' rel='stylesheet' type='text/css'>

        <?php
            $cs = [
                '/tp/dweb_v2/css/bootstrap.css',
                '/tp/dweb_v2/css/font-awesome.min.css',
                '/tp/dweb_v2/css/animate.min.css',
                '/tp/dweb_v2/css/a.css',
//                '/tp/dweb_v2/css/modal-video.min.css',
                '/assets/css/icons.css',
                '/tp/dweb_v2/css/r.css',
                '/tp/dweb_v2/css/demo.css',
//                '/assets/css/web/owl.carousel.css',
//                '/assets/css/web/owl.theme.css',
//                '/assets/css/web/owl.transitions.css',
//                '/assets/css/components.css',
            ];
            echo '<link href="'.srcLink($cs,6).'" media="screen" rel="stylesheet" type="text/css">';
            $js = [
                '/assets/js/web/jquery-1.11.2.min.js',
            ];
            echo '<script type="text/javascript" src="'.srcLink($js,2).'"></script>';
        ?>

    </head>
    <?php
        $url = $this->UriParams()->getRequest()->getRequestUri();
        $url2 = $this->home()->getMcaName('action');
        $classPage = substr($url, 1, -5);
    ?>
    <body class="demo">
        <?php
            echo $this->render('layout/header_demo');
            echo $this->content;
            echo $this->render('layout/footer_demo');
        ?>
    </body>
    <?php
        $cs = [
            '/tp/dweb_v2/css/r.css',
        ];
        echo '<link href="'.srcLink($cs,3).'" media="screen" rel="stylesheet" type="text/css">';
        $js = [
//            '/tp/dweb/js/jquery-1.10.1.min.js',
            '/tp/dweb_v2/js/bootstrap.min.js',
            '/assets/js/web/jquery.lazy.min.js',
//            '/assets/js/web/owl.carousel.js',
//            '/tp/dweb_v2/js/waypoint/jquery.waypoints.min.js',
            '/tp/dweb_v2/js/a_demo.js',
//            '/tp/dweb_v2/js/a_created.js',
//            '/tp/dweb_v2/js/hero-slider/TweenLite.min.js',
//            '/tp/dweb_v2/js/hero-slider/rAF.js',
//            '/tp/dweb_v2/js/hero-slider/EasePack.min.js',
//            '/tp/dweb_v2/js/hero-slider/demo-1.js',
//            '/tp/dweb_v2/js/jquery-modal-video.min.js',
            '/assets/plugins/parsleyjs/parsley.min.js',
            '/tp/dweb_v2/js/form.js',

        ];
        echo '<script type="text/javascript" src="'.srcLink($js,8).'"></script>';
    ?>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-137920625-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-137920625-1');
    </script>

</html>