<?php
$optionPage = $this->home()->optionPage();
?>

<div id="modalRegisterDWEB" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <form class="contactForm registerForm storeRegister" method="post" enctype="multipart/form-data" data-parsley-validate="" novalidate="">
                <h2 class="register__title">Dùng thử website DWEB</h2>
                <h4>Miễn phí 15 ngày với đầy đủ tính năng</h4>
                <div class="form-group">
                    <div>
                        <input type="text" name="store" class="" data-parsley-minlength="3" data-parsley-pattern="^[a-z0-9_-]{4,32}$" placeholder="Tên doanh nghiệp" required="required" data-parsley-error-message="Tên doanh nghiệp không hợp lệ" value="">
                        <span class="labelDWEB"><?= '.'.$_SERVER['HTTP_HOST'] ?></span>
                    </div>
                </div>
                <div class="form-group">
                    <div>
                        <input type="text" name="phone" class="" data-parsley-type="digits" data-parsley-length="[10,11]" placeholder="Số điện thoại" required="required" data-parsley-error-message="Số điện thoại không được để trống" value="">
                    </div>
                </div>
                <div class="form-group">
                    <div>
                        <input type="text" name="email" class="" data-parsley-type="email" placeholder="Email" required="required" data-parsley-error-message="Email không được để trống" value="">
                    </div>
                </div>
                <div class="form-group">
                    <div>
                        <input type="password" name="password" class="" data-parsley-minlength="6" placeholder="Password" required="required" data-parsley-error-message="Password không được để trống" value="">
                    </div>
                </div>
                <div class="form-group">
                    <div class="select-custom">
                        <select name="service" required="required">
                            <option>Lĩnh vực kinh doanh</option>
                            <option value="f001">Thời trang</option>
                            <option value="a011">Bất động </option>
                            <option value="a005">Giới thiệu công ty</option>
                            <option value="mp001">Mỹ phẩm - Làm đẹp</option>
                            <option value="tp001">Ẩm thực - Ăn uống</option>
                            <option value="t005">Mẹ và bé</option>
                            <option value="t001">Siêu thị nhiều mặt hàng</option>
                            <option value="t003">Công nghệ</option>
                            <option value="a009">Tin tức - bài viết</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <div>
                        <button type="submit">Đăng ký</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<div id="modalGlobal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <input type="hidden" value="" />
            <p>Lưu ý khi đổi giao diện dữ liệu trang chủ không phù hợp với giao diện mới, nên website không còn dữ liệu,
                bạn có thể cập nhật <a href="/admin/setup/template">tại đây</a></p>
            <a class="button-change-template">Chấp nhận</a>
        </div>
    </div>
</div>


<div id="chooseTheme" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <input type="hidden" class="themeId" value="" />
            <p>Hoàn tất đăng ký website.</p>
            <a class="button-choose-template">Đồng ý</a>
        </div>
    </div>
</div>

<footer class="footer">
    <div class="footer__one">
        <div class="container">
            <div class="footer__inner">
                <div class="footer__row">
                    <div class="footer__logo header-sologan"><span class="logo-first-key">D</span>WEB.</div>
                    <div class="footer__caption">
                        DWEB là nền tảng tạo website chuẩn seo miễn phí, chúng tôi cung cấp và cập nhật những checklist của một website chuẩn Google để tích hợp vào những website, giúp doanh nghiệp có thể tạo ra những website tối ưu hiệu quả nhất. Ngay từ bây giờ bạn có thể tạo website miễn phí <a target="_blank" href="/created">tại đây</a>
                    </div>
                    <div class="footer__title">Liên hệ</div>
                    <div class="footer__address">
                        <div class="footer__address--item">
                            <div class="icon"><i class="fa fa-map-marker"></i></div>
                            <div class="c-details">Hà Nội: Tầng 3, 34 Hoàng Cầu, Toà nhà viễn đông, Hà Nội</div>
                        </div>
                        <div class="footer__address--item">
                            <div class="icon"><i class="fa fa-map-marker"></i></div>
                            <div class="c-details">TP Hồ Chí Minh: Lầu 16 Tòa nhà Havana, 132 Hàm Nghi, phường Bến Nghé, TP HCM</div>
                        </div>

                        <div class="footer__address--item">
                            <div class="icon"><i class="fa fa-envelope"></i></div>
                            <div class="c-details"><a href="mailto:contact@dweb.vn">contact@dweb.vn</a></div>
                        </div>
                    </div>
                    <ul class="footer__social">
                        <li><a href=""><i class="fa fa-facebook"></i></a></li>
                        <li><a href=""><i class="fa fa-google-plus"></i></a></li>
                    </ul>
                </div>
                <div class="footer__row">
                    <div class="footer__title">Chia sẻ</div>
                    <ul class="footer__nav">
                        <li><a href="https://blog.dweb.vn" target="_blank">Blog chia sẻ</a></li>
                        <li><a href="http://tool.dweb.vn" target="_blank">Kiểm tra website chuẩn seo</a></li>
                        <?php if(!empty($optionPage['chia-se'])): ?>
                            <?php echo $optionPage['chia-se']; else: ?>
                            <li><a href="https://blog.dweb.vn/viet-bai-chuan-seo-2019.html" target="_blank">Cách viết bài chuẩn seo</a></li>
                            <li><a href="https://blog.dweb.vn/kiem-tra-website-chuan-seo.html" target="_blank">Thế nào là website chuẩn SEO</a></li>
                            <li><a href="https://blog.dweb.vn/chien-luoc-noi-dung-website.html" target="_blank">Phân tích tổng thể nội dung website</a></li>
                            <li><a target="_blank" href="/thiet-ke-website-chuan-seo.html">Thiết kế website chuẩn seo</a></li>
                            <li><a target="_blank" href="https://dweb.vn/quan-tri-website-chuyen-nghiep.html">Dịch vụ quản trị website</a></li>
                            <li><a target="_blank" href="https://dweb.vn/dich-vu-seo.html">Dịch vụ SEO</a></li>
                            <li><a target="_blank" href="/thiet-ke-website-gia-re.html">Thiết kế website giá rẻ</a></li>
                        <?php endif; ?>
                    </ul>
                </div>
                <div class="footer__row">
                    <div class="footer__title">Giao diện</div>
                    <?php $theme = $this->NewsCategory()->featchTreeCategory(20); ?>
                    <ul class="footer__nav">
                        <?php $url = $this->UriParams()->getRequest()->getRequestUri(); ?>
                        <?php if(!empty($theme)): ?>
                            <?php foreach($theme as $t): ?>
                                <li><a <?= $url == $t->getViewLink() ? 'class="active"':null ?> href="<?= $t->getViewLink() ?>"><?= $t->getName() ?></a></li>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </ul>
                </div>

            </div>
        </div>
    </div>
    <div class="footer__two">
        <div class="container">
            <div class="footer__copyright">Công ty cổ phần công nghệ <a href="http://dweb.vn"> DTT</a> Việt Nam. Địa chỉ: Tầng 3, 36 Hoàng Cầu, toà nhà viễn đông, Hà Nội</div>
        </div>
    </div>
</footer>