<?php
    $optionPage = $this->home()->optionPage();
?>

<div id="modalRegisterDWEB" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <form class="contactForm registerForm storeRegister" method="post" enctype="multipart/form-data" data-parsley-validate="" novalidate="">
                <h2 class="register__title">Dùng thử website DWEB</h2>
                <h4>Miễn phí 15 ngày với đầy đủ tính năng</h4>
                <div class="form-group">
                    <div>
                        <input type="text" name="store" class="" data-parsley-minlength="3" data-parsley-pattern="^[a-z0-9_-]{4,32}$" placeholder="Tên doanh nghiệp" required="required" data-parsley-error-message="Tên doanh nghiệp không hợp lệ" value="">
                        <span class="labelDWEB"><?= '.'.$_SERVER['HTTP_HOST'] ?></span>
                    </div>
                </div>
                <div class="form-group">
                    <div>
                        <input type="text" name="phone" class="" data-parsley-type="digits" data-parsley-length="[10,11]" placeholder="Số điện thoại" required="required" data-parsley-error-message="Số điện thoại không được để trống" value="">
                    </div>
                </div>
                <div class="form-group">
                    <div>
                        <input type="text" name="email" class="" data-parsley-type="email" placeholder="Email" required="required" data-parsley-error-message="Email không được để trống" value="">
                    </div>
                </div>
                <div class="form-group">
                    <div>
                        <input type="password" name="password" class="" data-parsley-minlength="6" placeholder="Password" required="required" data-parsley-error-message="Password không được để trống" value="">
                    </div>
                </div>
                <div class="form-group">
                    <div class="select-custom">
                        <select name="service" required="required">
                            <option>Lĩnh vực kinh doanh</option>
                            <option value="f001">Thời trang</option>
                            <option value="a011">Bất động </option>
                            <option value="a005">Giới thiệu công ty</option>
                            <option value="mp001">Mỹ phẩm - Làm đẹp</option>
                            <option value="tp001">Ẩm thực - Ăn uống</option>
                            <option value="t005">Mẹ và bé</option>
                            <option value="t001">Siêu thị nhiều mặt hàng</option>
                            <option value="t003">Công nghệ</option>
                            <option value="a009">Tin tức - bài viết</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <div>
                        <button type="submit">Đăng ký</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<footer class="footer">
    <div class="footer__one">
        <div class="container">
            <div class="footer__inner">
                <div class="footer__row">
                    <h2 class="footer__logo header-sologan"><span class="logo-first-key">D</span>WEB.</h2>
                    <div class="footer__caption">DWEB được viết tắt trong từ Difference Web, chúng tôi áp dụng những kỹ năng, sự khéo léo và tỉ mỉ đến từng dự án và phấn đấu để cung cấp giải pháp thiết kế sáng tạo, luôn muốn mang đến sự trải nghiệm khách hàng trong những sản phẩm mà chúng tôi tạo nên</div>
                </div>
                <div class="footer__row">
                    <h2 class="footer__title">Chia sẻ</h2>
                    <ul class="footer__nav">
                        <?php if(!empty($optionPage['chia-se'])): ?>
                            <?php echo $optionPage['chia-se']; else: ?>
                            <li><a href="/thiet-ke-web-gia-re-n356.html">Thiết kế web giá rẻ</a></li>
                            <li><a href="#">Ý kiến khách hàng</a></li>
                            <li><a href="#">Tuyển dụng DWEB</a></li>
                            <li><a href="#">Quy định sử dụng</a></li>
                            <li><a href="#">Chính sách bảo mật</a></li>
                            <li><a href="#">Liên hệ</a></li>
                        <?php endif; ?>
                    </ul>
                </div>
                <div class="footer__row">
                    <h2 class="footer__title">Giao diện</h2>
                    <?php $theme = $this->NewsCategory()->featchTreeCategory(20); ?>
                    <ul class="footer__nav">
                        <?php $url = $this->UriParams()->getRequest()->getRequestUri(); ?>
                        <?php if(!empty($theme)): ?>
                            <?php foreach($theme as $t): ?>
                                <li><a <?= $url == $t->getViewLink() ? 'class="active"':null ?> href="<?= $t->getViewLink() ?>"><?= $t->getName() ?></a></li>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </ul>
                </div>
                <div class="footer__row">
                    <h2 class="footer__title">Dịch vụ</h2>
                    <ul class="footer__nav">
                        <li><a href="#">Đăng ký tên miền</a></li>
                        <li><a href="#">Dịch vụ email</a></li>
                        <li><a href="#">Quảng cáo Google Adwords</a></li>
                        <li><a href="#">Quảng cáo facebook</a></li>
                        <li><a href="#">Thiết kế web đa ngành</a></li>
                    </ul>
                </div>

            </div>
        </div>
    </div>
    <div class="footer__two">
        <div class="container">
            <div class="footer__copyright">© Copyright <?= date('Y') ?>. All rights reserved. Công ty cổ phần công nghệ <a href=""> DWEB</a> Việt Nam. Địa chỉ: Tầng 4, 36 Hoàng Cầu, toà nhà viễn đông, Hà Nội</div>
        </div>
    </div>
</footer>