<?php $url = $this->UriParams()->getRequest()->getRequestUri(); ?>

<header class="header">
    <div class="container header-container">
        <div class="header-inner">
            <div class="header-logo">
                <a href="/"><<?= $url == '/' ? 'h1':'h2' ?> class="header-sologan" title="DWEB nền tảng website chuẩn seo của SEONGON"><span class="logo-first-key">D</span>WEB.</<?= $url == '/' ? 'h1':'h2' ?>></a>
            </div>
            <div class="header-nav">
                <ul>
                    <li><a href="/" <?= $url == '/' ? 'class="active"':null ?>>Trang chủ</a></li>
                    <li><a <?= $url == '/bang-gia.html' ? 'class="active"':null ?> href="/bang-gia.html">Bảng giá</a></li>
                    <li><a <?= $url == '/kho-giao-dien.html' ? 'class="active"':null ?> href="/kho-giao-dien.html">Kho giao diện</a></li>
                    <li><a <?= $url == '/blog.html' ? 'class="active"':null ?> href="http://blog.dweb.vn">Blog</a></li>
                    <li><a <?= $url == '/lien-he.html' ? 'class="active"':null ?> href="/lien-he.html">Liên hệ</a></li>
                    <?php if ($this->user()->hasIdentity()): ?>
                        <li><a class="button-login" href="/admin">Quản lý</a></li>
                    <?php else: ?>
                        <li><a class="button-login" href="/admin">Đăng nhập</a></li>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
    </div>
</header>