<?php
    $optionPage = $this->home()->optionPage();
    $menuOption = $this->home()->getMenu();
?>
<div class="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <ul class="f2">
                    <?php if(!empty($optionPage['view_cot-thong-tin-footer-1'])): ?>
                    <li>
                        <h3><?= $optionPage['tieu-de-cot-thong-tin-1'] ? $optionPage['tieu-de-cot-thong-tin-1'] : '' ?></h3>
                        <?= $optionPage['noi-dung-cot-thong-tin-1'] ? $optionPage['noi-dung-cot-thong-tin-1'] : '' ?>
                    </li>
                    <?php endif; ?>
                    <?php if(!empty($optionPage['view_cot-thong-tin-footer-2'])):?>
                        <li>
                            <h3><?= $optionPage['tieu-de-cot-thong-tin-2'] ? $optionPage['tieu-de-cot-thong-tin-2'] : '' ?></h3>
                            <?php if(!empty($menuOption['footer_menu'])):?>
                            <ul>
                                <?php foreach ($menuOption['footer_menu'] as $m):?>
                                    <li><a href="<?= $m['url']?>"><?= $m['name']?></a></li>
                                <?php endforeach;?>
                            </ul>
                            <?php endif;?>
                        </li>
                    <?php endif; ?>
                    <?php if(!empty($optionPage['view_cot-thong-tin-footer-3'])):?>
                        <li>
                            <div class="social">
                                <h3><span><?= $optionPage['tieu-de-cot-thong-tin-3'] ? $optionPage['tieu-de-cot-thong-tin-3'] : ''?></span></h3>
                                <?= $optionPage['facebook'] ? '<a class="fb" href="'.$optionPage['facebook'].'"></a>' : ''?>
                                <?= $optionPage['google'] ? '<a class="gg" href="'.$optionPage['google'].'"></a>' : ''?>
                                <?= $optionPage['pinterest'] ? '<a class="pt" href="'.$optionPage['pinterest'].'"></a>' : ''?>
                                <?= $optionPage['instagram'] ? '<a class="it" href="'.$optionPage['instagram'].'"></a>' : ''?>
                                <?= $optionPage['youtube'] ? '<a class="yt" href="'.$optionPage['youtube'].'"></a>' : ''?>
                            </div>
                        </li>
                    <?php endif;?>
                </ul>
            </div>
        </div>
    </div>
</div>