<?php
    $view = $this->news;
    $current_page_URL = $_SERVER["SERVER_NAME"] . $_SERVER["REQUEST_URI"];
?>

<div class="gallery">
    <div class="gallery__inner">
        <div class="gallery__left">
            <?php
                $image = json_decode($view->getImage(), true);
                if(!empty($image)):
            ?>
                <ul class="gallery__slider owl-carousel owl-theme">
                    <?php foreach ($image as $i): ?>
                    <li><figure class="gallery__image" style="background-image: url(<?= $i ?>)"></figure></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </div>
        <div class="gallery__right">
            <h1 class="gallery__title"><?= $view->getTitle() ?></h1>
            <div class="gallery__content">
                <?php echo $view->getContent(); ?>
            </div>
            <div class="social">
                <div style="float: left;margin: 0 5px 0 0;" class="fb-like" data-href="<?= $current_page_URL.$view->getViewLink() ?>" data-layout="button" data-action="like" data-show-faces="false" data-share="true"></div>
                <div class="g-plusone" data-size="medium"></div>
            </div>
            <script src="https://apis.google.com/js/platform.js" async defer>
                {lang: 'vi'}
            </script>
        </div>
    </div>
</div>