<?php
    $paginator = $this->paginator;
    $paginator->setItemCountPerPage($this->uriParams()->getRequest()->getQuery('icpp') ? : 12);
    $cs = [
        '/tp/A014/css/n.css'
    ];
    echo '<link href="'.srcLink($cs,1).'" media="screen" rel="stylesheet" type="text/css">';
    $optionPage = $this->home()->optionPage();
    $optionBasic = $this->home()->optionBasic();
    $menuOption = $this->home()->getMenu();
?>
<?php
/**** Start SEO DWEB *****/
    $this->headTitle($this->escapeHtml($this->translate('Danh sách tin tức')));
    $this->headMeta()->appendName('description', ('Danh sách tin tức'));
    $this->headMeta()->appendName('keywords', ('Danh sách tin tức'));
    $this->headMeta()->appendProperty('og:title', 'Danh sách tin tức');

    $this->headMeta()->appendProperty('og:description', 'Danh sách tin tức');
    $this->headMeta()->appendProperty('og:image', '');
    $this->headMeta()->appendProperty('og:image:secure_url', '');
    $this->headMeta()->appendProperty('og:image:width', '');
    $this->headMeta()->appendProperty('og:image:height', '');
    $this->headMeta()->appendProperty('og:type', 'Page');
    $this->headMeta()->appendProperty('og:url', 'http://'.$_SERVER['HTTP_HOST'].'/bai-viet.html');
    $this->headMeta()->appendProperty('og:site_name', $optionBasic['sologan']);

    $this->headMeta()->appendName('twitter:card', '');
    $this->headMeta()->appendName('twitter:title', 'Danh sách tin tức');
    $this->headMeta()->appendName('twitter:description', 'Danh sách tin tức');
    $this->headMeta()->appendName('twitter:image', '');
/**** End SEO DWEB *****/
?>
<div class="page-news">
    <div class="container">
        <div class="row">
            <?php
                if(!empty($menuOption['news_sidebar']) || !empty($optionPage['view_danh-muc-sidebar-1']) || !empty($optionPage['view_danh-muc-sidebar-2']) || !empty($optionPage['view_banner-sidebar'])):
                    echo '<div class="col-md-8">';
                else:
                    echo '<div class="col-md-12">';
                endif;
            ?>
                <?php
                if(count($paginator)){
                    $n = $this->newsCategory()->getCategories();
                    ?>
                    <h1 class="title-page">Tin tức</h1>
                    <div class="post-last__list post-last__list--category">
                        <?php
                        foreach($paginator as $n):
                            $extraContent = json_decode($n->getExtracontent(), true);

                            $image = json_decode($n->getImage(), true);
                            $imageFirst = '';
                            if(!empty($image)){
                                $imageFirst = array_shift($image);
                            }
                            ?>
                            <div class="post-last__item">
                                <div class="post-last__item--inner">
                                    <div class="post-last__left">
                                        <a href="<?= $n->getViewLink(); ?>">
                                            <figure class="post-last__image lazy" data-src="<?= $imageFirst ?>"></figure>
                                        </a>
                                    </div>
                                    <div class="post-last__content">
                                        <h3 class="post-last__title"><a href="<?= $n->getViewLink() ?>" title="<?=$n->getTitle();?>"><?=$n->getTitle()?></a>
                                        </h3>
                                        <div class="post-last__intro">
                                            <?php
                                            $s = substr($n->getDescription(),0,300);
                                            $rs = substr($s,0,strrpos($s, ' '));
                                            if(strlen($n->getDescription()) > 300):
                                                echo $rs;
                                                echo '...';
                                            else:
                                                echo $n->getDescription();
                                            endif;

                                            ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>

                    <?php
                    echo '<div class="category__paginator">';
                    echo $this->paginationControl($this->paginator, 'Elastic', 'partial/listPage');
                    echo '</div>';
                }
                ?>
            </div>
        <?php
        if(!empty($menuOption['news_sidebar']) || !empty($optionPage['view_danh-muc-sidebar-1']) || !empty($optionPage['view_danh-muc-sidebar-2']) || !empty($optionPage['view_banner-sidebar'])){
            echo $this->render('layout/sidebar');
        }?>
        </div>
    </div>
</div>
