<?php
$optionBasic = $this->home()->optionBasic();
$url = $this->UriParams()->getRequest()->getRequestUri();
?>
<div class="head">
    <div class="container">
        <div class="row">
            <div class="col-sm-5">
                <a id="menuMobile">
                    <i class="icon-menu icons" aria-hidden="true"></i>
                </a>
                <?php
                $menuOption = $this->home()->getMenu();
                if(!empty($menuOption['head_menu'])):

                    ?>
                    <div class="navHome">
                        <?php
                        $menuOption = $this->home()->getMenu();
                        if(!empty($menuOption['head_menu'])) {
                            ?>
                            <ul>
                                <?php
                                if(!empty($menuOption['head_menu'])){
                                    $c = 0;
                                    foreach($menuOption['head_menu'] as $m){
                                        $c++;
                                        if($c == 4){
                                            break;
                                        }
                                        ?>
                                        <li>
                                        <a href="<?= $m['url'] ?>"><?= $m['name'] ?></a>
                                        <?php
                                        if($m['children']){
                                            echo '<div>';
                                            echo '<ul class="nav3">';
                                            foreach($m['children'] as $mc){
                                                ?>
                                                <li><a href="<?= $mc['url'] ?>"><?= $mc['name'] ?></a>
                                                <?php
                                                if($mc['children']){
                                                    echo '<ul>';
                                                    foreach($mc['children'] as $mcc){
                                                        ?>
                                                        <li><a href="<?= $mcc['url'] ?>"><?= $mcc['name'] ?></a>
                                                        <?php
                                                    }
                                                    echo '</ul>';
                                                }
                                                ?>
                                                </li>
                                                <?php
                                            }
                                            echo '</div>';
                                        }
                                        ?>
                                        </li>
                                        <?php
                                    }
                                }
                                ?>
                            </ul>
                        <?php } ?>
                    </div>
                    <div class="navMobile">
                        <ul>
                            <?php
                            foreach ($menuOption['head_menu'] as $m):
                                ?>
                                <li>
                                    <?= $m['children'] ? '<button></button>':null ?><a href="<?= $m['url'] ?>"><?= $m['name'] ?></a>
                                    <?php if(!empty($m['children'])): ?>
                                        <ul class="nav2">
                                            <?php foreach($m['children'] as $mm): ?>
                                                <li <?= $mm['children'] ? 'class="navIsset"':null ?>><?= $mm['children'] ? '<button></button>':null ?><a href="<?= $mm['url'] ?>"><?= $mm['name'] ?></a>
                                                    <?php if(!empty($mm['children'])): ?>
                                                        <ul>
                                                            <?php foreach($mm['children'] as $mmm): ?>
                                                                <li><a href="<?= $mmm['url'] ?>"><?= $mmm['name'] ?></a></li>
                                                            <?php endforeach; ?>
                                                        </ul>
                                                    <?php endif; ?>
                                                </li>
                                            <?php endforeach; ?>
                                        </ul>
                                    <?php endif; ?>
                                </li>
                            <?php endforeach;?>
                        </ul>
                    </div>
                    <?php
                endif;
                ?>
            </div>

            <div class="col-sm-2">
                <div class="logo">
                    <a href="/">
                        <?php if(!empty($optionBasic['logo'])): ?>
                        <img src="<?= $optionBasic['logo'] ?>" alt="Fashion" />
                        <?php endif; ?>
                    </a>
                </div>
            </div>

            <div class="col-sm-5">
                <div class="navTool">
                    <div class="formSearch">
                        <a class="icon-font icon-magnifier open-search"></a>
                        <div class="form-search">
                            <form id="search" action="/search" method="get">
                                <input type="text" name="q" placeholder="Tìm kiếm ..."/>
                                <a class="icon-font icon-magnifier" onclick="document.getElementById('search').submit();"></a>
                                <div id="searchFolding"></div>
                            </form>
                        </div>
                    </div>
                    <div class="user">
                        <a class="icon-font icon-user"></a>
                        <ul class="account">
                            <?php
                            if ($this->user()->hasIdentity()) {
                                ?>
                                <li>
                                    <a href="/admin"><i class="icon-user icons"></i>Xin chào: <?= $this->user()->getUser()->getFullName() ? $this->user()->getUser()->getFullName():ucfirst($this->user()->getUser()->getUserName()) ?></a>
                                </li>
                                <li>
                                    <a href="/user/signout"><i class="icon-logout icons"></i>Thoát</a>
                                </li>
                                <?php
                            }else{
                                ?>
                                <li><a href="/user/signup"><i class="icon-login icons"></i>Đăng ký</a></li>
                                <li><a href="/user/signin"><i class="icon-user-follow icons"></i>Đăng nhập</a></li>
                                <?php
                            }
                            ?>
                        </ul>
                    </div>
                    <?php
                        $cartService = $this->cart()->getServiceCart();
                        $products = $cartService->getProducts();
                    ?>
                    <div class="cart">
                        <a class="icon-font icon-basket" href="/cart"><span><?= $cartService->getTotalProducts() ?></span></a>
                        <a href="/cart"><span><?= number_format($cartService->getTotalMoney()) ?> đ</span></a>
                    </div>
                </div>
            </div>

        </div>

    </div>
</div>
