<?php
$view = $this->page;
/***** sample Label:type:key endsample ****/
/***** Page Template: Liên hệ

/******* Vi du lay key "iframe" *********/
    $field = json_decode($view->getExtraContent(), true);

$view = $this->page;
$imageFirst = '';
if(!empty(json_decode($view->getImage(), true))){
    $imageFirst = array_shift(json_decode($view->getImage(), true));
}
$optionBasic = $this->home()->optionBasic();
$image = 'http://'.$_SERVER['HTTP_HOST'].$imageFirst;
?>

<?php
$imageInfo = getimagesize($image);
/**** Start SEO DWEB *****/
echo $this->headLink(['rel' => 'canonical', 'href' => 'http://'.$_SERVER['HTTP_HOST'].$view->getViewLink() ]);
$this->headTitle($this->translate(!empty($view->getMetaTitle()) ? $view->getMetaTitle():$view->getName()));
$this->headMeta()->appendName('description', (!empty($view->getMetaDescription()) ? $view->getMetaDescription():null));
$this->headMeta()->appendName('keywords', (!empty($view->getMetaKeyword()) ? $view->getMetaKeyword():null));

$this->headMeta()->appendProperty('og:title', !empty($view->getMetaTitle()) ? $view->getMetaTitle():$view->getName());
$this->headMeta()->appendProperty('og:description', !empty($view->getMetaDescription()) ? $view->getMetaDescription():null);
$this->headMeta()->appendProperty('og:image', !empty($imageFirst) ? 'http://'.$_SERVER['HTTP_HOST'].$imageFirst:null);
$this->headMeta()->appendProperty('og:image:secure_url', !empty($imageFirst) ? 'http://'.$_SERVER['HTTP_HOST'].$imageFirst:null);
$this->headMeta()->appendProperty('og:image:width', $imageInfo['0']);
$this->headMeta()->appendProperty('og:image:height', $imageInfo['1']);
$this->headMeta()->appendProperty('og:type', 'Page');
$this->headMeta()->appendProperty('og:url', 'http://'.$_SERVER['HTTP_HOST'].$view->getViewLink());
$this->headMeta()->appendProperty('og:site_name', $optionBasic['sologan']);

$this->headMeta()->appendName('twitter:card', !empty($image) ? $image:'summary_large_image');
$this->headMeta()->appendName('twitter:title', !empty($view->getMetaTitle()) ? $view->getMetaTitle():null);
$this->headMeta()->appendName('twitter:description', (!empty($view->getMetaDescription()) ? $view->getMetaDescription():null));
$this->headMeta()->appendName('twitter:image', !empty($image) ? $image:null);
/**** End SEO DWEB *****/
?>
<?php
$cs = [
    '/tp/F010/css/contact.css',
    '/tp/F010/css/n.css'
];
echo '<link href="'.srcLink($cs,1).'" media="screen" rel="stylesheet" type="text/css">';
?>
<section class="contact">
    <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="contactForm">
                        <div class="row">
                            <div class="contact__inner">
                                <div class="col-md-6">
                                    <h2 class="contact__logo">
                                        <?php if(!empty($optionBasic['logo'])): ?>
                                            <img src="<?= $optionBasic['logo'] ?>" alt="Fashion" />
                                        <?php endif; ?>
                                    </h2>
                                    <div class="contact__description">
                                        <?php
                                            echo html_entity_decode($view->getDescription());
                                        ?>
                                    </div>

                                </div>
                                <div class="col-md-6 ">
                                    <form class="contact__from-right" data-parsley-validate novalidate>

                                        <div class="form-group">
                                            <input type="text" class="title" placeholder="Tiêu đề" required="required" data-parsley-error-message="Tiêu đề không được để trống" value="">
                                        </div>
                                        <div class="form-group">
                                            <input type="text" name="email" class="email" data-parsley-type="email" placeholder="Email" required="required" data-parsley-error-message="Email không được để trống" value="">
                                        </div>
                                        <div class="form-group">
                                            <input type="text" name="phone" class="phone" data-parsley-type="digits" data-parsley-length="[10,11]" placeholder="Số điện thoại" required="required" data-parsley-error-message="Số điện thoại không được để trống" value="">
                                        </div>
                                        <div class="form-group">
                                            <textarea class="content" placeholder="Nội dung" required="required" data-parsley-error-message="Nội dung không được để trống"></textarea>
                                        </div>
                                        <div class="form-group">
                                            <button type="submit">Gửi</button>
                                        </div>
                                    </form>
                                </div>
                                <!--<div class="detailNews">
                            <h1 class="detail-news__title"><?/*= html_entity_decode($view->getName()) */?></h1>

                        </div>-->
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
</section>
