<?php
    $optionPage = $this->home()->optionPage();
?>
<footer class="footer">
    <div class="container">
        <div class="footer__two">
            <div class="footer__copyright"><?=$optionPage['copyright'] ? $optionPage['copyright'] : ''?></div>
            <div class="footer__social">
                <ul>
                    <li><a href="<?=$optionPage['facebook'] ? $optionPage['facebook'] : '#'?>"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="<?=$optionPage['google'] ? $optionPage['facebook'] : '#'?>"><i class="fa fa-google"></i></a></li>
                    <li><a href="<?=$optionPage['instagram'] ? $optionPage['facebook'] : '#'?>"><i class="fa fa-instagram"></i></a></li>
                    <li><a href="<?=$optionPage['skype'] ? $optionPage['facebook'] : '#'?>"><i class="fa fa-skype"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>