<?php if(!empty($this->newsLayout)):?>
<section class="news">
    <?= $this->newsLayout['news-title text']['value'] ? '<h2 class="titleHome"><span>'.$this->newsLayout['news-title text']['value'].'</span></h2>' : ''?>
    <?php $slider = $this->newsLayout['news-slider-checkbox checkbox']['value']?>
    <ul class="<?= $slider ? 'news-slider owl-carousel owl-theme' : 'lN' ?> news__list">
        <?php
        foreach($this->newsLayout['news-list article']['news-list'] as $k => $n):
            $image = json_decode($n['image'], true);
            if(!empty($image)){
                $imageFirst = array_shift($image);
            }
            ?>
            <li>
                <a href="<?= $n['url'] ?>"><figure class="lazy image-article" data-src="<?= !empty($imageFirst) ? $imageFirst:'' ?>"></figure></a>
                <a href="<?= $n['url'] ?>"><h3><?= $n['title'] ?></h3></a>
                <p><a href="<?= $n['url'] ?>">Đọc thêm</a></p>
            </li>
            <?php
        endforeach;
        ?>
    </ul>
</section>
<?php endif;?>