<?php if(!empty($this->bannerList['banner-list banner']['banner-list'])):?>
<section class="slider">
    <?php
        echo '<ul class="banner owl-carousel owl-theme">';
        foreach($this->bannerList['banner-list banner']['banner-list'] as $k => $b):
            $image = json_decode($b['image'], true);
            if(!empty($image)) {
                $imageFirst = array_shift($image);
            }
            ?>
            <li>
                <a>
                    <figure class="lazy image-banner" data-src="<?= !empty($imageFirst) ? $imageFirst:null ?>"></figure>
                </a>
            </li>
        <?php endforeach;?>
</section>
<?php endif;?>