<?php if(!empty($this->tabProductLayout['tab-product1 product']['tab-product1']) || !empty($this->tabProductLayout['tab-product2 product']['tab-product2']) || !empty($this->tabProductLayout['tab-product3 product']['tab-product3'])):?>
<section class="tab-product product">
    <ul class="tab-product__title nav nav-products nav-tabs" role="tablist">
        <?php if(!empty($this->tabProductLayout['tab1-title text']['value'])):?>
            <li role="presentation" class="active">
                <a  href="#tab1-<?=$this->id?>" aria-controls="tab1-<?=$this->id?>" role="tab" data-toggle="tab"><?= $this->tabProductLayout['tab1-title text']['value']?></a>
            </li>
        <?php endif;?>
        <?php if(!empty($this->tabProductLayout['tab2-title text']['value'])):?>
            <li role="presentation">
                <a href="#tab2-<?=$this->id?>" aria-controls="tab2-<?=$this->id?>" role="tab" data-toggle="tab"><?= $this->tabProductLayout['tab2-title text']['value']?></a>
            </li>
        <?php endif;?>
        <?php if(!empty($this->tabProductLayout['tab3-title text']['value'])):?>
            <li role="presentation">
                <a href="#tab3-<?=$this->id?>" aria-controls="tab3-<?=$this->id?>" role="tab" data-toggle="tab"><?= $this->tabProductLayout['tab3-title text']['value']?></a>
            </li>
        <?php endif;?>
    </ul>
    <div class="tab-content">
        <div id="tab1-<?=$this->id?>" role="tabpanel" class="tab-pane fade">
            <ul class="product__list lP">
                <?php foreach($this->tabProductLayout['tab-product1 product']['tab-product1'] as $k => $p):
                    $image = json_decode($p['image'], true);
                    if(!empty($image)){
                        $imageFirst = array_shift($image);
                    }
                    ?>
                    <li>
                        <a class="pI" href="<?= $p['url'] ?>"><figure class="lazy image-product" data-src="<?= !empty($imageFirst) ? $imageFirst:'' ?>"></figure></a>
                        <div>
                            <h4><a href="<?= $p['url'] ?>">Mua ngay</a></h4>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
        <div id="tab2-<?=$this->id?>" role="tabpanel" class="tab-pane fade in active">
            <ul class="product__list lP">
                <?php foreach($this->tabProductLayout['tab-product2 product']['tab-product2'] as $k => $p):
                    $image = json_decode($p['image'], true);
                    if(!empty($image)){
                        $imageFirst = array_shift($image);
                    }
                    ?>
                    <li>
                        <a class="pI" href="<?= $p['url'] ?>"><figure class="lazy image-product" data-src="<?= !empty($imageFirst) ? $imageFirst:'' ?>"></figure></a>
                        <div>
                            <h4><a href="<?= $p['url'] ?>">Mua ngay</a></h4>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
        <div id="tab3-<?=$this->id?>" role="tabpanel" class="tab-pane fade">
            <ul class="product__list lP">
                <?php foreach($this->tabProductLayout['tab-product3 product']['tab-product3'] as $k => $p):
                    $image = json_decode($p['image'], true);
                    if(!empty($image)){
                        $imageFirst = array_shift($image);
                    }
                    ?>
                    <li>
                        <a class="pI" href="<?= $p['url'] ?>"><figure class="lazy image-product" data-src="<?= !empty($imageFirst) ? $imageFirst:'' ?>"></figure></a>
                        <div>
                            <h4><a href="<?= $p['url'] ?>">Mua ngay</a></h4>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>

</section>
<?php endif;?>

