<?php
$cs = [
    '/tp/daithanhmiennam/css/p.css'
];
echo '<link href="'.srcLink($cs,1).'" media="screen" rel="stylesheet" type="text/css">';
$menuOption = $this->home()->getMenu();
$optionPage = $this->home()->optionPage();
$optionBasic = $this->home()->optionBasic();
$product = $this->paginator;
$tag = $this->tag;
$product->setItemCountPerPage($optionBasic['postPerPageProduct'] ? $optionBasic['postPerPageProduct'] : 12);
$title = isset($tag) ? 'Đang tìm kiếm với từ khoá "'.$tag.'"': ($optionBasic['metaNameProduct'] ? $optionBasic['metaNameProduct']:'Danh sách sản phẩm');
?>
<?php
/**** Start SEO DWEB *****/
$this->headTitle($this->escapeHtml($this->translate($title)));
$this->headMeta()->appendName('description', $optionBasic['metaDescriptionProduct'] ? $optionBasic['metaDescriptionProduct'] : '');
$this->headMeta()->appendName('keywords', $optionBasic['metaKeywordProduct'] ? $optionBasic['metaKeywordProduct'] : '');

$this->headMeta()->appendProperty('og:title', $optionBasic['metaTitleProduct'] ? $optionBasic['metaTitleProduct'] : '');
$this->headMeta()->appendProperty('og:description', $optionBasic['metaDescriptionProduct'] ? $optionBasic['metaDescriptionProduct'] : '');
$this->headMeta()->appendProperty('og:image', '');
$this->headMeta()->appendProperty('og:image:secure_url', '');
$this->headMeta()->appendProperty('og:image:width', '');
$this->headMeta()->appendProperty('og:image:height', '');
$this->headMeta()->appendProperty('og:type', 'Page');
$this->headMeta()->appendProperty('og:url', 'http://'.$_SERVER['HTTP_HOST'].'/san-pham.html');
$this->headMeta()->appendProperty('og:site_name', $optionBasic['sologan']);
$this->headMeta()->appendName('twitter:card', '');
$this->headMeta()->appendName('twitter:title', 'Danh sách sản phẩm');
$this->headMeta()->appendName('twitter:description', 'Danh sách sản phẩm');
$this->headMeta()->appendName('twitter:image', '');
/**** End SEO DWEB *****/
?>

<div class="container">

    <div class="row">
        <div class="col-md-12">
            <ul class="breadcrumb breadcrumb-category">
                <li><a href="/">Trang chủ</a></li>
                <li><a href="/san-pham.html">Sản phẩm</a></li>
            </ul>
            <div class="productCategory">
                <?php echo $this->render('product/product/sidebar');?>
                <?php
                $show = $this->request->getQuery('show');
                if(count($product)){
                    echo '<div class="right">';
                    echo '<h1><span>'.$title.'</span>
                          <select onchange="location = this.options[this.selectedIndex].value;">
                                <option value="' . $this->product()->removeFilter('show') . '">Mới cập nhật</option>
                                <option value="' . $this->product()->addFilter('show', 'priceAsc',2) . '" '.($show == 'priceAsc' ? 'selected':'').'>Giá tăng dần</option>
                                <option value="' . $this->product()->addFilter('show', 'priceDesc',2) . '" '.($show == 'priceDesc' ? 'selected':'').'>Giá giảm dần</option>
                                <option value="' . $this->product()->addFilter('show', 'SaleOff',2) . '" '.($show == 'SaleOff' ? 'selected':'').'>Giảm giá</option>
                          </select>
                        </h1>';
                    echo '<div class="product product-category"><ul class="lP">';
                    foreach($product as $p){
                        $image = json_decode($p->getImage(), true);
                        if(!empty($image)){
                            $imageFirst = array_shift($image);
                        }
                        echo '<li><div class="product__item">
                                <a class="pI" href="'.$p->getViewLink().'"><figure class="lazy image-product" data-src="'.(!empty($imageFirst) ? $imageFirst:null).'"></figure></a>
                                <div>
                                    <h3><a href="'.$p->getViewLink().'">'. $p->getTitle().'</a></h3>
                                    <p '.($p->getPriceOld() ? 'class="oldPrice"':'').'>'.($p->getPriceOld() ? '<span>'.number_format($p->getPriceOld()).'₫</span><i>'.number_format($p->getPrice()).'₫</i>':number_format($p->getPrice()).'₫').'</p>
                                </div>
                            </div></li>';
                    }
                    echo '</ul></div>';
                    echo '<div class="paginatorProduct">';
                    echo $this->paginationControl($this->paginator, 'Elastic', 'partial/listPage');
                    echo '</div>';
                    echo '</div>';
                }
                ?>
            </div>
        </div>
    </div>
</div>