<?php
    echo $this->headtitle($this->escapehtml($this->translate('Danh sách Banner')));
?>
<input type="hidden" class="updateHomepage" />
<div class="row">
    <div class="col-sm-12">
        <div class="card-box">
            <div class="portlet-body">
                <div id="sample_editable_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
                    <div class="btn-toolbar">
                        <div class="btn-group focus-btn-group">
                            <a href="/admin/media/add" class="btn btn-default waves-effect waves-light">Thêm hình</a>
                        </div>
                    </div>
                    <?php
                        echo $dg = new \Admin\Dg\DgBanner ( array (
                            'data' => $this->results->getData (),
                            'paging' => $this->results->getPaging (),
                            'rowCount' => $this->results->getRowCount (),
                            'rowInPage' => $this->results->getRowInPage (),
                            'uri' => $this->url,
                        ));
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>
