<?php
    $f = $this->results->getData();
    echo '<input type="hidden" class="totalPage" data-value="'.$this->totalPage.'" />';
    if(!empty($f)){
        foreach($f as $ff){
            echo '<li class="image-item" data-id="'.$ff->getId().'"><figure style="background-image: url('.$ff->getPictureUri().')"></figure></li>' ;
//            echo '<li class="image-item" data-id="'.$ff->getId().'"><img src="'.$ff->getPictureUri().'" alt="" /></li>' ;
        }
    }
?>