<?php
    $optionBasic = $this->home()->optionBasic();
?>
<div class="head">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <form id="search" action="/search" method="get">
                    <input type="text" name="q" placeholder="Tìm kiếm ..."/>
                    <a href="javascript:{}" onclick="document.getElementById('search').submit();"><i class="fa fa-search" aria-hidden="true"></i></a>
                    <div id="searchFolding"></div>
                </form>
            </div>
            <div class="col-md-4">
                <?php if(!empty($optionBasic['logo'])): ?>
                <div class="logo">
                    <a href="/">
                        <img src="<?= $optionBasic['logo'] ?>" alt="<?= !empty($optionBasic['sologan']) ? $optionBasic['sologan']:null ?>" />
                    </a>
                </div>
                <?php else: ?>
                <div class="logo">
                    <a class="logo-text" href="/">FASHION<p>Make of style</p></a>
                </div>
                <?php endif; ?>
            </div>
            <div class="col-md-4">
                <ul class="RegisterLogin">
                    <?php
                        if ($this->user()->hasIdentity()) {
                    ?>
                        <li><a>Xin chào: <?= $this->user()->getUser()->getFullName() ? $this->user()->getUser()->getFullName():ucfirst($this->user()->getUser()->getUserName()) ?></a></li>
                        <li><a href="/user/signout">Thoát</a></li>
                    <?php
                        }else{
                    ?>
                        <li><a href="/user/signup">Đăng ký</a></li>
                        <li><a href="/user/signin">Đăng nhập</a></li>
                    <?php
                        }
                    ?>
                    <?php
                        $cartService = $this->cart()->getServiceCart();
                        $products = $cartService->getProducts();
                    ?>
                    <li><a class="totalCart" href="/cart">Giỏ hàng <i class="fa fa-shopping-cart" aria-hidden="true"></i><span><?= $cartService->getTotalProducts() ?></span></a></li>
                </ul>
            </div>
            <div class="col-md-12">
                <div class="nav">
                    <?php
                        $menuOption = $this->home()->getMenu();
                    ?>
                    <ul>
                        <?php
                            if(!empty($menuOption['head_menu'])){
                            foreach($menuOption['head_menu'] as $c){
                        ?>
                                <li>
                                    <a href="<?= $c['url'] ?>"><?= $c['name'] ?></a>
                                    <?php
                                    if($c['chilrend']){
                                        echo '<div>
                                        <ul class="nav1">
                                            <h2>Có gì mới</h2>
                                            <li><a href="">Hàng mới</a></li>
                                            <li><a href="">OFF 30% for more than 2 items</a></li>
                                        </ul>
                                        <ul class="nav2"><h2>Danh mục</h2>';
                                        foreach($c->getChilds() as $cc){
                                            ?>
                                                <li><a href="<?= $cc->getViewLink() ?>"><?= $cc->getName() ?></a></li>
                                            <?php
                                        }
                                        echo '</ul>';
                                        $new = [];
                                        if(count($new)){
                                            echo '<ul class="nav3"><h2>Bài viết nổi bật</h2>';
                                                foreach($new as $n){
                                                    ?>
                                                        <li><a href="<?= $n->getViewLink() ?>"><?= $n->getTitle() ?></a></li>
                                                    <?php
                                                }
                                                echo '</ul>';
                                        }
                                        echo '</div>';
                                    }
                                    ?>
                                </li>
                        <?php
                            }
                            }
                        ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>