<?php
    $view = $this->page;

    $imageFirst = '';
    if(!empty(json_decode($view->getImage(), true))){
        $imageFirst = array_shift(json_decode($view->getImage(), true));
    }

    $this->headTitle($this->escapeHtml(html_entity_decode($this->translate($view->getName()))));

    $this->headMeta()->appendName('description', ($view->getMetaDescription() ? $view->getMetaDescription():$view->getName()));
    $this->headMeta()->appendName('keywords', ($view->getMetaKeyword() ? $view->getMetaKeyword():$view->getName()));

    $this->headMeta()->appendProperty('og:locale', 'vi_VN');
    $this->headMeta()->appendProperty('og:image', 'http://'.$_SERVER["SERVER_NAME"].$imageFirst);
    $this->headMeta()->appendProperty('og:url', 'http://'.$current_page_URL);
    $this->headMeta()->appendProperty('og:title', $view->getMetaTitle() ? $view->getMetaTitle():$view->getName());
    $this->headMeta()->appendProperty('og:description', ($view->getMetaDescription() ? $view->getMetaDescription():$view->getName()));

    $this->headMeta()->appendProperty('twitter:card', 'http://'.$_SERVER["SERVER_NAME"]);
    $this->headMeta()->appendProperty('twitter:title', $view->getMetaTitle() ? $view->getMetaTitle():$view->getName());
    $this->headMeta()->appendProperty('twitter:image', 'http://'.$_SERVER["SERVER_NAME"].$imageFirst);
    $this->headMeta()->appendProperty('twitter:description', $view->getMetaDescription() ? $view->getMetaDescription():$view->getName());
?>

<?php
    $cs = [
        '/tp/A015/css/p.css',
        '/tp/A015/css/n.css'
    ];
    echo '<link href="'.srcLink($cs,1).'" media="screen" rel="stylesheet" type="text/css">';
?>
<section class="lazy hero-news hero-news__single" data-src="<?= $imageFirst ? $imageFirst:'https://ir.vinhomes.vn/dizi/themes/vinhome/assets/images/banner-quan-he-co-dong.jpg' ?>"></section>
<section class="page-news">
    <div class="main">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="page-news__inner">
                        <div class="detailNews">
                            <h1 class="detail-news__title"><?= html_entity_decode($view->getName()) ?></h1>
                            <?php
                                echo html_entity_decode($view->getDescription());
                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
