<?php
    $url = $this->UriParams()->getRequest()->getRequestUri();
    $menuOption = $this->home()->getMenu();
    $optionBasic = $this->home()->optionBasic();
    $optionPage = $this->home()->optionPage();
?>
<header class="head">
    <div class="head1">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="head1__inner">
                        <div class="head1__left">
                            <ul>
                                <li><a href=""><i class="fa fa-facebook"></i></a></li>
                                <li><a href=""><i class="fa fa-twitter"></i></a></li>
                                <li><a href=""><i class="fa fa-google-plus"></i></a></li>
                            </ul>
                        </div>
                        <div class="head1__right">
                            <ul class="RegisterLogin">
                                <?php
                                if ($this->user()->hasIdentity()) {
                                    ?>
                                    <li><a>Xin chào: <?= $this->user()->getUser()->getFullName() ? $this->user()->getUser()->getFullName():ucfirst($this->user()->getUser()->getUserName()) ?></a></li>
                                    <li><a href="/user/signout">Thoát</a></li>
                                    <?php
                                }else{
                                    ?>
                                    <li><a href="/user/signup">Đăng ký</a></li>
                                    <li><a href="/user/signin">Đăng nhập</a></li>
                                    <?php
                                }
                                ?>

                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="head2">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="head2__inner">

                        <div class="logo">
                            <a href="/">
                                <?php if(!empty($optionBasic['logo'])): ?>
                                    <img src="<?= $optionBasic['logo'] ?>" alt="Fashion" />
                                <?php endif; ?>
                            </a>
                        </div>

                        <div class="head2__right">
                            <a class="navigation-button">
                                <span></span>
                                <span></span>
                                <span></span>
                            </a>
                            <div class="navHome">
                                <ul>
                                    <?php foreach($menuOption['head_menu'] as $m): ?>
                                        <li <?= $url == $m['url'] ? 'class="active"':null ?>><a href="<?= $m['url'] ?>"><?= $m['name'] ?></a>
                                            <?php if(!empty($m['children'])): ?>
                                                <ul class="navHome__list">
                                                    <?php foreach($m['children'] as $mm): ?>
                                                        <li><a href="<?= $mm['url'] ?>"><?= $mm['name'] ?></a>
                                                            <?php if(!empty($mm['children'])): ?>
                                                                <ul>
                                                                    <?php foreach ($mm['children'] as $mcc):?>
                                                                        <li><a href="<?= $mcc['url'] ?>"><?= $mcc['name'] ?></a></li>
                                                                    <?php endforeach;?>
                                                                </ul>
                                                            <?php endif;?>
                                                        </li>
                                                    <?php endforeach; ?>
                                                </ul>
                                            <?php endif; ?>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                            <div class="navigation-mobile">
                                <ul class="navigation-mobile__list">
                                    <?php foreach($menuOption['head_menu'] as $m): ?>
                                        <li <?= $url == $m['url'] ? 'class="active"':null ?>><?= $m['children'] ? '<button></button>' : null ?><a href="<?= $m['url'] ?>"><?= $m['name'] ?></a>
                                            <?php if(!empty($m['children'])): ?>
                                                <ul class="nav2">
                                                    <?php foreach($m['children'] as $mm): ?>
                                                        <li><?= $mm['children'] ? '<button></button>' : null ?><a href="<?= $mm['url'] ?>"><?= $mm['name'] ?></a>
                                                            <?php if(!empty($mm['children'])): ?>
                                                                <ul>
                                                                    <?php foreach ($mm['children'] as $mcc):?>
                                                                        <li><a href="<?= $mcc['url'] ?>"><?= $mcc['name'] ?></a></li>
                                                                    <?php endforeach;?>
                                                                </ul>
                                                            <?php endif;?>
                                                        </li>
                                                    <?php endforeach; ?>
                                                </ul>
                                            <?php endif; ?>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</header>