<?php
    $view = $this->news;
    use Home\Model\DateBase;
    $optionPage = $this->home()->optionPage();

    $imageFirst = '';
    if(!empty(json_decode($view->getImage(), true))){
        $imageFirst = array_shift(json_decode($view->getImage(), true));
    }

    $current_page_URL = $_SERVER["SERVER_NAME"] . $_SERVER["REQUEST_URI"];
    $a = json_decode($view->getExtraContent());
    $this->headTitle($this->escapeHtml(html_entity_decode($this->translate($view->getTitle()))));

    $this->headMeta()->appendName('description', ($view->getMetaDescription() ? $view->getMetaDescription():$view->getTitle()));
    $this->headMeta()->appendName('keywords', ($view->getMetaKeyword() ? $view->getMetaKeyword():$view->getTitle()));

    $this->headMeta()->appendProperty('og:locale', 'vi_VN');
    $this->headMeta()->appendProperty('og:image', 'http://'.$_SERVER["SERVER_NAME"].$imageFirst);
    $this->headMeta()->appendProperty('og:url', 'http://'.$current_page_URL);
    $this->headMeta()->appendProperty('og:title', $view->getMetaTitle() ? $view->getMetaTitle():$view->getTitle());
    $this->headMeta()->appendProperty('og:description', ($view->getMetaDescription() ? $view->getMetaDescription():$view->getTitle()));

    $this->headMeta()->appendProperty('twitter:card', 'http://'.$_SERVER["SERVER_NAME"]);
    $this->headMeta()->appendProperty('twitter:title', $view->getMetaTitle() ? $view->getMetaTitle():$view->getTitle());
    $this->headMeta()->appendProperty('twitter:image', 'http://'.$_SERVER["SERVER_NAME"].$imageFirst);
    $this->headMeta()->appendProperty('twitter:description', $view->getMetaDescription() ? $view->getMetaDescription():$view->getTitle());

    $cs = [
        '/tp/A013/css/n.css'
    ];
    echo '<link href="'.srcLink($cs,1).'" media="screen" rel="stylesheet" type="text/css">';
    $js = [
        '/tp/A013/js/n.js'
    ];
    echo '<script type="text/javascript" src="'.srcLink($js,1).'"></script>';
?>
<?php
//    echo $this->render('news/news/gallery');
?>

<section class="lazy hero-news hero-news__single" data-src="<?= $imageFirst ? $imageFirst:'https://ir.vinhomes.vn/dizi/themes/vinhome/assets/images/banner-quan-he-co-dong.jpg' ?>">
    <div class="shape-top gray"></div>
</section>

<section class="page-news">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="page-news__inner">
                    <div class="detailNews">
                        <h1 class="detail-news__title"><?= html_entity_decode($view->getTitle()) ?></h1>
                        <div class="single-news__profile">
                            <span><i class="fa fa-clock-o"></i><?= DateBase::toFormat($view->getCreatedDateTime(), 'd/m/Y') ?></span><span><i class="fa fa-folder-o"></i><?= $view->getCateName() ?></span><span><i class="fa fa-eye"></i><?= $view->getView() ?></span>
                        </div>

                        <?php
                            echo $view->getContent();
                        ?>

                        <div class="social">
                            <div style="float: left;margin: 0 5px 0 0;" class="fb-like" data-href="<?= $current_page_URL.$view->getViewLink() ?>" data-layout="button" data-action="like" data-show-faces="false" data-share="true"></div>
                            <div class="g-plusone" data-size="medium"></div>
                        </div>
                        <script src="https://apis.google.com/js/platform.js" async defer>
                            {lang: 'vi'}
                        </script>
                    </div>

                <?php
                $relation = json_decode($view->getArticleRelated(), true);
                if(!empty($relation)):
                    echo '<h2 class="single__relation--headline">Bài viết liên quan</h2>';
                    echo '<div class="single__relation post-last__list post-last__list--category">';
                    $i = 0;
                    foreach($relation as $n) {
                        $i++;
                        $image = json_decode($n['image'], true);
                        $imageFirst = '';
                        if(!empty($image)){
                            $imageFirst = array_shift($image);
                        }
                        if($i < 7):
                            ?>
                            <div class="post-last__item">
                                <div class="post-last__item--inner">
                                    <div class="">
                                        <a href="<?= $n['url']  ?>">
                                            <figure class="post-last__image lazy" data-src="<?= (!empty($imageFirst) ? $imageFirst : null) ?>"></figure>
                                        </a>
                                    </div>
                                    <div class="post-last__content">
                                        <h3 class="post-last__title"><a href="<?= $n['url']  ?>"><?= $n['title'] ?></a></h3>
                                    </div>
                                </div>
                            </div>
                            <?php
                        endif;
                    }
                    echo '</div>';
                endif;
                ?>
                </div>
            </div>
        </div>
    </div>
</section>

<?php if(!empty($optionPage['tieu-de-email'])): ?>
    <section class="form form__pdt">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="form__inner">
                        <h2 class="headline-default"><?= $optionPage['tieu-de-email'] ? $optionPage['tieu-de-email']:'Email' ?></h2>
                        <?= $optionPage['mo-ta-email'] ? '<div class="four-post__intro"><span>'.$optionPage['mo-ta-email'].'</span></div>':'' ?>
                        <form class="form__register" data-parsley-validate novalidate>
                            <div>
                                <input class="email" type="text" data-parsley-type="email" required="required" data-parsley-error-message="Email không được để trống" placeholder="Email *" />
                            </div>
                            <div>
                                <input class="phone" type="text" data-parsley-type="digits" data-parsley-length="[10,11]" required="required" data-parsley-error-message="Số điện thoại không được để trống" placeholder="Số điện thoại *" />
                            </div>
                            <div>
                                <button type="submit">Gửi</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
<?php endif; ?>
