<?php  use Home\Model\DateBase;
    if(!empty($this->newsLayout['news-list article']['news-list'])):
?>
<section class="news">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2 class="titleHome">
                    <i class="fa fa-tree" aria-hidden="true"></i><i class="fa fa-tree" aria-hidden="true"></i><i class="fa fa-tree" aria-hidden="true"></i>
                    <span><?= $this->newsLayout['news-title text']['value'] ?></span>
                </h2>
                <?php $slider = $this->newsLayout['news-slider-checkbox checkbox']['value']?>
                <ul class="<?= $slider ? 'news-slider owl-carousel owl-theme' : 'lN' ?> news__list">
                    <?php
                    foreach($this->newsLayout['news-list article']['news-list'] as $k => $n):
                        $image = json_decode($n['image'], true);
                        if(!empty($image)){
                            $imageFirst = array_shift($image);
                        }
                        ?>
                        <li class="news-item">
                            <div class="news-item__inner">
                                <a href="<?= $n['url'] ?>"><figure class="lazy image-article" data-src="<?= !empty($imageFirst) ? $imageFirst:'' ?>">

                                    </figure></a>
                                <div class="news-item__info">
                                    <p><span class="lN__date"><?= DateBase::toFormat($n['date'], 'M d, Y') ?></span></p>
                                    <h3><a href="<?= $n['url'] ?>"><?= $n['title'] ?></a></h3>
                                </div>
                            </div>
                        </li>
                        <?php
                    endforeach;
                    ?>
                </ul>
            </div>
        </div>
    </div>
</section>
<?php endif;?>