<section class="product">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2 class="titleHome">
                    <i class="fa fa-tree" aria-hidden="true"></i>
                    <i class="fa fa-tree" aria-hidden="true"></i>
                    <i class="fa fa-tree" aria-hidden="true"></i>
                    <span><?= $this->productLayout['product-title text']['value'] ? $this->productLayout['product-title text']['value']: ''?></span></h2>
                <?php $slider = $this->productLayout['product-slider-checkbox checkbox']['value']?>
                <ul class=" <?= $slider ? 'two-up__product-list owl-carousel owl-theme' : 'lP'?> product__list">
                    <?php foreach($this->productLayout['product-list product']['product-list'] as $k => $p):
                        $image = json_decode($p['image'], true);
                        if(!empty($image)){
                            $imageFirst = array_shift($image);
                        }
                        ?>
                        <li>
                            <div class="product-item__inner">
                                <div class="product-image__wrapper">
                                    <a class="pI" href="<?= $p['url'] ?>"><figure class="lazy image-product" data-src="<?= !empty($imageFirst) ? $imageFirst:'' ?>"></figure></a>
                                </div>
                                <div class="product-item__info">
                                    <h3><a href="<?= $p['url'] ?>"><?= $p['title'] ?></a></h3>
                                    <p class="price <?= ($p['priceOld'] ? 'priceOld':null) ?>">
                                        <?=  (!empty($p['priceOld']) ? '<span>'.number_format($p['priceOld']).'</span><i>'.number_format($p['price']).'</i>':number_format($p['price']) ) ?>
                                    </p>
                                    <a class="btnAddCart" data-quantity="1" data-id="<?= $p['id']?>">Giỏ hàng</a>
                                </div>
                            </div>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
</section>

