<?php
$paginator = $this->paginator;
$this->headTitle($this->escapeHtml($this->translate('Danh sách tin tức')));
$this->headMeta()->appendName('description', ('Danh sách tin tức'));
$this->headMeta()->appendName('keywords', ('Danh sách tin tức'));
$this->headMeta()->appendProperty('og:title', 'Danh sách tin tức');
$cs = [
    '/tp/F006/css/n.css'
];
echo '<link href="'.srcLink($cs,1).'" media="screen" rel="stylesheet" type="text/css">';
?>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <?php
            if(count($paginator)){
                $n = $this->newsCategory()->getCategories();
                if(count($n)){
                    echo '<ul class="navNews">';
                        echo '<li><a class="active" href="/news">Tất cả</a></li>';
                        foreach($n as $b){
                            echo '<li><a href="'.$b->getViewLink().'">'.$b->getName().'</a></li>';
                        }
                    echo '</ul>';
                }
                echo '<ul class="lN lNCategory">';
                foreach($paginator as $n){
                    $image = json_decode($n->getImage(), true);
                    if(!empty($image)){
                        $imageFirst = array_shift($image);
                    }

                    echo '<li>
                        <a href="'.$n->getViewLink().'"><figure class="lazy image-article" data-src="'. (!empty($imageFirst) ? $imageFirst:null).'"></figure></a>
                        <h2><a href="'.$n->getViewLink().'">'.$n->getTitle().'</a></h2>
                        <p>'.$n->getCateName().'</p>
                    </li>';
                }
                echo '</ul>';
                echo '<div class="paginatorProduct">';
                    echo $this->paginationControl($this->paginator, 'Elastic', 'partial/listPage');
                echo '</div>';
            }
            ?>
        </div>
    </div>
</div>