<?php
    $optionPage = $this->home()->optionPage();
    $storeId = $this->home()->storeId();
    $optionBasic = $this->home()->optionBasic();
    $menuOption = $this->home()->getMenu();
?>
<div class="footer">
    <div class="footer__one">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="footer__category--inner">
                        <ul class="footer__category">
                            <?php if(!empty($optionPage['view_gioi-thieu'])):?>
                                <li>
                                    <a class="logo" href="/">
                                        <?php if(!empty($optionBasic['logo'])): ?>
                                            <img src="<?= $optionBasic['logo'] ?>" alt="<?= !empty($optionBasic['sologan']) ? $optionBasic['sologan']:null ?>" />
                                        <?php endif; ?>
                                    </a>
                                    <div class="footer__content">
                                        <?php if(!empty($optionPage['noi-dung-gioi-thieu'])): ?>
                                            <?= $optionPage['noi-dung-gioi-thieu'] ?>
                                        <?php endif; ?>
                                    </div>
                                    <ul class="social">
                                        <?php if(!empty($optionPage['facebook'])): ?>
                                            <li>
                                                <a href="<?= $optionPage['facebook'] ?>">
                                                    <i class="fa fa-facebook" aria-hidden="true"></i>
                                                </a>
                                            </li>
                                        <?php endif; ?>
                                        <?php if(!empty($optionPage['youtube'])): ?>
                                            <li>
                                                <a href="<?= $optionPage['youtube'] ?>">
                                                    <i class="fa fa-youtube" aria-hidden="true"></i>
                                                </a>
                                            </li>
                                        <?php endif; ?>
                                    </ul>
                                </li>
                            <?php endif; ?>
                            <?php if(!empty($optionPage['view_danh-sach-lien-ket-1'])):?>
                                <li>
                                    <h4 class="footer__title"><?= $optionPage['tieu-de-danh-sach-lien-ket-1'] ?></h4>
                                    <div class="footer__content">
                                        <ul>
                                            <?php foreach($menuOption['footer_menu1'] as $m): ?>
                                                <li <?= $url == $m['url'] ? 'class="active"':null ?>><a href="<?= $m['url'] ?>"><?= $m['name'] ?></a>
                                                </li>
                                            <?php endforeach; ?>
                                        </ul>
                                    </div>
                                </li>
                            <?php endif;?>
                            <?php if(!empty($optionPage['view_danh-sach-lien-ket-2'])):?>
                                <li>
                                    <h4 class="footer__title"><?= $optionPage['tieu-de-danh-sach-lien-ket-2'] ?></h4>
                                    <div class="footer__content">
                                        <ul>
                                            <?php foreach($menuOption['footer_menu2'] as $m): ?>
                                                <li <?= $url == $m['url'] ? 'class="active"':null ?>><a href="<?= $m['url'] ?>"><?= $m['name'] ?></a>
                                                </li>
                                            <?php endforeach; ?>
                                        </ul>
                                    </div>
                                </li>
                            <?php endif;?>
                            <?php if(!empty($optionPage['view_danh-sach-lien-ket-3'])):?>
                                <li>
                                    <h4 class="footer__title"><?= $optionPage['tieu-de-danh-sach-lien-ket-3'] ?></h4>
                                    <div class="footer__content">
                                        <ul>
                                            <?php foreach($menuOption['footer_menu3'] as $m): ?>
                                                <li <?= $url == $m['url'] ? 'class="active"':null ?>><a href="<?= $m['url'] ?>"><?= $m['name'] ?></a>
                                                </li>
                                            <?php endforeach; ?>
                                        </ul>
                                    </div>
                                </li>
                            <?php endif;?>
                            <?php if(!empty($optionPage['view_danh-sach-lien-ket-4'])):?>
                                <li>
                                    <h4 class="footer__title"><?= $optionPage['tieu-de-danh-sach-lien-ket-4'] ?></h4>
                                    <div class="footer__content">
                                        <ul>
                                            <?php foreach($menuOption['footer_menu4'] as $m): ?>
                                                <li <?= $url == $m['url'] ? 'class="active"':null ?>><a href="<?= $m['url'] ?>"><?= $m['name'] ?></a>
                                                </li>
                                            <?php endforeach; ?>
                                        </ul>
                                    </div>
                                </li>
                            <?php endif;?>
                            <?php if(!empty($optionPage['view_thong-tin-dia-chi'])):?>
                                <li>
                                    <h4 class="footer__title"><?= $optionPage['tieu-de-thong-tin'] ?></h4>
                                    <div class="footer__content footer__content--textarea">
                                        <?= $optionPage['dia-chi'] ? $optionPage['dia-chi'] : ''?>
                                    </div>
                                </li>
                            <?php endif;?>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php if ($optionPage['view_danh-muc-san-pham-footer']): ?>
        <div class="footer__two">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="footer__category--inner">
                            <ul class="footer__category">
                                <?php foreach($optionPage['danh-muc-san-pham-footer'] as $c): ?>
                                    <li>
                                        <h4><a href="<?= $c['url'] ?>"><?= $c['title'] ?></a></h4>
                                        <?php if(!empty($c['child'])): ?>
                                            <ul>
                                                <?php foreach($c['child'] as $cc): ?>
                                                    <li><a href="<?= $cc['url'] ?>"><?= $cc['title'] ?></a></li>
                                                <?php endforeach; ?>
                                            </ul>
                                        <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php endif; ?>
    <?php if(!empty($optionPage['view_copyright'])):?>
    <div class="footer__three">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="footer__copyright">
                        <?= $optionPage['copyright'] ? $optionPage['copyright'] : ''?>
                    </div>

                </div>
            </div>
        </div>
    </div>
<?php endif;?>
</div>