<?php
    $paginator = $this->paginator;

    $paginator->setItemCountPerPage($this->uriParams()->getRequest()->getQuery('icpp') ? : 10);
    $optionPage = $this->home()->optionPage();
    $cs = [
        '/tp/T012/css/n.css',
    ];
    echo '<link href="'.srcLink($cs,1).'" media="screen" rel="stylesheet" type="text/css">';
    $optionPage = $this->home()->optionPage();
    $optionBasic = $this->home()->optionBasic();
    $menuOption = $this->home()->getMenu();
?>
<?php
    /**** Start SEO DWEB *****/
    $this->headTitle($this->escapeHtml($this->translate('Danh sách tin tức')));
    $this->headMeta()->appendName('description', '');
    $this->headMeta()->appendName('keywords', '');

    $this->headMeta()->appendProperty('og:title', 'Danh sách tin tức');
    $this->headMeta()->appendProperty('og:description', 'Danh sách tin tức');
    $this->headMeta()->appendProperty('og:image', '');
    $this->headMeta()->appendProperty('og:image:secure_url', '');
    $this->headMeta()->appendProperty('og:image:width', '');
    $this->headMeta()->appendProperty('og:image:height', '');
    $this->headMeta()->appendProperty('og:type', 'Page');
    $this->headMeta()->appendProperty('og:url', 'http://'.$_SERVER['HTTP_HOST'].'/bai-viet.html');
    $this->headMeta()->appendProperty('og:site_name', $optionBasic['sologan']);

    $this->headMeta()->appendName('twitter:card', '');
    $this->headMeta()->appendName('twitter:title', 'Danh sách tin tức');
    $this->headMeta()->appendName('twitter:description', 'Danh sách tin tức');
    $this->headMeta()->appendName('twitter:image', '');
    /**** End SEO DWEB *****/
?>
<div class="news">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <ul class="breadcrumb breadcrumb-category">
                    <li><a href="/">Trang chủ</a></li>
                    <li><a href="/bai-viet.html">Tin tức</a></li>
                </ul>
            </div>
            <?php
            if(!empty($menuOption['news_sidebar']) || !empty($optionPage['view_danh-muc-sidebar-1']) || !empty($optionPage['view_danh-muc-sidebar-2']) || !empty($optionPage['view_banner-sidebar'])):
                echo $this->render('news/news/sidebar');
                echo '<div class="col-md-9">';
            else:
                echo '<div class="col-md-12">';
            endif;
            ?>
                <div class="right">
                <?php
                    if(count($paginator)){
                        echo '<ul class="lN lNCategory">';
                        foreach($paginator as $n){
                            $image = json_decode($n->getImage(), true);
                            $imageFirst = '';
                            if(!empty($image)){
                                $imageFirst = array_shift($image);
                            }
                            echo '<li>
                                <a href="'.$n->getViewLink().'">
                                    <figure class="lazy image-article" data-src="'.(!empty($imageFirst) ? $imageFirst : null).'"></figure>
                                </a>
                                <div class="news__content">
                                    <p class="news__category">'.$n->getCateName().'</p>
                                    <h3 class="news__title"><a href="'.$n->getViewLink().'">'.$n->getTitle().'</a></h3>
                                    <p class="news__intro">'.$n->getDescription().'</p>
                                </div>
                            </li>';
                        }
                        echo '</ul>';
                        echo '<div class="paginatorProduct">';
                        echo $this->paginationControl($this->paginator, 'Elastic', 'partial/listPage');
                        echo '</div>';
                    }
                ?>
                </div>
            </div>
        </div>
    </div>
</div>