<?php if(!empty($this->newsLayout['news-list article']['news-list'])):?>
<section class="news">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <?= $this->newsLayout['news-title text']['value'] ? '<h2 class="feature-product__title">'.$this->newsLayout['news-title text']['value'].'</h2>' : '' ?>
                <?= $this->newsLayout['news-sub-title text']['value'] ? '<p class="feature-product__title-sub">'.$this->newsLayout['news-sub-title text']['value'].'</p>' : '' ?>
                <?php
                    $slider = $this->newsLayout['news-slider-checkbox checkbox']['value'];
                    if(!empty($slider)){
                        echo '<ul class="news-slider owl-carousel owl-theme">' ;
                    }
                    else {
                        echo '<ul class="lN">';
                    }
                    foreach($this->newsLayout['news-list article']['news-list'] as $k => $n){
                        $image = json_decode($n['image'], true);
                        if(!empty($image)){
                            $imageFirst = array_shift($image);
                        }
                        ?>
                        <li>
                            <a href="<?= $n['url'] ?>"><figure class="<?= $slider ? 'owl-lazy' : 'lazy' ?> image-article" data-src="<?= !empty($imageFirst) ? $imageFirst:'' ?>"></figure></a>
                            <p class="category"><?= $n['category'] ?></p>
                            <h2><a href="<?= $n['url'] ?>"><?= $n['title'] ?></a></h2>
                            <p class="intro">
                                <?php
                                $s = substr($n['intro'],0,150);
                                $rs = substr($s,0,strrpos($s, ' '));
                                if(strlen($n['intro']) > 100):
                                    echo $rs;
                                    echo '...';
                                else:
                                    echo $n['intro'];
                                endif;

                                ?>
                        </li>
                        <?php
                    }
                    echo '</ul>';
                ?>
            </div>
        </div>
    </div>
</section>
<?php endif;?>