<?php if(!empty($this->optionLayout['option-html texteditor']['value']) || !empty($this->optionLayout['option-background file']['value'])):?>
<section class="text-editor" style="background-image: url('<?= $this->optionLayout['option-background file']['value']?>')">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <?= $this->optionLayout['option-html texteditor']['value'] ?>
            </div>
        </div>
    </div>
</section>
<?php endif;?>