<?php
    use Home\Model\DateBase;
    $list = $this->list;
    $user_rating = $_COOKIE['user_rating'];
    $user_rating = json_decode($user_rating, true);
?>
<?php if($list): ?>
    <?php foreach ($list as $l):
        $user_rating = json_decode($l->getExtraContent(), true);
        ?>
        <div class="box-comment__item">
            <div class="box-comment__user">
                <span><?=  $user_rating['name'][0] ?></span>
            </div>
            <div class="box-comment__user--comment">
                <strong><?=  $user_rating['name'] ?></strong>
                <div>
                    <?= $l->getContent(); ?>
                </div>
                <div class="box-comment__user--tool">
                    <a href="">Trả lời</a>
                    <a href=""><i class="fa fa-thumbs-o-up"></i> Thích</a>
                    <span><?= DateBase::time_elapsed_string($l->getCreatedDateTime()) ?></span>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
<?php endif; ?>

