<?php if(!empty($this->smallBannerList['small-banner-list banner']['small-banner-list'])):?>
<section class="small-banner">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <ul class="small-banner__list">
                <?php
                    foreach($this->smallBannerList['small-banner-list banner']['small-banner-list'] as $k => $b):
                        $image = json_decode($b['image'], true);
                        if (!empty($image)) {
                            $imageFirst = array_shift($image);
                        }
                        ?>
                    <li class="small-banner__item">
                        <a href="<?= $b['url'] ?>">
                            <figure class="lazy small-banner__image" data-src="<?= !empty($imageFirst) ? $imageFirst:null ?>">
                            </figure>
                            <h3 class="three-up__title"><?= $b['title'] ?><i class="fa fa-caret-right "></i></h3>
                        </a>
                    </li>
                    <?php endforeach;?>
                </ul>
            </div>
        </div>
    </div>
</section>
<?php endif;?>