<?php
use Home\Model\DateBase;
if(!empty($this->newsLayout['news-list article']['news-list'])):?>
<section class="news">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <?= $this->newsLayout['news-title text']['value'] ? '<h2 class="title-home">'.$this->newsLayout['news-title text']['value'].'</h2>' : '' ?>
                <?php
                    $slider = $this->newsLayout['news-slider-checkbox checkbox']['value'];
                    if(!empty($slider)){
                        echo '<ul class="news-slider owl-carousel owl-theme">' ;
                    }
                    else {
                        echo '<ul class="lN">';
                    }
                    foreach($this->newsLayout['news-list article']['news-list'] as $k => $n){
                        $image = json_decode($n['image'], true);
                        if(!empty($image)){
                            $imageFirst = array_shift($image);
                        }
                        ?>
                        <li class="news__item">
                            <div class="news__item--inner">
                                <a href="<?= $n['url'] ?>"><figure class="lazy image-article" data-src="<?= !empty($imageFirst) ? $imageFirst:'' ?>"></figure></a>
                                <div class="news__item--info">
                                    <p class="news__date"><?= DateBase::toFormat($n['date'], 'M d, Y') ?></p>
                                    <h3><a href="<?= $n['url'] ?>"><?= $n['title'] ?></a></h3>
                                </div>
                            </div>
                        </li>
                        <?php
                    }
                    echo '</ul>';
                ?>
            </div>
        </div>
    </div>
</section>
<?php endif;?>