<?php
    $optionPage = $this->home()->optionPage();
?>

<footer class="footer">
    <div class="footer__one">
        <div class="container">
            <div class="footer__inner">
                <div class="footer__row">
                    <div class="footer__logo header-sologan"><span class="logo-first-key">D</span>WEB.</div>
                    <div class="footer__caption">
                        DWEB là nền tảng tạo website chuẩn seo miễn phí, chúng tôi cung cấp và cập nhật những checklist của một website chuẩn Google để tích hợp vào những website, giúp doanh nghiệp có thể tạo ra những website tối ưu hiệu quả nhất. Ngay từ bây giờ bạn có thể tạo website miễn phí <a target="_blank" href="https://dweb.vn/created">tại đây</a>
                    </div>
                    <div class="footer__title">Liên hệ</div>
                    <div class="footer__address">
                        <div class="footer__address--item">
                            <div class="icon"><i class="fa fa-map-marker"></i></div>
                            <div class="c-details">Hà Nội: Tầng 3, 34 Hoàng Cầu, Toà nhà viễn đông, Hà Nội</div>
                        </div>
                        <div class="footer__address--item">
                            <div class="icon"><i class="fa fa-map-marker"></i></div>
                            <div class="c-details">TP Hồ Chí Minh: Lầu 16 Tòa nhà Havana, 132 Hàm Nghi, phường Bến Nghé, TP HCM</div>
                        </div>
                        <div class="footer__address--item">
                            <div class="icon"><i class="fa fa-phone"></i></div>
                            <div class="c-details">Hỗ trợ: 24/7 0986174666</div>
                        </div>
                        <div class="footer__address--item">
                            <div class="icon"><i class="fa fa-envelope"></i></div>
                            <div class="c-details"><a href="mailto:contact@dweb.vn">contact@dweb.vn</a></div>
                        </div>
                    </div>
                    <ul class="footer__social">
                        <li><a href=""><i class="fa fa-facebook"></i></a></li>
                        <li><a href=""><i class="fa fa-google-plus"></i></a></li>
                    </ul>
                </div>
                <div class="footer__row">
                    <div class="footer__title">Chia sẻ</div>
                    <ul class="footer__nav">
                        <li><a href="https://blog.dweb.vn" target="_blank">Blog chia sẻ</a></li>
                        <li><a href="http://tool.dweb.vn" target="_blank">Kiểm tra website chuẩn seo</a></li>
                        <li><a href="https://blog.dweb.vn/viet-bai-chuan-seo-2019.html" target="_blank">Cách viết bài chuẩn seo</a></li>
                        <li><a href="https://blog.dweb.vn/kiem-tra-website-chuan-seo.html" target="_blank">Thế nào là website chuẩn SEO</a></li>
                        <li><a href="https://blog.dweb.vn/chien-luoc-noi-dung-website.html" target="_blank">Phân tích tổng thể nội dung website</a></li>
                        <li><a target="_blank" href="https://dweb.vn/thiet-ke-website-chuan-seo.html">Thiết kế website chuẩn seo</a></li>
                        <li><a target="_blank" href="https://dweb.vn/quan-tri-website-chuyen-nghiep.html">Dịch vụ quản trị website</a></li>
                        <li><a target="_blank" href="https://dweb.vn/dich-vu-seo.html">Dịch vụ SEO</a></li>
                        <li><a target="_blank" href="https://dweb.vn/thiet-ke-website-gia-re.html">Thiết kế website giá rẻ</a></li>
                    </ul>
                </div>
                <div class="footer__row">
                    <div class="footer__title">Giao diện</div>
                    <ul class="footer__nav">
                        <li><a href="https://dweb.vn/thoi-trang-nc14.html">Thời trang</a></li>
                        <li><a href="https://dweb.vn/giao-dien-bat-dong-san-nc15.html">Bất động sản</a></li>
                        <li><a href="https://dweb.vn/cong-ty-nc16.html">Công ty</a></li>
                        <li><a href="https://dweb.vn/my-pham-lam-dep-nc17.html">Mỹ Phẩm - Làm Đẹp</a></li>
                        <li><a href="https://dweb.vn/am-thuc-an-uong-nc18.html">Ẩm Thực - Ăn Uống</a></li>
                        <li><a href="https://dweb.vn/giao-dien-me-va-be-nc19.html">Mẹ và Bé</a></li>
                        <li><a href="https://dweb.vn/giao-dien-sieu-thi-nc122.html">Siêu thị nhiều mặt hàng</a></li>
                        <li><a href="https://dweb.vn/giao-dien-cong-nghe-nc140.html">Công nghệ</a></li>
                        <li><a href="https://dweb.vn/giao-dien-tin-tuc-blog-nc299.html">Tin tức - Bài viết</a></li>
                    </ul>
                </div>

            </div>
        </div>
    </div>
    <div class="footer__two">
        <div class="container">
            <div class="footer__copyright">Công ty cổ phần công nghệ <a href="http://dweb.vn"> DTT</a> Việt Nam. Địa chỉ: Tầng 3, 36 Hoàng Cầu, toà nhà viễn đông, Hà Nội</div>
        </div>
    </div>
</footer>