<?php
echo $this->doctype();
$optionBasic = $this->home()->optionBasic();
?>
<html lang="en">
    <head>
        <?php
            echo $this->headTitle('Blog')->setSeparator(' | ')->setAutoEscape(false);
            $this->headMeta()->appendName('DC.language', 'scheme=utf-8 content=vi');
            $this->headMeta()->appendName('author', 'blog.dweb.vn');
            $this->headMeta()->appendName('format-detection', 'telephone=no');
            $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1, maximum-scale=1');
            echo $this->headMeta();
            echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $optionBasic['favicon'] ? $optionBasic['favicon']:null ]);

        ?>
        <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,600" rel="stylesheet">
        <link href='https://fonts.googleapis.com/css?family=Roboto:300,500,700' rel='stylesheet' type='text/css'>
        <?php
            $cs = [
                '/tp/blog/css/bootstrap.css',
                '/tp/blog/css/font-awesome.min.css',
                '/tp/blog/css/animate.min.css',
                '/assets/css/web/owl.carousel.css',
                '/tp/blog/css/page.css',
                '/tp/blog/css/a.css',
                '/tp/blog/css/r.css',
            ];
            echo '<link href="'.srcLink($cs,4).'" media="screen" rel="stylesheet" type="text/css">';
            $js = [
                '/assets/js/web/jquery-1.11.2.min.js',
            ];
            echo '<script type="text/javascript" src="'.srcLink($js,22).'"></script>';
        ?>
        <!-- Facebook Pixel Code -->
        <script>
            !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
                n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
                n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
                t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
                document,'script','https://connect.facebook.net/en_US/fbevents.js');
            fbq('init', '1971198599778175'); // Insert your pixel ID here.
            fbq('track', 'PageView');
        </script>
        <noscript><img height="1" width="1" style="display:none"
                       src="https://www.facebook.com/tr?id=1971198599778175&ev=PageView&noscript=1"
            /></noscript>
        <!-- DO NOT MODIFY -->
        <!-- End Facebook Pixel Code -->
        <?php
        $url2 = $this->home()->getMcaName('action');
        $url = $this->UriParams()->getRequest()->getRequestUri();
        ?>
    </head>
    <?php
        $url = $this->UriParams()->getRequest()->getRequestUri();
        $classPage = substr($url, 1, -5);
    ?>
    <body>
        <?php
            echo $this->render('layout/header');
            echo $this->content;
            echo $this->render('layout/footer');
        ?>
    </body>
    <?php
        $cs = [
            '/tp/blog/css/r.css',
        ];
        echo '<link href="'.srcLink($cs,1).'" media="screen" rel="stylesheet" type="text/css">';
        $js = [
//            '/tp/dweb/js/jquery-1.10.1.min.js',
            '/tp/blog/js/bootstrap.min.js',
            '/assets/js/web/owl.carousel.js',
            '/tp/blog/js/waypoint/jquery.waypoints.min.js',
            '/tp/blog/js/a.js',
            '/assets/js/web/jquery.lazy.min.js',
            '/tp/blog/js/hero-slider/TweenLite.min.js',
            '/tp/blog/js/hero-slider/rAF.js',
            '/tp/blog/js/hero-slider/EasePack.min.js',
            '/tp/blog/js/hero-slider/demo-1.js',
        ];
        echo '<script type="text/javascript" src="'.srcLink($js,22).'"></script>';
    ?>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-137904019-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-137904019-1');
    </script>

</html>