<?php
    $optionBasic = $this->home()->optionBasic();
    $optionPage = $this->home()->optionPage();
    $url = $this->UriParams()->getRequest()->getRequestUri();
    $cartService = $this->cart()->getServiceCart();
    $products = $cartService->getProducts();
    $menuOption = $this->home()->getMenu();
?>
<div class="head">
    <?php if(!empty($optionPage['view_header-1'])):?>
        <div class="head1">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="head1__inner">
                            <div class="head1__left">
                                <ul class="RegisterLogin">
                                    <?php if(!empty($menuOption['header_menu'])):
                                        foreach($menuOption['header_menu'] as $m):
                                    ?>
                                        <li <?= $url == $m['url'] ? 'class="active"':null ?>><a href="<?= $m['url'] ?>"><?= $m['name'] ?></a>
                                    <?php endforeach;
                                        endif;
                                        ?>
                                    <?php
                                    if ($this->user()->hasIdentity()) {
                                        ?>
                                        <li><a><i class="fa fa-user"></i>Xin chào: <?= $this->user()->getUser()->getFullName() ? $this->user()->getUser()->getFullName():ucfirst($this->user()->getUser()->getUserName()) ?></a></li>
                                        <li><a href="/user/signout"><i class="fa fa-sign-out"></i>Thoát</a></li>
                                        <?php
                                    }else{
                                    ?>
                                        <li><a href="/user/signup"><i class="fa fa-key"></i>Đăng ký</a></li>
                                        <li><a href="/user/signin"><i class="fa fa-sign-in"></i>Đăng nhập</a></li>
                                    <?php
                                    }
                                    ?>
                                </ul>
                            </div>
                            <div class="head1__right">
                                <ul class="head1__support">
                                    <?php if(!empty($optionPage['ho-tro'])): ?>
                                    <li>
                                        <i class="fa fa-headphones"></i>
                                        <?= $optionPage['ho-tro']?>
                                    </li>
                                    <?php endif;?>
                                    <?php if(!empty($optionPage['skype'])): ?>
                                        <li>
                                            <i class="fa fa-skype"></i>
                                            <a href="Skype:<?= $optionPage['skype'] ?>?chat">
                                                skype: <?= $optionPage['skype'] ?>
                                            </a
                                        </li>
                                    <?php endif; ?>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php endif;?>
    <?php if(!empty($optionPage['view_header-2'])):?>
    <div class="head2">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="head2__inner">
                        <div class="head2__logo">
                            <a class="logo" href="/">
                                <?php if(!empty($optionBasic['logo'])): ?>
                                    <img src="<?= $optionBasic['logo'] ?>" alt="<?= !empty($optionBasic['sologan']) ? $optionBasic['sologan']:null ?>" />
                                <?php endif; ?>
                            </a>
                        </div>
                        <div class="head2__service">
                            <ul class="toolTop">
                                <?= $optionPage['o-thong-tin-1'] ? '<li><i class="fa fa-map-marker"></i><p>'.$optionPage['o-thong-tin-1'].'</p></li>':null ?>
                                <?= $optionPage['o-thong-tin-2'] ? '<li><i class="fa fa-cube"></i><p>'.$optionPage['o-thong-tin-2'].'</p></li>':null ?>
                                <?= $optionPage['o-thong-tin-3'] ? '<li><i class="fa fa-car"></i><p>'.$optionPage['o-thong-tin-3'].'</p></li>':null ?>
                                <?= $optionPage['o-thong-tin-4'] ? '<li><i class="fa fa-home"></i><p>'.$optionPage['o-thong-tin-4'].'</p></li>':null ?>
                                <?= $optionPage['o-thong-tin-5'] ? '<li><i class="fa fa-history"></i><p>'.$optionPage['o-thong-tin-5'].'</p></li>':null ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php endif;?>
    <div class="head3">
        <div class="container">
            <div class="row">
            <div class="col-md-12">
                <div class="CategoryShip">
                    <div class="categoryHome">
                        <h2>
                            <i class="fa fa-bars"></i>Danh mục sản phẩm
                            <span></span>
                        </h2>
                        <div class="navHome">
                            <?php
                                $menuOption = $this->home()->getMenu();
                                if(!empty($menuOption['danh_muc_trai'])):
                            ?>
                            <ul>
                                <?php
                                    foreach($menuOption['danh_muc_trai'] as $c){
                                        ?>
                                        <li>
                                        <a href="<?= $c['url'] ?>">
                                            <?= $c['name'] ?>
                                        </a>
                                        <?= !empty($c['children']) ? '<span class="icon-caret"></span>':null ?>
                                        <?php
                                        if(isset($c['children'])){
                                            echo '<ul class="nav2">';
                                            foreach($c['children'] as $cc){
                                                ?>
                                                <li><a href="<?= $cc['url'] ?>"><?= $cc['name'] ?></a>
                                                <?= !empty($cc['children']) ? '<span class="icon-caret"></span>':null ?>
                                                <?php
                                                    if(isset($cc['children'])){
                                                        echo '<ul class="nav3">';
                                                        foreach($cc['children'] as $ccc){
                                                            ?>
                                                            <li><a href="<?= $ccc['url'] ?>"><?= $ccc['name'] ?></a></li>
                                                        <?php
                                                        }
                                                        echo '</ul>';
                                                    }
                                                ?>
                                                </li>
                                            <?php
                                            }
                                            echo '</ul>';
                                        }
                                        ?>
                                        </li>
                                    <?php
                                    }
                                ?>
                            </ul>
                            <?php endif; ?>
                        </div>
                        <div class="navMobile">
                            <ul class="navMobile__list">
                                <?php foreach($menuOption['danh_muc_trai'] as $m): ?>
                                    <li <?= $url == $m['url'] ? 'class="active"':null ?>><?= $m['children'] ? '<button><i class="fa fa-caret-down"></i></button>' : null ?><a href="<?= $m['url'] ?>"><?= $m['name'] ?></a>
                                        <?php if(!empty($m['children'])): ?>
                                            <ul class="nav2">
                                                <?php foreach($m['children'] as $mm): ?>
                                                    <li><?= $mm['children'] ? '<button><i class="fa fa-caret-down"></i></button>' : null ?><a href="<?= $mm['url'] ?>"><?= $mm['name'] ?></a>
                                                        <?php if(!empty($mm['children'])): ?>
                                                            <ul>
                                                                <?php foreach ($mm['children'] as $mcc):?>
                                                                    <li><a href="<?= $mcc['url'] ?>"><?= $mcc['name'] ?></a></li>
                                                                <?php endforeach;?>
                                                            </ul>
                                                        <?php endif;?>
                                                    </li>
                                                <?php endforeach; ?>
                                            </ul>
                                        <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    </div>

                    <div class="head__horizontal">
                        <div class="head__formsearch">
                            <form id="search" action="/search" method="get">
                                <input type="text" name="q" placeholder="Tìm kiếm sản phẩm"/>
                                <a href="javascript:{}" onclick="document.getElementById('search').submit();"><i class="fa fa-search"></i></a>
                                <div id="searchFolding"></div>
                            </form>
                        </div>
                        <div class="head__cart">
                            <a class="totalCart" href="/cart">
                                <i class="fa fa-cart-plus"></i>
                                <div>
                                    <p>Giỏ hàng:</p>
                                    <p>(<?= $cartService->getTotalProducts() ?>) Sản phẩm - <?= number_format($cartService->getTotalMoney()).' VNĐ' ?></p>
                                </div>
                            </a>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        </div>
    </div>
</div>

<div class="slide-right">
    <div class="slide-right__inner">
        <a class="slide-right__close"></a>
        <a class="slide-right__cart"><i class="fa fa-shopping-bag" aria-hidden="true"></i><p>Giỏ hàng</p><span><?= $cartService->getTotalProducts() ?></span></a>
    </div>
    <div class="slider-right__content">
        <div class="slider-right__content--inner">
            <?php
                if(!empty($products)):
            ?>
                <h2>Giỏ hàng của tôi (<?= $cartService->getTotalProducts() ?>)</h2>
                <div class="slider-right__money">
                    <p><a href="/cart">Xem giỏ hàng</a></p>
                    <span>Tổng tiền: </span>
                    <strong><?= number_format($cartService->getTotalMoney()).'đ'; ?></strong>
                </div>
                <ul class="slider-right__product">
                    <?php
                        foreach ($products as $p):
                        $imageFirst = '';
                        if(!empty(json_decode($p->getImage(), true))){
                            $imageFirst = array_shift(json_decode($p->getImage(), true));
                        }
                    ?>
                        <li>
                            <a href="<?= $p->getViewLink() ?>">
                                <div class="slider-right__product--left">
                                    <figure class="lazy slider-right__product--image" data-src="<?= $imageFirst ?>"></figure>
                                </div>
                                <h3><?=$p->getTitle() ?>
                                    <p><strong><?= number_format($p->getPriceOld() ? $p->getPriceOld():$p->getPrice()).' đ' ?></strong> x <?= $p->getQuantity() ?></p>
                                </h3>
                            </a>
                            <?= '<span class="deleteCart fa fa-trash-o" data-id="'.$p->getId().'" data-color="'.(isset($p->getOptions()['dataColor']) ? $p->getOptions()['dataColor']->getId():'').'" data-size="'.(isset($p->getOptions()['dataSize']) ? $p->getOptions()['dataSize']->getId():'').'"></span>' ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
                <div class="slider-right__money">
                    <span>Tổng tiền: </span>
                    <strong><?= number_format($cartService->getTotalMoney()).'đ'; ?></strong>
                </div>
                <a class="slider-right__order" href="/cart/checkout">Đặt hàng</a>
            <?php
                endif;
            ?>
        </div>
    </div>
</div>