<?php
$optionBasic = $this->home()->optionBasic();
$optionPage = $this->home()->optionPage();
$url = $this->UriParams()->getRequest()->getRequestUri();
?>
<section class="head">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="head__inner">
                    <div class="logo">
                        <a href="/">
                            <?php if(!empty($optionBasic['logo'])): ?>
                                <img src="<?= $optionBasic['logo'] ?>" alt="Fashion" />
                            <?php endif; ?>
                        </a>
                    </div>
                    <?php
                    $menuOption = $this->home()->getMenu();
                    if(!empty($menuOption['head_menu'])):
                        ?>
                        <div class="navHome">
                            <ul>
                                <?php foreach($menuOption['head_menu'] as $m):?>

                                    <li <?= $url == $m['url'] ? 'class="active"':null ?>><a href="<?= $m['url'] ?>"><?= $m['name'] ?></a>
                                        <?php if(!empty($m['children'])): ?>
                                            <ul>
                                                <?php foreach($m['children'] as $mm): ?>
                                                    <li><a href="<?= $mm['url'] ?>"><?= $mm['name'] ?></a></li>
                                                <?php endforeach; ?>
                                            </ul>
                                        <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                        <div class="head__phone">
                           <!-- <div class="head__phone--left">
                                <p>PHONE: <strong><?/*= !empty($optionPage['dien-thoai']) ? $optionPage['dien-thoai']:'(+1) 876-5445-234' */?></strong></p>
                                <p>EMAIL: <strong><?/*= !empty($optionPage['email']) ? $optionPage['email']:'admin@lunartheme.com' */?></strong></p>
                            </div>-->
                            <div class="head__phone--right">
                                <a class="icon-social-instagram icons" href="<?= !empty($optionPage['youtube']) ? $optionPage['youtube']:null ?>"></a>
                                <a class="icon-social-facebook icons" href="<?= !empty($optionPage['facebook']) ? $optionPage['facebook']:null ?>"></a>
                                <a class="icon-social-twitter icons" href="<?= !empty($optionPage['twitter']) ? $optionPage['twitter']:null ?>"></a>
                                <a class="icon-social-google icons" href="<?= !empty($optionPage['google']) ? $optionPage['google']:null ?>"></a>
                            </div>
                        </div>
                        <a class="button__nav-menu">
                            <span></span>
                            <span></span>
                            <span></span>
                        </a>

                    <?php
                    endif;
                    ?>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="navigation-mobile">
    <ul class="navigation-mobile__list">
        <?php foreach($menuOption['head_menu'] as $m): ?>
            <li <?= $url == $m['url'] ? 'class="active"':null ?>><a href="<?= $m['url'] ?>"><?= $m['name'] ?></a>
                <?php if(!empty($m['children'])): ?>
                    <ul>
                        <?php foreach($m['children'] as $mm): ?>
                            <li><a href="<?= $mm['url'] ?>"><?= $mm['name'] ?></a></li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
