<?php
$user = $this->user;
?>
<div class="account-pages"></div>
<div class="clearfix"></div>
<div class="wrapper-page signin-page">
    <div class="card-box">
        <div class="panel-heading">
            <h3 class="text-center"> Admin </h3>
        </div>
        <div class="panel-body">
            <?php $form = $this->form ?>
            <form method="post" class="form-horizontal m-t-20">
                <div class="form-group">
                    <div class="col-xs-12">
                        <?=$this->formelement($form->get('username')->setAttributes(['class' => 'form-control','placeholder'=>'Tài khoản & Email']))?>
                        <?= $this->formelementerrors($form->get('username'),['class' => 'error'])?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-xs-12">
                        <?=$this->formelement($form->get('password')->setAttributes(['class' => 'form-control','placeholder'=>'Mật khẩu']))?>
                        <?= $this->formelementerrors($form->get('password'),['class' => 'error'])?>
                    </div>
                </div>
                <?php if($user): ?>
                <div class="form-group">
                    <div class="col-xs-12">
                        <label class="signin-page__label">Danh sách website</label>
                        <ul class="signin-page__list">
                        <?php foreach ($user as $u): ?>
                            <li><a><?= $u->getUserName(); ?></a></li>
                        <?php endforeach; ?>
                        </ul>
                    </div>
                </div>
                <?php endif; ?>
                <div class="form-group text-center m-t-40">
                    <div class="col-xs-12">
                        <button class="btn btn-pink btn-block text-uppercase waves-effect waves-light" type="submit">Đăng nhập</button>
                    </div>
                </div>
                <div class="form-group m-t-30 m-b-0">
                    <div class="col-sm-12">
                        <a href="#" class="text-dark"><i class="fa fa-lock m-r-5"></i> Bạn quên mật khẩu ?</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<style>
    .error{
        padding: 0 0 0 5px;
        margin: 0 0;
        position: relative;
        top: 7px;
    }
    .error li{
        list-style: none;
    }
    .signin-page__label {
        font-weight: 400;
    }
    .signin-page__list {
        padding: 0;
        margin: 15px -5px 0;
        display: flex;
        justify-content: space-between;
    }
    .signin-page__list li {
        list-style: none;
        border: 1px solid #DDD;
        padding: 5px;
        margin: 0 5px;
        flex: 1;
        text-align: center;
        border-radius: 3px;
    }
    .signin-page__list li a {
        color: #888;
        cursor: pointer;
        display: block;
    }
</style>

