<?php
    $kk = $this->kk;
    $vv = $this->vv;
    $section = $this->section;
    $id = $this->id;
    $count_item = $this->count_item;
?>
<div class="form-group">
    <label class="col-md-2 control-label"><?= $kk ?></label>
    <div class="col-md-10">
        <?php if($vv['type'] == 'checkbox'): ?>
            <div class="checkbox">
                <input name="<?= $section ?>-<?= $id ?>[<?= $count_item ?>][<?= $vv['keyData'] ?>]"  type="checkbox" class="form-control">
                <label><?= '' ?></label>
            </div>
        <?php elseif($vv['type'] == 'text'): ?>
            <input name="<?= $section ?>-<?= $id ?>[<?= $count_item ?>][<?= $vv['keyData'] ?>]" value="<?= '' ?>" type="text" class="form-control">
        <?php elseif($vv['type'] == 'textarea'): ?>
            <textarea name="<?= $section ?>-<?= $id ?>[<?= $count_item ?>][<?= $vv['keyData'] ?>]" class="form-control"><?= '' ?></textarea>
        <?php elseif($vv['type'] == 'texteditor'): ?>
            <textarea name="<?= $section ?>-<?= $id ?>[<?= $count_item ?>][<?= $vv['keyData'] ?>]" class="textEditor form-control"><?= '' ?></textarea>
        <?php elseif($vv['type'] == 'editorhtml'): ?>
            <div class="panel panel-default">
                <div class="panel-body p-0">
                    <textarea name="<?= $section ?>-<?= $id ?>[<?= $count_item ?>][<?= $vv['keyData'] ?>]" id="codeHtml<?= $section.$id ?>" class="editorHtml form-control"><?= '' ?></textarea>
                </div>
            </div>
        <?php elseif($vv['type'] == 'file'): ?>
            <input type="hidden" class="" value="" id="image_<?= $section ?>-<?= $id ?>" name="<?= $section ?>-<?= $id ?>[<?= $count_item ?>][<?= $vv['keyData'] ?>]">
            <input type="file" class="filestyle filestyleMulti" value="" id="<?= $section ?>-<?= $id ?>" name="<?= $section ?>-<?= $id ?>[<?= $count_item ?>][<?= $vv['keyData'] ?>]">
        <?php elseif($vv['type'] == 'product'): ?>

        <?php endif; ?>
    </div>
</div>