<?php
    $fields = $this->fields;
    $section = $this->section;
    $id = $this->id;
    $type_field = $this->fields['type'];
    $count_item = $this->row_id;
?>
<?php if(!empty($fields)): ?>
    <div class="repeater-item">
        <?php
            $viewModel = new \Zend\View\Model\ViewModel();
            $viewModel->setTemplate("admin/setup/fields");
            $viewModel->setVariables(array(
                'fields' => $fields,
                'section' => $section,
                'id' => $id,
                'type_field' => $type_field,
                'count_item' => $count_item,
            ));
            echo $this->render($viewModel);
        ?>
        <div class="control">
            <span class="repeater-number"><?php echo $count_item ?></span>
            <a href="#" class="table-action-btn"><i class="md md-close"></i></a>
        </div>
    </div>
<?php endif; exit(); ?>