<?php
    echo $this->headtitle($this->escapehtml($this->translate('Cài đặt robots / sitemap')));
    $form = $this->form;
    $value = $this->value;
    $robot = $this->robot;
    $xml = $this->xml;
?>

<form method="post" enctype="multipart/form-data" data-parsley-validate novalidate>
    <div class="row">
        <div class="col-sm-12">
            <div class="card-box ">
                <ol class="breadcrumb p-t-0 m-b-0">
                    <li>
                        <a class="header-title" href="/admin/setup"><i class="ion-reply"></i> Cấu hình</a>
                    </li>
                </ol>
                <p class="text-muted m-b-15 font-13">
                    Cập nhật nội dung file robot.txt / sitemaps.xml
                </p>
                <div class="row">
                    <div class="col-sm-12">

                        <div class="row">
                            <div class="col-sm-12">
                                <div class="panel panel-color panel-inverse">
                                    <div class="panel-heading">
                                        <h3 class="panel-title">Robots.txt</h3>
                                        <small class="text-muted"><a class="text-muted" target="_blank" href="http://<?= $robot ?>">http://<?= $robot ?></a></small>
                                    </div>
                                    <div class="panel-body p-0 code-edit-wrap">
                                        <?= $this->formelement($form->get('robots')->setAttributes(['class' => 'form-control','id' => 'robots', 'placeholder'=>'Robot.txt'])) ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="panel panel-color panel-inverse">
                                    <div class="panel-heading">
                                        <h3 class="panel-title">Sitemap.xml</h3>
                                        <small class="text-muted"><a class="text-muted" target="_blank" href="http://<?= $xml ?>">http://<?= $xml ?></a></small>
                                    </div>
                                    <div class="panel-body p-0 code-edit-wrap">
                                        <?= $this->formelement($form->get('xml')->setAttributes(['class' => 'form-control','id' => 'xml', 'placeholder'=>'Nội dung file xml'])) ?>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="form-actions m-t-10">
                            <?=$this->formelement($form->get('submit')->setAttributes(['class' => 'btn btn-default']))?>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
