<?php
    $fields = $this->fields;
    $section = $this->section;
    $id = $this->id;
?>
<?php if(!empty($fields)): ?>
    <div  class="portlet <?= vnString($fields['label']); ?>">
        <div class="portlet-heading portlet-default collapsed" data-toggle="collapse" data-parent="#<?= $section.$id ?>" href="#<?= $section.$id ?>" aria-expanded="false">
            <h3 class="portlet-title">  <?= $fields['label'] ?> </h3>
            <div class="portlet-widgets">
                <a class="btn__delete--module" data-module="<?= vnString($fields['label']); ?>"><i class="ion-trash-a"></i></a>
                <span class="divider"></span>
                <a class=""><i class="ion-minus-round"></i></a>
            </div>
            <div class="clearfix"></div>
        </div>
        <div id="<?= $section.$id ?>" class="panel-collapse collapse" aria-expanded="false">
            <div class="portlet-body">
                <?php
                    foreach ($fields['fields'] as $kk => $vv):
                ?>
                <div class="form-group">
                    <label class="col-md-2 control-label"><?= $kk ?></label>
                    <div class="col-md-10">
                        <?php if($vv['type'] == 'checkbox'): ?>
                            <div class="checkbox">
                                <input name="<?= $section ?>-<?= $id ?>[<?= $vv['keyData'] ?>][0]"  type="checkbox" class="form-control">
                                <label><?= '' ?></label>
                            </div>
                        <?php elseif($vv['type'] == 'text'): ?>
                            <input name="<?= $section ?>-<?= $id ?>[<?= $vv['keyData'] ?>][0]" value="<?= '' ?>" type="text" class="form-control">
                        <?php elseif($vv['type'] == 'textarea'): ?>
                            <textarea name="<?= $section ?>-<?= $id ?>[<?= $vv['keyData'] ?>][0]" class="form-control"><?= '' ?></textarea>
                        <?php elseif($vv['type'] == 'texteditor'): ?>
                            <textarea name="<?= $section ?>-<?= $id ?>[<?= $vv['keyData'] ?>][0]" class="textEditor form-control"><?= '' ?></textarea>
                        <?php elseif($vv['type'] == 'editorhtml'): ?>
                            <div class="panel panel-default">
                                <div class="panel-body p-0">
                                    <textarea name="<?= $section ?>-<?= $id ?>[<?= $vv['keyData'] ?>][0]" id="codeHtml<?= $section.$id ?>" class="editorHtml form-control"><?= '' ?></textarea>
                                </div>
                            </div>
                        <?php elseif($vv['type'] == 'file'): ?>
                            <input type="hidden" class="" value="" id="image_<?= $section ?>-<?= $id ?>" name="<?= $section ?>-<?= $id ?>[<?= $vv['keyData'] ?>][0]">
                            <input type="file" class="filestyle filestyleMulti" value="" id="<?= $section ?>-<?= $id ?>" name="<?= $section ?>-<?= $id ?>[<?= $vv['keyData'] ?>][0]">
                        <?php elseif($vv['type'] == 'product'): ?>

                        <?php endif; ?>
                    </div>
                </div>
                <?php  endforeach; ?>
            </div>
        </div>
    </div>
<?php endif; exit(); ?>