<?php
    $fields = $this->fields;
    $section = $this->section;
    $id = $this->id;
    $type_field = $this->fields['type'];
    $count_item = 1;
?>

<?php if(!empty($fields)):

    ?>
    <div  class="portlet <?= vnString($fields['label']); ?>">
        <div class="portlet-heading portlet-default collapsed" data-toggle="collapse" data-parent="#<?= $section.$id ?>" href="#<?= $section.$id ?>" aria-expanded="false">
            <h3 class="portlet-title">  <?= $fields['label'] ?> </h3>
            <div class="portlet-widgets">
                <a class="btn__delete--module" data-module="<?= $section; ?>"><i class="ion-trash-a"></i></a>
                <span class="divider"></span>
                <a class=""><i class="ion-minus-round"></i></a>
            </div>
            <div class="clearfix"></div>
        </div>
        <div id="<?= $section.$id ?>" class="panel-collapse collapse" aria-expanded="false">
            <div class="portlet-body <?php echo $type_field.'-inner' ?>">
                <?php if($type_field == 'repeater'): ?>
                    <input type="hidden" class="repeater_count" value="<?php echo $count_item ?>">
                    <input type="hidden" class="repeater_id" value="<?php echo $section.$id ?>">
                    <input type="hidden" class="repeater_layout" value="<?php echo $section ?>">
                    <div class="repeater__list">
                    <div class="repeater-item">
                <?php endif; ?>
                <?php
                    $viewModel = new \Zend\View\Model\ViewModel();
                    $viewModel->setTemplate("admin/setup/fields");
                    $viewModel->setVariables(array(
                        'fields' => $fields,
                        'section' => $section,
                        'id' => $id,
                        'type_field' => $type_field,
                        'count_item' => $count_item,
                    ));;
                    echo $this->render($viewModel);
                ?>
                <?php if($type_field == 'repeater'): ?>
                        <div class="control">
                            <span class="repeater-number"><?php echo 1 ?></span>
                        </div>
                    </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="btn-group pull-right">
                                <a class="add-row btn btn-default waves-effect waves-light">Add Row</a>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
<?php endif; exit(); ?>