<?php
    use Home\Model\DateBase;
    $view = $this->news;
    $url = $this->UriParams()->getRequest()->getRequestUri();
    $image = json_decode($view->getImage(), true);
    $imageFirst = '';
    if(!empty($image)){
        $imageFirst = array_shift($image);
    }
    $category = $this->NewsCategory()->getCategories();

    $this->headTitle($this->escapeHtml($this->translate(html_entity_decode($view->getTitle()))));

    $this->headMeta()->appendName('keywords', ($view->getMetaKeyword()));
    $this->headMeta()->appendName('description', ($view->getMetaDescription()));

    $this->headMeta()->appendProperty('fb:app_id', '1697190970583102');
    $this->headMeta()->appendProperty('article:author', 'https://www.facebook.com/dwebvietnam');
    $this->headMeta()->appendProperty('og:locale', 'vi_VN');
    $this->headMeta()->appendProperty('og:image',  'http://'.$_SERVER["SERVER_NAME"].$imageFirst );
    $this->headMeta()->appendProperty('og:url', 'http://'.$_SERVER["SERVER_NAME"].$url);
    $this->headMeta()->appendProperty('og:title', $view->getTitle() );
    $this->headMeta()->appendProperty('og:description', ($view->getMetaDescription()));

    $this->headMeta()->appendProperty('twitter:card', $_SERVER["SERVER_NAME"]);
    $this->headMeta()->appendProperty('twitter:title', $view->getTitle());
    $this->headMeta()->appendProperty('twitter:image', 'http://'.$_SERVER["SERVER_NAME"].$imageFirst);
    $this->headMeta()->appendProperty('twitter:description', $view->getMetaDescription());

    $optionPage = $this->home()->optionPage();

?>


<section class="news-category">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="news__category">
                    <ul class="news__list-category">
                        <?php if(!empty($category)): ?>
                            <?php foreach($category as $t): ?>
                                <li><a <?= $view->getCategoryId() == $t->getId() ? 'class="active"':null ?> href="<?= $t->getViewLink() ?>"><?= $t->getName() ?></a></li>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

<?php
    if($view->getType() == 2):
        echo $this->render('news/news/gallery');
    else:
 ?>
    <section class="single-news">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <figure class="lazy single-news__image" data-src="<?= $imageFirst ?>"></figure>
                    <div class="single-news__detail">
                        <h1 class="single-news__title"><?= $view->getTitle() ?></h1>
                        <div class="single-news__profile">
                            <span><i class="fa fa-clock-o"></i><?= DateBase::toFormat($view->getCreatedDateTime(), 'd/m/Y') ?></span><span><i class="fa fa-folder-o"></i><?= $view->getCateName() ?></span><span><i class="fa fa-eye"></i><?= $view->getView() ?></span>
                        </div>
                        <div class="single-news__content">
                            <?php
                                echo html_entity_decode($view->getContent());
                            ?>
                        </div>

                        <div class="single-news__relation">
                            <?php
                                $relation = json_decode($view->getArticleRelated(), true);
                                if(!empty($relation)) {
                                    echo '<h2 class="single-news__relation--title">Bài viết liên quan</h2>';
                                    echo '<ul>';
                                    foreach($relation as $r) {
                            ?>
                                <li><i class="fa fa-caret-right"></i><a href="<?= $r['url'] ?>"><?= $r['title'] ?></a></li>
                            <?php
                                    }
                                echo '</ul>';
                                }
                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
<?php endif; ?>

