<?php
echo $this->doctype();
$optionBasic = $this->home()->optionBasic();
$url = $this->UriParams()->getRequest()->getRequestUri();
?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
        <link rel="stylesheet" id="Open_Sans_sub-css" href="//fonts.googleapis.com/css?family=Open+Sans%3A200%2C300%2C400%2C400italic%2C700&amp;v1&amp;subset=latin%2Clatin-ext" type="text/css" media="screen" />
        <?php
        echo $this->headTitle()->setSeparator('')->setAutoEscape(false);
        $this->headMeta()->appendName('DC.language', 'scheme=utf-8 content=vi');
        echo $this->headMeta();

        echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $optionBasic['favicon'] ? $optionBasic['favicon']:null ]);
        $cs = [
            '/tp/A012/css/bootstrap.css',
            '/assets/css/web/font-awesome.min.css',
            '/tp/A012/css/simple-line-icons.css',
            '/assets/css/web/owl.carousel.css',
            '/assets/css/web/owl.theme.css',
            '/assets/css/web/owl.transitions.css',
            '/tp/A012/css/h.css',
        ];
        echo '<link href="'.srcLink($cs,2).'" media="screen" rel="stylesheet" type="text/css">';
        $js = [
            '/assets/js/web/jquery-1.11.2.min.js',
        ];
        echo '<script type="text/javascript" src="'.srcLink($js,1).'"></script>';
        echo !empty($optionBasic['scriptHead']) ? '<script>'.$optionBasic['scriptHead'].'</script>' : null;
        ?>
    </head>
    <?php
        $url2 = $this->home()->getMcaName('module');
    ?>
    <body <?= $url2 == 'home' ? 'class="home"':null ?>>
        <?php
            echo $this->render('layout/header');
            echo $this->content;
            echo $this->render('layout/footer');
            echo !empty($optionBasic['scriptBody']) ? '<script>'.$optionBasic['scriptBody'].'</script>' : null;
        ?>
    </body>

    <?php
        $r = [
            '/tp/A012/css/r.css',
        ];
        echo '<link href="'.srcLink($r,1).'" media="screen" rel="stylesheet" type="text/css">';
        if(!empty($optionBasic['styleFooter'])) echo '<style>'.$optionBasic['styleFooter'].'</style>';
        $js = [
            '/assets/js/web/bootstrap.min.js',
            '/assets/js/web/jquery.lazy.min.js',
            '/assets/js/web/owl.carousel.js',
            '/assets/js/web/jquery-ui-1.10.3.custom.min.js',
            '/assets/plugins/parsleyjs/parsley.min.js',
            '/tp/A012/js/a.js',
            '/tp/dweb/js/waypoint/jquery.waypoints.min.js',
            '/tp/dweb/js/jquery-modal-video.min.js'
        ];
        echo '<script type="text/javascript" src="'.srcLink($js,3).'"></script>';
        echo !empty($optionBasic['scriptFooter']) ? '<script>'.$optionBasic['scriptFooter'].'</script>' : null;
    ?>
    <?= $this->render('layout/modal'); ?>
</html>