<?php
$paginator =  $this->paginator;
$category = $this->category;
$this->headTitle($this->escapeHtml($this->translate($category->getName())));
$this->headMeta()->appendName('description', ($category->getName()));
$this->headMeta()->appendName('keywords', ($category->getName()));
$this->headMeta()->appendProperty('og:title', $category->getName());
$cs = [
    '/tp/agiay/css/n.css'
];
echo '<link href="'.srcLink($cs,1).'" media="screen" rel="stylesheet" type="text/css">';
?>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <?php
                $n = $this->newsCategory()->getCategories();
                if(count($n)){
                    echo '<ul class="navNews">';
                    echo '<li><a href="/news">Tất cả</a></li>';
                    foreach($n as $b){
                        echo '<li><a '.($category->getId() == $b->getId() ? 'class="active"':'').' href="'.$b->getViewLink().'">'.$b->getName().'</a></li>';
                    }
                    echo '</ul>';
                }
            if(count($paginator)){
                echo '<ul class="lN lNCategory">';
                foreach($paginator as $n){
                    $image = json_decode($n->getImage(), true);
                    if(!empty($image)){
                        $imageFirst = array_shift($image);
                    }

                    echo '<li>
                        <a href="'.$n->getViewLink().'"><figure class="lazy image-article" data-src="'. (!empty($imageFirst) ? $imageFirst:null).'"></figure></a>
                        <h2><a href="'.$n->getViewLink().'">'.$n->getTitle().'</a></h2>
                    </li>';
                }
                echo '</ul>';
                echo '<div class="paginatorProduct">';
                    echo $this->paginationControl($this->paginator, 'Elastic', 'partial/listPage');
                echo '</div>';
            }
            ?>
        </div>
    </div>
</div>
