<?php
    $cs = [
        '/tp/A001/css/p.css'
    ];
    echo '<link href="'.srcLink($cs,1).'" media="screen" rel="stylesheet" type="text/css">';
?>
<div class="main">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="right">
                    <div class="contentPage">
                        <?php
                            echo html_entity_decode($this->page->getDescription());
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>