<?php
    echo $this->headtitle($this->escapehtml($this->translate('Danh sách Menu')));
    $product = $this->product;
    $article = $this->article;
    $keyMenu = $this->keyMenu;
    $page = $this->page;
?>
<div class="row">
    <div class="col-sm-12">
        <div class="card-box">
            <div class="row">
                <div class="col-sm-6">
                    <div>
                        <label class="control-label" for="uitemplateId">Cài đặt Menu</label>
                        <p class="text-muted m-b-15 font-13">
                            Các Menu có trong mỗi giao diện là khác nhau.<br/>Bạn có thể thêm mới Menu phía bên phải, và xoá Menu ở phía trái.
                        </p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <ul class="nav nav-tabs navtab-bg nav-justified">
                        <?php
                        $c = 0;
                        foreach($keyMenu as $k):
                            $c++;
                            ?>
                            <li class="<?= $c == 1 ? 'active':'' ?>">
                                <a href="#<?= $k->getNameKey(); ?>" data-toggle="tab" aria-expanded="<?= $c == 1 ? 'true':'false' ?>">
                                    <span class="visible-xs"><i class="fa fa-home"></i></span>
                                    <span class="hidden-xs"><?= $k->getName(); ?></span>
                                </a>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                    <div class="tab-content tab-content__menu">
                        <?php
                        $c = 0;
                        foreach($keyMenu as $k):
                            $c++;
                            ?>
                            <div class="tab-pane <?= $c == 1 ? 'active':'' ?>" id="<?= $k->getNameKey(); ?>">
                                <input type="hidden" class="dataMenu" />
                                <div class="form-group">
                                    <div class="custom-dd dd menuDweb" id="menu">
                                        <ol class="dd-list outer">
                                        <?php
                                            if(!empty($k->getMenu())):
                                            $menuKey = json_decode($k->getMenu(), true);
                                            if(!empty($menuKey)):
                                            foreach($menuKey as $m):
                                        ?>
                                                <li class="dd-item" data-id="<?= !empty($m['id']) ? $m['id']:'' ?>" data-image="<?= !empty($m['image']) ? $m['image']:'' ?>" data-url="<?= !empty($m['url']) ? $m['url']:'' ?>" data-category="<?= !empty($m['category']) ? $m['category']:'' ?>" data-name="<?= !empty($m['name']) ? $m['name']:'' ?>">
                                                    <button class="dd-action pull-right" type="button" data-action="remove" title="Remove"><i class="ti-close"></i></button>
                                                    <div class="dd-handle"><?= !empty($m['name']) ?$m['name']:'' ?></div>
                                                    <?php if(!empty($m['children'])): ?>
                                                    <ol class="dd-list">
                                                        <?php foreach($m['children'] as $mm): ?>
                                                        <li class="dd-item" data-id="<?= !empty($mm['id']) ? $mm['id']:'' ?>" data-image="<?= !empty($mm['image']) ? $mm['image']:'' ?>" data-url="<?= !empty($mm['url']) ? $mm['url']:'' ?>" data-category="<?= !empty($mm['category']) ? $mm['category']:'' ?>" data-name="<?= !empty($mm['name']) ? $mm['name']:'' ?>">
                                                            <button class="dd-action pull-right" type="button" data-action="remove" title="Remove"><i class="ti-close"></i></button>
                                                            <div class="dd-handle"><?= !empty($mm['name']) ?$mm['name']:'' ?></div>
                                                            <?php if(!empty($mm['children'])): ?>
                                                            <ol class="dd-list">
                                                                <?php foreach($mm['children'] as $mmm): ?>
                                                                    <li class="dd-item" data-id="<?= !empty($mmm['id']) ? $mmm['id']:'' ?>" data-image="<?= !empty($mmm['image']) ? $mmm['image']:'' ?>" data-url="<?= !empty($mmm['url']) ? $mmm['url']:'' ?>" data-category="<?= !empty($mmm['category']) ? $mmm['category']:'' ?>" data-name="<?= !empty($mmm['name']) ? $mmm['name']:'' ?>">
                                                                        <button class="dd-action pull-right" type="button" data-action="remove" title="Remove"><i class="ti-close"></i></button>
                                                                        <div class="dd-handle"><?= !empty($mmm['name']) ?$mmm['name']:'' ?></div>
                                                                        <?php if(!empty($mmm['children'])): ?>
                                                                            <ol class="dd-list">
                                                                                <?php foreach($mmm['children'] as $mmmm): ?>
                                                                                    <li class="dd-item" data-id="<?= !empty($mmmm['id']) ? $mmmm['id']:'' ?>" data-image="<?= !empty($mmmm['image']) ? $mmmm['image']:'' ?>" data-url="<?= !empty($mmmm['url']) ? $mmmm['url']:'' ?>" data-category="<?= !empty($mmmm['category']) ? $mmmm['category']:'' ?>" data-name="<?= !empty($mmmm['name']) ? $mmmm['name']:'' ?>">
                                                                                        <button class="dd-action pull-right" type="button" data-action="remove" title="Remove"><i class="ti-close"></i></button>
                                                                                        <div class="dd-handle"><?= !empty($mmmm['name']) ?$mmmm['name']:'' ?></div>
                                                                                    </li>
                                                                                <?php endforeach; ?>
                                                                            </ol>
                                                                        <?php endif; ?>
                                                                    </li>
                                                                <?php endforeach; ?>
                                                            </ol>
                                                            <?php endif; ?>
                                                        </li>
                                                        <?php endforeach; ?>
                                                    </ol>
                                                    <?php endif; ?>
                                                </li>
                                        <?php
                                            endforeach;
                                            endif;
                                            endif;
                                        ?>
                                        </ol>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <button data-key="<?= $k->getNameKey(); ?>" class="saveMenu btn btn-default waves-effect waves-light">Lưu</button>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>

                <div class="col-sm-6">
                    <form class="form-horizontal formAddMenu" role="form" data-parsley-validate novalidate>
                        <div class="form-group">
                            <label for="name" class="col-sm-4 control-label">Tên</label>
                            <div class="col-sm-8">
                                <input type="text" required="" class="inputMenu form-control" data-parsley-error-message="Tên menu không được để trống" placeholder="Tên Menu">
                            </div>
                        </div>
                        <div class="form-group urlMain">
                            <label for="inputEmail3" class="col-sm-4 control-label">Đường dẫn</label>
                            <div class="col-sm-6">
                                <div class="menuOption">
                                    <select class="form-control select2 pathMenu">
                                        <optgroup label="Trang">
                                            <option data-url="/">Trang chủ</option>
                                            <option data-url="/bai-viet.html">Danh sách bài viết</option>
                                            <option data-url="/san-pham.html">Danh sách sản phẩm</option>
                                            <?php if(!empty($page)): foreach($page as $a): ?>
                                                <option data-id="<?= $a->getId() ?>" data-url="<?= $a->getViewLink() ?>"><?= $a->getName() ?></option>
                                            <?php endforeach; endif; ?>
                                        </optgroup>
                                        <?php if(!empty($article)): ?>
                                        <optgroup label="Danh mục tin tức">
                                            <?php foreach($article as $a): ?>
                                                <option data-id="<?= $a->getId() ?>" data-url="<?= $a->getViewLink() ?>"><?= $a->getName() ?></option>
                                            <?php endforeach; ?>
                                        </optgroup>
                                        <?php endif; ?>
                                        <?php if(!empty($product)): ?>
                                            <optgroup label="Danh mục sản phẩm">
                                                <?php foreach($product as $a): ?>
                                                    <option data-id="<?= $a->getId() ?>" data-url="<?= $a->getViewLink() ?>"><?= $a->getName() ?></option>
                                                <?php endforeach; ?>
                                            </optgroup>
                                        <?php endif; ?>
                                    </select>
                                </div>
                                <input type="text" class="urlHand form-control" placeholder="Đường dẫn tự viết">
                            </div>
                            <div class="col-sm-2"><a class="btnCustomUrl btn btn-white waves-effect">Tự viết</a></div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-4 control-label">Hình ảnh</label>
                            <div class="col-sm-8 wrapper-image">
                                <input type="file" id="menuImage" class="filestyle" data-buttonText="Chọn Hình" data-buttonname="btn-white" data-iconname="fa fa-cloud-upload">
                                <input type="hidden" class="menuImage" value="" />
                                <div class="captionImage"></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-4 col-sm-8">
                                <button type="submit" class="addMenu btn btn-default waves-effect waves-light">Thêm</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
