<?php
    echo $this->headtitle($this->escapehtml($this->translate('Thêm đoạn mã Script/CSS')));
    $form = $this->form;
    $value = $this->value;
?>

<form method="post" enctype="multipart/form-data" data-parsley-validate novalidate>
    <div class="row">
        <div class="col-sm-12">
            <div class="card-box ">
                <ol class="breadcrumb p-t-0 m-b-0">
                    <li>
                        <a class="header-title" href="/admin/setup"><i class="ion-reply"></i> Cấu hình</a>
                    </li>
                </ol>
                <p class="text-muted m-b-15 font-13">
                    Các đoạn mã javscript, css thêm ở đây.
                </p>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                        <h3 class="panel-title">CSS</h3>
                                        <small>Các bạn có thể thêm đoạn mã css ở đây.</small>
                                        <div class="m-t-10"></div>
                                    </div>
                                    <div class="panel-body p-0 code-edit-wrap">
                                        <?= $this->formelement($form->get('styleFooter')->setAttributes(['class' => 'form-control','id' => 'code3', 'placeholder'=>'Style CSS'])) ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="panel panel-color panel-inverse">
                                    <div class="panel-heading">
                                        <h3 class="panel-title">Script head</h3>
                                        <small class="text-muted">Các đoạn mã trong thẻ Head.</small>
                                    </div>
                                    <div class="panel-body p-0 code-edit-wrap">
                                        <?= $this->formelement($form->get('scriptHead')->setAttributes(['class' => 'form-control','id' => 'scriptHead', 'placeholder'=>'Các đoạn mã script trên head'])) ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="panel panel-color panel-inverse">
                                    <div class="panel-heading">
                                        <h3 class="panel-title">Script in body</h3>
                                        <small class="text-muted">Các đoạn mã trong thẻ Body.</small>
                                    </div>
                                    <div class="panel-body p-0 code-edit-wrap">
                                        <?= $this->formelement($form->get('scriptBody')->setAttributes(['class' => 'form-control','id' => 'scriptBody', 'placeholder'=>'Các đoạn mã script trong body'])) ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="panel panel-color panel-inverse">
                                    <div class="panel-heading">
                                        <h3 class="panel-title">Script Footer</h3>
                                        <small class="text-muted">Các đoạn mã script footer, Live chat, Google Analytics, Facebook Pixel ID</small>
                                    </div>
                                    <div class="panel-body p-0 code-edit-wrap">
                                        <?= $this->formelement($form->get('scriptFooter')->setAttributes(['class' => 'form-control','id' => 'scriptFooter', 'placeholder'=>'Các đoạn mã trong footer'])) ?>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="form-actions m-t-10">
                            <?=$this->formelement($form->get('submit')->setAttributes(['class' => 'btn btn-default']))?>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
