<?php
echo $this->doctype();
$optionBasic = $this->home()->optionBasic();
$url = $this->UriParams()->getRequest()->getRequestUri();
?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,400,700" rel="stylesheet">
        <?php
        echo $this->headTitle()->setSeparator('')->setAutoEscape(false);
        $this->headMeta()->appendName('DC.language', 'scheme=utf-8 content=vi');
        echo $this->headMeta();

        echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $optionBasic['favicon'] ? $optionBasic['favicon']:null ]);
        $cs = [
            '/tp/A015/css/bootstrap.css',
            '/assets/css/web/font-awesome.min.css',
            '/tp/A015/css/simple-line-icons.css',
            '/assets/css/web/owl.carousel.css',
            '/assets/css/web/owl.theme.css',
            '/assets/css/web/owl.transitions.css',
            '/tp/A015/css/h.css',
        ];
        echo '<link href="'.srcLink($cs,2).'" media="screen" rel="stylesheet" type="text/css">';
        $js = [
            '/assets/js/web/jquery-1.11.2.min.js',
        ];
        echo '<script type="text/javascript" src="'.srcLink($js,1).'"></script>';
        echo !empty($optionBasic['scriptHead']) ? '<script>'.$optionBasic['scriptHead'].'</script>' : null;
        ?>
    </head>
    <?php
        $url2 = $this->home()->getMcaName('module');
    ?>
    <body <?= $url2 == 'home' ? 'class="home"':null ?>>
        <span class="line-hozi line-first"></span>
        <span class="line-hozi line-center"></span>
        <span class="line-hozi line-last"></span>
        <?php
            echo $this->render('layout/header');
            echo $this->content;
            echo $this->render('layout/footer');
            echo !empty($optionBasic['scriptBody']) ? '<script>'.$optionBasic['scriptBody'].'</script>' : null;
        ?>
    </body>

    <?php
        $r = [
            '/tp/A015/css/r.css',
        ];
        echo '<link href="'.srcLink($r,1).'" media="screen" rel="stylesheet" type="text/css">';
        $js = [
            '/assets/js/web/bootstrap.min.js',
            '/assets/js/web/jquery.lazy.min.js',
            '/assets/js/web/owl.carousel.js',
            '/assets/js/web/jquery-ui-1.10.3.custom.min.js',
            '/assets/plugins/parsleyjs/parsley.min.js',
            '/tp/A015/js/a.js',
            '/tp/dweb/js/waypoint/jquery.waypoints.min.js',
            '/tp/dweb/js/jquery-modal-video.min.js'
        ];
        echo '<script type="text/javascript" src="'.srcLink($js,3).'"></script>';
        echo !empty($optionBasic['scriptFooter']) ? '<script>'.$optionBasic['scriptFooter'].'</script>' : null;
    ?>
    <?= $this->render('layout/modal'); ?>
</html>