<?php if(!empty($this->introLayout['intro-title text']['value']) || !empty($this->introLayout['intro-content textarea']['value'])
 || !empty($this->introLayout['intro-image file']['value'])):?>
<?php //echo "<pre>"; print_r($this->introLayout); echo "</pre>"?>
<section class="intro">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="intro__inner">
                    <div class="intro__left">
                        <div class="intro-right__inner">
                            <figure class="lazy intro__image" data-src="<?= $this->introLayout['intro-image file']['value'] ? $this->introLayout['intro-image file']['value'] : ''?>">
                                <div class="intro__image--content"><span></span></div>
                                <div class="intro__image--content"><span></span></div>
                            </figure>
                        </div>
                    </div>
                    <div class="intro__right">
                        <h3 class="intro__title">
                            <span><?= $this->introLayout['intro-title text']['value'] ? $this->introLayout['intro-title text']['value'] : ''?></span>
                        </h3>
                        <p class="intro__content">
                            <?= $this->introLayout['intro-content texteditor']['value'] ? $this->introLayout['intro-content texteditor']['value'] : ''?>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<?php endif;?>