<?php  use Home\Model\DateBase;
    if(!empty($this->newsLayout['news-list article']['news-list'])):
?>
<section class="news">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2 class="titleHome">
                    <span><?= $this->newsLayout['news-title text']['value'] ?></span>
                </h2>
                <?php $slider = $this->newsLayout['news-slider-checkbox checkbox']['value']?>
                <ul class="<?= $slider ? 'news-slider owl-carousel owl-theme' : 'lN' ?> news__list">
                    <?php
                    foreach($this->newsLayout['news-list article']['news-list'] as $k => $n):
                        $image = json_decode($n['image'], true);
                        if(!empty($image)){
                            $imageFirst = array_shift($image);
                        }
                        ?>
                        <li class="news-item">
                            <div class="news-item__inner">
                                <div>
                                    <figure class="lazy image-article" data-src="<?= !empty($imageFirst) ? $imageFirst:'' ?>">
                                    </figure>
                                </div>
                                <div class="news-item__info">
                                    <p class="news-item__content">
                                        <?= $n['intro'] ?>
                                    </p>
                                    <p>
                                        <i class="fa fa-tree" aria-hidden="true"></i>
                                        <i class="fa fa-tree" aria-hidden="true"></i>
                                        <i class="fa fa-tree" aria-hidden="true"></i>
                                    </p>
                                    <a href="<?= $n['url'] ?>" title="<?= $n['title'] ?>">
                                        <h3>
                                            <?= $n['title'] ?>
                                            <br>
                                            <sub>Đọc thêm</sub>
                                        </h3>
                                    </a>
                                </div>
                            </div>
                        </li>
                        <?php
                    endforeach;
                    ?>
                </ul>
            </div>
        </div>
    </div>
</section>
<?php endif;?>