<?php
    $optionBasic = $this->home()->optionBasic();
    $optionPage = $this->home()->optionPage();
    $url = $this->UriParams()->getRequest()->getRequestUri();
    $cartService = $this->cart()->getServiceCart();
    $products = $cartService->getProducts();
    $menuOption = $this->home()->getMenu();
?>
<div class="head">
    <div class="head1">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <h2>CHÀO MỪNG BẠN ĐẾN VỚI HỆ THỐNG SIÊU THỊ NỘI THẤT !</h2>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <ul class="RegisterLogin">
                        <?php if(!empty($menuOption['header_menu'])):
                            foreach($menuOption['header_menu'] as $m):
                        ?>
                        <li <?= $url == $m['url'] ? 'class="active"':null ?>>
                            <a href="<?= $m['url'] ?>"><?= $m['name'] ?></a>
                        </li>
                        <?php endforeach;
                            endif;
                        if ($this->user()->hasIdentity()) {
                            ?>
                            <li><a>Xin chào: <?= $this->user()->getUser()->getFullName() ? $this->user()->getUser()->getFullName():ucfirst($this->user()->getUser()->getUserName()) ?></a></li>
                            <li><a href="/user/signout">Thoát</a></li>
                        <?php
                        }else{
                            ?>
                            <li><a href="/user/signup">Đăng ký</a></li>
                            <li><a href="/user/signin">Đăng nhập</a></li>
                        <?php
                        }
                        ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="head2">
        <div class="container">
            <div class="row">
                <div class="head2__inner">
                    <div class="col-xs-6 col-xs-offset-3 col-sm-offset-0 col-sm-12 col-md-2 col-lg-2">
                        <a class="logo" href="/">
                            <?php if(!empty($optionBasic['logo'])): ?>
                                <img src="<?= $optionBasic['logo'] ?>" alt="<?= !empty($optionBasic['sologan']) ? $optionBasic['sologan']:null ?>" />
                            <?php endif; ?>
                        </a>
                    </div>
                    <div class="col-lg-6 col-md-6 col-xs-12">
                        <form id="search" action="/search" method="get">
                            <input type="text" name="q" placeholder="Tìm kiếm sản phẩm bạn muốn mua tại đây"/>
                            <a href="javascript:{}" onclick="document.getElementById('search').submit();">
                                <i class="fa fa-search"></i>
                            </a>
                            <div id="searchFolding"></div>
                        </form>
                    </div>
                    <div class="col-lg-4 col-md-4">
                        <div class="head2__inner-left">
                            <a class="head2__tel" href="tel:<?= $optionPage['so-dien-thoai-tu-van'] ?>">
                                <div class="head2__tel-img">
                                    <figure class="lazy" data-src="/tp/T012/img/icon_phone.png"></figure>
                                </div>
                                <div class="head2__tel-inner">
                                    <p>Hotline: </p>
                                    <span><?= !empty($optionPage['so-dien-thoai-tu-van']) ? $optionPage['so-dien-thoai-tu-van']:'' ?></span>
                                </div>
                            </a>
                            <a class="totalCart" href="/cart">
                                <i class="fa fa-cart-plus"></i>
                                <p>Giỏ hàng: (<?= $cartService->getTotalProducts() ?>)</p>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="head3">
        <div class="container">
            <div class="row">
            <div class="col-md-12">
                <div class="CategoryShip">
                    <div class="categoryHome">
                        <h2>
                            <i class="fa fa-bars"></i>Danh mục sản phẩm
                            <span></span>
                        </h2>
                        <div class="navHome">
                            <?php
                                $menuOption = $this->home()->getMenu();
                                if(!empty($menuOption['danh_muc_trai'])):
                            ?>
                            <ul>
                                <?php
                                    foreach($menuOption['danh_muc_trai'] as $c){
                                        ?>
                                        <li>
                                        <a href="<?= $c['url'] ?>">
                                            <?= $c['name'] ?>
                                        </a>
                                        <?= !empty($c['children']) ? '<span class="icon-caret"></span>':null ?>
                                        <?php
                                        if(isset($c['children'])){
                                            echo '<ul class="nav2">';
                                            foreach($c['children'] as $cc){
                                                ?>
                                                <li><a href="<?= $cc['url'] ?>"><?= $cc['name'] ?></a>
                                                <?= !empty($cc['children']) ? '<span class="icon-caret"></span>':null ?>
                                                <?php
                                                    if(isset($cc['children'])){
                                                        echo '<ul class="nav3">';
                                                        foreach($cc['children'] as $ccc){
                                                            ?>
                                                            <li><a href="<?= $ccc['url'] ?>"><?= $ccc['name'] ?></a></li>
                                                        <?php
                                                        }
                                                        echo '</ul>';
                                                    }
                                                ?>
                                                </li>
                                            <?php
                                            }
                                            echo '</ul>';
                                        }
                                        ?>
                                        </li>
                                    <?php
                                    }
                                ?>
                            </ul>
                            <?php endif; ?>
                        </div>
                        <div class="navMobile">
                            <ul class="navMobile__list">
                                <?php foreach($menuOption['danh_muc_trai'] as $m): ?>
                                    <li <?= $url == $m['url'] ? 'class="active"':null ?>><?= $m['children'] ? '<button><i class="fa fa-caret-down"></i></button>' : null ?><a href="<?= $m['url'] ?>"><?= $m['name'] ?></a>
                                        <?php if(!empty($m['children'])): ?>
                                            <ul class="nav2">
                                                <?php foreach($m['children'] as $mm): ?>
                                                    <li><?= $mm['children'] ? '<button><i class="fa fa-caret-down"></i></button>' : null ?><a href="<?= $mm['url'] ?>"><?= $mm['name'] ?></a>
                                                        <?php if(!empty($mm['children'])): ?>
                                                            <ul>
                                                                <?php foreach ($mm['children'] as $mcc):?>
                                                                    <li><a href="<?= $mcc['url'] ?>"><?= $mcc['name'] ?></a></li>
                                                                <?php endforeach;?>
                                                            </ul>
                                                        <?php endif;?>
                                                    </li>
                                                <?php endforeach; ?>
                                            </ul>
                                        <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </div>
</div>