<?php
    $this->headTitle($this->escapeHtml('Bảng giá'));
    $this->headMeta()->appendName('description', 'Bảng giá');
    $this->headMeta()->appendName('keywords', 'Bảng giá thiết kế website');
    $this->headMeta()->appendProperty('og:title', 'Bảng giá');
    $cs = [
        '/tp/dweb_v2/css/page.css'
    ];
    echo '<link href="'.srcLink($cs,3).'" media="screen" rel="stylesheet" type="text/css">';
    $optionPage = $this->home()->optionPage();
?>

<section class="m-t-100 landing-head-hero custom-hero" style="background-image: url(/tp/dweb_v2/image/price_background.jpg);">
    <div class="container">
        <div class="landing-head-hero__content">
            <h2 class="wp1 animated fadeInUp">Bảng giá</h2>
            <p class="wp2 animated fadeInUp">DWEB giúp bạn sở hữu một website với chi phí tối ưu nhất!</p>
        </div>
    </div>
</section>
<section class="price price__custom--1">

    <div class="container">

        <div class="price__inner">
            <p class="about__sub">Bảng giá</p>
            <h2 class="about__headline">Bảng giá website
            </h2>
            <div class="price__list">
                <div class="price__item">
                    <div class="price__img">
                        <img src="/tp/dweb_v2/image/service_1.png" alt="thiết kế website miễn phí" style="width: 80px;">
                    </div>
                    <div class="price__item-title">
                        <h2>Miễn phí</h2>
                        <p>Miễn phí kho giao diện</p>
                    </div>
                    <div class="price__item-price">
                        <h3>0 đ</h3>
                        <p>Miễn phí 3 tháng</p>
                    </div>
                    <div>Phí duy trì 1 năm</div>
                    <div>Dung lượng 200Mb</div>
                    <div>Băng thông không giới hạn</div>
                    <div>Giới hạn danh sách giao diện</div>
                    <div>Responsive/ Mobile/ Desktop</div>
                    <div>Tuỳ chỉnh giao diện</div>
                    <div>Miễn phí 3 tháng</div>
                    <div>Chuẩn seo Onpage</div>
                    <div><a class="btn-d" target="_blank" href="/created">Tạo website</a></div>
                </div>
                <div class="price__item">
                    <div class="price__img">
                        <img src="/tp/dweb_v2/image/price-3.png" alt="thiết kế website miễn phí" style="width: 80px;">
                    </div>
                    <div class="price__item-title">
                        <h2>Cơ bản</h2>
                        <p>Kế hoạch ngắn hạn &lt; 6 tháng</p>
                    </div>
                    <div class="price__item-price">
                        <h3>990.000 đ</h3>
                        <p>Tặng tên miền .com, .net (250k)</p>
                    </div>
                    <div>Phí duy trì 1 năm</div>
                    <div>Dung lượng 500Mb</div>
                    <div>Băng thông không giới hạn</div>
                    <div>Giới hạn danh sách giao diện</div>
                    <div>Responsive/ Mobile/ Desktop</div>
                    <div>Tuỳ chỉnh giao diện</div>
                    <div>Thánh toán tối thiểu 1 năm</div>
                    <div>Chuẩn seo Onpage</div>




                    <div><a class="btn-d" target="_blank" href="/created">Tạo website</a></div>
                </div><div class="price__item">
                    <div class="price__img">
                        <img src="/tp/dweb_v2/image/service_3.png" alt="thiết kế website miễn phí" style="width: 80px;">
                    </div>
                    <div class="price__item-title">
                        <h2>Nâng cấp</h2>
                        <p>Giành cho startup</p>
                    </div>
                    <div class="price__item-price">
                        <h3>2.400.000 đ</h3>
                        <p>Tặng tên miền .com, .net (250k)

                        </p>
                    </div>
                    <div>Phí duy trì 1 năm</div>
                    <div>Dung lượng 1Gb</div>
                    <div>Băng thông không giới hạn</div>
                    <div>Sử dụng toàn bộ giao diện</div>
                    <div>Responsive/ Mobile/ Desktop</div>
                    <div>Tuỳ chỉnh giao diện</div>
                    <div>Thanh toán tối thiểu 6 Tháng</div>
                    <div>Chuẩn seo Onpage</div>



                    <div>Cài đặt Chat Box</div>



                    <div><a class="btn-d" target="_blank" href="/created">Tạo website</a></div>
                </div>
                <div class="price__item price__item--advance">
                    <div class="price__img">
                        <img src="/tp/dweb_v2/image/price-1.png" alt="thiết kế website chuyên nghiệp" style="width: 80px;">
                    </div>
                    <div class="price__item-title">
                        <h2>Cao cấp</h2>
                        <p>Thiết kế tính năng, giao diện</p>
                    </div>
                    <div class="price__item-price">
                        <h3>4.000.000+ đ</h3>
                        <p>Tặng tên miền .com, .net (250k)

                        </p>
                    </div>
                    <div>Phí duy trì 1 năm</div>
                    <div>Dung lượng 5Gb</div>
                    <div>Băng thông không giới hạn</div>
                    <div>Thiết kế theo yêu cầu</div>
                    <div>Responsive/ Mobile/ Desktop</div>
                    <div>Tuỳ chỉnh giao diện</div>
                    <div>Thanh toán tối thiểu 6 tháng</div>
                    <div>Chuẩn seo Onpage</div>



                    <div>Công cụ (Chatbox, Analytics, Console log, Fixel ...)</div>
                    <div><a class="btn-d" href="/thiet-ke-website-chuan-seo.html#form-brief">Gửi yêu cầu</a></div>
                </div>

            </div>

            <p class="price__note"><strong>Miễn phí:</strong> Bạn có thể dùng miễn phí tất cả các giao diện mẫu, với tên miền khi tạo sẵn (doanhnghiep.dweb.vn) trỏ tên miền riêng tenmienrieng.com<br>Miễn phí dùng 3 tháng có chèn quảng cáo, từ tháng 4 được tính phí 199k/ tháng.</p>
            <p class="price__note"><strong>Cơ bản:</strong> Dung lượng lưu trữ nội dung, hình ảnh, video 500mb, giới hạn thay đổi sử dụng kho giao diện sẵn có.</p>
            <p class="price__note"><strong>Nâng cấp:</strong> Dung lượng được nâng cấp 1Gb, đựợc sử dụng và thay đổi miễn phí giao diện có sẵn trong kho giao diện.</p>
            <p class="price__note"><strong>Nâng cao:</strong> Gói nâng cao được lấy yêu cầu cụ thể, lên thiết kế, được coding dựa trên thiết kế yêu cầu cụ thể doanh nghiệp. Gửi yêu cầu cho chúng tôi <a href="/thiet-ke-website-chuan-seo.html#form-brief"><strong>tại đây</strong></a></p>

        </div>

    </div>
</section>

<section class="price-domain">
    <div class="container">
        <div class="price-domain__inner">
            <h2 class="price-domain__title">Bảng giá <span>tên miền</span></h2>
            <div class="price__domain">
                <table class="table">
                    <thead>
                    <tr> <th width="60%"> TÊN MIỀN VIỆT NAM </th> <th> PHÍ KHỞI TẠO (VNĐ) </th> <th> PHÍ DUY TRÌ HÀNG NĂM (VNĐ) </th> </tr>
                    </thead>
                    <tbody>
                    <tr> <td>.vn</td> <td>350.000</td> <td>480.000</td> </tr>
                    <tr> <td>.com.vn | .net.vn | .biz.vn</td> <td>350.000</td> <td>350.000</td> </tr>
                    <tr> <td>.org.vn | .gov.vn | .edu.vn | .pro.vn | .info.vn | .int.vn | .ac.vn | .health.vn</td> <td>200.000</td> <td>200.000</td> </tr>
                    <tr> <td>.name.vn</td> <td>30.000</td> <td>30.000</td> </tr> <tr> <td>Tên miền địa giới hành chính</td> <td>200.000</td> <td>200.000</td> </tr>
                    </tbody>
                </table>
            </div>
            <div class="price__domain">
                <table class="table">
                    <thead>
                    <tr> <th width="60%"> TÊN MIỀN QUỐC TẾ </th> <th> PHÍ KHỞI TẠO (VNĐ) </th> <th> PHÍ DUY TRÌ HÀNG NĂM (VNĐ) </th> </tr>
                    </thead>
                    <tbody>
                    <tr> <td>.com | .net</td> <td>Miễn phí</td> <td>275.000</td> </tr>
                    <tr> <td>.org | .info | .link</td> <td>Miễn phí</td> <td>285.000</td> </tr>
                    <tr> <td>.us | .biz | .pw</td> <td>Miễn phí</td> <td>275.000</td> </tr>
                    <tr> <td>.co.uk | .eu | .name</td> <td>Miễn phí</td> <td>290.000</td> </tr>
                    <tr> <td>.mobi | .ninja | .in | .com.co | .net.co | .nom.co | .ca</td> <td>Miễn phí</td> <td>499.000</td> </tr>
                    <tr> <td>.bz | .ws | .tv</td> <td>Miễn phí</td> <td>735.000</td> </tr>
                    <tr> <td>.co</td> <td>Miễn phí</td> <td>800.000</td> </tr>
                    <tr> <td>.me</td> <td>Miễn phí</td> <td>710.000</td> </tr>
                    <tr> <td>.ceo</td> <td>Miễn phí</td> <td>2.666.000</td> </tr>
                    <tr> <td>.xxx | .jp</td> <td>Miễn phí</td> <td>2.666.000</td> </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>


<?php if(!empty($optionPage['du-an-tieu-bieu'])): ?>
    <section class="project project--custom">
        <div class="container">
            <h2 class="project-title title-h2 align-center">Giao diện</h2>
            <div class="project-description">
                Hãy lựa chọn một theme phù hợp với cửa hàng kinh doanh Online của bạn! <br/>
                Xem các website mẫu của khách hàng đã tin tưởng sử dụng DWEB.
            </div>
            <div class="project-list">
                <?php foreach ($optionPage['du-an-tieu-bieu'] as $p):
                    $image = json_decode($p['image'], true);
                    if(!empty($image)){
                        $imageFirst = array_shift($image);
                    }
                    $extraContent = json_decode($p['extraContent'], true);
                    ?>
                    <div class="project-item">
                        <div class="project-inner">
                            <figure class="lazy project-image" data-src="<?= $imageFirst ?>"></figure>
                            <div class="project-control">
                                <a class="btn-d project__button-reviewer" target="_blank" href="<?= $p['intro'] ?>">Xem thử</a>
                                <a class="btn-d project__button-detail" href="/register-<?= vnString($p['title']) ?>.html">Tạo website</a>
                                <h3 class="project__title"><?= $p['title'] ?></h3>
                                <p class="project__description"><?= !empty($extraContent['mo-ta']) ? $extraContent['mo-ta']:null ?></p>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
            <div class="project__button-load-more">
                <div class="project__button-line"></div>
                <a class="project__button-link" href="/kho-giao-dien.html">Xem tất cả</a>
                <div class="project__button-line"></div>
            </div>
        </div>
    </section>
<?php endif; ?>

<section class="support-module">
    <div class="container">
        <div class="support-module__inner">
            <h2 class="support-module__headline">Tư vấn miễn phí</h2>
            <div class="support-module__sub">
                Ngay từ bây giờ bạn có thể bắt đầu kinh doanh dùng thử<br/>
                gói website 3 tháng <strong>Miễn phí</strong> và những chiến dịch quảng cáo<br/> Google Ads, Facebook Ads chỉ với <strong>100.000</strong>.
            </div>
            <form class="support-module__form" data-parsley-validate novalidate>
                <div>
                    <input type="text" data-parsley-type="digits" data-parsley-length="[10,11]" required="required" placeholder="Số điện thoại *" />
                </div>
                <div>
                    <button type="submit">Gửi</button>
                </div>
            </form>
        </div>
    </div>
</section>
