<?php
    $q = $this->request->getQuery('n');
    $this->headTitle($this->escapeHtml('Kho giao diện'));
    $this->headMeta()->appendName('description', 'Kho giao diện, Thời trang, Kiến Trúc - Nội Thất, Công ty, Mỹ Phẩm - Làm Đẹp, Ẩm Thực - Ăn Uống, Mẹ và Bé, Siêu thị nhiều mặt hàng, Công nghệ');
    $this->headMeta()->appendName('keywords', ('Thời trang, Kiến Trúc - Nội Thất, Công ty, Mỹ Phẩm - Làm Đẹp, Ẩm Thực - Ăn Uống, Mẹ và Bé, Siêu thị nhiều mặt hàng, Công nghệ'));
    $this->headMeta()->appendProperty('og:title', 'Kho giao diện');

    $cs = [
        '/tp/dweb_v2/css/page.css'
    ];
    echo '<link href="'.srcLink($cs,3).'" media="screen" rel="stylesheet" type="text/css">';
    $theme = $this->NewsCategory()->featchTreeCategory(20);
    $data = $this->paginator;
    $data->setItemCountPerPage($this->uriParams()->getRequest()->getQuery('icpp') ? : 15);
    $user = $this->user;
    $user_created = !empty($_SESSION["user_created_website"]) ? json_decode($_SESSION["user_created_website"], true):[];
?>

<section class="m-t-100 theme">
    <div class="theme__inner">
        <div class="theme__left">
            <div class="theme__left--inner">
                <form id="search" action="/kho-giao-dien.html" class="theme__search" method="get">
                    <input type="text" name="n" placeholder="Thiết kế, thời trang ..."/>
                    <a href="javascript:{}" onclick="document.getElementById('search').submit();"><i class="fa fa-search" aria-hidden="true"></i></a>
                </form>
                <?= !empty($q) ? '<p class="theme__result">Bạn đang tìm kiếm với từ khoá: <span>'.$q.'</span></p>':null ?>
                <ul class="theme__list-category">
                    <?php if(!empty($theme)): ?>
                        <?php foreach($theme as $t): ?>
                            <li><a href="<?= $t->getViewLink() ?>"><?= $t->getName() ?></a></li>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
        <div class="theme__right">
            <div class="theme__intro">Lựa chọn mẫu website<br/> mà bạn yêu thích</div>
            <?php if(!empty($data)): ?>
                <div class="project-list">
                    <?php foreach ($data as $p):
                        $image = json_decode($p->getImage(), true);
                        if(!empty($image)){
                            $imageFirst = array_shift($image);
                        }
                        $extraContent = json_decode($p->getExtraContent(), true);
                        ?>
                        <div class="project-item">
                            <div class="project-inner">
                                <figure class="project-image lazy" data-src="https://dweb.vn<?= $imageFirst ?>"></figure>
                                <div class="project-control">
                                    <a class="btn-d project__button-reviewer" target="_blank" href="<?= $p->getViewDemo() ?>">Xem thử</a>
                                    <?php
                                        $themeId = end(explode('-', vnString($p->getTitle())));
                                    ?>
                                    <?php if(!empty($user_created)): ?>
                                        <a class="btn-d project__button-detail project__button-choose" data-user="<?= $_SESSION["user_created_website"] ?>" data-theme="<?= $themeId  ?>">Lựa chọn</a>
                                    <?php elseif($user): ?>
                                        <a class="btn-d project__button-detail project__button-change" data-theme="<?= $themeId  ?>">Sử dụng</a>
                                    <?php else: ?>

                                        <a class="btn-d project__button-detail" target="_blank" href="/created/<?= $themeId ?>">Tạo website</a>
                                    <?php endif; ?>
                                    <h3 class="project__title"><?= $p->getTitle(); ?></h3>
                                    <p class="project__description"><?= !empty($extraContent['mo-ta']) ? $extraContent['mo-ta']:null ?></p>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>

                <?php
                echo '<div class="news__paginator">';
                echo $this->paginationControl($this->paginator, 'Elastic', 'partial/listPage');
                echo '</div>';
            endif;
            ?>
            <div class="single-news__button">
                <span>Nếu bạn chưa tìm thấy giao diện phù hợp, bạn có thể gửi cho chúng tôi mẫu website bạn cần<br/>chúng tôi sẽ cố gắng bổ sung giao diện bạn gửi lên kho giao diện trong thời gian sớm nhất. </span><a class="btn-d" target="_blank" href="/thiet-ke-website-chuan-seo.html#form-brief">Gửi mẫu giao diện</a>
            </div>
        </div>
    </div>
</section>

