<?php
use Home\Model\DateBase;
if(!empty($this->projectLayout['project-list banner']['project-list'])):?>
<section class="project">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="project--title">
                        <?= $this->projectLayout['project-small-title text']['value'] ? '<h2 class="project--title-small">'.$this->projectLayout['project-small-title text']['value'].'</h2>' : '' ?>
                        <?= $this->projectLayout['project-big-title text']['value'] ? '<h2 class="project--title-medium">'.$this->projectLayout['project-big-title text']['value'].'</h2>' : ''?>
                        <?= $this->projectLayout['project-sub-title text']['value'] ? '<p class="project--title-description">'.$this->projectLayout['project-sub-title text']['value'].'</p>': '' ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <?php $slider = $this->projectLayout['project-slider-checkbox checkbox']['value'];?>
                    <ul class=" <?= $slider ? 'project__carousel owl-carousel owl-theme project__slider' : 'project--list'?>">
                        <?php
                            foreach($this->projectLayout['project-list banner']['project-list'] as $k => $n):
                                $image = json_decode($n['image'], true);
                                if(!empty($image)){
                                    $imageFirst = array_shift($image);
                                }
                                ?>
                                <li class="project--item">
                                    <a href="<?= $n['url'] ?>">
                                        <figure class="project--image" style="background-image: url(<?= $imageFirst ?>)"></figure>
                                    </a>
                                    <h3 class="project--item-title"><a href="<?= $n['url'] ?>"><?= $n['title'] ?></a></h3>
                                    <p class="project--item-description"></p>
                                </li>
                                <?php
                            endforeach;
                        ?>
                    </ul>
                    <?= $this->projectLayout['project-link text']['value'] ? '<a class="project--button-view-all" href="'.$this->projectLayout['project-link text']['value'].'">'.$this->projectLayout['project-button text']['value'].'</a>' : ''?>
                </div>
            </div>
        </div>
    </section>
<?php endif;?>