<?php if(!empty($this->bannerList['banner-list banner']['banner-list'])):?>
<section class="slider">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
            <?php
                echo '<ul class="banner owl-carousel owl-theme">';
                foreach($this->bannerList['banner-list banner']['banner-list'] as $k => $b):
                    $image = json_decode($b['image'], true);
                    if(!empty($image)) {
                        $imageFirst = array_shift($image);
                    }
                    ?>
                    <li>
                        <a href="<?= $b['url'] ?>">
                            <figure class="slider-image" style="background-image: url(<?= $imageFirst ?>)"></figure>
                        </a>
                    </li>
                <?php endforeach;?>
                </ul>
            </div>
        </div>
    </div>
</section>
<?php endif;?>
