<?php
$optionBasic = $this->home()->optionBasic();
$optionPage = $this->home()->optionPage();
$menuOption = $this->home()->getMenu();
use Home\Model\DateBase;
?>

<footer class="footer">
    <?php if(!empty($optionPage['view_cot-gioi-thieu']) || !empty($optionPage['view_danh-sach-lien-ket']) || !empty($optionPage['view_thong-tin-dia-chi'])): ?>
        <div class="footer__one">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <?php if(!empty($optionPage['view_cot-gioi-thieu'])): ?>
                            <div class="col-md-4">
                                <a class="logo" href="/">
                                    <?php if(!empty($optionBasic['logo'])): ?>
                                        <img src="<?= $optionBasic['logo'] ?>" alt="<?= !empty($optionBasic['sologan']) ? $optionBasic['sologan']:null ?>" />
                                    <?php endif; ?>
                                </a>
                                <div class="footer__content" style="margin: 10px 0 0">
                                    <?php if(!empty($optionPage['noi-dung-gioi-thieu'])): ?>
                                        <?= $optionPage['noi-dung-gioi-thieu'] ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                        <?php endif; ?>
                        <?php if(!empty($optionPage['view_danh-sach-lien-ket'])): ?>
                            <div class="col-md-4">
                                <h2 class="footer__title"><?= $optionPage['tieu-de-danh-sach-lien-ket'] ? $optionPage['tieu-de-danh-sach-lien-ket'] : ''?></h2>

                                <ul class="footer__list">
                                    <?php foreach($menuOption['footer_menu'] as $m): ?>
                                        <li <?= $url == $m['url'] ? 'class="active"':null ?>><a href="<?= $m['url'] ?>"><?= $m['name'] ?></a>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                        <?php endif; ?>
                        <?php if(!empty($optionPage['view_thong-tin-dia-chi'])): ?>
                            <div class="col-md-4">
                                <h2 class="footer__title"><?= $optionPage['tieu-de-thong-tin'] ? $optionPage['tieu-de-thong-tin'] : ''?></h2>

                                <div class="footer__content">
                                    <?= $optionPage['dia-chi'] ? $optionPage['dia-chi'] : ''?>
                                </div>
                                <div class="footer--design">
                                    <ul class="footer__social">
                                        <?= $optionPage['facebook'] ? '<li><a href="'.$optionPage['facebook'].'" class="icon-social-facebook icons"></a></li>' : ''?>
                                        <?= $optionPage['twitter'] ? '<li><a href="'.$optionPage['twitter'].'" class="icon-social-twitter icons"></a></li>' : ''?>
                                        <?= $optionPage['google'] ? '<li><a href="'.$optionPage['google'].'" class="icon-social-google icons"></i></a></li>' : ''?>
                                    </ul>
                                </div>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    <?php endif;?>
</footer>

