<?php
echo $this->doctype();
$optionBasic = $this->home()->optionBasic();
?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
        <link rel="stylesheet" id="Open_Sans_sub-css" href="//fonts.googleapis.com/css?family=Open+Sans%3A200%2C300%2C400%2C400italic%2C700&amp;v1&amp;subset=latin%2Clatin-ext" type="text/css" media="screen" />
        <link href="https://fonts.googleapis.com/css?family=Amatic+SC&amp;subset=latin-ext,vietnamese" rel="stylesheet">
        <?php
        echo $this->headTitle()->setSeparator('')->setAutoEscape(false);
        $this->headMeta()->appendName('DC.language', 'scheme=utf-8 content=vi');
        echo $this->headMeta();

        echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $optionBasic['favicon'] ? $optionBasic['favicon']:null ]);
        $cs = [
            '/tp/MB001/css/bootstrap.css',
            '/assets/css/web/font-awesome.min.css',
            '/tp/MB001/css/simple-line-icons.css',
            '/assets/css/web/owl.carousel.css',
            '/assets/css/web/owl.theme.css',
            '/assets/css/web/owl.transitions.css',
            '/tp/MB001/css/h.css',

        ];
        echo '<link href="'.srcLink($cs,2).'" media="screen" rel="stylesheet" type="text/css">';
        $js = [
            '/assets/js/web/jquery-1.11.2.min.js',
        ];
        echo '<script type="text/javascript" src="'.srcLink($js,1).'"></script>';
        echo !empty($optionBasic['scriptHead']) ? '<script>'.$optionBasic['scriptHead'].'</script>' : null;
        ?>
    </head>
    <body>
        <?php
            echo $this->render('layout/header');
            echo $this->content;
            echo '
            <div class="modal fade" id="myModal" role="dialog">
                <div class="modal-dialog">
                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">Giỏ hàng</h4>
                        </div>
                        <div class="modal-body"></div>
                    </div>
                </div>
            </div>';
            echo $this->render('layout/footer');
            echo !empty($optionBasic['scriptBody']) ? '<script>'.$optionBasic['scriptBody'].'</script>' : null;
        ?>
    </body>
    <?php
        $r = [
            '/tp/MB001/css/r.css',
        ];
        echo '<link href="'.srcLink($r,1).'" media="screen" rel="stylesheet" type="text/css">';
        if(!empty($optionBasic['styleFooter'])) echo '<style>'.$optionBasic['styleFooter'].'</style>';
        $js = [
            '/assets/js/web/bootstrap.min.js',
            '/assets/js/web/jquery.lazy.min.js',
            '/assets/js/web/owl.carousel.js',
            '/assets/js/web/jquery-ui-1.10.3.custom.min.js',
            '/tp/MB001/js/a.js',
            '/assets/plugins/parsleyjs/parsley.min.js'
        ];
        echo '<script type="text/javascript" src="'.srcLink($js,3).'"></script>';
        echo !empty($optionBasic['scriptFooter']) ? '<script>'.$optionBasic['scriptFooter'].'</script>' : null;
    ?>
</html>