<?php

    $this->headMeta()->appendName('description', ('Hướng dẫn sử dụng DWEB.VN'));
    $this->headMeta()->appendName('keywords', ('Hướng dẫn sử dụng DWEB.VN'));

    $this->headMeta()->appendProperty('fb:app_id', '1697190970583102');
    $this->headMeta()->appendProperty('article:author', 'https://www.facebook.com/dwebvietnam');
    $this->headMeta()->appendProperty('og:locale', 'vi_VN');
    $this->headMeta()->appendProperty('og:image', 'http://dweb.vn/tp/dweb/image/dweb-thumbnail.png');
    $this->headMeta()->appendProperty('og:url', 'http://dweb.vn');
    $this->headMeta()->appendProperty('og:title', 'Hướng dẫn sử dụng DWEB.VN');
    $this->headMeta()->appendProperty('og:description', ('Hướng dẫn sử dụng DWEB.VN'));

    $this->headMeta()->appendProperty('twitter:card', 'DWEB.VN');
    $this->headMeta()->appendProperty('twitter:title', 'Hướng dẫn sử dụng DWEB.VN');
    $this->headMeta()->appendProperty('twitter:image', 'http://dweb.vn/tp/dweb/image/dweb-thumbnail.png');
    $this->headMeta()->appendProperty('twitter:description', 'Hướng dẫn sử dụng DWEB.VN');

    $optionPage = $this->home()->optionPage();
?>
<section class="guide">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="guide__sidebar">
                    <ul class="sidebar__menu">
                        <li><a href="">Đăng nhập</a></li>
                        <li><a href="">Trang chủ</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-9">
                <div class="guide__content">
                    <div class="guide__item guide__login">
                        <h2 class="title__headline">1. Đăng nhập</h2>
                        <div>
                            Bạn đăng nhập bằng <a target="_blank" href="http://<?= $_SERVER['HTTP_HOST'] ?>/admin">đường dẫn sau</a> với tài khoản bạn đã đăng ký.
                        </div>
                    </div>
                    <div class="guide__item guide__login">
                        <h2 class="title__headline">2. Trang chủ</h2>
                        <h3>2.1 Header</h3>
                        <div>
                            <p>Để cài đặt được header có 2 mục chính là logo và menu</p>
                            <p>1. <a href="http://<?= $_SERVER['HTTP_HOST'] ?>/admin/setup" target="_blank">Cài đặt logo</a></p>
                            <p>2. <a href="http://<?= $_SERVER['HTTP_HOST'] ?>/admin/setup/menu" target="_blank">Cài đặt menu</a></p>
                            <p><img src="/tp/guide/image/head.png" alt="guide header dweb" /></p>
                        </div>
                        <h3>2.2 Slider</h3>
                        <div>
                            <p>Để quản lý được slider, trước tiên bạn cần xem danh sách những slider hiện có, có thể thêm, sửa, xoá banner <a href="http://<?= $_SERVER['HTTP_HOST'] ?>/admin/media/banner" target="_blank">tại đây</a>,
                                và lựa chọn <a href="http://<?= $_SERVER['HTTP_HOST'] ?>/admin/page/homepage" target="_blank">hiển thị</a> slider ở các vị trí khác nhau.</p>
                        </div>
                        <h3>2.3 Tuỳ chỉnh hiển thị phần trang chủ</h3>
                        <div>
                            <p>
                            Trước tiên bạn hãy quản lý
                            <a href="http://<?= $_SERVER['HTTP_HOST'] ?>/admin/media/banner" target="_blank">banner</a>,
                            <a href="http://<?= $_SERVER['HTTP_HOST'] ?>/admin/article" target="_blank">bài viết</a>,
                            <a href="http://<?= $_SERVER['HTTP_HOST'] ?>/admin/product" target="_blank">hoặc sản phẩm</a>,
                                và lựa chọn <a href="http://<?= $_SERVER['HTTP_HOST'] ?>/admin/page/homepage" target="_blank">hiển thị</a>
                                các banner, bài viết, sản phẩm ra ngoài trang chủ <a href="http://<?= $_SERVER['HTTP_HOST'] ?>/admin/page/homepage" target="_blank">tại đây</a>, tại đây các trường hiển thị sẽ phù hợp với template mà bạn đang chọn.
                            </p>
                        </div>
                        <h3>2.4 Tuỳ chỉnh khác</h3>
                        <div>
                            <p>
                                Mỗi một giao diện thì các trường sẽ tương ứng với với giao diện đó, bạn có thể quản lý trên tab
                                <a href="http://<?= $_SERVER['HTTP_HOST'] ?>/admin/page/homepage" target="_blank">tuỳ chỉnh giao diện tại đây</a>
                                , một số giao diện chúng ta có thêm tab, Head, Sản phẩm, Sidebar.
                                <p><img src="/tp/guide/image/option.png" alt="guide option dweb" /></p>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>