<?php
echo $this->doctype();
$optionBasic = $this->home()->optionBasic();
?>
<html lang="en">
    <head>
        <?php
            echo $this->headTitle('Hướng dẫn sử dụng DWEB.VN')->setSeparator(' - ')->setAutoEscape(false);
            $this->headMeta()->appendName('DC.language', 'scheme=utf-8 content=vi');
            $this->headMeta()->appendName('author', 'blog.dweb.vn');
            $this->headMeta()->appendName('format-detection', 'telephone=no');
            $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1, maximum-scale=1');
            echo $this->headMeta();
            echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $optionBasic['favicon'] ? $optionBasic['favicon']:null ]);

        ?>

        <link href='https://fonts.googleapis.com/css?family=Roboto:300,500,700' rel='stylesheet' type='text/css'>
        <?php
            $cs = [
                '/tp/guide/css/bootstrap.css',
                '/tp/guide/css/font-awesome.min.css',
                '/tp/guide/css/animate.min.css',
                '/tp/guide/css/page.css',
                '/tp/guide/css/a.css',
                '/tp/guide/css/r.css',
            ];
            echo '<link href="'.srcLink($cs,3).'" media="screen" rel="stylesheet" type="text/css">';
            $js = [
                '/assets/js/web/jquery-1.11.2.min.js',
            ];
            echo '<script type="text/javascript" src="'.srcLink($js,2).'"></script>';
            echo !empty($optionBasic['scriptHead']) ? '<script>'.$optionBasic['scriptHead'].'</script>' : null;
        ?>
        <!-- Facebook Pixel Code -->
        <script>
            !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
                n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
                n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
                t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
                document,'script','https://connect.facebook.net/en_US/fbevents.js');
            fbq('init', '1971198599778175'); // Insert your pixel ID here.
            fbq('track', 'PageView');
        </script>
        <noscript><img height="1" width="1" style="display:none"
                       src="https://www.facebook.com/tr?id=1971198599778175&ev=PageView&noscript=1"
            /></noscript>
        <!-- DO NOT MODIFY -->
        <!-- End Facebook Pixel Code -->
    </head>
    <?php
        $url = $this->UriParams()->getRequest()->getRequestUri();
        $classPage = substr($url, 1, -5);
    ?>
    <body>
        <?php
            echo $this->render('layout/header');
            echo $this->content;
            echo $this->render('layout/footer');
            echo $this->render('layout/modal');
            echo !empty($optionBasic['scriptBody']) ? '<script>'.$optionBasic['scriptBody'].'</script>' : null;
        ?>
        <script type='text/javascript'>window._sbzq||function(e){e._sbzq=[];var t=e._sbzq;t.push(["_setAccount",69949]);var n=e.location.protocol=="https:"?"https:":"http:";var r=document.createElement("script");r.type="text/javascript";r.async=true;r.src=n+"//static.subiz.com/public/js/loader.js";var i=document.getElementsByTagName("script")[0];i.parentNode.insertBefore(r,i)}(window);</script>
    </body>
    <?php
        $cs = [
            '/tp/blog/css/r.css',
        ];
        echo '<link href="'.srcLink($cs,3).'" media="screen" rel="stylesheet" type="text/css">';
        $js = [
//            '/tp/dweb/js/jquery-1.10.1.min.js',
            '/tp/guide/js/bootstrap.min.js',
            '/tp/guide/js/waypoint/jquery.waypoints.min.js',
            '/tp/guide/js/a.js',
            '/assets/js/web/jquery.lazy.min.js',
            '/tp/guide/js/hero-slider/TweenLite.min.js',
            '/tp/guide/js/hero-slider/rAF.js',
            '/tp/guide/js/hero-slider/EasePack.min.js',
            '/tp/guide/js/hero-slider/demo-1.js',
        ];
        echo '<script type="text/javascript" src="'.srcLink($js,1).'"></script>';
        echo !empty($optionBasic['scriptFooter']) ? '<script>'.$optionBasic['scriptFooter'].'</script>' : null;
    ?>
</html>