<?php if(!empty($this->fourBannerList['four-banner-list banner']['four-banner-list'])):?>
    <section class="four-banner">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <?= $this->fourBannerList['four-banner-title text']['value'] ? '<h2 class="four-banner__title">'.$this->fourBannerList['four-banner-title text']['value'].'</h2>' : '' ?>
                    <div class="four-banner__inner">
                        <?php
                            $c = 0;
                            foreach($this->fourBannerList['four-banner-list banner']['four-banner-list'] as $k => $b):
                                $c++;
                                $image = json_decode($b['image'], true);
                                $imageFirst = '';
                                if(!empty($image)){
                                    $imageFirst = array_shift($image);
                                }
                                if($c == 1):
                                    ?>
                                    <div class="four-banner__row">
                                        <a href="<?= $b['url'] ?>">
                                            <figure class="lazy four-banner__image" data-src="<?= $imageFirst ?>">
                                                <div>
                                                    <h2><?= $b['title'] ?></h2>
                                                    <p><?= $b['description'] ?></p>
                                                    <span>Mua ngay</span>
                                                </div>
                                            </figure>
                                        </a>
                                    </div>
                                    <div class="four-banner__row">
                                <?php elseif ($c == 2 || $c == 3): ?>
                                    <a href="<?= $b['url'] ?>">
                                        <figure class="lazy four-banner__image four-banner__image--50" data-src="<?= $imageFirst ?>">
                                            <div>
                                                <h2><?= $b['title'] ?></h2>
                                                <span>Mua ngay</span>
                                            </div>
                                        </figure>
                                    </a>
                                <?php elseif ($c == 4): ?>
                                    </div>
                                    <div class="four-banner__row">
                                        <a href="<?= $b['url'] ?>">
                                            <figure class="lazy four-banner__image" data-src="<?= $imageFirst ?>">
                                                <div>
                                                    <h2><?= $b['title'] ?></h2>
                                                    <p><?= $b['description'] ?></p>
                                                    <span>Mua ngay</span>
                                                </div>
                                            </figure>
                                        </a>
                                    </div>
                                <?php
                                endif;
                            endforeach;
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </section>
<?php endif;?>
