<?php if(!empty($this->smallBannerList['small-banner-list banner']['small-banner-list'])):
    ?>
    <div class="ADsHome1">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <ul>
                        <?php
                            $i = 0;
                            foreach($this->smallBannerList['small-banner-list banner']['small-banner-list'] as $b):
                                $i++;
                                $imageFirst = '';
                                if(!empty(json_decode($b['image'], true))){
                                    $imageFirst = array_shift(json_decode($b['image'], true));
                                }
                                ?>
                                <li <?= $i == 1 ? 'class="active"':null ?>><a href="<?= $b['url'] ?>"><figure class="lazy three-banner-center" data-src="<?= $imageFirst ?>"></figure> </a> </li>
                            <?php endforeach;?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>