<?php if(!empty($this->tabProductLayout['tab-product1 product']['tab-product1']) || !empty($this->tabProductLayout['tab-product2 product']['tab-product2']) || !empty($this->tabProductLayout['tab-product3 product']['tab-product3'])):?>
    <div class="tab-product product">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="tab-product__inner">
                        <ul class="tab-product__title nav nav-products" role="tablist">
                            <?php if(!empty($this->tabProductLayout['tab1-title text']['value'])):?>
                                <li role="presentation" class="active">
                                    <a  href="#tab1-<?=$this->id?>" aria-controls="tab1-<?=$this->id?>" role="tab" data-toggle="tab"><?= $this->tabProductLayout['tab1-title text']['value']?></a>
                                </li>
                            <?php endif;?>
                            <?php if(!empty($this->tabProductLayout['tab2-title text']['value'])):?>
                                <li role="presentation">
                                    <a href="#tab2-<?=$this->id?>" aria-controls="tab2-<?=$this->id?>" role="tab" data-toggle="tab"><?= $this->tabProductLayout['tab2-title text']['value']?></a>
                                </li>
                            <?php endif;?>
                            <?php if(!empty($this->tabProductLayout['tab3-title text']['value'])):?>
                                <li role="presentation">
                                    <a href="#tab3-<?=$this->id?>" aria-controls="tab3-<?=$this->id?>" role="tab" data-toggle="tab"><?= $this->tabProductLayout['tab3-title text']['value']?></a>
                                </li>
                            <?php endif;?>
                        </ul>
                        <div class="tab-content">
                            <div id="tab1-<?=$this->id?>" role="tabpanel" class="tab-pane fade active in">
                                <ul class="lP">
                                    <?php foreach($this->tabProductLayout['tab-product1 product']['tab-product1'] as $k => $p):
                                        $image = json_decode($p['image'], true);
                                        if(!empty($image)){
                                            $imageFirst = array_shift($image);
                                        }
                                        ?>
                                        <li class="product-item">
                                            <div class="product-item__inner">
                                                <div class="product_image-wrapper">
                                                    <a href="<?= $p['url'] ?>">
                                                        <figure class="lazy product_image" data-src="<?= !empty($imageFirst) ? $imageFirst:'' ?>"></figure>
                                                    </a>
                                                </div>
                                                <p class="product-price"><?= $p['priceOld'] ? number_format($p['priceOld']).' đ<i>'.number_format($p['price']).' đ</i>':number_format($p['price']).' đ' ?></p>
                                                <h3 class="product-title"><?= $p['title'] ?></h3>
                                            </div>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                            <div id="tab2-<?=$this->id?>" role="tabpanel" class="tab-pane fade">
                                <ul class="lP">
                                    <?php foreach($this->tabProductLayout['tab-product2 product']['tab-product2'] as $k => $p):
                                        $image = json_decode($p['image'], true);
                                        if(!empty($image)){
                                            $imageFirst = array_shift($image);
                                        }
                                        ?>
                                        <li class="product-item">
                                            <div class="product-item__inner">
                                                <div class="product_image-wrapper">
                                                    <a href="<?= $p['url'] ?>">
                                                        <figure class="lazy product_image" data-src="<?= !empty($imageFirst) ? $imageFirst:'' ?>"></figure>
                                                    </a>
                                                </div>
                                                <p class="product-price"><?= $p['priceOld'] ? number_format($p['priceOld']).' đ<i>'.number_format($p['price']).' đ</i>':number_format($p['price']).' đ' ?></p>
                                                <h3 class="product-title"><?= $p['title'] ?></h3>
                                            </div>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                            <div id="tab3-<?=$this->id?>" role="tabpanel" class="tab-pane fade">
                                <ul class="lP">
                                    <?php foreach($this->tabProductLayout['tab-product3 product']['tab-product3'] as $k => $p):
                                        $image = json_decode($p['image'], true);
                                        if(!empty($image)){
                                            $imageFirst = array_shift($image);
                                        }
                                        ?>
                                        <li class="product-item">
                                            <div class="product-item__inner">
                                                <div class="product_image-wrapper">
                                                    <a href="<?= $p['url'] ?>">
                                                        <figure class="lazy product_image" data-src="<?= !empty($imageFirst) ? $imageFirst:'' ?>"></figure>
                                                    </a>
                                                </div>
                                                <p class="product-price"><?= $p['priceOld'] ? number_format($p['priceOld']).' đ<i>'.number_format($p['price']).' đ</i>':number_format($p['price']).' đ' ?></p>
                                                <h3 class="product-title"><?= $p['title'] ?></h3>
                                            </div>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php endif;?>

